# Goal is building windows of data ( to feed to CNN)

1. Data Import , Cleaning and Visualizing (for a report)

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import re

In [2]:
df = pd.read_csv("results/scorpan.csv")
df

,id,id_memoire,id_ech,Wilaya,Region,X,Y,Longitude,latitude,altitude,...,wc2_1_30s_tavg_10_Band_1,wc2_1_30s_tavg_09_Band_1,wc2_1_30s_tavg_08_Band_1,wc2_1_30s_tavg_07_Band_1,wc2_1_30s_tavg_06_Band_1,wc2_1_30s_tavg_05_Band_1,wc2_1_30s_tavg_04_Band_1,wc2_1_30s_tavg_03_Band_1,wc2_1_30s_tavg_02_Band_1,wc2_1_30s_tavg_01_Band_1
0,1,1,1,Alger,El-Harrach,3 107,36 684,3.107 Est,36.684Â° Nord,22,...,1 979 999 924,2 379 999 924,2 610 000 038,25,2 210 000 038,"18,5",1 530 000 019,1 339 999 962,1 210 000 038,1 160 000 038
1,2,1,1,Alger,El-Harrach,3 107,36 684,3.107 Est,36.684Â° Nord,22,...,1 979 999 924,2 379 999 924,2 610 000 038,25,2 210 000 038,"18,5",1 530 000 019,1 339 999 962,1 210 000 038,1 160 000 038
2,3,1,1,Alger,El-Harrach,3 107,36 684,3.107 Est,36.684Â° Nord,22,...,1 979 999 924,2 379 999 924,2 610 000 038,25,2 210 000 038,"18,5",1 530 000 019,1 339 999 962,1 210 000 038,1 160 000 038
3,4,2,2,Alger,El-Harrach,313 333,360 716 666,3Â°E08â€™,36Â°N43,24,...,1 560 000 038,2 070 000 076,"24,5",2 439 999 962,2 020 000 076,1 589 999 962,1 210 000 038,9 399 999 619,6 900 000 095,5 599 999 905
4,5,2,2,Alger,El-Harrach,313 333,360 716 666,3Â°E08â€™,36Â°N43,24,...,1 560 000 038,2 070 000 076,"24,5",2 439 999 962,2 020 000 076,1 589 999 962,1 210 000 038,9 399 999 619,6 900 000 095,5 599 999 905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,1916,98,638,Tlemcen,Hennaya,-1 521 323 465 419 020,3 502 563 533 189 600,NaN,NaN,NaN,...,2 010 000 038,2 429 999 924,"27,5",27,2 360 000 038,1 979 999 924,"16,5","14,5",1 280 000 019,1 180 000 019
717,1919,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1 510 000 038,"20,5",2 520 000 076,2 539 999 962,2 120 000 076,"16,5",1 239 999 962,"9,5",6 900 000 095,"5,5"
718,1920,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1 510 000 038,"20,5",2 520 000 076,2 539 999 962,2 120 000 076,"16,5",1 239 999 962,"9,5",6 900 000 095,"5,5"
719,1921,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1 510 000 038,"20,5",2 520 000 076,2 539 999 962,2 120 000 076,"16,5",1 239 999 962,"9,5",6 900 000 095,"5,5"
720,1922,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1 510 000 038,"20,5",2 520 000 076,2 539 999 962,2 120 000 076,"16,5",1 239 999 962,"9,5",6 900 000 095,"5,5"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 721 entries, 0 to 720
Columns: 124 entries, id to wc2_1_30s_tavg_01_Band_1
dtypes: float64(1), int64(39), object(84)
memory usage: 698.6+ KB

In [4]:
df.iloc[100]

id                                    407
id_memoire                             29
id_ech                                139
Wilaya                              Batna
Region                             Fesdis
                                ...
wc2_1_30s_tavg_05_Band_1    1 569 999 981
wc2_1_30s_tavg_04_Band_1    1 180 000 019
wc2_1_30s_tavg_03_Band_1    8 600 000 381
wc2_1_30s_tavg_02_Band_1    6 199 999 809
wc2_1_30s_tavg_01_Band_1    5 400 000 095
Name: 100, Length: 124, dtype: object

In [5]:
for i in df.columns[3:23]:
    print(df[i].value_counts())
    print("\n\n")

Wilaya
Mitija           160
Skikda            80
El taref          71
Msila             58
Jijel             58
Biskra            50
Batna             42
Djelfa            40
Annaba            39
Relizane          39
Setif             26
Alger             23
Tlemcen           10
Ouled Djellal     10
Boumerdes          6
Medea              4
Chelef             3
Tiaret             2
Name: count, dtype: int64



Region
El Hadaiek                           80
Fesdis                               40
Ben Amar                             27
Bouira Lahdab                        26
Hodna                                24
El Kenner                            24
El-Gouriat- OkrÃ©ra                  23
Mezloug                              20
Le lac Bleu                          18
El Kala                              18
bas-chelif                           18
Taza                                 16
Ain Oussara                          14
Beni-Belaid                          12
Oued Mafragh                         12
El Karma                             12
Kef Tiour                            10
Hennaya                              10
El Hadjeb. Ain Ben Noui              10
El Outaya                            10
Doucen                               10
Tolga                                10
Zeribet El Ouad                      10
El-Harrach                            7
Boudoukha                             6
Oued Smar                             6
Mzirra                                5
Mziraa                                5
Dellys                                4
Benchicao                             4
Tenes                                 3
Bologhine                             2
Bab ezzouar                           2
cote Algerienne pres de boumerdes     2
Staoueli                              2
Baraki                                2
Ain Oulmane                           2
Ain Arnet                             2
Sebain                                2
Name: count, dtype: int64



X
8 174 722 222    23
8,2              18
8 341 388 889    18
79 925           12
6 085            12
                 ..
34 555            2
2 628 577 778     2
5 324 166 667     2
6 173 911 389     2
598 344 175       1
Name: count, Length: 166, dtype: int64



Y
3 684 388 889    23
36,9             18
3 690 472 222    18
3 596 319 444    12
3 684 666 667    12
                 ..
3 676 652 778     2
3 647 620 833     2
3 647 174 167     2
3 647 400 833     2
3 681 484 056     2
Name: count, Length: 161, dtype: int64



Longitude
8Â°10'29''E                 23
08Â° 12â€™ E                18
8Â°20'29''E                 18
0Â° 44â€™ 59.6â€™â€™ E      12
7Â° 58â€™ 93â€™â€™ E        12
                            ..
2Â° 37' 52.94"E              2
3Â°27'19.8"E                 2
2Â° 37' 42.88"E              2
2Â° 36' 22.78"E              2
3Â° 56â€™ 12.638â€™â€™ E     2
Name: count, Length: 162, dtype: int64



latitude
36Â°50'38''N            23
36Â°54'17''N            18
36Â°54â€™N              18
36Â°50'48"N             12
36Â° 50â€™ 55â€™â€™N    12
                        ..
36Â° 30' 39.93"N         2
36Â° 30' 56.71"N         2
36Â° 28' 57.55"N         2
36Â° 29' 0.12"N          2
36Â° 28' 26.61"N         2
Name: count, Length: 161, dtype: int64



altitude
5        29
22       26
14       24
35       18
15       18
44       16
31       16
168      15
17       12
3        12
10       12
6        12
13       11
906      10
198      10
97       10
993      10
23        8
405,6     6
122       6
841       6
836       6
427       6
450       6
416       6
777       6
397,3     6
397,6     6
381,9     6
706       6
711       6
153       5
50        5
107       5
140       5
775       4
778       4
962       3
1080      3
920       2
912       2
914       2
937       2
1100      2
12        2
42        2
24        2
704       2
177       2
102       1
Name: count, dtype: int64



UD
5      196
0      189
15     131
30     109
60      60
100     36
Name: count, dtype: int64



LD
15     196
5      189
30     131
60     109
100     60
200     36
Name: count, dtype: int64



average profondeur
10      196
2,5     189
22,5    131
45      109
80       60
150      36
Name: count, dtype: int64



USDA Soil Taxonomy
S      54
SL     46
AL     23
LS     12
CL      8
L       7
A       6
AS      6
LA      6
SAL     4
SCL     2
C       2
Name: count, dtype: int64



pH
8        34
8,2      32
8,1      30
7,9      22
8,3      16
         ..
8 369     1
8 246     1
8 217     1
8 071     1
7 951     1
Name: count, Length: 430, dtype: int64



CE
0,1      45
0,13     32
0,15     23
0,17     19
0,11     13
         ..
3 955     1
2 355     1
2,15      1
2 455     1
1 586     1
Name: count, Length: 271, dtype: int64



CEC
23,38     6
6,15      4
24,52     4
22,05     4
23        4
         ..
8 446     1
3 838     1
4 323     1
4 792     1
10 011    1
Name: count, Length: 379, dtype: int64



A%
7,06      16
40        10
45         6
13         6
36,9       6
          ..
10 585     1
7,17       1
11 466     1
12 317     1
49 752     1
Name: count, Length: 454, dtype: int64



L%
24,8                      16
15                        14
32                        12
33                        10
30                         8
                          ..
13 538                     1
10 789 000 000 000 000     1
10 938                     1
12 620 000 000 000 000     1
28,09                      1
Name: count, Length: 451, dtype: int64



S%
70,31     16
1         12
45        10
5,9        8
8,6        6
          ..
71 766     1
76 286     1
74,95      1
78 101     1
19 144     1
Name: count, Length: 475, dtype: int64



ALR(L)
0,545646365     16
-0,201645488     6
0,342422391      6
-0,425968841     6
-0,477121351     6
                ..
0,014425445      1
-0,362694669     1
0,081131528      1
-0,028793137     1
-0,248258892     1
Name: count, Length: 477, dtype: int64



ALR(S)
0,998211782     16
0,089400287      6
0,539911795      6
0,051152414      6
-0,051152619     6
                ..
0,82245502       1
0,898560704      1
0,66131709       1
0,57972962       1
-0,414777945     1
Name: count, Length: 477, dtype: int64



OM
3        14
3,1      10
3,5       8
2,4       8
2,1       8
         ..
5 049     1
4 725     1
5 464     1
5 445     1
1 256     1
Name: count, Length: 299, dtype: int64

longitude format enhancing

In [6]:
for i in df["Longitude"]:
    print(i)

3.107 Est
3.107 Est
3.107 Est
3Â°E08â€™
3Â°E08â€™
3Â°09'00"E
3Â°09'00"E
 2Â°52'49"E
 2Â°52'49"E
3Â°10'42.1"E
3Â°10'42.1"E
3Â°9.573' E
3Â°9.573' E
3Â°9.573' E
3Â°9.573' E
3Â°06'05"E
3Â°06'05"E
6Â° 16â€™ 26.18â€™â€™ E
6Â° 16â€™ 26.18â€™â€™ E
6Â° 16â€™ 26.18â€™â€™ E
6Â° 16â€™ 26.18â€™â€™ E
6Â° 16â€™ 26.18â€™â€™ E
6Â° 18â€™ 22. 9â€™â€™ E
6Â° 18â€™ 22. 9â€™â€™ E
6Â° 18â€™ 22. 9â€™â€™ E
6Â° 18â€™ 22. 9â€™â€™ E
6Â° 18â€™ 22. 9â€™â€™ E
5 Â° 6â€™ 05.28â€™â€™ E
5 Â° 6â€™ 05.28â€™â€™ E
5 Â° 6â€™ 05.28â€™â€™ E
5 Â° 6â€™ 05.28â€™â€™ E
5 Â° 6â€™ 05.28â€™â€™ E
5Â° 08â€™ 16.05â€™â€™ E
5Â° 08â€™ 16.05â€™â€™ E
5Â° 08â€™ 16.05â€™â€™ E
5Â° 08â€™ 16.05â€™â€™ E
5Â° 08â€™ 16.05â€™â€™ E
 5Â° 22â€™ 11.68â€™â€™ E
 5Â° 22â€™ 11.68â€™â€™ E
 5Â° 22â€™ 11.68â€™â€™ E
 5Â° 22â€™ 11.68â€™â€™ E
 5Â° 22â€™ 11.68â€™â€™ E
5Â° 23â€™ 23.53â€™â€™ E
5Â° 23â€™ 23.53â€™â€™ E
5Â° 23â€™ 23.53â€™â€™ E
5Â° 23â€™ 23.53â€™â€™ E
5Â° 23â€™ 23.53â€™â€™ E
5Â° 41â€™ 06.34â€™â€™ E
5Â° 41â€™ 06.34â€™â€™ E
5Â° 41â€™ 06.34â€™â€™ E
5Â° 41â€™ 06.34â€™â€™ E
5Â° 41â€™ 06.34â€™â€™ E
5Â° 43â€™ 16.93â€™â€™ E
5Â° 43â€™ 16.93â€™â€™ E
5Â° 43â€™ 16.93â€™â€™ E
5Â° 43â€™ 16.93â€™â€™ E
5Â° 43â€™ 16.93â€™â€™ E
6Â° 25â€™ 30.7â€™â€™ E
6Â° 25â€™ 30.7â€™â€™ E
6Â° 25â€™ 30.7â€™â€™ E
6Â° 25â€™ 30.7â€™â€™ E
6Â° 25â€™ 30.7â€™â€™ E
6Â° 27â€™ 14.7â€™â€™ E
6Â° 27â€™ 14.7â€™â€™ E
6Â° 27â€™ 14.7â€™â€™ E
6Â° 27â€™ 14.7â€™â€™ E
6Â° 27â€™ 14.7â€™â€™ E
5Â° 37â€™ 58.25â€™â€™ E
5Â° 37â€™ 58.25â€™â€™ E
5Â° 37â€™ 58.25â€™â€™ E
5Â° 37â€™ 58.25â€™â€™ E
5Â° 37â€™ 58.25â€™â€™ E
5Â° 37â€™ 00.25â€™â€™ E
5Â° 37â€™ 00.25â€™â€™ E
5Â° 37â€™ 00.25â€™â€™ E
5Â° 37â€™ 00.25â€™â€™ E
5Â° 37â€™ 00.25â€™â€™ E
6Â° 14â€™ 51â€™â€™ E
6Â° 14â€™ 51â€™â€™ E
6Â° 14â€™ 51â€™â€™ E
6Â° 14â€™ 51â€™â€™ E
06Â°13'54.93"E
06Â°13'54.93"E
06Â°13'54.93"E
06Â°13'54.93"E
06Â°12'29.19"E
06Â°12'29.19"E
06Â°12'29.19"E
06Â°12'29.19"E
06Â°13'29.9"E
06Â°13'29.9"E
06Â°13'29.9"E
06Â°13'29.9"E
06Â°14'20.32"E
06Â°14'20.32"E
06Â°14'20.32"E
06Â°14'20.32"E
06Â° 15' 8.63"E
06Â° 15' 8.63"E
06Â° 15' 8.63"E
06Â° 15' 8.63"E
06Â°15'43.85"E
06Â°15'43.85"E
06Â°15'43.85"E
06Â°15'43.85"E
06Â°16'58"E
06Â°16'58"E
06Â°16'58"E
06Â°16'58"E
06Â°16'19.88"E
06Â°16'19.88"E
06Â°16'19.88"E
06Â°16'19.88"E
06Â°16'13.93"E
06Â°16'13.93"E
06Â°16'13.93"E
06Â°16'13.93"E
3Â°27'19.8"E
3Â°27'19.8"E
01Â°20'
01Â°20'
01Â°20'
3Ëš1â€™39â€™â€™E
3Ëš1â€™39â€™â€™E
3Ëš1â€™39â€™â€™E
3Ëš1â€™39â€™â€™E
3Ëš1â€™39â€™â€™E
3Ëš1â€™39â€™â€™E
3Ëš1â€™41â€™â€™E
3Ëš1â€™41â€™â€™E
3Ëš1â€™41â€™â€™E
3Ëš1â€™41â€™â€™E
3Ëš1â€™41â€™â€™E
3Ëš1â€™41â€™â€™E
3Ëš5â€™3â€™â€™E
3Ëš5â€™3â€™â€™E
3Ëš5â€™3â€™â€™E
3Ëš5â€™3â€™â€™E
3Ëš5â€™0â€™â€™E
3Ëš5â€™0â€™â€™E
3Ëš5â€™0â€™â€™E
3Ëš5â€™0â€™â€™E
3Ëš5â€™0â€™â€™E
3Ëš5â€™0â€™â€™E
3Ëš4â€™54â€™â€™E
3Ëš4â€™54â€™â€™E
3Ëš4â€™54â€™â€™E
3Ëš4â€™54â€™â€™E
2Ëš56â€™18â€™â€™E
2Ëš56â€™18â€™â€™E
2Ëš56â€™18â€™â€™E
2Ëš56â€™18â€™â€™E
2Ëš56â€™18â€™â€™E
2Ëš56â€™18â€™â€™E
2Ëš56â€™25â€™â€™E
2Ëš56â€™25â€™â€™E
2Ëš56â€™25â€™â€™E
2Ëš56â€™25â€™â€™E
2Ëš56â€™25â€™â€™E
2Ëš56â€™25â€™â€™E
2Ëš56â€™27â€™â€™E
2Ëš56â€™27â€™â€™E
 4Â° 34â€˜ 6.3â€˜â€˜E
 4Â° 34â€˜ 6.3â€˜â€˜E
 4Â° 34â€˜ 6.3â€˜â€˜E
 4Â° 34â€˜ 6.3â€˜â€˜E
 4Â° 34â€˜ 6.3â€˜â€˜E
 4Â° 34â€˜ 6.3â€˜â€˜E
4Â° 34â€˜ 0.5â€˜â€˜E
4Â° 34â€˜ 0.5â€˜â€˜E
4Â° 34â€˜ 0.5â€˜â€˜E
4Â° 34â€˜ 0.5â€˜â€˜E
4Â° 34â€˜ 0.5â€˜â€˜E
4Â° 34â€˜ 0.5â€˜â€˜E
4Â° 33â€˜ 4.1â€˜â€˜E
4Â° 33â€˜ 4.1â€˜â€˜E
4Â° 33â€˜ 4.1â€˜â€˜E
4Â° 33â€˜ 4.1â€˜â€˜E
4Â° 33â€˜ 4.1â€˜â€˜E
4Â° 33â€˜ 4.1â€˜â€˜E
 4Â° 32â€˜ 21.3â€˜â€˜E
 4Â° 32â€˜ 21.3â€˜â€˜E
 4Â° 32â€˜ 21.3â€˜â€˜E
 4Â° 32â€˜ 21.3â€˜â€˜E
 4Â° 32â€˜ 21.3â€˜â€˜E
 4Â° 32â€˜ 21.3â€˜â€˜E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
 6Â°5' 6"E
5Â°56'43"E
5Â°56'43"E
5Â°56'43"E
5Â°56'43"E
5Â°56'43"E
5Â°56'43"E
5Â°56'32"E
5Â°56'32"E
5Â°56'32"E
5Â°56'32"E
5Â°56'32"E
5Â°56'32"E
5Â°56'34"E
5Â°56'34"E
5Â°56'34"E
5Â°56'34"E
5Â°56'34"E
5Â°56'34"E
5Â°58'59"E
5Â°58'59"E
5Â°58'59"E
5Â°58'59"E
5Â°58'59"E
5Â°58'59"E
5Â°33'01"E
5Â°33'01"E
5Â°33'01"E
5Â°33'01"E
5Â°32'53"E
5Â°32'53"E
5Â°32'53"E
5Â°32'53"E
5Â°32'53"E
5Â°32'53"E
5Â°32'53"E
5Â°32'53"E
5Â°33'00"E
5Â°33'00"E
5Â°33'00"E
5Â°33'00"E
6Â°23'57"E
6Â°23'57"E
6Â°23'58"E
6Â°23'58"E
6Â°23'55"E
6Â°23'55"E
2Â°50â€™ 52â€™â€™E
2Â°50â€™ 52â€™â€™E
2Â°50â€™ 52â€™â€™E
2Â°50â€™ 52â€™â€™E
2Â° 29' 34.59" E
2Â° 29' 34.59" E
2Â° 29' 34.59" E
2Â° 29' 34.59" E
2Â° 28' 45.83" E
2Â° 28' 45.83" E
2Â° 28' 45.83" E
2Â° 28' 45.83" E
2Â° 26' 32.31" E
2Â° 26' 32.31" E
2Â° 26' 32.31" E
2Â° 26' 32.31" E
2Â° 26' 36.85" E
2Â° 26' 36.85" E
2Â° 26' 36.85" E
2Â° 26' 36.85" E
2Â° 25' 55.57" E
2Â° 25' 55.57" E
2Â° 25' 55.57" E
2Â° 25' 55.57" E
2Â° 26' 36.24" E
2Â° 26' 36.24" E
2Â° 26' 36.24" E
2Â° 26' 36.24" E
2Â° 25' 52.46" E
2Â° 25' 52.46" E
2Â° 25' 52.46" E
2Â° 25' 52.46" E
2Â° 25' 46.49" E
2Â° 25' 46.49" E
2Â° 25' 46.49" E
2Â° 25' 46.49" E
2Â° 25' 40.00" E
2Â° 25' 40.00" E
2Â° 25' 40.00" E
2Â° 25' 40.00" E
2Â° 27' 9.29" E
2Â° 27' 9.29" E
2Â° 27' 9.29" E
2Â° 27' 9.29" E
2Â° 35' 45.39" E
2Â° 35' 45.39" E
2Â° 35' 45.39" E
2Â° 35' 45.39" E
2Â° 35' 44.05" E
2Â° 35' 44.05" E
2Â° 35' 44.05" E
2Â° 35' 44.05" E
2Â° 35' 21.50" E
2Â° 35' 21.50" E
2Â° 35' 21.50" E
2Â° 35' 21.50" E
2Â° 31' 24.27" E
2Â° 31' 24.27" E
2Â° 31' 24.27" E
2Â° 31' 24.27" E
2Â° 31' 39.68" E
2Â° 31' 39.68" E
2Â° 31' 39.68" E
2Â° 31' 39.68" E
2Â° 32' 34.32" E
2Â° 32' 34.32" E
2Â° 32' 34.32" E
2Â° 32' 34.32" E
2Â° 32' 34.79" E
2Â° 32' 34.79" E
2Â° 32' 34.79" E
2Â° 32' 34.79" E
2Â° 32' 35.87" E
2Â° 32' 35.87" E
2Â° 32' 35.87" E
2Â° 32' 35.87" E
2Â° 32' 36.33" E
2Â° 32' 36.33" E
2Â° 32' 36.33" E
2Â° 32' 36.33" E
2Â° 32' 53.09" E
2Â° 32' 53.09" E
2Â° 32' 53.09" E
2Â° 32' 53.09" E
2Â° 34' 2.15" E
2Â° 34' 2.15" E
2Â° 34' 2.15" E
2Â° 34' 2.15" E
2Â° 33' 53.51" E
2Â° 33' 53.51" E
2Â° 33' 53.51" E
2Â° 33' 53.51" E
2Â° 34' 24.60" E
2Â° 34' 24.60" E
2Â° 34' 24.60" E
2Â° 34' 24.60" E
2Â° 34' 33.13" E
2Â° 34' 33.13" E
2Â° 34' 33.13" E
2Â° 34' 33.13" E
2Â° 34' 7.70" E
2Â° 34' 7.70" E
2Â° 34' 7.70" E
2Â° 34' 7.70" E
2Â° 34' 6.92" E
2Â° 34' 6.92" E
2Â° 34' 6.92" E
2Â° 34' 6.92" E
2Â° 34' 26.65" E
2Â° 34' 26.65" E
2Â° 34' 26.65" E
2Â° 34' 26.65" E
2Â° 35' 51.66" E
2Â° 35' 51.66" E
2Â° 35' 51.66" E
2Â° 35' 51.66" E
2Â° 36' 42.01" E
2Â° 36' 42.01" E
2Â° 36' 42.01" E
2Â° 36' 42.01" E
2Â° 37' 43.69" E
2Â° 37' 43.69" E
2Â° 37' 43.69" E
2Â° 37' 43.69" E
2Â° 33' 54.41"E
2Â° 33' 54.41"E
2Â° 34' 54.17"E
2Â° 34' 54.17"E
2Â° 34' 55.26"E
2Â° 34' 55.26"E
2Â° 35' 1.089"E
2Â° 35' 1.089"E
2Â° 35' 10.17"E
2Â° 35' 10.17"E
2Â° 35' 14.25"E
2Â° 35' 14.25"E
2Â° 35' 23.28"E
2Â° 35' 23.28"E
2Â° 35' 42.85"E
2Â° 35' 42.85"E
2Â° 35' 40.59"E
2Â° 35' 40.59"E
2Â° 36' 45.97"E
2Â° 36' 45.97"E
2Â° 36' 22.78"E
2Â° 36' 22.78"E
2Â° 37' 42.88"E
2Â° 37' 42.88"E
2Â° 37' 52.94"E
2Â° 37' 52.94"E
2Â° 37' 55.42"E
2Â° 37' 55.42"E
2Â° 37' 31.19"E
2Â° 37' 31.19"E
2Â° 37' 46.97"E
2Â° 37' 46.97"E
2Â° 37' 33.46"E
2Â° 37' 33.46"E
2Â° 37' 58.28"E
2Â° 37' 58.28"E
2Â° 37' 35.28"E
2Â° 37' 35.28"E
2Â° 37' 52.82"E
2Â° 37' 52.82"E
4Â°47â€™17.2â€™â€™E
4Â°47â€™17.2â€™â€™E
4Â°47â€™17.2â€™â€™E
4Â°47â€™17.2â€™â€™E
4Â°47â€™17.2â€™â€™E
4Â°47â€™17.2â€™â€™E
4Â°47â€™08.6â€™â€™E
4Â°47â€™08.6â€™â€™E
4Â°47â€™08.6â€™â€™E
4Â°47â€™08.6â€™â€™E
4Â°47â€™08.6â€™â€™E
4Â°47â€™08.6â€™â€™E
4Â°37â€™ 57.1â€™â€™E
4Â°37â€™ 57.1â€™â€™E
4Â°37â€™ 57.1â€™â€™E
4Â°37â€™ 57.1â€™â€™E
4Â°37â€™ 57.1â€™â€™E
4Â°37â€™ 57.1â€™â€™E
3Â° 54â€™ 53.8â€™â€™E
3Â° 54â€™ 53.8â€™â€™E
3Â° 54â€™ 53.8â€™â€™E
3Â° 54â€™ 53.8â€™â€™E
3Â° 54â€™ 53.8â€™â€™E
3Â° 54â€™ 49.7â€™â€™E
3Â° 54â€™ 49.7â€™â€™E
3Â° 54â€™ 49.7â€™â€™E
3Â° 54â€™ 49.7â€™â€™E
3Â° 54â€™ 49.7â€™â€™E
4Â°33'23"E
4Â°33'23"E
4Â°33'23"E
4Â°33'23"E
4Â°33'23"E
4Â°33'23"E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â°44'50''E
0Â°44'50''E
0Â°44'50''E
0Â°44'50''E
0Â°44'50''E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 29â€™ 31.2â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 33â€™ 22.0â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
0Â° 44â€™ 59.6â€™â€™ E
3Â° 0â€™ 57.627â€™â€™ E
3Â° 0â€™ 57.627â€™â€™ E
3Â° 56â€™ 12.638â€™â€™ E
3Â° 56â€™ 12.638â€™â€™ E
6Â°1 0â€™ 26.081â€™â€™ E
6Â°1 0â€™ 26.081â€™â€™ E
3Â° 11â€™ 25.555â€™â€™ E
3Â° 11â€™ 25.555â€™â€™ E
3Â° 11â€™ 10.332â€™â€™ E
3Â° 11â€™ 10.332â€™â€™ E
2Â° 55â€™ 39.3â€™â€™ E
2Â° 55â€™ 39.3â€™â€™ E
5Â° 25â€™ 3.068â€™â€™ E
5Â° 25â€™ 3.068â€™â€™ E
7Â°48'12"E
7Â°48'12"E
7Â°48'12"E
7Â°48'11"E
7Â°48'11"E
7Â°48'11"E
7Â°48'17"E
7Â°48'17"E
7Â°48'17"E
7Â°48'16"E
7Â°48'16"E
7Â°48'16"E
7Â°48'21"E
7Â°48'21"E
7Â°48'21"E
7Â°48'20"E
7Â°48'20"E
7Â°48'20"E
7Â°48'29"E
7Â°48'29"E
7Â°48'29"E
7Â°48'28"E
7Â°48'28"E
7Â°48'28"E
7Â°48'35"E
7Â°48'35"E
7Â°48'35"E
7Â°41'31''E
7Â°41'31''E
7Â°41'31''E
7Â°41'39''E
7Â°41'39''E
7Â°41'39''E
7Â°41'44''E
7Â°41'44''E
7Â°41'44''E
7Â°41'54''E
7Â°41'54''E
7Â°41'54''E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
7Â° 58â€™ 93â€™â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
08Â° 12â€™ E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°20'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
8Â°10'29''E
05Â° 19' 27" E
05Â° 19' 27" E
05Â° 18' 26" E
05Â° 18' 26" E
05Â° 16' 48" E
05Â° 16' 48" E
05Â° 20' 6" E
05Â° 20' 6" E
05Â° 20' 48" E
05Â° 20' 48" E
5Â° 20' E
5Â° 20' E
5Â° 20' E
5Â° 21â€™ E
5Â° 21â€™ E
5Â° 21â€™ E
5Â°17'48"E
5Â°17'48"E
5Â°17'48"E
5Â°17'48"E
5Â°17'43"E
5Â°17'43"E
5Â°17'42"E
5Â°17'42"E
1Â°19' 22''E
1Â°19' 22''E
6Â°52'46"E
6Â°52'46"E
6Â°52'46"E
6Â°52'46"E
6Â°52'46"E
6Â°53'07"E
6Â°53'07"E
6Â°53'07"E
6Â°53'07"E
6Â°53'07"E
6Â°53'46"E
6Â°53'46"E
6Â°53'46"E
6Â°53'46"E
6Â°53'46"E
6Â°53'57"E
6Â°53'57"E
6Â°53'57"E
6Â°53'57"E
6Â°53'57"E
6Â°53'57"E
6Â°52'45"E
6Â°52'45"E
6Â°52'45"E
6Â°52'45"E
6Â°52'45"E
6Â°52'45"E
6Â°53'00"E
6Â°53'00"E
6Â°53'00"E
6Â°53'00"E
6Â°53'00"E
6Â°53'22"E
6Â°53'22"E
6Â°53'22"E
6Â°53'22"E
6Â°53'22"E
6Â°53'22"E
6Â°53'22"E
6Â°53'22"E
6Â°53'33"E
6Â°53'33"E
6Â°53'33"E
6Â°53'33"E
6Â°53'33"E
6Â°53'33"E
6Â°53'36"E
6Â°53'36"E
6Â°53'36"E
6Â°53'36"E
6Â°53'36"E
6Â°53'36"E
6Â°53'57"E
6Â°53'57"E
6Â°53'57"E
6Â°53'57"E
6Â°53'57"E
6Â°53'57"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'00"E
6Â°54'14"E
6Â°54'14"E
6Â°54'14"E
6Â°54'14"E
6Â°54'17"E
6Â°54'17"E
6Â°54'17"E
6Â°54'17"E
6Â°54'17"E
6Â°54'17"E
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [7]:
def clean_longitude(value , atr):
    val1=0 
    val2=0
    val3=0
    if isinstance(value , str):
        if atr =="Longitude":
            value = value.replace("Â°" , "°").replace("â€™â€™" , '"').replace("â€˜â€˜" ,'"').replace("''" , '"').replace("â€™" , "'").replace("â€˜" ,"'").replace("Est" , "°").replace(" ", "").replace("E", "").replace("Ëš","°")
            print(value)
        elif atr == "latitude":
            value = value.replace("Â°" , "°").replace("â€™â€™" , '"').replace("â€˜â€˜" ,'"').replace("''" , '"').replace("â€™" , "'").replace("â€˜" ,"'").replace("Nord" , "").replace(" ", "").replace("N", "").replace("Ëš","°")
            print(value)

        val1_str = value.split("°")[0]
        val1 = float(val1_str)
        result = val1 

        try : 
            new_val = value.replace(f"{val1_str}°" , "")
            val2_str = new_val.split("'")[0]
            val2 = float(val2_str)
            result +=  val2/60
            try :
                val3 = float(value.replace(f"{val1_str}°{val2_str}'" , "").split('"')[0])
                result +=  val3/3600
            except Exception as e:
                pass
        except Exception as e :
            pass
        print(f"val1-->{val1}   val2-->{val2}   val3-->{val3}")
        print(result)
        print("=======================================")
        return result

df["Longitude"]=df["Longitude"].apply(lambda x : clean_longitude(x , "Longitude"))
df["Longitude"]

3.107°
val1-->3.107   val2-->0   val3-->0
3.107
=======================================
3.107°
val1-->3.107   val2-->0   val3-->0
3.107
=======================================
3.107°
val1-->3.107   val2-->0   val3-->0
3.107
=======================================
3°08'
val1-->3.0   val2-->8.0   val3-->0
3.1333333333333333
=======================================
3°08'
val1-->3.0   val2-->8.0   val3-->0
3.1333333333333333
=======================================
3°09'00"
val1-->3.0   val2-->9.0   val3-->0.0
3.15
=======================================
3°09'00"
val1-->3.0   val2-->9.0   val3-->0.0
3.15
=======================================
2°52'49"
val1-->2.0   val2-->52.0   val3-->49.0
2.8802777777777777
=======================================
2°52'49"
val1-->2.0   val2-->52.0   val3-->49.0
2.8802777777777777
=======================================
3°10'42.1"
val1-->3.0   val2-->10.0   val3-->42.1
3.1783611111111107
=======================================
3°10'42.1"
val1-->3.0   val2-->10.0   val3-->42.1
3.1783611111111107
=======================================
3°9.573'
val1-->3.0   val2-->9.573   val3-->0
3.15955
=======================================
3°9.573'
val1-->3.0   val2-->9.573   val3-->0
3.15955
=======================================
3°9.573'
val1-->3.0   val2-->9.573   val3-->0
3.15955
=======================================
3°9.573'
val1-->3.0   val2-->9.573   val3-->0
3.15955
=======================================
3°06'05"
val1-->3.0   val2-->6.0   val3-->5.0
3.101388888888889
=======================================
3°06'05"
val1-->3.0   val2-->6.0   val3-->5.0
3.101388888888889
=======================================
6°16'26.18"
val1-->6.0   val2-->16.0   val3-->26.18
6.273938888888889
=======================================
6°16'26.18"
val1-->6.0   val2-->16.0   val3-->26.18
6.273938888888889
=======================================
6°16'26.18"
val1-->6.0   val2-->16.0   val3-->26.18
6.273938888888889
=======================================
6°16'26.18"
val1-->6.0   val2-->16.0   val3-->26.18
6.273938888888889
=======================================
6°16'26.18"
val1-->6.0   val2-->16.0   val3-->26.18
6.273938888888889
=======================================
6°18'22.9"
val1-->6.0   val2-->18.0   val3-->22.9
6.306361111111111
=======================================
6°18'22.9"
val1-->6.0   val2-->18.0   val3-->22.9
6.306361111111111
=======================================
6°18'22.9"
val1-->6.0   val2-->18.0   val3-->22.9
6.306361111111111
=======================================
6°18'22.9"
val1-->6.0   val2-->18.0   val3-->22.9
6.306361111111111
=======================================
6°18'22.9"
val1-->6.0   val2-->18.0   val3-->22.9
6.306361111111111
=======================================
5°6'05.28"
val1-->5.0   val2-->6.0   val3-->5.28
5.101466666666666
=======================================
5°6'05.28"
val1-->5.0   val2-->6.0   val3-->5.28
5.101466666666666
=======================================
5°6'05.28"
val1-->5.0   val2-->6.0   val3-->5.28
5.101466666666666
=======================================
5°6'05.28"
val1-->5.0   val2-->6.0   val3-->5.28
5.101466666666666
=======================================
5°6'05.28"
val1-->5.0   val2-->6.0   val3-->5.28
5.101466666666666
=======================================
5°08'16.05"
val1-->5.0   val2-->8.0   val3-->16.05
5.137791666666667
=======================================
5°08'16.05"
val1-->5.0   val2-->8.0   val3-->16.05
5.137791666666667
=======================================
5°08'16.05"
val1-->5.0   val2-->8.0   val3-->16.05
5.137791666666667
=======================================
5°08'16.05"
val1-->5.0   val2-->8.0   val3-->16.05
5.137791666666667
=======================================
5°08'16.05"
val1-->5.0   val2-->8.0   val3-->16.05
5.137791666666667
=======================================
5°22'11.68"
val1-->5.0   val2-->22.0   val3-->11.68
5.369911111111111
=======================================
5°22'11.68"
val1-->5.0   val2-->22.0   val3-->11.68
5.369911111111111
=======================================
5°22'11.68"
val1-->5.0   val2-->22.0   val3-->11.68
5.369911111111111
=======================================
5°22'11.68"
val1-->5.0   val2-->22.0   val3-->11.68
5.369911111111111
=======================================
5°22'11.68"
val1-->5.0   val2-->22.0   val3-->11.68
5.369911111111111
=======================================
5°23'23.53"
val1-->5.0   val2-->23.0   val3-->23.53
5.389869444444445
=======================================
5°23'23.53"
val1-->5.0   val2-->23.0   val3-->23.53
5.389869444444445
=======================================
5°23'23.53"
val1-->5.0   val2-->23.0   val3-->23.53
5.389869444444445
=======================================
5°23'23.53"
val1-->5.0   val2-->23.0   val3-->23.53
5.389869444444445
=======================================
5°23'23.53"
val1-->5.0   val2-->23.0   val3-->23.53
5.389869444444445
=======================================
5°41'06.34"
val1-->5.0   val2-->41.0   val3-->6.34
5.685094444444445
=======================================
5°41'06.34"
val1-->5.0   val2-->41.0   val3-->6.34
5.685094444444445
=======================================
5°41'06.34"
val1-->5.0   val2-->41.0   val3-->6.34
5.685094444444445
=======================================
5°41'06.34"
val1-->5.0   val2-->41.0   val3-->6.34
5.685094444444445
=======================================
5°41'06.34"
val1-->5.0   val2-->41.0   val3-->6.34
5.685094444444445
=======================================
5°43'16.93"
val1-->5.0   val2-->43.0   val3-->16.93
5.721369444444445
=======================================
5°43'16.93"
val1-->5.0   val2-->43.0   val3-->16.93
5.721369444444445
=======================================
5°43'16.93"
val1-->5.0   val2-->43.0   val3-->16.93
5.721369444444445
=======================================
5°43'16.93"
val1-->5.0   val2-->43.0   val3-->16.93
5.721369444444445
=======================================
5°43'16.93"
val1-->5.0   val2-->43.0   val3-->16.93
5.721369444444445
=======================================
6°25'30.7"
val1-->6.0   val2-->25.0   val3-->30.7
6.425194444444445
=======================================
6°25'30.7"
val1-->6.0   val2-->25.0   val3-->30.7
6.425194444444445
=======================================
6°25'30.7"
val1-->6.0   val2-->25.0   val3-->30.7
6.425194444444445
=======================================
6°25'30.7"
val1-->6.0   val2-->25.0   val3-->30.7
6.425194444444445
=======================================
6°25'30.7"
val1-->6.0   val2-->25.0   val3-->30.7
6.425194444444445
=======================================
6°27'14.7"
val1-->6.0   val2-->27.0   val3-->14.7
6.454083333333333
=======================================
6°27'14.7"
val1-->6.0   val2-->27.0   val3-->14.7
6.454083333333333
=======================================
6°27'14.7"
val1-->6.0   val2-->27.0   val3-->14.7
6.454083333333333
=======================================
6°27'14.7"
val1-->6.0   val2-->27.0   val3-->14.7
6.454083333333333
=======================================
6°27'14.7"
val1-->6.0   val2-->27.0   val3-->14.7
6.454083333333333
=======================================
5°37'58.25"
val1-->5.0   val2-->37.0   val3-->58.25
5.632847222222223
=======================================
5°37'58.25"
val1-->5.0   val2-->37.0   val3-->58.25
5.632847222222223
=======================================
5°37'58.25"
val1-->5.0   val2-->37.0   val3-->58.25
5.632847222222223
=======================================
5°37'58.25"
val1-->5.0   val2-->37.0   val3-->58.25
5.632847222222223
=======================================
5°37'58.25"
val1-->5.0   val2-->37.0   val3-->58.25
5.632847222222223
=======================================
5°37'00.25"
val1-->5.0   val2-->37.0   val3-->0.25
5.616736111111112
=======================================
5°37'00.25"
val1-->5.0   val2-->37.0   val3-->0.25
5.616736111111112
=======================================
5°37'00.25"
val1-->5.0   val2-->37.0   val3-->0.25
5.616736111111112
=======================================
5°37'00.25"
val1-->5.0   val2-->37.0   val3-->0.25
5.616736111111112
=======================================
5°37'00.25"
val1-->5.0   val2-->37.0   val3-->0.25
5.616736111111112
=======================================
6°14'51"
val1-->6.0   val2-->14.0   val3-->51.0
6.2475000000000005
=======================================
6°14'51"
val1-->6.0   val2-->14.0   val3-->51.0
6.2475000000000005
=======================================
6°14'51"
val1-->6.0   val2-->14.0   val3-->51.0
6.2475000000000005
=======================================
6°14'51"
val1-->6.0   val2-->14.0   val3-->51.0
6.2475000000000005
=======================================
06°13'54.93"
val1-->6.0   val2-->13.0   val3-->54.93
6.231925
=======================================
06°13'54.93"
val1-->6.0   val2-->13.0   val3-->54.93
6.231925
=======================================
06°13'54.93"
val1-->6.0   val2-->13.0   val3-->54.93
6.231925
=======================================
06°13'54.93"
val1-->6.0   val2-->13.0   val3-->54.93
6.231925
=======================================
06°12'29.19"
val1-->6.0   val2-->12.0   val3-->29.19
6.208108333333334
=======================================
06°12'29.19"
val1-->6.0   val2-->12.0   val3-->29.19
6.208108333333334
=======================================
06°12'29.19"
val1-->6.0   val2-->12.0   val3-->29.19
6.208108333333334
=======================================
06°12'29.19"
val1-->6.0   val2-->12.0   val3-->29.19
6.208108333333334
=======================================
06°13'29.9"
val1-->6.0   val2-->13.0   val3-->29.9
6.224972222222222
=======================================
06°13'29.9"
val1-->6.0   val2-->13.0   val3-->29.9
6.224972222222222
=======================================
06°13'29.9"
val1-->6.0   val2-->13.0   val3-->29.9
6.224972222222222
=======================================
06°13'29.9"
val1-->6.0   val2-->13.0   val3-->29.9
6.224972222222222
=======================================
06°14'20.32"
val1-->6.0   val2-->14.0   val3-->20.32
6.2389777777777775
=======================================
06°14'20.32"
val1-->6.0   val2-->14.0   val3-->20.32
6.2389777777777775
=======================================
06°14'20.32"
val1-->6.0   val2-->14.0   val3-->20.32
6.2389777777777775
=======================================
06°14'20.32"
val1-->6.0   val2-->14.0   val3-->20.32
6.2389777777777775
=======================================
06°15'8.63"
val1-->6.0   val2-->15.0   val3-->8.63
6.252397222222222
=======================================
06°15'8.63"
val1-->6.0   val2-->15.0   val3-->8.63
6.252397222222222
=======================================
06°15'8.63"
val1-->6.0   val2-->15.0   val3-->8.63
6.252397222222222
=======================================
06°15'8.63"
val1-->6.0   val2-->15.0   val3-->8.63
6.252397222222222
=======================================
06°15'43.85"
val1-->6.0   val2-->15.0   val3-->43.85
6.262180555555555
=======================================
06°15'43.85"
val1-->6.0   val2-->15.0   val3-->43.85
6.262180555555555
=======================================
06°15'43.85"
val1-->6.0   val2-->15.0   val3-->43.85
6.262180555555555
=======================================
06°15'43.85"
val1-->6.0   val2-->15.0   val3-->43.85
6.262180555555555
=======================================
06°16'58"
val1-->6.0   val2-->16.0   val3-->58.0
6.282777777777778
=======================================
06°16'58"
val1-->6.0   val2-->16.0   val3-->58.0
6.282777777777778
=======================================
06°16'58"
val1-->6.0   val2-->16.0   val3-->58.0
6.282777777777778
=======================================
06°16'58"
val1-->6.0   val2-->16.0   val3-->58.0
6.282777777777778
=======================================
06°16'19.88"
val1-->6.0   val2-->16.0   val3-->19.88
6.272188888888889
=======================================
06°16'19.88"
val1-->6.0   val2-->16.0   val3-->19.88
6.272188888888889
=======================================
06°16'19.88"
val1-->6.0   val2-->16.0   val3-->19.88
6.272188888888889
=======================================
06°16'19.88"
val1-->6.0   val2-->16.0   val3-->19.88
6.272188888888889
=======================================
06°16'13.93"
val1-->6.0   val2-->16.0   val3-->13.93
6.270536111111111
=======================================
06°16'13.93"
val1-->6.0   val2-->16.0   val3-->13.93
6.270536111111111
=======================================
06°16'13.93"
val1-->6.0   val2-->16.0   val3-->13.93
6.270536111111111
=======================================
06°16'13.93"
val1-->6.0   val2-->16.0   val3-->13.93
6.270536111111111
=======================================
3°27'19.8"
val1-->3.0   val2-->27.0   val3-->19.8
3.4555000000000002
=======================================
3°27'19.8"
val1-->3.0   val2-->27.0   val3-->19.8
3.4555000000000002
=======================================
01°20'
val1-->1.0   val2-->20.0   val3-->0
1.3333333333333333
=======================================
01°20'
val1-->1.0   val2-->20.0   val3-->0
1.3333333333333333
=======================================
01°20'
val1-->1.0   val2-->20.0   val3-->0
1.3333333333333333
=======================================
3°1'39"
val1-->3.0   val2-->1.0   val3-->39.0
3.0275
=======================================
3°1'39"
val1-->3.0   val2-->1.0   val3-->39.0
3.0275
=======================================
3°1'39"
val1-->3.0   val2-->1.0   val3-->39.0
3.0275
=======================================
3°1'39"
val1-->3.0   val2-->1.0   val3-->39.0
3.0275
=======================================
3°1'39"
val1-->3.0   val2-->1.0   val3-->39.0
3.0275
=======================================
3°1'39"
val1-->3.0   val2-->1.0   val3-->39.0
3.0275
=======================================
3°1'41"
val1-->3.0   val2-->1.0   val3-->41.0
3.0280555555555555
=======================================
3°1'41"
val1-->3.0   val2-->1.0   val3-->41.0
3.0280555555555555
=======================================
3°1'41"
val1-->3.0   val2-->1.0   val3-->41.0
3.0280555555555555
=======================================
3°1'41"
val1-->3.0   val2-->1.0   val3-->41.0
3.0280555555555555
=======================================
3°1'41"
val1-->3.0   val2-->1.0   val3-->41.0
3.0280555555555555
=======================================
3°1'41"
val1-->3.0   val2-->1.0   val3-->41.0
3.0280555555555555
=======================================
3°5'3"
val1-->3.0   val2-->5.0   val3-->3.0
3.084166666666667
=======================================
3°5'3"
val1-->3.0   val2-->5.0   val3-->3.0
3.084166666666667
=======================================
3°5'3"
val1-->3.0   val2-->5.0   val3-->3.0
3.084166666666667
=======================================
3°5'3"
val1-->3.0   val2-->5.0   val3-->3.0
3.084166666666667
=======================================
3°5'0"
val1-->3.0   val2-->5.0   val3-->0.0
3.0833333333333335
=======================================
3°5'0"
val1-->3.0   val2-->5.0   val3-->0.0
3.0833333333333335
=======================================
3°5'0"
val1-->3.0   val2-->5.0   val3-->0.0
3.0833333333333335
=======================================
3°5'0"
val1-->3.0   val2-->5.0   val3-->0.0
3.0833333333333335
=======================================
3°5'0"
val1-->3.0   val2-->5.0   val3-->0.0
3.0833333333333335
=======================================
3°5'0"
val1-->3.0   val2-->5.0   val3-->0.0
3.0833333333333335
=======================================
3°4'54"
val1-->3.0   val2-->4.0   val3-->54.0
3.081666666666667
=======================================
3°4'54"
val1-->3.0   val2-->4.0   val3-->54.0
3.081666666666667
=======================================
3°4'54"
val1-->3.0   val2-->4.0   val3-->54.0
3.081666666666667
=======================================
3°4'54"
val1-->3.0   val2-->4.0   val3-->54.0
3.081666666666667
=======================================
2°56'18"
val1-->2.0   val2-->56.0   val3-->18.0
2.9383333333333335
=======================================
2°56'18"
val1-->2.0   val2-->56.0   val3-->18.0
2.9383333333333335
=======================================
2°56'18"
val1-->2.0   val2-->56.0   val3-->18.0
2.9383333333333335
=======================================
2°56'18"
val1-->2.0   val2-->56.0   val3-->18.0
2.9383333333333335
=======================================
2°56'18"
val1-->2.0   val2-->56.0   val3-->18.0
2.9383333333333335
=======================================
2°56'18"
val1-->2.0   val2-->56.0   val3-->18.0
2.9383333333333335
=======================================
2°56'25"
val1-->2.0   val2-->56.0   val3-->25.0
2.940277777777778
=======================================
2°56'25"
val1-->2.0   val2-->56.0   val3-->25.0
2.940277777777778
=======================================
2°56'25"
val1-->2.0   val2-->56.0   val3-->25.0
2.940277777777778
=======================================
2°56'25"
val1-->2.0   val2-->56.0   val3-->25.0
2.940277777777778
=======================================
2°56'25"
val1-->2.0   val2-->56.0   val3-->25.0
2.940277777777778
=======================================
2°56'25"
val1-->2.0   val2-->56.0   val3-->25.0
2.940277777777778
=======================================
2°56'27"
val1-->2.0   val2-->56.0   val3-->27.0
2.9408333333333334
=======================================
2°56'27"
val1-->2.0   val2-->56.0   val3-->27.0
2.9408333333333334
=======================================
4°34'6.3"
val1-->4.0   val2-->34.0   val3-->6.3
4.568416666666667
=======================================
4°34'6.3"
val1-->4.0   val2-->34.0   val3-->6.3
4.568416666666667
=======================================
4°34'6.3"
val1-->4.0   val2-->34.0   val3-->6.3
4.568416666666667
=======================================
4°34'6.3"
val1-->4.0   val2-->34.0   val3-->6.3
4.568416666666667
=======================================
4°34'6.3"
val1-->4.0   val2-->34.0   val3-->6.3
4.568416666666667
=======================================
4°34'6.3"
val1-->4.0   val2-->34.0   val3-->6.3
4.568416666666667
=======================================
4°34'0.5"
val1-->4.0   val2-->34.0   val3-->0.5
4.566805555555555
=======================================
4°34'0.5"
val1-->4.0   val2-->34.0   val3-->0.5
4.566805555555555
=======================================
4°34'0.5"
val1-->4.0   val2-->34.0   val3-->0.5
4.566805555555555
=======================================
4°34'0.5"
val1-->4.0   val2-->34.0   val3-->0.5
4.566805555555555
=======================================
4°34'0.5"
val1-->4.0   val2-->34.0   val3-->0.5
4.566805555555555
=======================================
4°34'0.5"
val1-->4.0   val2-->34.0   val3-->0.5
4.566805555555555
=======================================
4°33'4.1"
val1-->4.0   val2-->33.0   val3-->4.1
4.551138888888889
=======================================
4°33'4.1"
val1-->4.0   val2-->33.0   val3-->4.1
4.551138888888889
=======================================
4°33'4.1"
val1-->4.0   val2-->33.0   val3-->4.1
4.551138888888889
=======================================
4°33'4.1"
val1-->4.0   val2-->33.0   val3-->4.1
4.551138888888889
=======================================
4°33'4.1"
val1-->4.0   val2-->33.0   val3-->4.1
4.551138888888889
=======================================
4°33'4.1"
val1-->4.0   val2-->33.0   val3-->4.1
4.551138888888889
=======================================
4°32'21.3"
val1-->4.0   val2-->32.0   val3-->21.3
4.53925
=======================================
4°32'21.3"
val1-->4.0   val2-->32.0   val3-->21.3
4.53925
=======================================
4°32'21.3"
val1-->4.0   val2-->32.0   val3-->21.3
4.53925
=======================================
4°32'21.3"
val1-->4.0   val2-->32.0   val3-->21.3
4.53925
=======================================
4°32'21.3"
val1-->4.0   val2-->32.0   val3-->21.3
4.53925
=======================================
4°32'21.3"
val1-->4.0   val2-->32.0   val3-->21.3
4.53925
=======================================
6°5'6"
val1-->6.0   val2-->5.0   val3-->6.0
6.085
=======================================
6°5'6"
val1-->6.0   val2-->5.0   val3-->6.0
6.085
=======================================
6°5'6"
val1-->6.0   val2-->5.0   val3-->6.0
6.085
=======================================
6°5'6"

0      3.107000
1      3.107000
2      3.107000
3      3.133333
4      3.133333
         ...
716         NaN
717         NaN
718         NaN
719         NaN
720         NaN
Name: Longitude, Length: 721, dtype: float64

In [8]:
for i in df["latitude"]:
    print(i)

36.684Â° Nord
36.684Â° Nord
36.684Â° Nord
36Â°N43
36Â°N43
36Â°43'27"N
36Â°43'27"N
36Â°45'27"N
36Â°45'27"N
36Â°42'14.7"N
36Â°42'14.7"N
36Â°42.319 'N
36Â°42.319 'N
36Â°42.319 'N
36Â°42.319 'N
36Â°41'02"N
36Â°41'02"N
34Â° 43â€™ 37â€™â€™ N
34Â° 43â€™ 37â€™â€™ N
34Â° 43â€™ 37â€™â€™ N
34Â° 43â€™ 37â€™â€™ N
34Â° 43â€™ 37â€™â€™ N
 34Â° 43â€™ 6.04â€™â€™ N
 34Â° 43â€™ 6.04â€™â€™ N
 34Â° 43â€™ 6.04â€™â€™ N
 34Â° 43â€™ 6.04â€™â€™ N
 34Â° 43â€™ 6.04â€™â€™ N
34 Â° 38â€™ 06.29â€™â€™ N
34 Â° 38â€™ 06.29â€™â€™ N
34 Â° 38â€™ 06.29â€™â€™ N
34 Â° 38â€™ 06.29â€™â€™ N
34 Â° 38â€™ 06.29â€™â€™ N
34Â° 38â€™ 16.88â€™â€™ N
34Â° 38â€™ 16.88â€™â€™ N
34Â° 38â€™ 16.88â€™â€™ N
34Â° 38â€™ 16.88â€™â€™ N
34Â° 38â€™ 16.88â€™â€™ N
34Â° 43â€™ 0.51â€™â€™ N
34Â° 43â€™ 0.51â€™â€™ N
34Â° 43â€™ 0.51â€™â€™ N
34Â° 43â€™ 0.51â€™â€™ N
34Â° 43â€™ 0.51â€™â€™ N
34Â° 43â€™ 47.14â€™â€™ N
34Â° 43â€™ 47.14â€™â€™ N
34Â° 43â€™ 47.14â€™â€™ N
34Â° 43â€™ 47.14â€™â€™ N
34Â° 43â€™ 47.14â€™â€™ N
34Â° 48â€™ 34.20â€™ â€™N
34Â° 48â€™ 34.20â€™ â€™N
34Â° 48â€™ 34.20â€™ â€™N
34Â° 48â€™ 34.20â€™ â€™N
34Â° 48â€™ 34.20â€™ â€™N
34Â° 48â€™ 22â€™â€™ N
34Â° 48â€™ 22â€™â€™ N
34Â° 48â€™ 22â€™â€™ N
34Â° 48â€™ 22â€™â€™ N
34Â° 48â€™ 22â€™â€™ N
34Â° 42â€™ 5.8â€™â€™ N
34Â° 42â€™ 5.8â€™â€™ N
34Â° 42â€™ 5.8â€™â€™ N
34Â° 42â€™ 5.8â€™â€™ N
34Â° 42â€™ 5.8â€™â€™ N
34Â° 41â€™ 43.71â€™â€™ N
34Â° 41â€™ 43.71â€™â€™ N
34Â° 41â€™ 43.71â€™â€™ N
34Â° 41â€™ 43.71â€™â€™ N
34Â° 41â€™ 43.71â€™â€™ N
34Â° 54â€™ 25.87â€™â€™ N
34Â° 54â€™ 25.87â€™â€™ N
34Â° 54â€™ 25.87â€™â€™ N
34Â° 54â€™ 25.87â€™â€™ N
34Â° 54â€™ 25.87â€™â€™ N
34Â° 55â€™ 15.50â€™â€™ N
34Â° 55â€™ 15.50â€™â€™ N
34Â° 55â€™ 15.50â€™â€™ N
34Â° 55â€™ 15.50â€™â€™ N
34Â° 55â€™ 15.50â€™â€™ N
35Â° 37â€™ 04â€™â€™ N
35Â° 37â€™ 04â€™â€™ N
35Â° 37â€™ 04â€™â€™ N
35Â° 37â€™ 04â€™â€™ N
35Â° 36' 30" N
35Â° 36' 30" N
35Â° 36' 30" N
35Â° 36' 30" N
35Â° 35'15.23"N
35Â° 35'15.23"N
35Â° 35'15.23"N
35Â° 35'15.23"N
35Â° 36' 9.66"N
35Â° 36' 9.66"N
35Â° 36' 9.66"N
35Â° 36' 9.66"N
35Â° 36' 37.67"N
35Â° 36' 37.67"N
35Â° 36' 37.67"N
35Â° 36' 37.67"N
35Â° 36' 29.99"N
35Â° 36' 29.99"N
35Â° 36' 29.99"N
35Â° 36' 29.99"N
35Â° 36' 39.27"N
35Â° 36' 39.27"N
35Â° 36' 39.27"N
35Â° 36' 39.27"N
35Â° 36' 50.49"N
35Â° 36' 50.49"N
35Â° 36' 50.49"N
35Â° 36' 50.49"N
35Â° 36' 58.76"N
35Â° 36' 58.76"N
35Â° 36' 58.76"N
35Â° 36' 58.76"N
35Â° 36' 34.72"N
35Â° 36' 34.72"N
35Â° 36' 34.72"N
35Â° 36' 34.72"N
36Â°45'59.5"N
36Â°45'59.5"N
36Â°30
36Â°30
36Â°30
35Ëš12â€™1â€™â€™N
35Ëš12â€™1â€™â€™N
35Ëš12â€™1â€™â€™N
35Ëš12â€™1â€™â€™N
35Ëš12â€™1â€™â€™N
35Ëš12â€™1â€™â€™N
35Ëš12â€™3â€™â€™N
35Ëš12â€™3â€™â€™N
35Ëš12â€™3â€™â€™N
35Ëš12â€™3â€™â€™N
35Ëš12â€™3â€™â€™N
35Ëš12â€™3â€™â€™N
35Ëš15â€™57â€™â€™N
35Ëš15â€™57â€™â€™N
35Ëš15â€™57â€™â€™N
35Ëš15â€™57â€™â€™N
35Ëš15â€™1â€™â€™N
35Ëš15â€™1â€™â€™N
35Ëš15â€™1â€™â€™N
35Ëš15â€™1â€™â€™N
35Ëš15â€™1â€™â€™N
35Ëš15â€™1â€™â€™N
35Ëš15â€™33â€™â€™N
35Ëš15â€™33â€™â€™N
35Ëš15â€™33â€™â€™N
35Ëš15â€™33â€™â€™N
35Ëš23â€™53â€™â€™N
35Ëš23â€™53â€™â€™N
35Ëš23â€™53â€™â€™N
35Ëš23â€™53â€™â€™N
35Ëš23â€™53â€™â€™N
35Ëš23â€™53â€™â€™N
35Ëš24â€™9â€™â€™N
35Ëš24â€™9â€™â€™N
35Ëš24â€™9â€™â€™N
35Ëš24â€™9â€™â€™N
35Ëš24â€™9â€™â€™N
35Ëš24â€™9â€™â€™N
35Ëš23â€™58â€™â€™N
35Ëš23â€™58â€™â€™N
35Â° 20â€˜ 55.0â€˜â€˜N
35Â° 20â€˜ 55.0â€˜â€˜N
35Â° 20â€˜ 55.0â€˜â€˜N
35Â° 20â€˜ 55.0â€˜â€˜N
35Â° 20â€˜ 55.0â€˜â€˜N
35Â° 20â€˜ 55.0â€˜â€˜N
 35Â° 20â€˜ 57.2â€˜â€˜ N
 35Â° 20â€˜ 57.2â€˜â€˜ N
 35Â° 20â€˜ 57.2â€˜â€˜ N
 35Â° 20â€˜ 57.2â€˜â€˜ N
 35Â° 20â€˜ 57.2â€˜â€˜ N
 35Â° 20â€˜ 57.2â€˜â€˜ N
35Â° 20â€˜ 56.5â€˜â€˜N
35Â° 20â€˜ 56.5â€˜â€˜N
35Â° 20â€˜ 56.5â€˜â€˜N
35Â° 20â€˜ 56.5â€˜â€˜N
35Â° 20â€˜ 56.5â€˜â€˜N
35Â° 20â€˜ 56.5â€˜â€˜N
 35Â° 20â€˜ 59.0â€˜â€˜N
 35Â° 20â€˜ 59.0â€˜â€˜N
 35Â° 20â€˜ 59.0â€˜â€˜N
 35Â° 20â€˜ 59.0â€˜â€˜N
 35Â° 20â€˜ 59.0â€˜â€˜N
 35Â° 20â€˜ 59.0â€˜â€˜N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°53' 28" N
36Â°48'12"N
36Â°48'12"N
36Â°48'12"N
36Â°48'12"N
36Â°48'12"N
36Â°48'12"N
36Â°48'27"N
36Â°48'27"N
36Â°48'27"N
36Â°48'27"N
36Â°48'27"N
36Â°48'27"N
36Â°48'18"N
36Â°48'18"N
36Â°48'18"N
36Â°48'18"N
36Â°48'18"N
36Â°48'18"N
36Â°50'03"N
36Â°50'03"N
36Â°50'03"N
36Â°50'03"N
36Â°50'03"N
36Â°50'03"N
36Â°42'38"N
36Â°42'38"N
36Â°42'38"N
36Â°42'38"N
36Â°42'33"N
36Â°42'33"N
36Â°42'33"N
36Â°42'33"N
36Â°42'29"N
36Â°42'29"N
36Â°42'29"N
36Â°42'29"N
36Â°42'28"N
36Â°42'28"N
36Â°42'28"N
36Â°42'28"N
36Â°44'33"N
36Â°44'33"N
36Â°44'30"N
36Â°44'30"N
36Â°44'31"N
36Â°44'31"N
36Â° 11â€™ 56â€™â€™N
36Â° 11â€™ 56â€™â€™N
36Â° 11â€™ 56â€™â€™N
36Â° 11â€™ 56â€™â€™N
36Â° 32' 37.87" N
36Â° 32' 37.87" N
36Â° 32' 37.87" N
36Â° 32' 37.87" N
36Â° 32' 42.82" N
36Â° 32' 42.82" N
36Â° 32' 42.82" N
36Â° 32' 42.82" N
36Â° 32' 5.60" N
36Â° 32' 5.60" N
36Â° 32' 5.60" N
36Â° 32' 5.60" N
36Â° 31' 43.33" N
36Â° 31' 43.33" N
36Â° 31' 43.33" N
36Â° 31' 43.33" N
36Â° 30' 29.56" N
36Â° 30' 29.56" N
36Â° 30' 29.56" N
36Â° 30' 29.56" N
36Â° 30' 23.06" N
36Â° 30' 23.06" N
36Â° 30' 23.06" N
36Â° 30' 23.06" N
36Â° 30' 45.15" N
36Â° 30' 45.15" N
36Â° 30' 45.15" N
36Â° 30' 45.15" N
36Â° 30' 51.052" N
36Â° 30' 51.052" N
36Â° 30' 51.052" N
36Â° 30' 51.052" N
36Â° 30' 55.94" N
36Â° 30' 55.94" N
36Â° 30' 55.94" N
36Â° 30' 55.94" N
36Â° 30' 32.17" N
36Â° 30' 32.17" N
36Â° 30' 32.17" N
36Â° 30' 32.17" N
36Â° 33' 48.60" N
36Â° 33' 48.60" N
36Â° 33' 48.60" N
36Â° 33' 48.60" N
36Â° 34' 2.36" N
36Â° 34' 2.36" N
36Â° 34' 2.36" N
36Â° 34' 2.36" N
36Â° 34' 10.21" N
36Â° 34' 10.21" N
36Â° 34' 10.21" N
36Â° 34' 10.21" N
36Â° 33' 18.42" N
36Â° 33' 18.42" N
36Â° 33' 18.42" N
36Â° 33' 18.42" N
36Â° 33' 2.15" N
36Â° 33' 2.15" N
36Â° 33' 2.15" N
36Â° 33' 2.15" N
36Â° 31' 56.17" N
36Â° 31' 56.17" N
36Â° 31' 56.17" N
36Â° 31' 56.17" N
36Â° 31' 45.69" N
36Â° 31' 45.69" N
36Â° 31' 45.69" N
36Â° 31' 45.69" N
36Â° 31' 36.64" N
36Â° 31' 36.64" N
36Â° 31' 36.64" N
36Â° 31' 36.64" N
36Â° 31' 26.41" N
36Â° 31' 26.41" N
36Â° 31' 26.41" N
36Â° 31' 26.41" N
36Â° 31' 16.78" N
36Â° 31' 16.78" N
36Â° 31' 16.78" N
36Â° 31' 16.78" N
36Â° 30' 34.43" N
36Â° 30' 34.43" N
36Â° 30' 34.43" N
36Â° 30' 34.43" N
36Â° 30' 30.44" N
36Â° 30' 30.44" N
36Â° 30' 30.44" N
36Â° 30' 30.44" N
36Â° 30' 30.94" N
36Â° 30' 30.94" N
36Â° 30' 30.94" N
36Â° 30' 30.94" N
36Â° 30' 26.12" N
36Â° 30' 26.12" N
36Â° 30' 26.12" N
36Â° 30' 26.12" N
36Â° 29' 40.61" N
36Â° 29' 40.61" N
36Â° 29' 40.61" N
36Â° 29' 40.61" N
36Â° 29' 25.62" N
36Â° 29' 25.62" N
36Â° 29' 25.62" N
36Â° 29' 25.62" N
36Â° 28' 29.79" N
36Â° 28' 29.79" N
36Â° 28' 29.79" N
36Â° 28' 29.79" N
36Â° 28' 13.97" N
36Â° 28' 13.97" N
36Â° 28' 13.97" N
36Â° 28' 13.97" N
36Â° 28' 17.42" N
36Â° 28' 17.42" N
36Â° 28' 17.42" N
36Â° 28' 17.42" N
36Â° 31' 6.17" N
36Â° 31' 6.17" N
36Â° 31' 6.17" N
36Â° 31' 6.17" N
36Â° 29' 19.28"N
36Â° 29' 19.28"N
36Â° 28' 30.56"N
36Â° 28' 30.56"N
36Â° 28' 22.93"N
36Â° 28' 22.93"N
36Â° 28' 15.28"N
36Â° 28' 15.28"N
36Â° 28' 8.55"N
36Â° 28' 8.55"N
36Â° 28' 26.61"N
36Â° 28' 26.61"N
36Â° 28' 16.07"N
36Â° 28' 16.07"N
36Â° 28' 42.11"N
36Â° 28' 42.11"N
36Â° 28' 50.93"N
36Â° 28' 50.93"N
36Â° 28' 26.43"N
36Â° 28' 26.43"N
36Â° 28' 18.27"N
36Â° 28' 18.27"N
36Â° 28' 34.35"N
36Â° 28' 34.35"N
36Â° 28' 34.03"N
36Â° 28' 34.03"N
36Â° 28' 42.34"N
36Â° 28' 42.34"N
36Â° 28' 45.38"N
36Â° 28' 45.38"N
36Â° 28' 52.88"N
36Â° 28' 52.88"N
36Â° 29' 0.12"N
36Â° 29' 0.12"N
36Â° 28' 57.55"N
36Â° 28' 57.55"N
36Â° 30' 56.71"N
36Â° 30' 56.71"N
36Â° 30' 39.93"N
36Â° 30' 39.93"N
35Â°17â€™56.4â€™â€™N
35Â°17â€™56.4â€™â€™N
35Â°17â€™56.4â€™â€™N
35Â°17â€™56.4â€™â€™N
35Â°17â€™56.4â€™â€™N
35Â°17â€™56.4â€™â€™N
35Â°15â€™51.3â€™â€™N
35Â°15â€™51.3â€™â€™N
35Â°15â€™51.3â€™â€™N
35Â°15â€™51.3â€™â€™N
35Â°15â€™51.3â€™â€™N
35Â°15â€™51.3â€™â€™N
35Â°19â€™59.2â€™â€™N
35Â°19â€™59.2â€™â€™N
35Â°19â€™59.2â€™â€™N
35Â°19â€™59.2â€™â€™N
35Â°19â€™59.2â€™â€™N
35Â°19â€™59.2â€™â€™N
35Â° 01â€™ 47.2â€™â€™N
35Â° 01â€™ 47.2â€™â€™N
35Â° 01â€™ 47.2â€™â€™N
35Â° 01â€™ 47.2â€™â€™N
35Â° 01â€™ 47.2â€™â€™N
35Â° 01â€™ 44.9â€™â€™N
35Â° 01â€™ 44.9â€™â€™N
35Â° 01â€™ 44.9â€™â€™N
35Â° 01â€™ 44.9â€™â€™N
35Â° 01â€™ 44.9â€™â€™N
35Â°44'24"N
35Â°44'24"N
35Â°44'24"N
35Â°44'24"N
35Â°44'24"N
35Â°44'24"N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
 35Â° 47â€™ 44.33â€™â€™ N
 35Â° 47â€™ 44.33â€™â€™ N
 35Â° 47â€™ 44.33â€™â€™ N
 35Â° 47â€™ 44.33â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â°57'49''N
35Â°57'49''N
35Â°57'49''N
35Â°57'49''N
35Â°57'49''N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 44â€™ 17.0â€™â€™ N
35Â° 47â€™ 44.33â€™â€™ N
35Â° 47â€™ 44.33â€™â€™ N
35Â° 47â€™ 44.33â€™â€™ N
35Â° 47â€™ 44.33â€™â€™ N
35Â° 47â€™ 44.33â€™â€™ N
35Â° 47â€™ 44.33â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
35Â° 57â€™ 47.5â€™â€™ N
36Â° 48â€™ 53.426â€™â€™ N
36Â° 48â€™ 53.426â€™â€™ N
36Â° 52â€™ 42.096â€™â€™ N
36Â° 52â€™ 42.096â€™â€™ N
35Â° 33â€™ 39.687â€™â€™ N
35Â° 33â€™ 39.687â€™â€™ N
36Â° 44â€™ 49.873â€™â€™ N
36Â° 44â€™ 49.873â€™â€™ N
36Â° 42â€™ 25.409â€™â€™ N
36Â° 42â€™ 25.409â€™â€™ N
36Â° 38â€™ 56.739â€™â€™ N
36Â° 38â€™ 56.739â€™â€™ N
36Â° 9â€™ 35.232â€™â€™ N
36Â° 9â€™ 35.232â€™â€™ N
36Â°46'55"N
36Â°46'55"N
36Â°46'55"N
36Â°46'51"N
36Â°46'51"N
36Â°46'51"N
36Â°46'55"N
36Â°46'55"N
36Â°46'55"N
36Â°46'51"N
36Â°46'51"N
36Â°46'51"N
36Â°46'54"N
36Â°46'54"N
36Â°46'54"N
36Â°46'50"N
36Â°46'50"N
36Â°46'50"N
36Â°46'53"N
36Â°46'53"N
36Â°46'53"N
36Â°46'49"N
36Â°46'49"N
36Â°46'49"N
36Â°46'50"N
36Â°46'50"N
36Â°46'50"N
36Â°46'54''N
36Â°46'54''N
36Â°46'54''N
36Â°46'55''N
36Â°46'55''N
36Â°46'55''N
36Â°46'59''N
36Â°46'59''N
36Â°46'59''N
36Â°46'52''N
36Â°46'52''N
36Â°46'52''N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â° 50â€™ 55â€™â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54â€™N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°54'17''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â°50'38''N
36Â° 04' 39" N
36Â° 04' 39" N
36Â° 04' 29" N
36Â° 04' 29" N
35Â° 56' 45" N
35Â° 56' 45" N
36Â° 03' 57" N
36Â° 03' 57" N
36Â° 07' 30" N
36Â° 07' 30" N
36Â° 08' N
36Â° 08' N
36Â° 08' N
36Â° 9â€™ N
36Â° 9â€™ N
36Â° 9â€™ N
36Â°04'33"N
36Â°04'33"N
36Â°04'31"N
36Â°04'31"N
36Â°04'27"N
36Â°04'27"N
36Â°04'28"N
36Â°04'28"N
35Â°23' 17''N
35Â°23' 17''N
36Â°51'03"N
36Â°51'03"N
36Â°51'03"N
36Â°51'03"N
36Â°51'03"N
36Â°50'53"N
36Â°50'53"N
36Â°50'53"N
36Â°50'53"N
36Â°50'53"N
36Â°50'51"N
36Â°50'51"N
36Â°50'51"N
36Â°50'51"N
36Â°50'51"N
36Â°50'48"N
36Â°50'48"N
36Â°50'48"N
36Â°50'48"N
36Â°50'48"N
36Â°50'48"N
36Â°50'54"N
36Â°50'54"N
36Â°50'54"N
36Â°50'54"N
36Â°50'54"N
36Â°50'54"N
36Â°51'02"N
36Â°51'02"N
36Â°51'02"N
36Â°51'02"N
36Â°51'02"N
36Â°51'45"N
36Â°51'45"N
36Â°51'45"N
36Â°51'45"N
36Â°51'45"N
36Â°51'45"N
36Â°51'45"N
36Â°51'45"N
36Â°51'48"N
36Â°51'48"N
36Â°51'48"N
36Â°51'48"N
36Â°51'48"N
36Â°51'48"N
36Â°51'38"N
36Â°51'38"N
36Â°51'38"N
36Â°51'38"N
36Â°51'38"N
36Â°51'38"N
36Â°50'54"N
36Â°50'54"N
36Â°50'54"N
36Â°50'54"N
36Â°50'54"N
36Â°50'54"N
36Â°50'56"N
36Â°50'56"N
36Â°50'56"N
36Â°50'56"N
36Â°50'56"N
36Â°50'56"N
36Â°50'48"N
36Â°50'48"N
36Â°50'48"N
36Â°50'48"N
36Â°50'48"N
36Â°50'48"N
36Â°50'50"N
36Â°50'50"N
36Â°50'50"N
36Â°50'50"N
36Â°50'50"N
36Â°50'50"N
36Â°50'50"N
36Â°50'50"N
36Â°50'50"N
36Â°50'50"N
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [9]:
df["latitude"]=df["latitude"].apply(lambda x : clean_longitude(x , "latitude"))
df["latitude"]

36.684°

val1-->36.684   val2-->0   val3-->0
36.684
=======================================
36.684°
val1-->36.684   val2-->0   val3-->0
36.684
=======================================
36.684°
val1-->36.684   val2-->0   val3-->0
36.684
=======================================
36°43
val1-->36.0   val2-->43.0   val3-->0
36.71666666666667
=======================================
36°43
val1-->36.0   val2-->43.0   val3-->0
36.71666666666667
=======================================
36°43'27"
val1-->36.0   val2-->43.0   val3-->27.0
36.72416666666667
=======================================
36°43'27"
val1-->36.0   val2-->43.0   val3-->27.0
36.72416666666667
=======================================
36°45'27"
val1-->36.0   val2-->45.0   val3-->27.0
36.7575
=======================================
36°45'27"
val1-->36.0   val2-->45.0   val3-->27.0
36.7575
=======================================
36°42'14.7"
val1-->36.0   val2-->42.0   val3-->14.7
36.70408333333334
=======================================
36°42'14.7"
val1-->36.0   val2-->42.0   val3-->14.7
36.70408333333334
=======================================
36°42.319'
val1-->36.0   val2-->42.319   val3-->0
36.70531666666667
=======================================
36°42.319'
val1-->36.0   val2-->42.319   val3-->0
36.70531666666667
=======================================
36°42.319'
val1-->36.0   val2-->42.319   val3-->0
36.70531666666667
=======================================
36°42.319'
val1-->36.0   val2-->42.319   val3-->0
36.70531666666667
=======================================
36°41'02"
val1-->36.0   val2-->41.0   val3-->2.0
36.68388888888889
=======================================
36°41'02"
val1-->36.0   val2-->41.0   val3-->2.0
36.68388888888889
=======================================
34°43'37"
val1-->34.0   val2-->43.0   val3-->37.0
34.72694444444445
=======================================
34°43'37"
val1-->34.0   val2-->43.0   val3-->37.0
34.72694444444445
=======================================
34°43'37"
val1-->34.0   val2-->43.0   val3-->37.0
34.72694444444445
=======================================
34°43'37"
val1-->34.0   val2-->43.0   val3-->37.0
34.72694444444445
=======================================
34°43'37"
val1-->34.0   val2-->43.0   val3-->37.0
34.72694444444445
=======================================
34°43'6.04"
val1-->34.0   val2-->43.0   val3-->6.04
34.71834444444445
=======================================
34°43'6.04"
val1-->34.0   val2-->43.0   val3-->6.04
34.71834444444445
=======================================
34°43'6.04"
val1-->34.0   val2-->43.0   val3-->6.04
34.71834444444445
=======================================
34°43'6.04"
val1-->34.0   val2-->43.0   val3-->6.04
34.71834444444445
=======================================
34°43'6.04"
val1-->34.0   val2-->43.0   val3-->6.04
34.71834444444445
=======================================
34°38'06.29"
val1-->34.0   val2-->38.0   val3-->6.29
34.635080555555554
=======================================
34°38'06.29"
val1-->34.0   val2-->38.0   val3-->6.29
34.635080555555554
=======================================
34°38'06.29"
val1-->34.0   val2-->38.0   val3-->6.29
34.635080555555554
=======================================
34°38'06.29"
val1-->34.0   val2-->38.0   val3-->6.29
34.635080555555554
=======================================
34°38'06.29"
val1-->34.0   val2-->38.0   val3-->6.29
34.635080555555554
=======================================
34°38'16.88"
val1-->34.0   val2-->38.0   val3-->16.88
34.63802222222222
=======================================
34°38'16.88"
val1-->34.0   val2-->38.0   val3-->16.88
34.63802222222222
=======================================
34°38'16.88"
val1-->34.0   val2-->38.0   val3-->16.88
34.63802222222222
=======================================
34°38'16.88"
val1-->34.0   val2-->38.0   val3-->16.88
34.63802222222222
=======================================
34°38'16.88"
val1-->34.0   val2-->38.0   val3-->16.88
34.63802222222222
=======================================
34°43'0.51"
val1-->34.0   val2-->43.0   val3-->0.51
34.71680833333333
=======================================
34°43'0.51"
val1-->34.0   val2-->43.0   val3-->0.51
34.71680833333333
=======================================
34°43'0.51"
val1-->34.0   val2-->43.0   val3-->0.51
34.71680833333333
=======================================
34°43'0.51"
val1-->34.0   val2-->43.0   val3-->0.51
34.71680833333333
=======================================
34°43'0.51"
val1-->34.0   val2-->43.0   val3-->0.51
34.71680833333333
=======================================
34°43'47.14"
val1-->34.0   val2-->43.0   val3-->47.14
34.72976111111111
=======================================
34°43'47.14"
val1-->34.0   val2-->43.0   val3-->47.14
34.72976111111111
=======================================
34°43'47.14"
val1-->34.0   val2-->43.0   val3-->47.14
34.72976111111111
=======================================
34°43'47.14"
val1-->34.0   val2-->43.0   val3-->47.14
34.72976111111111
=======================================
34°43'47.14"
val1-->34.0   val2-->43.0   val3-->47.14
34.72976111111111
=======================================
34°48'34.20''
val1-->34.0   val2-->48.0   val3-->0
34.8
=======================================
34°48'34.20''
val1-->34.0   val2-->48.0   val3-->0
34.8
=======================================
34°48'34.20''
val1-->34.0   val2-->48.0   val3-->0
34.8
=======================================
34°48'34.20''
val1-->34.0   val2-->48.0   val3-->0
34.8
=======================================
34°48'34.20''
val1-->34.0   val2-->48.0   val3-->0
34.8
=======================================
34°48'22"
val1-->34.0   val2-->48.0   val3-->22.0
34.80611111111111
=======================================
34°48'22"
val1-->34.0   val2-->48.0   val3-->22.0
34.80611111111111
=======================================
34°48'22"
val1-->34.0   val2-->48.0   val3-->22.0
34.80611111111111
=======================================
34°48'22"
val1-->34.0   val2-->48.0   val3-->22.0
34.80611111111111
=======================================
34°48'22"
val1-->34.0   val2-->48.0   val3-->22.0
34.80611111111111
=======================================
34°42'5.8"
val1-->34.0   val2-->42.0   val3-->5.8
34.70161111111111
=======================================
34°42'5.8"
val1-->34.0   val2-->42.0   val3-->5.8
34.70161111111111
=======================================
34°42'5.8"
val1-->34.0   val2-->42.0   val3-->5.8
34.70161111111111
=======================================
34°42'5.8"
val1-->34.0   val2-->42.0   val3-->5.8
34.70161111111111
=======================================
34°42'5.8"
val1-->34.0   val2-->42.0   val3-->5.8
34.70161111111111
=======================================
34°41'43.71"
val1-->34.0   val2-->41.0   val3-->43.71
34.695474999999995
=======================================
34°41'43.71"
val1-->34.0   val2-->41.0   val3-->43.71
34.695474999999995
=======================================
34°41'43.71"
val1-->34.0   val2-->41.0   val3-->43.71
34.695474999999995
=======================================
34°41'43.71"
val1-->34.0   val2-->41.0   val3-->43.71
34.695474999999995
=======================================
34°41'43.71"
val1-->34.0   val2-->41.0   val3-->43.71
34.695474999999995
=======================================
34°54'25.87"
val1-->34.0   val2-->54.0   val3-->25.87
34.90718611111111
=======================================
34°54'25.87"
val1-->34.0   val2-->54.0   val3-->25.87
34.90718611111111
=======================================
34°54'25.87"
val1-->34.0   val2-->54.0   val3-->25.87
34.90718611111111
=======================================
34°54'25.87"
val1-->34.0   val2-->54.0   val3-->25.87
34.90718611111111
=======================================
34°54'25.87"
val1-->34.0   val2-->54.0   val3-->25.87
34.90718611111111
=======================================
34°55'15.50"
val1-->34.0   val2-->55.0   val3-->15.5
34.92097222222222
=======================================
34°55'15.50"
val1-->34.0   val2-->55.0   val3-->15.5
34.92097222222222
=======================================
34°55'15.50"
val1-->34.0   val2-->55.0   val3-->15.5
34.92097222222222
=======================================
34°55'15.50"
val1-->34.0   val2-->55.0   val3-->15.5
34.92097222222222
=======================================
34°55'15.50"
val1-->34.0   val2-->55.0   val3-->15.5
34.92097222222222
=======================================
35°37'04"
val1-->35.0   val2-->37.0   val3-->4.0
35.617777777777775
=======================================
35°37'04"
val1-->35.0   val2-->37.0   val3-->4.0
35.617777777777775
=======================================
35°37'04"
val1-->35.0   val2-->37.0   val3-->4.0
35.617777777777775
=======================================
35°37'04"
val1-->35.0   val2-->37.0   val3-->4.0
35.617777777777775
=======================================
35°36'30"
val1-->35.0   val2-->36.0   val3-->30.0
35.608333333333334
=======================================
35°36'30"
val1-->35.0   val2-->36.0   val3-->30.0
35.608333333333334
=======================================
35°36'30"
val1-->35.0   val2-->36.0   val3-->30.0
35.608333333333334
=======================================
35°36'30"
val1-->35.0   val2-->36.0   val3-->30.0
35.608333333333334
=======================================
35°35'15.23"
val1-->35.0   val2-->35.0   val3-->15.23
35.587563888888894
=======================================
35°35'15.23"
val1-->35.0   val2-->35.0   val3-->15.23
35.587563888888894
=======================================
35°35'15.23"
val1-->35.0   val2-->35.0   val3-->15.23
35.587563888888894
=======================================
35°35'15.23"
val1-->35.0   val2-->35.0   val3-->15.23
35.587563888888894
=======================================
35°36'9.66"
val1-->35.0   val2-->36.0   val3-->9.66
35.60268333333333
=======================================
35°36'9.66"
val1-->35.0   val2-->36.0   val3-->9.66
35.60268333333333
=======================================
35°36'9.66"
val1-->35.0   val2-->36.0   val3-->9.66
35.60268333333333
=======================================
35°36'9.66"
val1-->35.0   val2-->36.0   val3-->9.66
35.60268333333333
=======================================
35°36'37.67"
val1-->35.0   val2-->36.0   val3-->37.67
35.61046388888889
=======================================
35°36'37.67"
val1-->35.0   val2-->36.0   val3-->37.67
35.61046388888889
=======================================
35°36'37.67"
val1-->35.0   val2-->36.0   val3-->37.67
35.61046388888889
=======================================
35°36'37.67"
val1-->35.0   val2-->36.0   val3-->37.67
35.61046388888889
=======================================
35°36'29.99"
val1-->35.0   val2-->36.0   val3-->29.99
35.608330555555554
=======================================
35°36'29.99"
val1-->35.0   val2-->36.0   val3-->29.99
35.608330555555554
=======================================
35°36'29.99"
val1-->35.0   val2-->36.0   val3-->29.99
35.608330555555554
=======================================
35°36'29.99"
val1-->35.0   val2-->36.0   val3-->29.99
35.608330555555554
=======================================
35°36'39.27"
val1-->35.0   val2-->36.0   val3-->39.27
35.610908333333334
=======================================
35°36'39.27"
val1-->35.0   val2-->36.0   val3-->39.27
35.610908333333334
=======================================
35°36'39.27"
val1-->35.0   val2-->36.0   val3-->39.27
35.610908333333334
=======================================
35°36'39.27"
val1-->35.0   val2-->36.0   val3-->39.27
35.610908333333334
=======================================
35°36'50.49"
val1-->35.0   val2-->36.0   val3-->50.49
35.614025
=======================================
35°36'50.49"
val1-->35.0   val2-->36.0   val3-->50.49
35.614025
=======================================
35°36'50.49"
val1-->35.0   val2-->36.0   val3-->50.49
35.614025
=======================================
35°36'50.49"
val1-->35.0   val2-->36.0   val3-->50.49
35.614025
=======================================
35°36'58.76"
val1-->35.0   val2-->36.0   val3-->58.76
35.61632222222222
=======================================
35°36'58.76"
val1-->35.0   val2-->36.0   val3-->58.76
35.61632222222222
=======================================
35°36'58.76"
val1-->35.0   val2-->36.0   val3-->58.76
35.61632222222222
=======================================
35°36'58.76"
val1-->35.0   val2-->36.0   val3-->58.76
35.61632222222222
=======================================
35°36'34.72"
val1-->35.0   val2-->36.0   val3-->34.72
35.60964444444445
=======================================
35°36'34.72"
val1-->35.0   val2-->36.0   val3-->34.72
35.60964444444445
=======================================
35°36'34.72"
val1-->35.0   val2-->36.0   val3-->34.72
35.60964444444445
=======================================
35°36'34.72"
val1-->35.0   val2-->36.0   val3-->34.72
35.60964444444445
=======================================
36°45'59.5"
val1-->36.0   val2-->45.0   val3-->59.5
36.766527777777775
=======================================
36°45'59.5"
val1-->36.0   val2-->45.0   val3-->59.5
36.766527777777775
=======================================
36°30
val1-->36.0   val2-->30.0   val3-->0
36.5
=======================================
36°30
val1-->36.0   val2-->30.0   val3-->0
36.5
=======================================
36°30
val1-->36.0   val2-->30.0   val3-->0
36.5
=======================================
35°12'1"
val1-->35.0   val2-->12.0   val3-->1.0
35.20027777777778
=======================================
35°12'1"
val1-->35.0   val2-->12.0   val3-->1.0
35.20027777777778
=======================================
35°12'1"
val1-->35.0   val2-->12.0   val3-->1.0
35.20027777777778
=======================================
35°12'1"
val1-->35.0   val2-->12.0   val3-->1.0
35.20027777777778
=======================================
35°12'1"
val1-->35.0   val2-->12.0   val3-->1.0
35.20027777777778
=======================================
35°12'1"
val1-->35.0   val2-->12.0   val3-->1.0
35.20027777777778
=======================================
35°12'3"
val1-->35.0   val2-->12.0   val3-->3.0
35.200833333333335
=======================================
35°12'3"
val1-->35.0   val2-->12.0   val3-->3.0
35.200833333333335
=======================================
35°12'3"
val1-->35.0   val2-->12.0   val3-->3.0
35.200833333333335
=======================================
35°12'3"
val1-->35.0   val2-->12.0   val3-->3.0
35.200833333333335
=======================================
35°12'3"
val1-->35.0   val2-->12.0   val3-->3.0
35.200833333333335
=======================================
35°12'3"
val1-->35.0   val2-->12.0   val3-->3.0
35.200833333333335
=======================================
35°15'57"
val1-->35.0   val2-->15.0   val3-->57.0
35.26583333333333
=======================================
35°15'57"
val1-->35.0   val2-->15.0   val3-->57.0
35.26583333333333
=======================================
35°15'57"
val1-->35.0   val2-->15.0   val3-->57.0
35.26583333333333
=======================================
35°15'57"
val1-->35.0   val2-->15.0   val3-->57.0
35.26583333333333
=======================================
35°15'1"
val1-->35.0   val2-->15.0   val3-->1.0
35.250277777777775
=======================================
35°15'1"
val1-->35.0   val2-->15.0   val3-->1.0
35.250277777777775
=======================================
35°15'1"
val1-->35.0   val2-->15.0   val3-->1.0
35.250277777777775
=======================================
35°15'1"
val1-->35.0   val2-->15.0   val3-->1.0
35.250277777777775
=======================================
35°15'1"
val1-->35.0   val2-->15.0   val3-->1.0
35.250277777777775
=======================================
35°15'1"
val1-->35.0   val2-->15.0   val3-->1.0
35.250277777777775
=======================================
35°15'33"
val1-->35.0   val2-->15.0   val3-->33.0
35.259166666666665
=======================================
35°15'33"
val1-->35.0   val2-->15.0   val3-->33.0
35.259166666666665
=======================================
35°15'33"
val1-->35.0   val2-->15.0   val3-->33.0
35.259166666666665
=======================================
35°15'33"
val1-->35.0   val2-->15.0   val3-->33.0
35.259166666666665
=======================================
35°23'53"
val1-->35.0   val2-->23.0   val3-->53.0
35.39805555555556
=======================================
35°23'53"
val1-->35.0   val2-->23.0   val3-->53.0
35.39805555555556
=======================================
35°23'53"
val1-->35.0   val2-->23.0   val3-->53.0
35.39805555555556
=======================================
35°23'53"
val1-->35.0   val2-->23.0   val3-->53.0
35.39805555555556
=======================================
35°23'53"
val1-->35.0   val2-->23.0   val3-->53.0
35.39805555555556
=======================================
35°23'53"
val1-->35.0   val2-->23.0   val3-->53.0
35.39805555555556
=======================================
35°24'9"
val1-->35.0   val2-->24.0   val3-->9.0
35.402499999999996
=======================================
35°24'9"
val1-->35.0   val2-->24.0   val3-->9.0
35.402499999999996
=======================================
35°24'9"
val1-->35.0   val2-->24.0   val3-->9.0
35.402499999999996
=======================================
35°24'9"
val1-->35.0   val2-->24.0   val3-->9.0
35.402499999999996
=======================================
35°24'9"
val1-->35.0   val2-->24.0   val3-->9.0
35.402499999999996
=======================================
35°24'9"
val1-->35.0   val2-->24.0   val3-->9.0
35.402499999999996
=======================================
35°23'58"
val1-->35.0   val2-->23.0   val3-->58.0
35.39944444444444
=======================================
35°23'58"
val1-->35.0   val2-->23.0   val3-->58.0
35.39944444444444
=======================================
35°20'55.0"
val1-->35.0   val2-->20.0   val3-->55.0
35.34861111111111
=======================================
35°20'55.0"
val1-->35.0   val2-->20.0   val3-->55.0
35.34861111111111
=======================================
35°20'55.0"
val1-->35.0   val2-->20.0   val3-->55.0
35.34861111111111
=======================================
35°20'55.0"
val1-->35.0   val2-->20.0   val3-->55.0
35.34861111111111
=======================================
35°20'55.0"
val1-->35.0   val2-->20.0   val3-->55.0
35.34861111111111
=======================================
35°20'55.0"
val1-->35.0   val2-->20.0   val3-->55.0
35.34861111111111
=======================================
35°20'57.2"
val1-->35.0   val2-->20.0   val3-->57.2
35.349222222222224
=======================================
35°20'57.2"
val1-->35.0   val2-->20.0   val3-->57.2
35.349222222222224
=======================================
35°20'57.2"
val1-->35.0   val2-->20.0   val3-->57.2
35.349222222222224
=======================================
35°20'57.2"
val1-->35.0   val2-->20.0   val3-->57.2
35.349222222222224
=======================================
35°20'57.2"
val1-->35.0   val2-->20.0   val3-->57.2
35.349222222222224
=======================================
35°20'57.2"
val1-->35.0   val2-->20.0   val3-->57.2
35.349222222222224
=======================================
35°20'56.5"
val1-->35.0   val2-->20.0   val3-->56.5
35.34902777777778
=======================================
35°20'56.5"
val1-->35.0   val2-->20.0   val3-->56.5
35.34902777777778
=======================================
35°20'56.5"
val1-->35.0   val2-->20.0   val3-->56.5
35.34902777777778
=======================================
35°20'56.5"
val1-->35.0   val2-->20.0   val3-->56.5
35.34902777777778
=======================================
35°20'56.5"
val1-->35.0   val2-->20.0   val3-->56.5
35.34902777777778
=======================================
35°20'56.5"
val1-->35.0   val2-->20.0   val3-->56.5
35.34902777777778
=======================================
35°20'59.0"
val1-->35.0   val2-->20.0   val3-->59.0
35.349722222222226
=======================================
35°20'59.0"
val1-->35.0   val2-->20.0   val3-->59.0
35.349722222222226
=======================================
35°20'59.0"
val1-->35.0   val2-->20.0   val3-->59.0
35.349722222222226
=======================================
35°20'59.0"
val1-->35.0   val2-->20.0   val3-->59.0
35.349722222222226
=======================================
35°20'59.0"
val1-->35.0   val2-->20.0   val3-->59.0

0      36.684000
1      36.684000
2      36.684000
3      36.716667
4      36.716667
         ...
716          NaN
717          NaN
718          NaN
719          NaN
720          NaN
Name: latitude, Length: 721, dtype: float64

In [10]:
df

,id,id_memoire,id_ech,Wilaya,Region,X,Y,Longitude,latitude,altitude,...,wc2_1_30s_tavg_10_Band_1,wc2_1_30s_tavg_09_Band_1,wc2_1_30s_tavg_08_Band_1,wc2_1_30s_tavg_07_Band_1,wc2_1_30s_tavg_06_Band_1,wc2_1_30s_tavg_05_Band_1,wc2_1_30s_tavg_04_Band_1,wc2_1_30s_tavg_03_Band_1,wc2_1_30s_tavg_02_Band_1,wc2_1_30s_tavg_01_Band_1
0,1,1,1,Alger,El-Harrach,3 107,36 684,3.107000,36.684000,22,...,1 979 999 924,2 379 999 924,2 610 000 038,25,2 210 000 038,"18,5",1 530 000 019,1 339 999 962,1 210 000 038,1 160 000 038
1,2,1,1,Alger,El-Harrach,3 107,36 684,3.107000,36.684000,22,...,1 979 999 924,2 379 999 924,2 610 000 038,25,2 210 000 038,"18,5",1 530 000 019,1 339 999 962,1 210 000 038,1 160 000 038
2,3,1,1,Alger,El-Harrach,3 107,36 684,3.107000,36.684000,22,...,1 979 999 924,2 379 999 924,2 610 000 038,25,2 210 000 038,"18,5",1 530 000 019,1 339 999 962,1 210 000 038,1 160 000 038
3,4,2,2,Alger,El-Harrach,313 333,360 716 666,3.133333,36.716667,24,...,1 560 000 038,2 070 000 076,"24,5",2 439 999 962,2 020 000 076,1 589 999 962,1 210 000 038,9 399 999 619,6 900 000 095,5 599 999 905
4,5,2,2,Alger,El-Harrach,313 333,360 716 666,3.133333,36.716667,24,...,1 560 000 038,2 070 000 076,"24,5",2 439 999 962,2 020 000 076,1 589 999 962,1 210 000 038,9 399 999 619,6 900 000 095,5 599 999 905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,1916,98,638,Tlemcen,Hennaya,-1 521 323 465 419 020,3 502 563 533 189 600,NaN,NaN,NaN,...,2 010 000 038,2 429 999 924,"27,5",27,2 360 000 038,1 979 999 924,"16,5","14,5",1 280 000 019,1 180 000 019
717,1919,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1 510 000 038,"20,5",2 520 000 076,2 539 999 962,2 120 000 076,"16,5",1 239 999 962,"9,5",6 900 000 095,"5,5"
718,1920,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1 510 000 038,"20,5",2 520 000 076,2 539 999 962,2 120 000 076,"16,5",1 239 999 962,"9,5",6 900 000 095,"5,5"
719,1921,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1 510 000 038,"20,5",2 520 000 076,2 539 999 962,2 120 000 076,"16,5",1 239 999 962,"9,5",6 900 000 095,"5,5"
720,1922,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1 510 000 038,"20,5",2 520 000 076,2 539 999 962,2 120 000 076,"16,5",1 239 999 962,"9,5",6 900 000 095,"5,5"

In [11]:
df.iloc[500]

id                                   1670
id_memoire                             14
id_ech                                576
Wilaya                             Annaba
Region                           Ben Amar
                                ...
wc2_1_30s_tavg_05_Band_1    1 889 999 962
wc2_1_30s_tavg_04_Band_1    1 530 000 019
wc2_1_30s_tavg_03_Band_1    1 310 000 038
wc2_1_30s_tavg_02_Band_1    1 180 000 019
wc2_1_30s_tavg_01_Band_1    1 139 999 962
Name: 500, Length: 124, dtype: object

In [12]:
for i in df["altitude"]:
    print(i)

22
22
22
24
24
42
42
44
44
12
12
44
44
44
44
17
17
31
31
31
31
31
31
31
31
31
31
168
168
168
168
168
168
168
168
168
168
168
168
168
168
168
153
153
153
153
153
97
97
97
97
97
97
97
97
97
97
44
44
44
44
44
44
44
44
44
44
198
198
198
198
198
198
198
198
198
198
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
5
5
177
102
177
841
841
841
841
841
841
836
836
836
836
836
836
778
778
778
778
777
777
777
777
777
777
775
775
775
775
711
711
711
711
711
711
706
706
706
706
706
706
704
704
381,9
381,9
381,9
381,9
381,9
381,9
397,6
397,6
397,6
397,6
397,6
397,6
397,3
397,3
397,3
397,3
397,3
397,3
405,6
405,6
405,6
405,6
405,6
405,6
3
3
3
3
3
3
3
3
3
3
3
3
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
416
416
416
416
416
416
450
450
450
450
450
450
427
427
427
427
427
427
993
993
993
993
993
993
993
993
993
993
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
10
10
10
10
10
10
10
10
10
10
10
10
6
6
6
6
6
6
6
6
6
6
6
6
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
35
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
920
920
906
906
912
912
914
914
937
937
962
962
962
1080
1080
1080
906
906
906
906
906
906
906
906
1100
1100
140
140
140
140
140
50
50
50
50
50
13
13
13
13
13
14
14
14
14
14
14
122
122
122
122
122
122
107
107
107
107
107
23
23
23
23
23
23
23
23
13
13
13
13
13
13
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
17
17
17
17
17
17
17
17
17
17
31
31
31
31
31
31
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [13]:
def clean_altitude_depth(value):
    value = str(value).replace(",",".")
    value = float(value)
    return value

df["altitude"]=df["altitude"].apply(clean_altitude_depth)
df["altitude"]

0      22.0
1      22.0
2      22.0
3      24.0
4      24.0
       ...
716     NaN
717     NaN
718     NaN
719     NaN
720     NaN
Name: altitude, Length: 721, dtype: float64

In [14]:
for i in df["average profondeur"]:
    print(i)

22,5
45
80
22,5
45
22,5
45
10
22,5
22,5
45
22,5
45
80
150
22,5
45
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
22,5
22,5
10
22,5
45
80
45
80
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
45
80
22,5
45
22,5
45
22,5
45
10
22,5
22,5
45
10
22,5
10
22,5
10
22,5
10
22,5
22,5
45
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
22,5
45
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
22,5
2,5
10
22,5
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
2,5
10
22,5
2,5
10
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
80
150
2,5
10
22,5
45
2,5
10
22,5
45
80
150
22,5
45
80
150
45
80
22,5
45
80
150

In [15]:
df["average profondeur"]=df["average profondeur"].apply(clean_altitude_depth)
df["average profondeur"]

0       22.5
1       45.0
2       80.0
3       22.5
4       45.0
       ...
716     80.0
717     22.5
718     45.0
719     80.0
720    150.0
Name: average profondeur, Length: 721, dtype: float64

In [16]:
for i in df["USDA Soil Taxonomy"]:
    print(i)

nan
nan
nan
CL
CL
nan
nan
nan
nan
nan
nan
CL
CL
SCL
SCL
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
SL
SL
L
L
L
SL
SL
SAL
SAL
SL
SL
SL
SL
SL
SL
L
L
L
L
AL
AL
SL
SL
SL
SL
LS
LS
SL
SL
SL
SL
SAL
SAL
SL
SL
SL
SL
LS
LS
LS
LS
SL
SL
SL
SL
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
A
A
A
A
A
A
AS
AS
AS
AS
AS
AS
LA
LA
LA
LA
LA
LA
LS
LS
LS
LS
LS
LS
SL
SL
SL
SL
SL
SL
SL
SL
SL
SL
SL
SL
SL
SL
SL
SL
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
S
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
AL
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
CL
CL
SL
SL
CL
CL
C
C
SL
SL
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [17]:
def clean_numeric_data(value):
    print(value)
    value_str = str(value).replace(",", ".")
    first_occurrence_index = value_str.find("\u202f")
    if first_occurrence_index != -1:
        value_str = (value_str[:first_occurrence_index] + '.' + value_str[first_occurrence_index + 1:])
        value_str = value_str.replace("\u202f", "")
    
    print(value_str)
    return float(value_str)

In [18]:
for i in df.columns[14:23]:
    print(f"column {i}")
    df[i]=df[i].apply(clean_numeric_data)
df.describe()

column pH
7,87
7.87
7 774
7.774
7 799
7.799
7,95
7.95
8 096
8.096
8,5
8.5
8,5
8.5
8,59
8.59
8,59
8.59
7,83
7.83
7,83
7.83
7,2
7.2
7,2
7.2
7,8
7.8
7,8
7.8
8,5
8.5
8,5
8.5
7 021
7.021
7,06
7.06
7 182
7.182
7 457
7.457
7 619
7.619
7 867
7.867
7 878
7.878
7 893
7.893
7,86
7.86
7 828
7.828
6 935
6.935
6 997
6.997
7 123
7.123
7 143
7.143
7 105
7.105
7 821
7.821
7 652
7.652
7 304
7.304
7 207
7.207
7,28
7.28
7 718
7.718
7 684
7.684
7 603
7.603
7,52
7.52
7 489
7.489
7 912
7.912
7 862
7.862
7,73
7.73
7 519
7.519
7 411
7.411
7 797
7.797
7,81
7.81
7 816
7.816
7 685
7.685
7 582
7.582
7 892
7.892
7 926
7.926
8 006
8.006
8 097
8.097
8 133
8.133
7 092
7.092
7 292
7.292
7 713
7.713
7 892
7.892
7 852
7.852
7 822
7.822
7 815
7.815
7 801
7.801
7 798
7.798
7 801
7.801
7 078
7.078
7 128
7.128
7,22
7.22
7 189
7.189
7 126
7.126
7 579
7.579
7 459
7.459
7 205
7.205
7 077
7.077
7 085
7.085
7,69
7.69
7,69
7.69
7,69
7.69
7,69
7.69
7 876
7.876
7 895
7.895
7 968
7.968
8 027
8.027
7 558
7.558
7 598
7.598
7 758
7.758
7 888
7.888
8 243
8.243
8 256
8.256
8 309
8.309
8 353
8.353
8,07
8.07
8 109
8.109
8 262
8.262
8 386
8.386
8 134
8.134
8 177
8.177
8 351
8.351
8 491
8.491
8 097
8.097
8 161
8.161
8 415
8.415
8,62
8.62
8 253
8.253
8,22
8.22
8 086
8.086
7 978
7.978
8 163
8.163
8 169
8.169
8 189
8.189
8 205
8.205
7 491
7.491
7 498
7.498
7 525
7.525
7 546
7.546
8,26
8.26
8,26
8.26
6,8
6.8
5,9
5.9
6,8
6.8
8,71
8.71
8,71
8.71
8,84
8.84
8,84
8.84
8,94
8.94
8,94
8.94
9,15
9.15
9,15
9.15
9,1
9.1
9,1
9.1
8,77
8.77
8 731
8.731
8,35
8.35
8,35
8.35
8 429
8.429
8 711
8.711
8,65
8.65
8 524
8.524
8,51
8.51
8,51
8.51
8,61
8.61
8,61
8.61
8,38
8.38
8,38
8.38
8,37
8.37
8,37
8.37
8 499
8.499
8 623
8.623
8,71
8.71
8,71
8.71
8,8
8.8
8,8
8.8
8,74
8.74
8 712
8.712
8,74
8.74
8 645
8.645
8 529
8.529
8 729
8.729
8,64
8.64
8,64
8.64
8 214
8.214
8 191
8.191
8 122
8.122
8 108
8.108
8,31
8.31
8 653
8.653
8 679
8.679
8 695
8.695
8 757
8.757
8 742
8.742
8 379
8.379
8 525
8.525
8 048
8.048
8 088
8.088
8 251
8.251
8 413
8.413
8 237
8.237
8 071
8.071
8 217
8.217
8 246
8.246
8 369
8.369
8 597
8.597
8 593
8.593
8 602
8.602
7,64
7.64
7,64
7.64
7,48
7.48
7,48
7.48
7,73
7.73
7,73
7.73
7,75
7.75
7,75
7.75
7,76
7.76
7,76
7.76
7,99
7.99
7,99
7.99
7,19
7.19
7,19
7.19
7,28
7.28
7,28
7.28
7,1
7.1
7,1
7.1
5,84
5.84
5,84
5.84
6,28
6.28
6,28
6.28
6,21
6.21
6,21
6.21
5,37
5.37
5,37
5.37
5,43
5.43
5,43
5.43
5,53
5.53
5,53
5.53
6,94
6.94
6,94
6.94
6,9
6.9
6,9
6.9
7,03
7.03
7,03
7.03
7,14
7.14
7,14
7.14
7,14
7.14
7,14
7.14
7,06
7.06
7,06
7.06
7,06
7.06
7,06
7.06
7,07
7.07
7,07
7.07
7,07
7.07
7,07
7.07
6,73
6.73
6,73
6.73
6,73
6.73
6,73
6.73
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
8,4
8.4
8,4
8.4
7,8
7.8
7,8
7.8
7,9
7.9
7,9
7.9
7,8
7.8
7,8
7.8
8,1
8.1
8,1
8.1
8,1
8.1
8,1
8.1
7,9
7.9
7,9
7.9
7,9
7.9
7,9
7.9
8,2
8.2
8,2
8.2
8,2
8.2
8,2
8.2
8,1
8.1
8,1
8.1
7,9
7.9
7,9
7.9
8
8
8
8
7,9
7.9
7,9
7.9
7,7
7.7
7,7
7.7
7,7
7.7
7,7
7.7
7,7
7.7
7,7
7.7
7,6
7.6
7,6
7.6
7,5
7.5
7,5
7.5
7,5
7.5
7,5
7.5
8
8
8
8
8,2
8.2
8,2
8.2
8
8
8
8
8,1
8.1
8,1
8.1
7,7
7.7
7,7
7.7
7,9
7.9
7,9
7.9
8,1
8.1
8,1
8.1
8,1
8.1
8,1
8.1
8,2
8.2
8,2
8.2
8,4
8.4
8,4
8.4
8,1
8.1
8,1
8.1
8
8
8
8
8,2
8.2
8,2
8.2
8,3
8.3
8,3
8.3
8,3
8.3
8,3
8.3
8
8
8
8
8,2
8.2
8,2
8.2
8,3
8.3
8,3
8.3
8,3
8.3
8,3
8.3
8,3
8.3
8,3
8.3
8,2
8.2
8,2
8.2
8,2
8.2
8,2
8.2
8
8
8
8
7,9
7.9
7,9
7.9
7,5
7.5
7,5
7.5
7,4
7.4
7,4
7.4
8
8
8
8
7,8
7.8
7,8
7.8
8,2
8.2
8,2
8.2
8,1
8.1
8,1
8.1
7,6
7.6
7,6
7.6
7,7
7.7
7,7
7.7
7,9
7.9
7,9
7.9
7,8
7.8
7,8
7.8
8
8
8
8
8
8
8
8
7,9
7.9
7,9
7.9
7,9
7.9
7,9
7.9
8,2
8.2
8,2
8.2
8
8
8
8
8,1
8.1
8,1
8.1
8,1
8.1
8,1
8.1
8
8
8
8
8
8
8
8
8,1
8.1
8,1
8.1
7,9
7.9
7,9
7.9
8,1
8.1
8,1
8.1
8,2
8.2
8,2
8.2
8,1
8.1
8,1
8.1
8
8
8
8
8,3
8.3
8,3
8.3
8,2
8.2
8,2
8.2
8,2
8.2
8,2
8.2
8
8
8
8
8,1
8.1
8,1
8.1
8
8
8
8
8,2
8.2
8,2
8.2
8,2
8.2
8,2
8.2
8,2
8.2
8,2
8.2
8,1
8.1
8,1
8.1
8
8
8
8
8
8
8
8
8 503
8.503
8 471
8.471
8 378
8.378
8 494
8.494
8 665
8.665
8 649
8.649
8 885
8.885
8 821
8.821
8 705
8.705
8 904
8.904
8 884
8.884
8 867
8.867
8 675
8.675
8 673
8.673
8 666
8.666
8 639
8.639
8 538
8.538
8 375
8.375
8 759
8.759
8 764
8.764
8 686
8.686
8 183
8.183
8 104
8.104
8 531
8.531
8 638
8.638
8 843
8.843
8 766
8.766
8 678
8.678
8 061
8.061
7 997
7.997
8 258
8.258
8 509
8.509
8 475
8.475
8 358
8.358
7 585
7.585
7 642
7.642
7 754
7.754
7 221
7.221
7,31
7.31
7,57
7.57
7 552
7.552
7,3
7.3
7 216
7.216
7,17
7.17
7,3
7.3
7,3
7.3
7 301
7.301
7 294
7.294
7 354
7.354
7 473
7.473
7 584
7.584
7 576
7.576
7 542
7.542
7,43
7.43
7 244
7.244
8 109
8.109
8 186
8.186
8 405
8.405
8 196
8.196
8 257
8.257
8 395
8.395
7 861
7.861
7 932
7.932
8,17
8.17
8 526
8.526
8 334
8.334
8 688
8.688
8 401
8.401
8 286
8.286
7 879
7.879
7 672
7.672
7 715
7.715
7 478
7.478
8,04
8.04
8,04
8.04
7,65
7.65
7,65
7.65
7,74
7.74
7,74
7.74
7,45
7.45
7,45
7.45
7,74
7.74
7,74
7.74
7,83
7.83
7,83
7.83
7,49
7.49
7,49
7.49
7,2
7.2
7,2
7.2
7,2
7.2
7,3
7.3
7,3
7.3
7,3
7.3
7,81
7.81
7,81
7.81
7,81
7.81
7,22
7.22
7,22
7.22
7,22
7.22
7,45
7.45
7,45
7.45
7,45
7.45
7,86
7.86
7,86
7.86
7,86
7.86
8,12
8.12
8,12
8.12
8,12
8.12
8,3
8.3
8,3
8.3
8,3
8.3
8,27
8.27
8,27
8.27
8,27
8.27
8,26
8.26
8 237
8.237
8 222
8.222
8 339
8.339
8 424
8.424
8,48
8.48
7 989
7.989
8 159
8.159
8,27
8.27
8,3
8.3
8 377
8.377
8 427
8.427
5 089
5.089
5 082
5.082
5,05
5.05
4,93
4.93
4,65
4.65
4 315
4.315
5 688
5.688
5 658
5.658
5,53
5.53
5 225
5.225
5 304
5.304
5 568
5.568
6 537
6.537
6 506
6.506
6 379
6.379
6 077
6.077
5 584
5.584
4 603
4.603
5 615
5.615
5 538
5.538
5,34
5.34
5 035
5.035
4 711
4.711
4 372
4.372
4 425
4.425
4 435
4.435
4 481
4.481
4 655
4.655
5 081
5.081
4 876
4.876
6 156
6.156
6 178
6.178
6 272
6.272
6 405
6.405
6 315
6.315
6 255
6.255
5 594
5.594
5 595
5.595
5,6
5.6
5 601
5.601
5,28
5.28
4 438
4.438
4 918
4.918
4 908
4.908
4 866
4.866
4 702
4.702
4 337
4.337
4 102
4.102
6 175
6.175
6 216
6.216
6 314
6.314
6 114
6.114
6 191
6.191
5 934
5.934
5,93
5.93
5 912
5.912
5 845
5.845
5 701
5.701
5 471
5.471
5 094
5.094
5 127
5.127
5 193
5.193
5 209
5.209
5 229
5.229
5 576
5.576
4 787
4.787
4 789
4.789
4,8
4.8
4 843
4.843
4 946
4.946
4,85
4.85
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
7,84
7.84
7 759
7.759
7 692
7.692
7,44
7.44
7,44
7.44
7,44
7.44
8,51
8.51
8,51
8.51
8,5
8.5
8,5
8.5
8,41
8.41
8,41
8.41
8,36
8.36
8,36
8.36
8,76
8.76
8,76
8.76
5 977
5.977
5 952
5.952
5 841
5.841
5 533
5.533
5 282
5.282
6 649
6.649
6 633
6.633
6 563
6.563
6 369
6.369
6 227
6.227
6 673
6.673
6 648
6.648
6 538
6.538
6 155
6.155
5 894
5.894
6,37
6.37
6,38
6.38
6 424
6.424
6 507
6.507
6 358
6.358
6 248
6.248
6 163
6.163
6 153
6.153
6 074
6.074
5 621
5.621
5 356
5.356
5 224
5.224
4,94
4.94
4,94
4.94
5,33
5.33
5,33
5.33
5,33
5.33
6,34
6.34
6,34
6.34
6 093
6.093
6 098
6.098
6 119
6.119
6 194
6.194
6 309
6.309
6 389
6.389
5 888
5.888
5 919
5.919
6 053
6.053
6 412
6.412
6 613
6.613
6 514
6.514
6 377
6.377
6 395
6.395
6 473
6.473
6 768
6.768
6 862
6.862
6 628
6.628
6 458
6.458
6 469
6.469
6 512
6.512
6 566
6.566
6 817
6.817
6 897
6.897
6 227
6.227
6 183
6.183
5 998
5.998
5 579
5.579
5 352
5.352
5 787
5.787
5 794
5.794
5 777
5.777
5 703
5.703
5 762
5.762
6 333
6.333
6 441
6.441
6 362
6.362
6 449
6.449
6,77
6.77
6 619
6.619
6 451
6.451
6 426
6.426
6 331
6.331
6 339
6.339
6 543
6.543
6 612
6.612
7 811
7.811
7 913
7.913
7 785
7.785
7 789
7.789
7,8
7.8
7,8
7.8
7 952
7.952
8 121
8.121
8 073
8.073
7 951
7.951
column CE
0,17
0.17
0,17
0.17
0,17
0.17
0,26
0.26
0,279
0.279
nan
nan
nan
nan
0,37
0.37
0,37
0.37
nan
nan
nan
nan
0,8
0.8
0,8
0.8
0,85
0.85
0,85
0.85
0,22
0.22
0,22
0.22
1 076
1.076
0,765
0.765
0,367
0.367
1 663
1.663
2 839
2.839
2 571
2.571
2 359
2.359
1 944
1.944
1,95
1.95
2,13
2.13
4 337
4.337
3 852
3.852
2 848
2.848
2 507
2.507
2 668
2.668
2 304
2.304
2 328
2.328
2 377
2.377
2 387
2.387
2 375
2.375
3 067
3.067
2 791
2.791
2 244
2.244
2 207
2.207
2,41
2.41
2 466
2.466
2 605
2.605
2 828
2.828
2 532
2.532
2 208
2.208
1 186
1.186
1 615
1.615
2 333
2.333
1 597
1.597
0,719
0.719
0,457
0.457
0,344
0.344
0,114
0.114
0,065
0.065
0,124
0.124
4 002
4.002
3 496
3.496
2 455
2.455
2,15
2.15
2 355
2.355
3 955
3.955
3 727
3.727
3 199
3.199
2 705
2.705
2 545
2.545
0,893
0.893
0,839
0.839
0,772
0.772
1 021
1.021
1 243
1.243
0,186
0.186
0,745
0.745
2 043
2.043
3 281
3.281
3 691
3.691
0,28
0.28
0,28
0.28
0,28
0.28
0,28
0.28
0,078
0.078
0,126
0.126
0,315
0.315
0,469
0.469
0,522
0.522
0,515
0.515
0,486
0.486
0,463
0.463
0,444
0.444
0,456
0.456
0,505
0.505
0,545
0.545
0,418
0.418
0,435
0.435
0,502
0.502
0,556
0.556
0,468
0.468
0,487
0.487
0,565
0.565
0,628
0.628
0,532
0.532
0,554
0.554
0,64
0.64
0,711
0.711
0,453
0.453
0,482
0.482
0,595
0.595
0,687
0.687
0,389
0.389
0,39
0.39
0,393
0.393
0,396
0.396
0,208
0.208
0,21
0.21
0,216
0.216
0,222
0.222
nan
nan
nan
nan
0,5
0.5
0,5
0.5
0,5
0.5
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
3 951
3.951
3 706
3.706
2 912
2.912
2 357
2.357
2 648
2.648
2 587
2.587
3 676
3.676
3 619
3.619
3 384
3.384
2 992
2.992
2 912
2.912
3 121
3.121
0,091
0.091
0,098
0.098
0,13
0.13
0,324
0.324
0,613
0.613
1 966
1.966
4 355
4.355
4 473
4.473
4,99
4.99
5 246
5.246
3 567
3.567
2 765
2.765
0,34
0.34
0,34
0.34
0,67
0.67
0,67
0.67
1,06
1.06
1,06
1.06
0,56
0.56
0,56
0.56
0,6
0.6
0,6
0.6
0,35
0.35
0,35
0.35
0,052
0.052
0,052
0.052
0,053
0.053
0,053
0.053
0,051
0.051
0,051
0.051
0,141
0.141
0,141
0.141
0,142
0.142
0,142
0.142
0,147
0.147
0,147
0.147
0,238
0.238
0,238
0.238
0,219
0.219
0,219
0.219
0,205
0.205
0,205
0.205
0,114
0.114
0,114
0.114
0,107
0.107
0,107
0.107
0,996
0.996
0,996
0.996
0,631
0.631
0,631
0.631
0,631
0.631
0,631
0.631
0,176
0.176
0,176
0.176
0,176
0.176
0,176
0.176
0,214
0.214
0,214
0.214
0,214
0.214
0,214
0.214
0,155
0.155
0,155
0.155
0,155
0.155
0,155
0.155
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0,47
0.47
0,47
0.47
0,68
0.68
0,68
0.68
0,14
0.14
0,14
0.14
0,2
0.2
0,2
0.2
0,2
0.2
0,2
0.2
0,15
0.15
0,15
0.15
0,14
0.14
0,14
0.14
0,15
0.15
0,15
0.15
0,1
0.1
0,1
0.1
0,18
0.18
0,18
0.18
0,08
0.08
0,08
0.08
0,12
0.12
0,12
0.12
0,08
0.08
0,08
0.08
0,08
0.08
0,08
0.08
0,12
0.12
0,12
0.12
0,11
0.11
0,11
0.11
0,06
0.06
0,06
0.06
0,1
0.1
0,1
0.1
0,15
0.15
0,15
0.15
0,13
0.13
0,13
0.13
0,37
0.37
0,37
0.37
0,3
0.3
0,3
0.3
0,47
0.47
0,47
0.47
0,38
0.38
0,38
0.38
0,18
0.18
0,18
0.18
0,22
0.22
0,22
0.22
0,17
0.17
0,17
0.17
0,15
0.15
0,15
0.15
0,29
0.29
0,29
0.29
0,5
0.5
0,5
0.5
0,18
0.18
0,18
0.18
0,17
0.17
0,17
0.17
0,13
0.13
0,13
0.13
0,15
0.15
0,15
0.15
0,17
0.17
0,17
0.17
0,17
0.17
0,17
0.17
0,13
0.13
0,13
0.13
0,16
0.16
0,16
0.16
0,16
0.16
0,16
0.16
0,2
0.2
0,2
0.2
0,11
0.11
0,11
0.11
0,18
0.18
0,18
0.18
0,06
0.06
0,06
0.06
0,07
0.07
0,07
0.07
0,17
0.17
0,17
0.17
0,28
0.28
0,28
0.28
0,12
0.12
0,12
0.12
0,16
0.16
0,16
0.16
0,18
0.18
0,18
0.18
0,15
0.15
0,15
0.15
0,09
0.09
0,09
0.09
0,11
0.11
0,11
0.11
0,15
0.15
0,15
0.15
0,15
0.15
0,15
0.15
0,13
0.13
0,13
0.13
0,15
0.15
0,15
0.15
0,12
0.12
0,12
0.12
0,17
0.17
0,17
0.17
0,17
0.17
0,17
0.17
0,17
0.17
0,17
0.17
0,1
0.1
0,1
0.1
0,14
0.14
0,14
0.14
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,15
0.15
0,15
0.15
0,13
0.13
0,13
0.13
0,15
0.15
0,15
0.15
0,18
0.18
0,18
0.18
0,13
0.13
0,13
0.13
0,11
0.11
0,11
0.11
0,12
0.12
0,12
0.12
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,13
0.13
0,33
0.33
0,33
0.33
0,22
0.22
0,22
0.22
0,69
0.69
0,676
0.676
0,622
0.622
0,683
0.683
0,749
0.749
0,797
0.797
2 082
2.082
2 083
2.083
2 064
2.064
2 105
2.105
2 087
2.087
2 029
2.029
2 794
2.794
2 829
2.829
2 984
2.984
3 528
3.528
3,57
3.57
2 823
2.823
0,215
0.215
0,15
0.15
0,155
0.155
0,937
0.937
0,996
0.996
0,152
0.152
0,114
0.114
0,084
0.084
0,219
0.219
0,274
0.274
1 698
1.698
2 901
2.901
3 005
3.005
2 504
2.504
1 651
1.651
1 194
1.194
23 342
23.342
23 541
23.541
25,92
25.92
45 598
45.598
59 319
59.319
40 769
40.769
38 256
38.256
47 323
47.323
56 131
56.131
60 817
60.817
0
0
4 136
4.136
26 828
26.828
36 869
36.869
34 928
34.928
41 634
41.634
12 294
12.294
12 815
12.815
15,09
15.09
22 383
22.383
27 895
27.895
40 294
40.294
44 716
44.716
58,7
58.7
59 559
59.559
69 869
69.869
84 525
84.525
151 285
151.285
89 482
89.482
60,76
60.76
86 592
86.592
78 746
78.746
98 358
98.358
0
0
5,04
5.04
29,01
29.01
52 103
52.103
46 342
46.342
43 722
43.722
0,575
0.575
0,575
0.575
0,582
0.582
0,582
0.582
0,21
0.21
0,21
0.21
0,219
0.219
0,219
0.219
0,205
0.205
0,205
0.205
0,12
0.12
0,12
0.12
0,355
0.355
0,355
0.355
0,92
0.92
0,92
0.92
0,92
0.92
0,4
0.4
0,4
0.4
0,4
0.4
0,3
0.3
0,3
0.3
0,3
0.3
0,47
0.47
0,47
0.47
0,47
0.47
0,2
0.2
0,2
0.2
0,2
0.2
1
1
1
1
1
1
0,4
0.4
0,4
0.4
0,4
0.4
0,28
0.28
0,28
0.28
0,28
0.28
0,25
0.25
0,25
0.25
0,25
0.25
0,16
0.16
0,145
0.145
0,135
0.135
0,11
0.11
0,11
0.11
0,11
0.11
0,13
0.13
0,122
0.122
0,117
0.117
0,1
0.1
0,115
0.115
0,125
0.125
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,101
0.101
0,099
0.099
0,122
0.122
0,121
0.121
0,119
0.119
0,112
0.112
0,109
0.109
0,11
0.11
0,093
0.093
0,099
0.099
0,121
0.121
0,152
0.152
0,141
0.141
0,125
0.125
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,101
0.101
0,098
0.098
0,123
0.123
0,123
0.123
0,122
0.122
0,119
0.119
0,112
0.112
0,11
0.11
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,105
0.105
0,113
0.113
0,132
0.132
0,096
0.096
0,099
0.099
0,09
0.09
0,09
0.09
0,09
0.09
0,09
0.09
0,09
0.09
0,094
0.094
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
0,1
0.1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0,21
0.21
0,21
0.21
0,24
0.24
0,24
0.24
0,25
0.25
0,25
0.25
0,25
0.25
0,25
0.25
0,65
0.65
0,65
0.65
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
1 403
1.403
1 687
1.687
1 875
1.875
2 856
2.856
1,36
1.36
1,36
1.36
3 637
3.637
1 481
1.481
1 178
1.178
1 586
1.586
column CEC
17 929
17.929
17 207
17.207
15 049
15.049
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
3,75
3.75
3,75
3.75
18,57
18.57
18,57
18.57
15,32
15.32
15,32
15.32
nan
nan
nan
nan
40,99
40.99
43 487
43.487
47 163
47.163
39 769
39.769
32 464
32.464
34 829
34.829
39 644
39.644
47 824
47.824
40 232
40.232
30 862
30.862
16 629
16.629
30 495
30.495
54,36
54.36
34 361
34.361
8 696
8.696
39 029
39.029
33 111
33.111
20 901
20.901
17,1
17.1
19 326
19.326
16 631
16.631
20 625
20.625
28 035
28.035
25 539
25.539
20 456
20.456
12 523
12.523
13 685
13.685
16 837
16.837
22 195
22.195
25,02
25.02
34 678
34.678
30 207
30.207
20 588
20.588
15 298
15.298
15 269
15.269
6 838
6.838
8 332
8.332
11 165
11.165
10 607
10.607
8 971
8.971
35 735
35.735
33 525
33.525
29 287
29.287
29 835
29.835
32 059
32.059
40 072
40.072
39 766
39.766
38 747
38.747
36 188
36.188
34 632
34.632
39 396
39.396
38 569
38.569
35 997
35.997
30,18
30.18
26 751
26.751
21 577
21.577
21 704
21.704
23 552
23.552
33 306
33.306
40 102
40.102
nan
nan
nan
nan
nan
nan
nan
nan
26 227
26.227
26 291
26.291
26 545
26.545
26,75
26.75
28 472
28.472
27 843
27.843
25,35
25.35
23 329
23.329
30 954
30.954
30 586
30.586
29 133
29.133
27 955
27.955
25 629
25.629
25 521
25.521
25 095
25.095
24 749
24.749
31 161
31.161
30 974
30.974
30 234
30.234
29 635
29.635
28 315
28.315
28 125
28.125
27 372
27.372
26 761
26.761
31 086
31.086
30 244
30.244
26 911
26.911
24,21
24.21
30 726
30.726
30 163
30.163
27 937
27.937
26 132
26.132
18
18
18
18
18
18
18
18
0,93
0.93
0,93
0.93
nan
nan
nan
nan
nan
nan
5,38
5.38
5,38
5.38
7,05
7.05
7,05
7.05
5,35
5.35
5,35
5.35
4,1
4.1
4,1
4.1
3,84
3.84
3,84
3.84
7 686
7.686
8 932
8.932
8,71
8.71
8,71
8.71
6 918
6.918
7 667
7.667
5 942
5.942
5 396
5.396
5,12
5.12
5,12
5.12
5,38
5.38
5,38
5.38
6,92
6.92
6,92
6.92
9,48
9.48
9,48
9.48
8 199
8.199
8 446
8.446
9,23
9.23
9,23
9.23
6,15
6.15
6,15
6.15
3 838
3.838
4 323
4.323
4 792
4.792
4 373
4.373
5,63
5.63
7 583
7.583
6,15
6.15
6,15
6.15
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0,3
0.3
0,3
0.3
0,5
0.5
0,5
0.5
0,25
0.25
0,25
0.25
0,65
0.65
0,65
0.65
0,4
0.4
0,4
0.4
0,25
0.25
0,25
0.25
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
22
22
22
22
22
22
22
22
25,5
25.5
25,5
25.5
25,5
25.5
25,5
25.5
28
28
28
28
28
28
28
28
23,5
23.5
23,5
23.5
23,5
23.5
23,5
23.5
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
23
23
23
23
22,05
22.05
22,05
22.05
15,97
15.97
15,97
15.97
20,91
20.91
20,91
20.91
19,77
19.77
19,77
19.77
18,63
18.63
18,63
18.63
19,77
19.77
19,77
19.77
19,2
19.2
19,2
19.2
23,19
23.19
23,19
23.19
21,13
21.13
21,13
21.13
23,38
23.38
23,38
23.38
23,38
23.38
23,38
23.38
24,52
24.52
24,52
24.52
24,33
24.33
24,33
24.33
25,28
25.28
25,28
25.28
26,04
26.04
26,04
26.04
16,14
16.14
16,14
16.14
16,64
16.64
16,64
16.64
23,38
23.38
23,38
23.38
23,95
23.95
23,95
23.95
12,6
12.6
12,6
12.6
13,73
13.73
13,73
13.73
12,21
12.21
12,21
12.21
16,34
16.34
16,34
16.34
14,72
14.72
14,72
14.72
15,48
15.48
15,48
15.48
25,85
25.85
25,85
25.85
25,47
25.47
25,47
25.47
26,33
26.33
26,33
26.33
26,97
26.97
26,97
26.97
25,43
25.43
25,43
25.43
25,98
25.98
25,98
25.98
24,36
24.36
24,36
24.36
25,55
25.55
25,55
25.55
26,13
26.13
26,13
26.13
24,52
24.52
24,52
24.52
26,61
26.61
26,61
26.61
26,04
26.04
26,04
26.04
21,86
21.86
21,86
21.86
22,62
22.62
22,62
22.62
25,01
25.01
25,01
25.01
23
23
23
23
25,38
25.38
25,38
25.38
23,76
23.76
23,76
23.76
19,26
19.26
19,26
19.26
19,35
19.35
19,35
19.35
17,68
17.68
17,68
17.68
18,41
18.41
18,41
18.41
26,62
26.62
26,62
26.62
26,97
26.97
26,97
26.97
26,75
26.75
26,75
26.75
26,65
26.65
26,65
26.65
23,33
23.33
23,33
23.33
25,19
25.19
25,19
25.19
23,69
23.69
23,69
23.69
21,1
21.1
21,1
21.1
18,18
18.18
18,18
18.18
15,21
15.21
15,21
15.21
14,42
14.42
14,42
14.42
22,42
22.42
22,42
22.42
20,39
20.39
20,39
20.39
26,99
26.99
26,99
26.99
27,89
27.89
27,89
27.89
27,59
27.59
27,59
27.59
27,18
27.18
27,18
27.18
22,05
22.05
22,05
22.05
17,3
17.3
17,3
17.3
20,91
20.91
20,91
20.91
20,7
20.7
20,7
20.7
17,73
17.73
17,73
17.73
12,42
12.42
12,42
12.42
18,06
18.06
18,06
18.06
17,11
17.11
17,11
17.11
20,15
20.15
20,15
20.15
12,83
12.83
12,83
12.83
18,06
18.06
18,06
18.06
11,02
11.02
11,02
11.02
19,35
19.35
19,35
19.35
13,92
13.92
13,92
13.92
14,33
14.33
14,33
14.33
52 014
52.014
48 755
48.755
42 427
42.427
50 668
50.668
36 541
36.541
31,93
31.93
22 549
22.549
47 137
47.137
68,92
68.92
58 749
58.749
46 003
46.003
44 993
44.993
29 854
29.854
29 603
29.603
28 505
28.505
24 592
24.592
22 584
22.584
24 482
24.482
45 338
45.338
47 205
47.205
51 601
51.601
54 792
54.792
44 472
44.472
29 538
29.538
29 037
29.037
26 995
26.995
24 963
24.963
35 113
35.113
20 581
20.581
16 975
16.975
20 064
20.064
22 421
22.421
19 082
19.082
19 083
19.083
20 463
20.463
20 926
20.926
22 038
22.038
19 183
19.183
18 078
18.078
14 524
14.524
17 504
17.504
18 635
18.635
18 456
18.456
17 301
17.301
17 884
17.884
18,03
18.03
18 601
18.601
19 695
19.695
19 724
19.724
22 985
22.985
18 379
18.379
18 524
18.524
19 155
19.155
20 781
20.781
20,7
20.7
16 848
16.848
18 087
18.087
21 575

,id,id_memoire,id_ech,Longitude,latitude,altitude,UD,LD,average profondeur,pH,...,wc2_1_30s_srad_10_Band_1,wc2_1_30s_srad_09_Band_1,wc2_1_30s_srad_08_Band_1,wc2_1_30s_srad_07_Band_1,wc2_1_30s_srad_06_Band_1,wc2_1_30s_srad_05_Band_1,wc2_1_30s_srad_04_Band_1,wc2_1_30s_srad_03_Band_1,wc2_1_30s_srad_02_Band_1,wc2_1_30s_srad_01_Band_1
count,721.000000,721.000000,721.000000,711.000000,711.000000,402.00000,721.000000,721.000000,721.000000,705.000000,...,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000
mean,1032.420250,49.238558,359.565881,4.851758,36.207702,238.20000,18.606103,38.217753,28.411928,7.461732,...,13813.570042,19034.812760,23737.511789,26317.142857,25012.471567,23663.932039,19733.320388,16101.829404,12000.907074,8867.153953
std,600.889102,25.838843,201.558749,2.231252,0.704983,328.24141,25.245300,46.338651,35.742261,1.063685,...,604.964894,741.489106,655.042013,779.546829,410.945603,667.290589,766.349308,787.991189,835.434261,655.271765
min,1.000000,1.000000,1.000000,0.492000,34.635081,3.00000,0.000000,5.000000,2.500000,4.102000,...,13086.000000,18059.000000,22529.000000,24747.000000,24145.000000,22379.000000,18844.000000,15277.000000,11125.000000,8209.000000
25%,523.000000,21.000000,189.000000,2.611669,35.610464,14.00000,0.000000,5.000000,2.500000,7.021000,...,13368.000000,18368.000000,23134.000000,25582.000000,24729.000000,23203.000000,19084.000000,15555.000000,11216.000000,8299.000000
50%,907.000000,57.000000,335.000000,5.307222,36.509564,35.00000,5.000000,15.000000,10.000000,7.815000,...,13428.000000,18875.000000,23911.000000,26490.000000,25015.000000,23561.000000,19441.000000,15637.000000,11746.000000,8622.000000
75%,1716.000000,63.000000,590.000000,6.883333,36.807500,397.60000,30.000000,60.000000,45.000000,8.200000,...,14256.000000,19473.000000,24287.000000,26989.000000,25261.000000,24015.000000,20156.000000,16788.000000,12533.000000,9447.000000
max,1922.000000,98.000000,640.000000,8.341389,36.904722,1100.00000,100.000000,200.000000,150.000000,9.150000,...,15231.000000,20867.000000,24937.000000,27516.000000,25935.000000,25126.000000,21736.000000,17993.000000,13949.000000,10585.000000

In [19]:
for i in df.columns[23:]:
    print(i)

AREA
PERIMETER
GEO2_7G_
GEO2_7G_ID
GLG
SNUM
FAOSOIL
DOMSOI
PHASE1
SQKM
SRTMGL1_band1
landcover
Band3
Band4
Band5
Band7
NDVI
wc2_1_30s_wind_12_Band_1
wc2_1_30s_wind_11_Band_1
wc2_1_30s_wind_10_Band_1
wc2_1_30s_wind_09_Band_1
wc2_1_30s_wind_08_Band_1
wc2_1_30s_wind_07_Band_1
wc2_1_30s_wind_06_Band_1
wc2_1_30s_wind_05_Band_1
wc2_1_30s_wind_04_Band_1
wc2_1_30s_wind_03_Band_1
wc2_1_30s_wind_02_Band_1
wc2_1_30s_wind_01_Band_1
wc2_1_30s_vapr_12_Band_1
wc2_1_30s_vapr_11_Band_1
wc2_1_30s_vapr_10_Band_1
wc2_1_30s_vapr_09_Band_1
wc2_1_30s_vapr_08_Band_1
wc2_1_30s_vapr_07_Band_1
wc2_1_30s_vapr_06_Band_1
wc2_1_30s_vapr_05_Band_1
wc2_1_30s_vapr_04_Band_1
wc2_1_30s_vapr_03_Band_1
wc2_1_30s_vapr_02_Band_1
wc2_1_30s_vapr_01_Band_1
wc2_1_30s_tmin_12_Band_1
wc2_1_30s_tmin_11_Band_1
wc2_1_30s_tmin_10_Band_1
wc2_1_30s_tmin_09_Band_1
wc2_1_30s_tmin_08_Band_1
wc2_1_30s_tmin_07_Band_1
wc2_1_30s_tmin_06_Band_1
wc2_1_30s_tmin_05_Band_1
wc2_1_30s_tmin_04_Band_1
wc2_1_30s_tmin_03_Band_1
wc2_1_30s_tmin_02_Band_1
wc2_1_30s_tmin_01_Band_1
wc2_1_30s_tmax_12_Band_1
wc2_1_30s_tmax_11_Band_1
wc2_1_30s_tmax_10_Band_1
wc2_1_30s_tmax_09_Band_1
wc2_1_30s_tmax_08_Band_1
wc2_1_30s_tmax_07_Band_1
wc2_1_30s_tmax_06_Band_1
wc2_1_30s_tmax_05_Band_1
wc2_1_30s_tmax_04_Band_1
wc2_1_30s_tmax_03_Band_1
wc2_1_30s_tmax_02_Band_1
wc2_1_30s_tmax_01_Band_1
wc2_1_30s_prec_12_Band_1
wc2_1_30s_prec_11_Band_1
wc2_1_30s_prec_10_Band_1
wc2_1_30s_prec_09_Band_1
wc2_1_30s_prec_08_Band_1
wc2_1_30s_prec_07_Band_1
wc2_1_30s_prec_06_Band_1
wc2_1_30s_prec_05_Band_1
wc2_1_30s_prec_04_Band_1
wc2_1_30s_prec_03_Band_1
wc2_1_30s_prec_02_Band_1
wc2_1_30s_prec_01_Band_1
wc2_1_30s_srad_12_Band_1
wc2_1_30s_srad_11_Band_1
wc2_1_30s_srad_10_Band_1
wc2_1_30s_srad_09_Band_1
wc2_1_30s_srad_08_Band_1
wc2_1_30s_srad_07_Band_1
wc2_1_30s_srad_06_Band_1
wc2_1_30s_srad_05_Band_1
wc2_1_30s_srad_04_Band_1
wc2_1_30s_srad_03_Band_1
wc2_1_30s_srad_02_Band_1
wc2_1_30s_srad_01_Band_1
wc2_1_30s_tavg_12_Band_1
wc2_1_30s_tavg_11_Band_1
wc2_1_30s_tavg_10_Band_1
wc2_1_30s_tavg_09_Band_1
wc2_1_30s_tavg_08_Band_1
wc2_1_30s_tavg_07_Band_1
wc2_1_30s_tavg_06_Band_1
wc2_1_30s_tavg_05_Band_1
wc2_1_30s_tavg_04_Band_1
wc2_1_30s_tavg_03_Band_1
wc2_1_30s_tavg_02_Band_1
wc2_1_30s_tavg_01_Band_1

In [20]:
df.describe()

,id,id_memoire,id_ech,Longitude,latitude,altitude,UD,LD,average profondeur,pH,...,wc2_1_30s_srad_10_Band_1,wc2_1_30s_srad_09_Band_1,wc2_1_30s_srad_08_Band_1,wc2_1_30s_srad_07_Band_1,wc2_1_30s_srad_06_Band_1,wc2_1_30s_srad_05_Band_1,wc2_1_30s_srad_04_Band_1,wc2_1_30s_srad_03_Band_1,wc2_1_30s_srad_02_Band_1,wc2_1_30s_srad_01_Band_1
count,721.000000,721.000000,721.000000,711.000000,711.000000,402.00000,721.000000,721.000000,721.000000,705.000000,...,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000,721.000000
mean,1032.420250,49.238558,359.565881,4.851758,36.207702,238.20000,18.606103,38.217753,28.411928,7.461732,...,13813.570042,19034.812760,23737.511789,26317.142857,25012.471567,23663.932039,19733.320388,16101.829404,12000.907074,8867.153953
std,600.889102,25.838843,201.558749,2.231252,0.704983,328.24141,25.245300,46.338651,35.742261,1.063685,...,604.964894,741.489106,655.042013,779.546829,410.945603,667.290589,766.349308,787.991189,835.434261,655.271765
min,1.000000,1.000000,1.000000,0.492000,34.635081,3.00000,0.000000,5.000000,2.500000,4.102000,...,13086.000000,18059.000000,22529.000000,24747.000000,24145.000000,22379.000000,18844.000000,15277.000000,11125.000000,8209.000000
25%,523.000000,21.000000,189.000000,2.611669,35.610464,14.00000,0.000000,5.000000,2.500000,7.021000,...,13368.000000,18368.000000,23134.000000,25582.000000,24729.000000,23203.000000,19084.000000,15555.000000,11216.000000,8299.000000
50%,907.000000,57.000000,335.000000,5.307222,36.509564,35.00000,5.000000,15.000000,10.000000,7.815000,...,13428.000000,18875.000000,23911.000000,26490.000000,25015.000000,23561.000000,19441.000000,15637.000000,11746.000000,8622.000000
75%,1716.000000,63.000000,590.000000,6.883333,36.807500,397.60000,30.000000,60.000000,45.000000,8.200000,...,14256.000000,19473.000000,24287.000000,26989.000000,25261.000000,24015.000000,20156.000000,16788.000000,12533.000000,9447.000000
max,1922.000000,98.000000,640.000000,8.341389,36.904722,1100.00000,100.000000,200.000000,150.000000,9.150000,...,15231.000000,20867.000000,24937.000000,27516.000000,25935.000000,25126.000000,21736.000000,17993.000000,13949.000000,10585.000000

In [21]:
for i in df.columns[23:]:
    if i not in ["GLG" , "FAOSOIL" , "DOMSOI" ]:
        df[i] = df[i].apply(clean_numeric_data)
df

0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,13065
0.13065
0,13065
0.13065
0,06871
0.06871
0,06871
0.06871
0,00747
0.00747
0,00747
0.00747
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
0,18151
0.18151
0,18151
0.18151
0,18151
0.18151
0,18151
0.18151
0,18151
0.18151
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
3,28046
3.28046
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,01208
0.01208
0,01208
0.01208
0,01208
0.01208
0,01208
0.01208
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
0,02995
0.02995
2250,44404
2250.44404
2250,44404
2250.44404
1,7211
1.7211
1,7211
1.7211
1,7211
1.7211
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,06587
0.06587
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,04841
0.04841
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01262
0.01262
0,01619
0.01619
0,01619
0.01619
0,01619
0.01619
0,01619
0.01619
0,01619
0.01619
0,01619
0.01619
0,0525
0.0525
0,0525
0.0525
0,0525
0.0525
0,0525
0.0525
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,09537
0.09537
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
1,44534
1.44534
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,09278
0.09278
0,36127
0.36127
0,36127
0.36127
0,36127
0.36127
0,36127
0.36127
0,36127
0.36127
0,36127
0.36127
0,36127
0.36127
0,36127
0.36127
0,36127
0.36127
0,36127
0.36127
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
0,49126
0.49126
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
0,02995
0.02995
0,02995
0.02995
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,06871
0.06871
0,09537
0.09537
0,09537
0.09537
0,74335
0.74335
0,74335
0.74335
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
2250,44404
2250.44404
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,08386
0.08386
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,74335
0.74335
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
0,83343
0.83343
1,7211
1.7211
1,7211
1.7211
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
0,16179
0.16179
1,7211
1.7211
1,7211
1.7211
1,7211
1.7211
1,7211
1.7211
1,7211
1.7211
1,7211
1.7211
4,45323
4.45323
4,45323
4.45323
4,45323
4.45323
4,45323
4.45323
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
3,15305
3.15305
3,15305
3.15305
1,90991
1.90991
1,90991
1.90991
0,41303
0.41303
0,41303
0.41303
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
5,84619
5.84619
5,84619
5.84619
5,84619
5.84619
5,84619
5.84619
5,84619
5.84619
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
36,00955
36.00955
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
0,61386
0.61386
0,61386
0.61386
0,61386
0.61386
0,61386
0.61386
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
1,41514
1.41514
966,65344
966.65344
966,65344
966.65344
29,16134
29.16134
29,16134
29.16134
29,16134
29.16134
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,6432
1.6432
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
1,44904
1.44904
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
4,02312
4.02312
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,87359
0.87359
0,79154
0.79154
0,79154
0.79154
0,79154
0.79154
0,79154
0.79154
0,79154
0.79154
0,79154
0.79154
1,77752
1.77752
1,77752
1.77752
1,77752
1.77752
1,77752
1.77752
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
966,65344
966.65344
966,65344
966.65344
966,65344
966.65344
966,65344
966.65344
966,65344
966.65344
966,65344
966.65344
966,65344
966.65344
966,65344
966.65344
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
2,63835
2.63835
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
26,32195
26.32195
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
2,0109
2.0109
9,45533
9.45533
9,45533
9.45533
9,45533
9.45533
9,45533
9.45533
9,45533
9.45533
9,45533
9.45533
9,45533
9.45533
9,45533
9.45533
9,45533
9.45533
9,45533
9.45533
15,44171
15.44171
15,44171
15.44171
15,44171
15.44171
15,44171
15.44171
15,44171
15.44171
15,44171
15.44171
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
11,34691
11.34691
966,65344
966.65344
966,65344
966.65344
966,65344
966.65344
966,65344
966.65344
1,41514
1.41514
1,41514
1.41514
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
1,90991
1.90991
2,63835
2.63835
2,63835
2.63835
15,44171
15.44171
15,44171
15.44171
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128
1.87128
1,87128

,id,id_memoire,id_ech,Wilaya,Region,X,Y,Longitude,latitude,altitude,...,wc2_1_30s_tavg_10_Band_1,wc2_1_30s_tavg_09_Band_1,wc2_1_30s_tavg_08_Band_1,wc2_1_30s_tavg_07_Band_1,wc2_1_30s_tavg_06_Band_1,wc2_1_30s_tavg_05_Band_1,wc2_1_30s_tavg_04_Band_1,wc2_1_30s_tavg_03_Band_1,wc2_1_30s_tavg_02_Band_1,wc2_1_30s_tavg_01_Band_1
0,1,1,1,Alger,El-Harrach,3 107,36 684,3.107000,36.684000,22.0,...,1.98,2.38,2.61,25.00,2.21,18.50,1.53,1.34,1.21,1.16
1,2,1,1,Alger,El-Harrach,3 107,36 684,3.107000,36.684000,22.0,...,1.98,2.38,2.61,25.00,2.21,18.50,1.53,1.34,1.21,1.16
2,3,1,1,Alger,El-Harrach,3 107,36 684,3.107000,36.684000,22.0,...,1.98,2.38,2.61,25.00,2.21,18.50,1.53,1.34,1.21,1.16
3,4,2,2,Alger,El-Harrach,313 333,360 716 666,3.133333,36.716667,24.0,...,1.56,2.07,24.50,2.44,2.02,1.59,1.21,9.40,6.90,5.60
4,5,2,2,Alger,El-Harrach,313 333,360 716 666,3.133333,36.716667,24.0,...,1.56,2.07,24.50,2.44,2.02,1.59,1.21,9.40,6.90,5.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,1916,98,638,Tlemcen,Hennaya,-1 521 323 465 419 020,3 502 563 533 189 600,NaN,NaN,NaN,...,2.01,2.43,27.50,27.00,2.36,1.98,16.50,14.50,1.28,1.18
717,1919,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1.51,20.50,2.52,2.54,2.12,16.50,1.24,9.50,6.90,5.50
718,1920,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1.51,20.50,2.52,2.54,2.12,16.50,1.24,9.50,6.90,5.50
719,1921,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1.51,20.50,2.52,2.54,2.12,16.50,1.24,9.50,6.90,5.50
720,1922,98,640,Tlemcen,Hennaya,-1 180 072 342 969 800,3 443 635 942 679 530,NaN,NaN,NaN,...,1.51,20.50,2.52,2.54,2.12,16.50,1.24,9.50,6.90,5.50

In [22]:
df.to_csv("V1.csv")

In [23]:
df = pd.read_excel("results/soil_dataset.xlsx" , sheet_name="scorpan")
df

,id,id_memoire,id_ech,Wilaya,Region,X,Y,altitude,UD,LD,...,wc2_1_30s_wind_10_Band_1,wc2_1_30s_wind_09_Band_1,wc2_1_30s_wind_08_Band_1,wc2_1_30s_wind_07_Band_1,wc2_1_30s_wind_06_Band_1,wc2_1_30s_wind_05_Band_1,wc2_1_30s_wind_04_Band_1,wc2_1_30s_wind_03_Band_1,wc2_1_30s_wind_02_Band_1,wc2_1_30s_wind_01_Band_1
0,1,1,1,Alger,Harache,3.107000,36.684000,22,15,30,...,2.8,2.9,3.1,3.3,3.5,3.2,3.6,3.4,3.2,3.3
1,2,1,1,Alger,Harache,3.107000,36.684000,22,30,60,...,2.8,2.9,3.1,3.3,3.5,3.2,3.6,3.4,3.2,3.3
2,3,1,1,Alger,Harache,3.107000,36.684000,22,60,100,...,2.8,2.9,3.1,3.3,3.5,3.2,3.6,3.4,3.2,3.3
3,4,2,2,Alger,Harache,3.133330,36.071667,24,15,30,...,2.6,2.6,2.7,2.9,3.2,3.1,3.7,3.2,3.0,2.8
4,5,2,2,Alger,Harache,3.133330,36.071667,24,30,60,...,2.6,2.6,2.7,2.9,3.2,3.1,3.7,3.2,3.0,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251,1898,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,5,15,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5
1252,1899,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,15,30,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5
1253,1900,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,30,60,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5
1254,1901,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,60,100,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5
1255,1902,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,100,200,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1256 entries, 0 to 1255
Columns: 113 entries, id to wc2_1_30s_wind_01_Band_1
dtypes: float64(72), int64(37), object(4)
memory usage: 1.1+ MB

In [25]:
for i in df.columns :
    print(i)

id
id_memoire
id_ech
Wilaya
Region
X
Y
altitude
UD
LD
average profondeur
USDA Soil Taxonomy
pH
CE
CEC
A%
L%
S%
ALR(L)
ALR(S)
OM
GEO2_7G_
GEO2_7G_ID
GLG
DEM_SRTMGL1
land_cover
wc2_1_30s_prec_12_Band_1
wc2_1_30s_prec_11_Band_1
wc2_1_30s_prec_10_Band_1
wc2_1_30s_prec_09_Band_1
wc2_1_30s_prec_08_Band_1
wc2_1_30s_prec_07_Band_1
wc2_1_30s_prec_06_Band_1
wc2_1_30s_prec_05_Band_1
wc2_1_30s_prec_04_Band_1
wc2_1_30s_prec_03_Band_1
wc2_1_30s_prec_02_Band_1
wc2_1_30s_prec_01_Band_1
wc2_1_30s_srad_12_Band_1
wc2_1_30s_srad_11_Band_1
wc2_1_30s_srad_10_Band_1
wc2_1_30s_srad_09_Band_1
wc2_1_30s_srad_08_Band_1
wc2_1_30s_srad_07_Band_1
wc2_1_30s_srad_06_Band_1
wc2_1_30s_srad_05_Band_1
wc2_1_30s_srad_04_Band_1
wc2_1_30s_srad_03_Band_1
wc2_1_30s_srad_02_Band_1
wc2_1_30s_srad_01_Band_1
SNUM
FAOSOIL
DOMSOI
wc2_1_30s_tavg_12_Band_1
wc2_1_30s_tavg_11_Band_1
wc2_1_30s_tavg_10_Band_1
wc2_1_30s_tavg_09_Band_1
wc2_1_30s_tavg_08_Band_1
wc2_1_30s_tavg_07_Band_1
wc2_1_30s_tavg_06_Band_1
wc2_1_30s_tavg_05_Band_1
wc2_1_30s_tavg_04_Band_1
wc2_1_30s_tavg_03_Band_1
wc2_1_30s_tavg_02_Band_1
wc2_1_30s_tavg_01_Band_1
wc2_1_30s_tmax_12_Band_1
wc2_1_30s_tmax_11_Band_1
wc2_1_30s_tmax_10_Band_1
wc2_1_30s_tmax_09_Band_1
wc2_1_30s_tmax_08_Band_1
wc2_1_30s_tmax_07_Band_1
wc2_1_30s_tmax_06_Band_1
wc2_1_30s_tmax_05_Band_1
wc2_1_30s_tmax_04_Band_1
wc2_1_30s_tmax_03_Band_1
wc2_1_30s_tmax_02_Band_1
wc2_1_30s_tmax_01_Band_1
wc2_1_30s_tmin_12_Band_1
wc2_1_30s_tmin_11_Band_1
wc2_1_30s_tmin_10_Band_1
wc2_1_30s_tmin_09_Band_1
wc2_1_30s_tmin_08_Band_1
wc2_1_30s_tmin_07_Band_1
wc2_1_30s_tmin_06_Band_1
wc2_1_30s_tmin_05_Band_1
wc2_1_30s_tmin_04_Band_1
wc2_1_30s_tmin_03_Band_1
wc2_1_30s_tmin_02_Band_1
wc2_1_30s_tmin_01_Band_1
wc2_1_30s_vapr_12_Band_1
wc2_1_30s_vapr_11_Band_1
wc2_1_30s_vapr_10_Band_1
wc2_1_30s_vapr_09_Band_1
wc2_1_30s_vapr_08_Band_1
wc2_1_30s_vapr_07_Band_1
wc2_1_30s_vapr_06_Band_1
wc2_1_30s_vapr_05_Band_1
wc2_1_30s_vapr_04_Band_1
wc2_1_30s_vapr_03_Band_1
wc2_1_30s_vapr_02_Band_1
wc2_1_30s_vapr_01_Band_1
wc2_1_30s_wind_12_Band_1
wc2_1_30s_wind_11_Band_1
wc2_1_30s_wind_10_Band_1
wc2_1_30s_wind_09_Band_1
wc2_1_30s_wind_08_Band_1
wc2_1_30s_wind_07_Band_1
wc2_1_30s_wind_06_Band_1
wc2_1_30s_wind_05_Band_1
wc2_1_30s_wind_04_Band_1
wc2_1_30s_wind_03_Band_1
wc2_1_30s_wind_02_Band_1
wc2_1_30s_wind_01_Band_1

here we will start to build the windows

In [26]:
import rasterio
import numpy as np
import pandas as pd
import os 
df = pd.read_excel("results/soil_dataset.xlsx", sheet_name="scorpan")
df = df.dropna(subset=["X", "Y"])

def latlon_to_pixel(lat, lon, transform):
    if np.isnan(lat) or np.isnan(lon):
        return None
    
    pixel_size_x = transform[0]  
    pixel_size_y = transform[4]   
    origin_x = transform[2]       
    origin_y = transform[5]       

    col = (lon - origin_x) / pixel_size_x
    row = (origin_y - lat) / -pixel_size_y  # Invert pixel size for latitude

    return int(round(row)), int(round(col))
# used to save the ordre of the covariables
covariables=[]
# used to store all the windows ta3 chaque X , Y Nx7x7x6
df_patches = []
nb_covariables = 6
for i in os.listdir("Maps"):
    raster_path = f"Maps/{i}/wc2.1_30s_{i}_01.tif"
    covariables.append(i)  # to keep the order
    with rasterio.open(raster_path) as src:
        raster_data = src.read()
        transform = src.transform  # transformation matrix from lat lon to pixels
        print(src.crs)
        print(transform)

    patch_size = (7, 7 , nb_covariables)
    half_h, half_w = patch_size[0] // 2, patch_size[1] // 2
    
    for idx, row in df.iterrows():
        lat, lon = row["X"], row["Y"]
        # transformation to pixels 
        pixel_y, pixel_x = latlon_to_pixel(lat, lon, transform)
        top, bottom = max(0, pixel_y - half_h), min(raster_data.shape[1], pixel_y + half_h + 1)
        left, right = max(0, pixel_x - half_w), min(raster_data.shape[2], pixel_x + half_w + 1)
        if len(covariables)==1:
            window = np.zeros((patch_size[0], patch_size[1], patch_size[2]))
            df_patches.append(window)
        
        df_patches[idx][:,:,len(covariables)-1] = raster_data[:, top:bottom, left:right]
    
df_patches = np.array(df_patches)
print(df_patches.shape)

EPSG:4326
| 0.01, 0.00,-180.00|
| 0.00,-0.01, 90.00|
| 0.00, 0.00, 1.00|
EPSG:4326
| 0.01, 0.00,-180.00|
| 0.00,-0.01, 90.00|
| 0.00, 0.00, 1.00|
EPSG:4326
| 0.01, 0.00,-180.00|
| 0.00,-0.01, 90.00|
| 0.00, 0.00, 1.00|
EPSG:4326
| 0.01, 0.00,-180.00|
| 0.00,-0.01, 90.00|
| 0.00, 0.00, 1.00|
EPSG:4326
| 0.01, 0.00,-180.00|
| 0.00,-0.01, 90.00|
| 0.00, 0.00, 1.00|
EPSG:4326
| 0.01, 0.00,-180.00|
| 0.00,-0.01, 90.00|
| 0.00, 0.00, 1.00|
(1256, 7, 7, 6)

each one represent the window for a specific covariant

In [27]:
for i in range(6):
    print(f"layer of :{covariables[i]}")
    print(df_patches[0][:,:,i])
    print("=======================================")

layer of :prec
[[12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12.]]
=======================================
layer of :srad
[[20778. 20778. 20815. 20813. 20814. 20851. 20815.]
 [20774. 20810. 20809. 20809. 20846. 20811. 20812.]
 [20806. 20805. 20805. 20842. 20843. 20844. 20845.]
 [20840. 20839. 20839. 20839. 20840. 20804. 20806.]
 [20837. 20800. 20800. 20800. 20763. 20800. 20802.]
 [20834. 20833. 20797. 20797. 20796. 20760. 20798.]
 [20831. 20830. 20830. 20793. 20793. 20757. 20758.]]
=======================================
layer of :tmax
[[34.40000153 34.5        34.5        34.40000153 34.5        34.59999847
  34.70000076]
 [34.29999924 34.29999924 34.29999924 34.29999924 34.40000153 34.59999847
  34.70000076]
 [34.20000076 34.20000076 34.20000076 34.29999924 34.40000153 34.59999847
  34.70000076]
 [34.29999924 34.20000076 34.29999924 34.29999924 34.40000153 34.5
  34.70000076]
 [34.29999924 34.20000076 34.29999924 34.29999924 34.29999924 34.5
  34.59999847]
 [34.29999924 34.20000076 34.29999924 34.29999924 34.29999924 34.40000153
  34.59999847]
 [34.29999924 34.29999924 34.29999924 34.29999924 34.29999924 34.29999924
  34.5       ]]
=======================================
layer of :tmin
[[21.10000038 21.20000076 21.20000076 21.20000076 21.20000076 21.39999962
  21.39999962]
 [21.10000038 21.10000038 21.10000038 21.10000038 21.20000076 21.29999924
  21.39999962]
 [21.         20.89999962 21.         21.         21.20000076 21.29999924
  21.39999962]
 [21.         21.         21.         21.10000038 21.10000038 21.29999924
  21.39999962]
 [21.         21.         21.         21.10000038 21.10000038 21.20000076
  21.39999962]
 [21.         21.         21.         21.10000038 21.10000038 21.20000076
  21.29999924]
 [21.         21.         21.10000038 21.10000038 21.10000038 21.20000076
  21.29999924]]
=======================================
layer of :vapr
[[1.75999999 1.76999998 1.76999998 1.75999999 1.76999998 1.77999997
  1.77999997]
 [1.75999999 1.75999999 1.75999999 1.75999999 1.76999998 1.77999997
  1.78999996]
 [1.75       1.75       1.75       1.75999999 1.76999998 1.77999997
  1.78999996]
 [1.75       1.75       1.75       1.75999999 1.75999999 1.77999997
  1.78999996]
 [1.75999999 1.75       1.75999999 1.75999999 1.75999999 1.76999998
  1.77999997]
 [1.75999999 1.75       1.75999999 1.75999999 1.75999999 1.76999998
  1.77999997]
 [1.75999999 1.75999999 1.75999999 1.75999999 1.75999999 1.75999999
  1.76999998]]
=======================================
layer of :wind
[[2.20000005 2.20000005 2.20000005 2.20000005 2.20000005 2.20000005
  2.20000005]
 [2.20000005 2.20000005 2.20000005 2.20000005 2.20000005 2.20000005
  2.20000005]
 [2.20000005 2.20000005 2.20000005 2.20000005 2.20000005 2.20000005
  2.20000005]
 [2.20000005 2.0999999  2.20000005 2.20000005 2.20000005 2.20000005
  2.20000005]
 [2.20000005 2.20000005 2.20000005 2.20000005 2.20000005 2.20000005
  2.20000005]
 [2.20000005 2.20000005 2.20000005 2.20000005 2.20000005 2.20000005
  2.20000005]
 [2.20000005 2.20000005 2.20000005 2.20000005 2.20000005 2.20000005
  2.20000005]]
=======================================

In [28]:
for i in range(6):
    print(f"layer of :{covariables[i]}")
    print(df_patches[100][:,:,i])
    print("=======================================")

layer of :prec
[[51. 51. 50. 49. 49. 49. 49.]
 [52. 51. 51. 51. 50. 49. 49.]
 [52. 51. 51. 50. 49. 49. 49.]
 [51. 51. 50. 49. 48. 47. 46.]
 [51. 50. 50. 49. 47. 46. 46.]
 [51. 50. 49. 48. 47. 46. 47.]
 [50. 50. 49. 47. 47. 47. 47.]]
=======================================
layer of :srad
[[20010. 20014. 20054. 20168. 20208. 20210. 20216.]
 [20010. 20015. 20053. 20166. 20242. 20250. 20256.]
 [19979. 20018. 20060. 20102. 20216. 20221. 20225.]
 [19986. 20027. 20068. 20111. 20189. 20194. 20235.]
 [20024. 20032. 20074. 20116. 20160. 20201. 20240.]
 [20066. 20073. 20115. 20122. 20165. 20168. 20206.]
 [20072. 20078. 20192. 20270. 20275. 20243. 20244.]]
=======================================
layer of :tmax
[[30.         30.10000038 30.20000076 30.39999962 30.5        30.5
  30.60000038]
 [29.60000038 29.79999924 29.70000076 30.         30.10000038 30.39999962
  30.60000038]
 [29.60000038 29.70000076 30.         30.20000076 30.39999962 30.5
  30.60000038]
 [29.89999962 30.10000038 30.20000076 30.5        30.70000076 30.79999924
  31.        ]
 [29.79999924 30.20000076 30.39999962 30.60000038 30.89999962 31.10000038
  31.20000076]
 [30.         30.29999924 30.5        30.70000076 31.         31.
  30.89999962]
 [30.20000076 30.39999962 30.60000038 30.79999924 30.89999962 31.
  30.89999962]]
=======================================
layer of :tmin
[[13.30000019 13.5        13.5        13.69999981 13.80000019 13.80000019
  13.89999962]
 [13.10000038 13.30000019 13.30000019 13.5        13.60000038 13.80000019
  14.        ]
 [13.19999981 13.30000019 13.5        13.69999981 13.89999962 14.
  14.        ]
 [13.39999962 13.60000038 13.69999981 13.89999962 14.10000038 14.19999981
  14.30000019]
 [13.39999962 13.69999981 13.80000019 14.         14.30000019 14.39999962
  14.5       ]
 [13.5        13.69999981 13.89999962 14.10000038 14.30000019 14.39999962
  14.30000019]
 [13.60000038 13.80000019 14.         14.19999981 14.30000019 14.39999962
  14.30000019]]
=======================================
layer of :vapr
[[1.51999998 1.53999996 1.54999995 1.59000003 1.59000003 1.58000004
  1.61000001]
 [1.47000003 1.5        1.48000002 1.51999998 1.51999998 1.58000004
  1.62      ]
 [1.49000001 1.49000001 1.51999998 1.55999994 1.60000002 1.61000001
  1.63      ]
 [1.51999998 1.53999996 1.57000005 1.62       1.66999996 1.67999995
  1.72000003]
 [1.5        1.55999994 1.60000002 1.63999999 1.71000004 1.75
  1.75999999]
 [1.51999998 1.57000005 1.61000001 1.65999997 1.73000002 1.74000001
  1.71000004]
 [1.55999994 1.60000002 1.63       1.67999995 1.71000004 1.72000003
  1.69000006]]
=======================================
layer of :wind
[[1.60000002 1.60000002 1.70000005 1.79999995 1.79999995 1.79999995
  1.79999995]
 [1.60000002 1.60000002 1.60000002 1.70000005 1.70000005 1.79999995
  1.79999995]
 [1.5        1.60000002 1.70000005 1.70000005 1.79999995 1.79999995
  1.79999995]
 [1.60000002 1.60000002 1.70000005 1.70000005 1.79999995 1.79999995
  1.89999998]
 [1.60000002 1.60000002 1.70000005 1.79999995 1.79999995 1.89999998
  1.89999998]
 [1.70000005 1.70000005 1.70000005 1.79999995 1.79999995 1.79999995
  1.79999995]
 [1.70000005 1.70000005 1.79999995 1.89999998 1.89999998 1.89999998
  1.79999995]]
=======================================

now we gonna define the outputs in format : (N x 1 x number_of_soil_crecs)

In [29]:
df

,id,id_memoire,id_ech,Wilaya,Region,X,Y,altitude,UD,LD,...,wc2_1_30s_wind_10_Band_1,wc2_1_30s_wind_09_Band_1,wc2_1_30s_wind_08_Band_1,wc2_1_30s_wind_07_Band_1,wc2_1_30s_wind_06_Band_1,wc2_1_30s_wind_05_Band_1,wc2_1_30s_wind_04_Band_1,wc2_1_30s_wind_03_Band_1,wc2_1_30s_wind_02_Band_1,wc2_1_30s_wind_01_Band_1
0,1,1,1,Alger,Harache,3.107000,36.684000,22,15,30,...,2.8,2.9,3.1,3.3,3.5,3.2,3.6,3.4,3.2,3.3
1,2,1,1,Alger,Harache,3.107000,36.684000,22,30,60,...,2.8,2.9,3.1,3.3,3.5,3.2,3.6,3.4,3.2,3.3
2,3,1,1,Alger,Harache,3.107000,36.684000,22,60,100,...,2.8,2.9,3.1,3.3,3.5,3.2,3.6,3.4,3.2,3.3
3,4,2,2,Alger,Harache,3.133330,36.071667,24,15,30,...,2.6,2.6,2.7,2.9,3.2,3.1,3.7,3.2,3.0,2.8
4,5,2,2,Alger,Harache,3.133330,36.071667,24,30,60,...,2.6,2.6,2.7,2.9,3.2,3.1,3.7,3.2,3.0,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251,1898,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,5,15,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5
1252,1899,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,15,30,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5
1253,1900,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,30,60,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5
1254,1901,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,60,100,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5
1255,1902,89,632,Skikda,El Hadaiek,6.904722,36.847222,31,100,200,...,3.1,3.2,3.2,3.4,3.6,3.5,3.5,3.6,3.6,3.5

In [33]:
final_outputs = []
for i in range(len(df)):
    output = []
    for j in df.columns[14:23]:
        output.append(df.iloc[i][j])
    output = np.array(output)
    output = output.reshape((len(output),1))
    final_outputs.append(output)
    
print(final_outputs)

[array([[ 1.79290000e+01],
       [ 4.61720905e+01],
       [ 4.56132493e+01],
       [ 8.21466017e+00],
       [-5.28862322e-03],
       [-7.49790032e-01],
       [ 2.01900000e+00],
       [ 1.62000000e+02],
       [ 8.60000000e+01]]), array([[ 1.72070000e+01],
       [ 4.03614960e+01],
       [ 3.72817768e+01],
       [ 2.23567272e+01],
       [-3.44707427e-02],
       [-2.56559117e-01],
       [ 1.50300000e+00],
       [ 1.62000000e+02],
       [ 8.60000000e+01]]), array([[ 1.50490000e+01],
       [ 4.96085300e+01],
       [ 4.23170428e+01],
       [ 8.07442715e+00],
       [-6.90411313e-02],
       [-7.88444722e-01],
       [ 7.06000000e-01],
       [ 1.62000000e+02],
       [ 8.60000000e+01]]), array([[ 4.06109533e+01],
       [ 3.23303997e+01],
       [ 4.04604562e+01],
       [ 2.72091442e+01],
       [ 9.74195656e-02],
       [-7.48963279e-02],
       [ 2.64500000e+00],
       [ 3.85000000e+02],
       [ 3.18000000e+02]]), array([[ 4.06109533e+01],
       [ 3.38983407e+01],
       [ 3.92483859e+01],
       [ 2.68532733e+01],
       [ 6.36432261e-02],
       [-1.01181343e-01],
       [ 1.09700000e+00],
       [ 3.85000000e+02],
       [ 3.18000000e+02]]), array([[ 40.61095331],
       [ 13.        ],
       [ 32.        ],
       [ 55.        ],
       [  0.39120629],
       [  0.626419  ],
       [  7.27      ],
       [162.        ],
       [ 86.        ]]), array([[ 40.61095331],
       [ 13.        ],
       [ 32.        ],
       [ 55.        ],
       [  0.39120629],
       [  0.626419  ],
       [  7.27      ],
       [162.        ],
       [ 86.        ]]), array([[ 40.61095331],
       [  7.21      ],
       [ 11.57      ],
       [ 81.22      ],
       [  0.20539749],
       [  1.05172712],
       [  4.1       ],
       [143.        ],
       [ 70.        ]]), array([[ 40.61095331],
       [  7.21      ],
       [ 11.57      ],
       [ 81.22      ],
       [  0.20539749],
       [  1.05172712],
       [  4.1       ],
       [143.        ],
       [ 70.        ]]), array([[  3.75      ],
       [ 27.23996636],
       [ 42.85725243],
       [ 29.90278121],
       [         nan],
       [         nan],
       [  1.36      ],
       [162.        ],
       [ 86.        ]]), array([[  3.75      ],
       [ 27.23996636],
       [ 42.85725243],
       [ 29.90278121],
       [         nan],
       [         nan],
       [  1.36      ],
       [162.        ],
       [ 86.        ]]), array([[ 1.85700000e+01],
       [ 3.95000000e+01],
       [ 1.86000000e+01],
       [ 4.19000000e+01],
       [-3.27084261e-01],
       [ 2.56168174e-02],
       [ 3.51542792e+00],
       [ 1.62000000e+02],
       [ 8.60000000e+01]]), array([[ 1.85700000e+01],
       [ 3.95000000e+01],
       [ 1.86000000e+01],
       [ 4.19000000e+01],
       [-3.27084261e-01],
       [ 2.56168174e-02],
       [ 3.51542792e+00],
       [ 1.62000000e+02],
       [ 8.60000000e+01]]), array([[ 15.32      ],
       [ 31.8       ],
       [ 12.85      ],
       [ 55.35      ],
       [ -0.39352413],
       [  0.24069037],
       [  3.51542792],
       [162.        ],
       [ 86.        ]]), array([[ 15.32      ],
       [ 31.8       ],
       [ 12.85      ],
       [ 55.35      ],
       [ -0.39352413],
       [  0.24069037],
       [  3.51542792],
       [162.        ],
       [ 86.        ]]), array([[ 40.61095331],
       [ 56.        ],
       [ 37.43      ],
       [  6.57      ],
       [ -0.17496828],
       [ -0.93062273],
       [  3.03      ],
       [162.        ],
       [ 86.        ]]), array([[ 40.61095331],
       [ 56.        ],
       [ 37.43      ],
       [  6.57      ],
       [ -0.17496828],
       [ -0.93062273],
       [  3.03      ],
       [162.        ],
       [ 86.        ]]), array([[ 4.09900000e+01],
       [ 4.82885171e+01],
       [ 4.11195888e+01],
       [ 1.05918941e+01],
       [-6.97951958e-02],
       [-6.58870330e-01],
       [ 2.08900000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 4.34870000e+01],
       [ 4.66935331e+01],
       [ 4.25265747e+01],
       [ 1.07798922e+01],
       [-4.05964248e-02],
       [-6.36642411e-01],
       [ 1.80400000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 4.71630000e+01],
       [ 4.62264623e+01],
       [ 4.32354324e+01],
       [ 1.05381054e+01],
       [-2.90509456e-02],
       [-6.42128215e-01],
       [ 1.21500000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.97690000e+01],
       [ 6.24173758e+01],
       [ 3.07576924e+01],
       [ 6.82493175e+00],
       [-3.07351826e-01],
       [-9.61207263e-01],
       [ 1.02200000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.24640000e+01],
       [ 7.51970000e+01],
       [ 2.07620000e+01],
       [ 4.04100000e+00],
       [-5.58931386e-01],
       [-1.26971172e+00],
       [ 1.12200000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.48290000e+01],
       [ 5.16680000e+01],
       [ 4.11300000e+01],
       [ 7.20200000e+00],
       [-9.90630255e-02],
       [-8.55768618e-01],
       [ 9.00000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.96440000e+01],
       [ 5.21160000e+01],
       [ 4.12470000e+01],
       [ 6.63700000e+00],
       [-1.01578792e-01],
       [-8.94999341e-01],
       [ 9.40000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 4.78240000e+01],
       [ 5.22290000e+01],
       [ 4.11750000e+01],
       [ 6.59600000e+00],
       [-1.03278186e-01],
       [-8.98631147e-01],
       [ 9.56000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 4.02320000e+01],
       [ 4.75760000e+01],
       [ 3.93390000e+01],
       [ 1.30850000e+01],
       [-8.25647009e-02],
       [-5.60614290e-01],
       [ 5.72000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.08620000e+01],
       [ 4.39120000e+01],
       [ 3.79440000e+01],
       [ 1.81440000e+01],
       [-6.34402050e-02],
       [-3.83850279e-01],
       [ 2.67000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[  16.629     ],
       [  17.91333479],
       [  25.86788024],
       [  56.21878497],
       [          nan],
       [          nan],
       [   1.456     ],
       [ 784.        ],
       [1085.        ]]), array([[  30.495     ],
       [  15.89646465],
       [  27.82077532],
       [  56.28276003],
       [          nan],
       [          nan],
       [   1.224     ],
       [ 784.        ],
       [1085.        ]]), array([[5.43600000e+01],
       [1.79574366e+01],
       [2.64811185e+01],
       [5.55614449e+01],
       [           nan],
       [           nan],
       [7.85000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[3.43610000e+01],
       [8.16192860e+00],
       [3.31429641e+01],
       [5.86951073e+01],
       [           nan],
       [           nan],
       [8.73000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[   8.696     ],
       [   9.19503892],
       [  30.28063321],
       [  60.52432787],
       [          nan],
       [          nan],
       [   1.128     ],
       [ 784.        ],
       [1085.        ]]), array([[3.90290000e+01],
       [1.27772537e+01],
       [3.77872664e+01],
       [4.94354799e+01],
       [           nan],
       [           nan],
       [1.08400000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[3.31110000e+01],
       [1.17337523e+01],
       [3.35537577e+01],
       [5.47124900e+01],
       [           nan],
       [           nan],
       [8.61000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[2.09010000e+01],
       [8.99288874e+00],
       [2.73608088e+01],
       [6.36463024e+01],
       [           nan],
       [           nan],
       [4.08000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[1.71000000e+01],
       [1.34402145e+01],
       [2.58417808e+01],
       [6.07180047e+01],
       [           nan],
       [           nan],
       [3.11000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[1.93260000e+01],
       [9.83903219e+00],
       [3.51489702e+01],
       [5.50119976e+01],
       [           nan],
       [           nan],
       [4.27000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[1.66310000e+01],
       [2.46390000e+01],
       [4.03700000e+01],
       [3.49910000e+01],
       [2.14435496e-01],
       [1.52333100e-01],
       [2.07400000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[2.06250000e+01],
       [1.87278127e+01],
       [3.67306327e+01],
       [4.45415546e+01],
       [2.92541120e-01],
       [3.76278081e-01],
       [1.60400000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[2.80350000e+01],
       [6.74600000e+00],
       [2.94710000e+01],
       [6.37830000e+01],
       [6.40347892e-01],
       [9.75657962e-01],
       [6.84000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[2.55390000e+01],
       [4.24300000e+00],
       [2.86520000e+01],
       [6.71050000e+01],
       [8.29480887e-01],
       [1.19908083e+00],
       [6.76000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[2.04560000e+01],
       [7.38200000e+00],
       [3.10950000e+01],
       [6.15230000e+01],
       [6.24515932e-01],
       [9.20862875e-01],
       [1.06000000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[1.25230000e+01],
       [2.01080000e+01],
       [4.41540000e+01],
       [3.57380000e+01],
       [3.41600961e-01],
       [2.49761152e-01],
       [9.32000000e-01],
       [7.37000000e+02],
       [1.00600000e+03]]), array([[1.36850000e+01],
       [2.32070000e+01],
       [4.12170000e+01],
       [3.55760000e+01],
       [2.49457189e-01],
       [1.85537927e-01],
       [8.42000000e-01],
       [7.37000000e+02],
       [1.00600000e+03]]), array([[1.68370000e+01],
       [2.88327117e+01],
       [3.62116379e+01],
       [3.49556504e+01],
       [9.89625291e-02],
       [8.36317481e-02],
       [6.61000000e-01],
       [7.37000000e+02],
       [1.00600000e+03]]), array([[2.21950000e+01],
       [2.61420000e+01],
       [4.07460000e+01],
       [3.31120000e+01],
       [1.92746004e-01],
       [1.02646437e-01],
       [6.22000000e-01],
       [7.37000000e+02],
       [1.00600000e+03]]), array([[2.50200000e+01],
       [2.16650000e+01],
       [4.63930000e+01],
       [3.19420000e+01],
       [3.30693563e-01],
       [1.68603212e-01],
       [6.69000000e-01],
       [7.37000000e+02],
       [1.00600000e+03]]), array([[3.46780000e+01],
       [8.08900000e+00],
       [3.16220000e+01],
       [6.02890000e+01],
       [5.92093962e-01],
       [8.72342708e-01],
       [7.14000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[3.02070000e+01],
       [8.66800000e+00],
       [3.34300000e+01],
       [5.79020000e+01],
       [5.86216973e-01],
       [8.24774161e-01],
       [9.86000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[2.05880000e+01],
       [9.59109591e+00],
       [3.69483695e+01],
       [5.34605346e+01],
       [5.85726591e-01],
       [7.46164611e-01],
       [1.45800000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[1.52980000e+01],
       [8.31400000e+00],
       [3.68220000e+01],
       [5.48640000e+01],
       [6.46296831e-01],
       [8.19476925e-01],
       [1.08500000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[1.52690000e+01],
       [6.92993070e+00],
       [3.52316477e+01],
       [5.78384216e+01],
       [7.06203436e-01],
       [9.21486914e-01],
       [5.94000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[6.83800000e+00],
       [5.67157682e+00],
       [9.67620668e+00],
       [8.46522165e+01],
       [2.32000560e-01],
       [1.17393376e+00],
       [1.49800000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[8.33200000e+00],
       [4.89577129e+00],
       [9.26245781e+00],
       [8.58417709e+01],
       [2.76904241e-01],
       [1.24387667e+00],
       [1.21500000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[1.11650000e+01],
       [3.19462631e+00],
       [8.83620043e+00],
       [8.79691733e+01],
       [4.41844136e-01],
       [1.43990909e+00],
       [5.93000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[1.06070000e+01],
       [2.18035478e+00],
       [1.12241221e+01],
       [8.65955232e+01],
       [7.11623220e-01],
       [1.59896628e+00],
       [1.74000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[8.97100000e+00],
       [2.12247182e+00],
       [1.32544568e+01],
       [8.46230714e+01],
       [7.95517956e-01],
       [1.60064481e+00],
       [1.12000000e-01],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[ 3.57350000e+01],
       [ 4.06331873e+01],
       [ 4.01341973e+01],
       [ 1.92326153e+01],
       [-5.36641583e-03],
       [-3.24842652e-01],
       [ 8.18000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.35250000e+01],
       [ 4.29625778e+01],
       [ 4.04044243e+01],
       [ 1.66329980e+01],
       [-2.66615095e-02],
       [-4.12119897e-01],
       [ 6.65000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 2.92870000e+01],
       [ 4.68932204e+01],
       [ 4.08866798e+01],
       [ 1.22200998e+01],
       [-5.95283064e-02],
       [-5.84035398e-01],
       [ 5.32000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 2.98350000e+01],
       [ 4.30528767e+01],
       [ 4.06034198e+01],
       [ 1.63437035e+01],
       [-2.54396623e-02],
       [-4.20651802e-01],
       [ 1.54800000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.20590000e+01],
       [ 3.84075269e+01],
       [ 4.01783842e+01],
       [ 2.14140890e+01],
       [ 1.95760106e-02],
       [-2.53716854e-01],
       [ 2.39500000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 4.00720000e+01],
       [ 4.06324190e+01],
       [ 3.99311721e+01],
       [ 1.94364090e+01],
       [-7.56072648e-03],
       [-3.20256756e-01],
       [ 2.07000000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.97660000e+01],
       [ 4.09151381e+01],
       [ 4.10451522e+01],
       [ 1.80397097e+01],
       [ 1.37774217e-03],
       [-3.55654583e-01],
       [ 1.61600000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.87470000e+01],
       [ 4.15526567e+01],
       [ 4.30398325e+01],
       [ 1.54075108e+01],
       [ 1.52716693e-02],
       [-4.30866422e-01],
       [ 7.75000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.61880000e+01],
       [ 4.19470692e+01],
       [ 4.15130607e+01],
       [ 1.65398701e+01],
       [-4.51697232e-03],
       [-4.04169633e-01],
       [ 1.06900000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.46320000e+01],
       [ 4.19753332e+01],
       [ 3.95424123e+01],
       [ 1.84822546e+01],
       [-2.59310949e-02],
       [-3.56239307e-01],
       [ 1.65400000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.93960000e+01],
       [ 3.29656703e+01],
       [ 4.20725793e+01],
       [ 2.49617504e+01],
       [ 1.05937094e-01],
       [-1.20787007e-01],
       [ 1.73100000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.85690000e+01],
       [ 3.90366096e+01],
       [ 4.16365836e+01],
       [ 1.93268067e+01],
       [ 2.80028846e-02],
       [-3.05312099e-01],
       [ 1.56200000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.59970000e+01],
       [ 5.19800000e+01],
       [ 4.01790000e+01],
       [ 7.84100000e+00],
       [-1.11837235e-01],
       [-8.21464905e-01],
       [ 1.20400000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.01800000e+01],
       [ 5.84400000e+01],
       [ 3.64950000e+01],
       [ 5.06500000e+00],
       [-2.04476914e-01],
       [-1.06213083e+00],
       [ 1.03200000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 2.67510000e+01],
       [ 5.79680000e+01],
       [ 3.42510000e+01],
       [ 7.78100000e+00],
       [-2.28515136e-01],
       [-8.72152976e-01],
       [ 1.05000000e+00],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[2.15770000e+01],
       [4.26700000e+00],
       [4.03870000e+01],
       [5.53460000e+01],
       [9.76117934e-01],
       [1.11296258e+00],
       [1.04300000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[2.17040000e+01],
       [1.72820000e+01],
       [4.26650000e+01],
       [4.00530000e+01],
       [3.92477498e-01],
       [3.65040799e-01],
       [1.02800000e+00],
       [7.84000000e+02],
       [1.08500000e+03]]), array([[ 2.35520000e+01],
       [ 4.41538723e+01],
       [ 4.67610305e+01],
       [ 9.08509724e+00],
       [ 2.49151779e-02],
       [-6.86639315e-01],
       [ 9.49000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 3.33060000e+01],
       [ 5.24834142e+01],
       [ 4.44588573e+01],
       [ 3.05772849e+00],
       [-7.20638651e-02],
       [-1.23462324e+00],
       [ 6.47000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 4.01020000e+01],
       [ 4.84195158e+01],
       [ 4.16535835e+01],
       [ 9.92690073e+00],
       [-6.53681621e-02],
       [-6.88206853e-01],
       [ 4.46000000e-01],
       [ 7.84000000e+02],
       [ 1.08500000e+03]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.955     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.955     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.955     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.955     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.955     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.725     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.725     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.725     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.725     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.725     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 17.        ],
       [ 77.        ],
       [  6.        ],
       [  0.65604155],
       [ -0.45229793],
       [  1.725     ],
       [360.        ],
       [447.        ]]), array([[ 40.61095331],
       [ 20.83333333],
       [ 75.        ],
       [  4.16666667],

CNN feeding ( in another ipynb file bcs it will be tested on colab)

In [34]:
np.save('inputs.npy', np.array(df_patches))
np.save('output.npy', np.array(final_outputs))