# Text Data

In [2]:
from langchain.text_splitter import RecursiveCharacterTextSplitter
import fitz
def doc_chunker(pdf_path):
    doc = fitz.open(pdf_path)
    pdf_text = ""
    for page in doc:
        pdf_text += page.get_text()

    splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
    chunks = splitter.split_text(pdf_text)
    keywords = keywords = [
        "soil", "sol",
        "pH",
        "moisture", "humidité",
        "organic matter", "matière organique", "MO",
        "texture", "texture du sol",
        "salinity", "salinité",

        "X", "Y",
        "Longitude", "Longitude",
        "Latitude", "Latitude",
        "Altitude", "Altitude",

        "UD", "Upper Depth", "Profondeur supérieure", "profondeur supérieure",
        "LD", "Lower Depth", "Profondeur inférieure", "profondeur inférieure",
        "Average profondeur", "Profondeur moyenne", "profondeur moyenne",
        "profondeur", "depth",

        "USDA Soil Taxonomy", "Taxonomie des sols USDA",

        "CE", "Conductivité électrique",
        "CEC", "Capacité d’échange cationique",

        "A%", "Argile", "Clay", "taux d’argile",
        "L%", "Limon", "Silt", "taux de limon",
        "S%", "Sable", "Sand", "taux de sable",

        "ALR(L)", "ALR(S)",
        "OM", "matière organique",
    ]
    
    relevant_chunks = [chunk for chunk in chunks if any(k in chunk.lower() for k in keywords)]
    len(relevant_chunks)
    return relevant_chunks

In [3]:
import os
def find_all_pdf_files(root_folder):
    pdf_files = []
    for root, dirs, files in os.walk(root_folder):
        for file in files:
            if file.lower().endswith(('.pdf')):
                pdf_files.append(os.path.join(root, file))
    return pdf_files

In [14]:
all_files = find_all_pdf_files("../theses/")
for index , i in enumerate(all_files[200:]):
  print(f"{200+index}/{len(all_files)}")
  text = " ".join(doc_chunker(i))
  Prompt = f"""
    You are an expert in soil data extraction. Given a raw text report, your task is to extract structured data about soil characteristics along with their geographic location.

    ### Text:
    {text}

    ### Instructions:
    - Parse the text and extract the following fields for **each unique location** (based on Latitude and Longitude) and **each reported depth**:
      - filename
      - X
      - Y
      - Longitude
      - Latitude
      - Altitude
      - UD (Upper Depth)
      - LD (Lower Depth)
      - Average profondeur (average of UD and LD)
      - USDA Soil Taxonomy
      - pH
      - CE
      - CEC
      - A% (Argile / Clay %)
      - L% (Limon / Silt %)
      - S% (Sable / Sand %)
      - ALR(L)
      - ALR(S)
      - OM (Organic Matter)

    - If a field is missing in the text, set its value to `null`.
    - Your output must be in **CSV format** and contain only the table — no explanations, no markdown formatting.

    ### Output format:
    Each row should represent a single depth profile. The first line should be the header:

    filename,X,Y,Longitude,Latitude,Altitude,UD,LD,Average profondeur,USDA Soil Taxonomy,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM

    Followed by one row per depth/location.

    Note that the file name is: {i}
    """

  from together import Together

  client = Together(api_key="875fef17f5f34497577741f100d62abc27b7a727ece6cb92a3f084d2f05dfb40")

  response = client.chat.completions.create(
      model="meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
      messages=[{"role": "user", "content": Prompt}]
  )
  print(response.choices[0].message.content)
  with open("res3.txt" , "a" , encoding="utf8") as src:
      src.write(response.choices[0].message.content)

200/218

KeyboardInterrupt:

In [1]:
import pandas as pd 
df = pd.read_csv("res.csv")
df

,filename,X,Y,Longitude,Latitude,Altitude,UD,LD,Average profondeur,USDA Soil Taxonomy,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,../theses/Nord\memoires traited\Bio écologie d...,NaN,NaN,NaN,NaN,NaN,0,10,NaN,NaN,8.33,NaN,NaN,17.6,20.3,62.1,NaN,NaN,2.12
1,../theses/Nord\memoires traited\Bio écologie d...,NaN,NaN,NaN,NaN,NaN,0,30,NaN,NaN,8.29,NaN,NaN,42.7,31.8,25.5,NaN,NaN,1.59
2,../theses/Nord\memoires traited\Bio écologie d...,NaN,NaN,NaN,NaN,NaN,0,30,NaN,NaN,8.3,NaN,NaN,31.6,23,45.2,NaN,NaN,1.05
3,../theses/Nord\memoires traited\Caractérisatio...,NaN,NaN,3.0583,36.7232,1200,0,10,5,NaN,7.2,NaN,15,20,40,40,NaN,NaN,NaN
4,../theses/Nord\memoires traited\Caractérisatio...,NaN,NaN,3.0583,36.7232,1200,10,20,15,NaN,7.5,NaN,12,25,35,40,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,0,8,4,NaN,7.39,2.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2352,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,8,34,21,NaN,7.65,4.87,NaN,NaN,NaN,NaN,NaN,NaN,0.53
2353,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,34,43,38.5,NaN,7.99,5.48,NaN,NaN,NaN,NaN,NaN,NaN,1.06
2354,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,43,60,51.5,NaN,8.04,4.07,NaN,NaN,NaN,NaN,NaN,NaN,0
2355,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,60,80,70,NaN,7.9,3.13,NaN,NaN,NaN,NaN,NaN,NaN,0

In [2]:
df_cleaned = df.dropna(subset=["X" , "Y" , "Longitude" , "Latitude"], how='all')
df_cleaned

,filename,X,Y,Longitude,Latitude,Altitude,UD,LD,Average profondeur,USDA Soil Taxonomy,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
3,../theses/Nord\memoires traited\Caractérisatio...,NaN,NaN,3.0583,36.7232,1200,0,10,5,NaN,7.2,NaN,15,20,40,40,NaN,NaN,NaN
4,../theses/Nord\memoires traited\Caractérisatio...,NaN,NaN,3.0583,36.7232,1200,10,20,15,NaN,7.5,NaN,12,25,35,40,NaN,NaN,NaN
57,../theses/Nord\memoires traited\TH9217.pdf,NaN,NaN,3°0'57.627E,36°48'53.426''N,NaN,NaN,NaN,NaN,NaN,NaN,8.04,0.575,NaN,NaN,NaN,NaN,NaN,NaN
58,../theses/Nord\memoires traited\TH9217.pdf,NaN,NaN,3°56'12.638''E,36°52'42.096''N,NaN,NaN,NaN,NaN,NaN,NaN,7.65,0.582,NaN,NaN,NaN,NaN,NaN,NaN
59,../theses/Nord\memoires traited\TH9217.pdf,NaN,NaN,6°10'26.081''E,35°33'39.687''N,NaN,NaN,NaN,NaN,NaN,NaN,7.74,0.210,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,0,8,4,NaN,7.39,2.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2352,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,8,34,21,NaN,7.65,4.87,NaN,NaN,NaN,NaN,NaN,NaN,0.53
2353,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,34,43,38.5,NaN,7.99,5.48,NaN,NaN,NaN,NaN,NaN,NaN,1.06
2354,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,43,60,51.5,NaN,8.04,4.07,NaN,NaN,NaN,NaN,NaN,NaN,0
2355,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.43190,27.19314,NaN,60,80,70,NaN,7.9,3.13,NaN,NaN,NaN,NaN,NaN,NaN,0

In [3]:
for i in range(len(df_cleaned)):
    print(f" X : {df_cleaned.iloc[i]['X']} , Y : {df_cleaned.iloc[i]['Y']}")

 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 2.14 , Y : 30.43
 X : 3.15987 , Y : 36.71253
 X : 3.15987 , Y : 36.71253
 X : 3.15987 , Y : 36.71253
 X : 3.15987 , Y : 36.71253
 X : 3.15987 , Y : 36.71253
 X : 3.15987 , Y : 36.71253
 X : 3.15987 , Y : 36.71253
 X : 3.15987 , Y : 36.71253
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 06 06 22 , Y : 35 34 58
 X : 06 06 15 , Y : 35 34 58
 X : 06 06 35 , Y : 35 34 48
 X : 06 06 55 , Y : 35 34 38
 X : 06 06 25 , Y : 35 34 28
 X : 06 06 35 , Y : 35 34 41
 X : 06 06 05 , Y : 35 34 46
 X : 06 06 25 , Y : 35 34 36
 X : 05 57 14.21 , Y : 35 33 42.15
 X : 05 57 19.15 , Y : 35 34 10.03
 X : 05 56 44.55 , Y : 35 34 14.34
 X : 05 57 29.05 , Y : 35 34 14.34
 X : 05 56 59.38 , Y : 35 34 26.39
 X : 05 57 14.21 , Y : 35 34 46.48
 X : 05 56 34.65 , Y : 35 35 02.57
 X : 05 57 43.88 , Y : 35 35 34.72
 X : 05 58 28.37 , Y : 35 35 14.64
 X : 06 06 22 , Y : 35 34 58
 X : 06 06 15 , Y : 35 34 58
 X : 06 06 35 , Y : 35 34 48
 X : 06 06 55 , Y : 35 34 38
 X : 06 06 25 , Y : 35 34 28
 X : 06 06 35 , Y : 35 34 41
 X : 06 06 05 , Y : 35 34 46
 X : 06 06 25 , Y : 35 34 36
 X : 05 57 14.21 , Y : 35 33 42.15
 X : 05 57 19.15 , Y : 35 34 10.03
 X : 05 56 44.55 , Y : 35 34 14.34
 X : 05 57 29.05 , Y : 35 34 14.34
 X : 05 56 59.38 , Y : 35 34 26.39
 X : 05 57 14.21 , Y : 35 34 46.48
 X : 05 56 34.65 , Y : 35 35 02.57
 X : 05 57 43.88 , Y : 35 35 34.72
 X : 05 58 28.37 , Y : 35 35 14.64
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 986 , Y : 412
 X : 986 , Y : 412
 X : 986 , Y : 412
 X : 986 , Y : 412
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 1002 , Y : 416
 X : 1002 , Y : 416
 X : 1002 , Y : 416
 X : 1003 , Y : 415
 X : 1003 , Y : 415
 X : 1003 , Y : 415
 X : 1003 , Y : 415
 X : 1003 , Y : 415
 X : 1003 , Y : 415
 X : 1003 , Y : 415
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 982 , Y : 408
 X : 1002 , Y : 414
 X : 1002 , Y : 414
 X : 1002 , Y : 414
 X : 1002 , Y : 414
 X : 1002 , Y : 414
 X : 1002 , Y : 414
 X : 1002 , Y : 414
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 7.904167 , Y : 36.78333
 X : 8.25 , Y : 36.78333
 X : 8.25 , Y : 36.78333
 X : 8.25 , Y : 36.78333
 X : 8.25 , Y : 36.78333
 X : 8.168056 , Y : 36.85
 X : 8.168056 , Y : 36.85
 X : 8.168056 , Y : 36.85
 X : 8.168056 , Y : 36.85
 X : 8.168056 , Y : 36.85
 X : 8.2 , Y : 36.83333
 X : 8.2 , Y : 36.83333
 X : 8.2 , Y : 36.83333
 X : 8.316667 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : 8.35 , Y : 36.85
 X : 8.35 , Y : 36.85
 X : 8.35 , Y : 36.85
 X : 8.35 , Y : 36.85
 X : 8.35 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : 8.316667 , Y : 36.85
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 673883 , Y : 3917621
 X : 1 , Y : 1
 X : 1 , Y : 1
 X : 2 , Y : 2
 X : 2 , Y : 2
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 1 , Y : 1
 X : 1 , Y : 1
 X : 2 , Y : 2
 X : 123 , Y : 456
 X : 123 , Y : 456
 X : 1 , Y : 1
 X : 1 , Y : 1
 X : 2 , Y : 2
 X : 1 , Y : 1
 X : 1 , Y : 1
 X : 2 , Y : 2
 X : 2 , Y : 2
 X : 510.8 , Y : 328.6
 X : 510.8 , Y : 328.6
 X : 506.7 , Y : 321.4
 X : 506.7 , Y : 321.4
 X : 514.4 , Y : 328.5
 X : 514.4 , Y : 328.3
 X : 514.4 , Y : 328.3
 X : 514.4 , Y : 328.3
 X : 509.9 , Y : 318.5
 X : 509.9 , Y : 318.5
 X : 509.9 , Y : 318.5
 X : 510.8 , Y : 327.8
 X : 510.8 , Y : 327.8
 X : 514.5 , Y : 328.4
 X : 514.5 , Y : 328.4
 X : 511.7 , Y : 326.4
 X : 511.7 , Y : 326.4
 X : 514.6 , Y : 328.4
 X : 514.6 , Y : 328.4
 X : 514.6 , Y : 328.4
 X : 519.7 , Y : 332.6
 X : 519.7 , Y : 332.6
 X : 519.7 , Y : 332.6
 X : 513.5 , Y : 327.5
 X : 513.5 , Y : 327.5
 X : 520.5 , Y : 330.3
 X : 520.5 , Y : 330.3
 X : 520.5 , Y : 330.3
 X : 510.4 , Y : 329.5
 X : 510.4 , Y : 329.5
 X : 510.4 , Y : 329.5
 X : 510.4 , Y : 329.5
 X : 510.4 , Y : 329.5
 X : 519.1 , Y : 321.1
 X : 519.1 , Y : 321.1
 X : 518.1 , Y : 323.6
 X : 518.1 , Y : 323.6
 X : 518.1 , Y : 323.6
 X : 518.1 , Y : 323.6
 X : 514.5 , Y : 322.6
 X : 514.5 , Y : 322.6
 X : 514.5 , Y : 322.6
 X : 515.7 , Y : 320.7
 X : 515.7 , Y : 320.7
 X : 515.7 , Y : 320.7
 X : 515.7 , Y : 320.7
 X : 521.4 , Y : 329.6
 X : 521.4 , Y : 329.6
 X : 521.4 , Y : 329.6
 X : 520.6 , Y : 328.3
 X : 520.6 , Y : 328.3
 X : 520.6 , Y : 328.3
 X : 520.6 , Y : 328.3
 X : 506.4 , Y : 316
 X : 506.4 , Y : 316
 X : 284.3 , Y : 433.1
 X : 284.3 , Y : 433.1
 X : 293.5 , Y : 440.1
 X : 293.5 , Y : 440.1
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 748589.34 , Y : 285027.67
 X : 749284.17 , Y : 284962.91
 X : 749331.1 , Y : 284977.05
 X : 749486.96 , Y : 284996.53
 X : 749587.89 , Y : 285000.85
 X : 749679.82 , Y : 285008.14
 X : 749778.72 , Y : 285020.45
 X : 749880.64 , Y : 285029.76
 X : 749978.56 , Y : 285038.07
 X : 750084.48 , Y : 285043.4
 X : 750163.43 , Y : 285046.65
 X : 750286.36 , Y : 285048.04
 X : 750378.32 , Y : 285045.33
 X : 750480.27 , Y : 285042.66
 X : 750696.19 , Y : 285032.35
 X : 750798.18 , Y : 285015.68
 X : 750904.18 , Y : 284998.03
 X : 751014.02 , Y : 285031.36
 X : 751123.84 , Y : 285068.68
 X : 750199.2 , Y : 285113.72
 X : 750316.24 , Y : 285080.11
 X : 750398.9 , Y : 285175.32
 X : 797826.4 , Y : -3471389.75
 X : 747913.93 , Y : 284638.76
 X : 749133.79 , Y : 284792.54
 X : 749354.87 , Y : 284729.28
 X : 749613.85 , Y : 284692.12
 X : 750391.39 , Y : 285021.39
 X : 751843.9245 , Y : 283524.7216
 X : 749632 , Y : 284964
 X : 749990 , Y : 284630
 X : 748640 , Y : 283950
 X : 720720 , Y : 3967766
 X : 721941 , Y : 3967916
 X : 722162 , Y : 3967852
 X : 722421 , Y : 3967814
 X : 723200 , Y : 3968141
 X : 723783 , Y : 3968136
 X : 723844 , Y : 3968136
 X : 724130 , Y : 3968209
 X : 724413 , Y : 3968419
 X : 749114.75 , Y : 285152.97
 X : 749311.61 , Y : 285155.02
 X : 749499.97 , Y : 285197.96
 X : 749661.38 , Y : 285276.48
 X : 749830.41 , Y : 285337.95
 X : 749993.01 , Y : 285383.75
 X : 750168.14 , Y : 285438.25
 X : 750639.52 , Y : 285494.88
 X : 750522.35 , Y : 285515.01
 X : 750710.45 , Y : 285568.24
 X : 750892.07 , Y : 285620.33
 X : 751092.56 , Y : 285665.88
 X : 751314.02 , Y : 285709.24
 X : 751487.14 , Y : 285761.12
 X : 751678.74 , Y : 285801.99
 X : 751856.14 , Y : 285829.66
 X : 752041.8 , Y : 285882.41
 X : 752224.35 , Y : 284936.48
 X : 752417.42 , Y : 285981.76
 X : 752619.15 , Y : 286031.36
 X : 752982.02 , Y : 286071.87
 X : 753127.77 , Y : 286125.63
 X : 752964.13 , Y : 286117.2
 X : 753291.39 , Y : 286124.58
 X : 753435.64 , Y : 286104.59
 X : 753541.3 , Y : 286056.38
 X : 753675.68 , Y : 285979.45
 X : 751939.25 , Y : 285455.24
 X : 752107.34 , Y : 285566.76
 X : 752259.14 , Y : 285707.57
 X : 752808.81 , Y : 285653.52
 X : 753040.13 , Y : 285602.31
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 161.12 , Y : 199.12
 X : 161.12 , Y : 199.12
 X : 161.11 , Y : 199.12
 X : 161.11 , Y : 199.12
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 4° 10' 39.60 , Y : 35° 38' 57.92
 X : 4° 10' 39.60 , Y : 35° 38' 57.92
 X : 4° 10' 39.60 , Y : 35° 38' 57.92
 X : 4° 10' 39.60 , Y : 35° 38' 57.92
 X : 4° 10' 39.60 , Y : 35° 38' 57.92
 X : 4° 14' 47.60 , Y : 35° 37' 3.10
 X : 4° 14' 47.60 , Y : 35° 37' 3.10
 X : 4° 14' 47.60 , Y : 35° 37' 3.10
 X : 4° 14' 47.60 , Y : 35° 37' 3.10
 X : 4° 14' 47.60 , Y : 35° 37' 3.10
 X : 4° 14' 43.10 , Y : 35° 37' 8.90
 X : 4° 14' 43.10 , Y : 35° 37' 8.90
 X : 4° 14' 43.10 , Y : 35° 37' 8.90
 X : 4° 14' 43.10 , Y : 35° 37' 8.90
 X : 4° 14' 43.10 , Y : 35° 37' 8.90
 X : 4° 14' 43.10 , Y : 35° 37' 8.90
 X : 4° 14' 36.50 , Y : 35° 37' 19.60
 X : 4° 14' 36.50 , Y : 35° 37' 19.60
 X : 4° 14' 36.50 , Y : 35° 37' 19.60
 X : 4° 14' 36.50 , Y : 35° 37' 19.60
 X : 4° 14' 36.50 , Y : 35° 37' 19.60
 X : 4° 11' 9.20 , Y : 35° 38' 0.90
 X : 4° 11' 9.20 , Y : 35° 38' 0.90
 X : 4° 11' 9.20 , Y : 35° 38' 0.90
 X : 4° 11' 9.20 , Y : 35° 38' 0.90
 X : 4° 11' 9.20 , Y : 35° 38' 0.90
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 1º 28' 20''E , Y : 35º 22' 08''N
 X : 1º 28' 20''E , Y : 35º 22' 08''N
 X : 1º 28' 20''E , Y : 35º 22' 08''N
 X : 1º 28' 20''E , Y : 35º 22' 08''N
 X : 1º 15' 30''E , Y : 35º 20' 57''N
 X : 1º 15' 30''E , Y : 35º 20' 57''N
 X : 1º 15' 30''E , Y : 35º 20' 57''N
 X : 1º 15' 30''E , Y : 35º 20' 57''N
 X : 1º 15' 20''E , Y : 35º 20'52''N
 X : 1º 15' 20''E , Y : 35º 20'52''N
 X : 1º 15' 20''E , Y : 35º 20'52''N
 X : 1º 38' 32''E , Y : 35º 30' 32''N
 X : 1º 38' 32''E , Y : 35º 30' 32''N
 X : 1º 38' 32''E , Y : 35º 30' 32''N
 X : 1º 24' 49''E , Y : 35º 24' 49''N
 X : 1º 24' 49''E , Y : 35º 24' 49''N
 X : 1º 24' 49''E , Y : 35º 24' 49''N
 X : 1º 24' 49''E , Y : 35º 24' 49''N
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 283.5 , Y : 259
 X : 322 , Y : 285
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : N 06° 20’ 11\",E 34° 44’ 37\"" , Y : 6.33638889
 X : N 06° 20’ 11\",E 34° 44’ 37\"" , Y : 6.33638889
 X : N 06° 20’ 11\",E 34° 44’ 37\"" , Y : 6.33638889
 X : N 05° 19’ 05\",E 34° 35’ 40\"" , Y : 5.31805556
 X : N 05° 19’ 05\",E 34° 35’ 40\"" , Y : 5.31805556
 X : N 05° 19’ 05\",E 34° 35’ 40\"" , Y : 5.31805556
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : nan , Y : nan
 X : 5°34'24.8 , Y : 35°01'50.5
 X : 5°34'24.8 , Y : 35°01'50.5
 X : 5°34'24.8 , Y : 35°01'50.5
 X : 5°33'42.03 , Y : 35°00'15.45
 X : 5°33'42.03 , Y : 35°00'15.45
 X : 5°33'42.03 , Y : 35°00'15.45
 X : 5°35'44 , Y : 34°59'9.7
 X : 5°35'44 , Y : 34°59'9.7
 X : 5°35'44 , Y : 34°59'9.7
 X : 5°37'55 , Y : 34°57'20
 X : 5°37'55 , Y : 34°57'20
 X : 5°37'55 , Y : 34°57'20
 X : 5°35'44 , Y : 34°56'13
 X : 5°35'44 , Y : 34°56'13
 X : 5°35'44 , Y : 34°56'13
 X : 5°35'44 , Y : 34°56'13
 X : 5°36'56 , Y : 34°55'0
 X : 5°36'56 , Y : 34°55'0
 X : 5°36'56 , Y : 34°55'0
 X : 5°30'58 , Y : 34°55'15
 X : 5°30'58 , Y : 34°55'15
 X : 5°30'58 , Y : 34°55'15
 X : 5°31'7 , Y : 34°54'15
 X : 5°31'7 , Y : 34°54'15
 X : 5°31'7 , Y : 34°54'15
 X : 5°31'7 , Y : 34°54'15
 X : 741915 , Y : 3853095
 X : 741915 , Y : 3853095
 X : 743595 , Y : 3848655
 X : 743595 , Y : 3848655
 X : 744705 , Y : 3845715

In [4]:
import re

def converter(value , flag=False):
    if flag : 
        value = value.replace(",",".").replace("′","'").replace("″",'"').replace("’’",'"').replace("’","'").replace("N","").replace("/","").replace("\\","")
    value = value.replace(",",".")
    print(value)
    regex_dms = re.compile(r'^(\d{1,3})[º°\s]+(\d{1,2})[\'\s]+([\d.,]+)[\'\s]*(E|W|N|S)?$')
    match = regex_dms.match(value.strip())
    if match:
        new_value = dms_str_to_decimal(value, match.groups())
        print(new_value)
        return new_value
    regex_dms_no_spaces = re.compile(r'^(\d{1,3})º(\d{1,2})\'([\d.,]+)\'\'?(E|W|N|S)?$')
    match_no_spaces = regex_dms_no_spaces.match(value.strip())
    if match_no_spaces:
        new_value = dms_str_to_decimal(value, match_no_spaces.groups())
        print(new_value)
        return new_value

    return None

def dms_str_to_decimal(dms_str, match_groups):
    degrees, minutes, seconds = map(float, match_groups[:3])
    decimal_value = degrees + (minutes / 60) + (seconds / 3600)
    if match_groups[3]:
        direction = match_groups[3].upper()
        if direction in ['S', 'W']:
            decimal_value = -decimal_value
    return decimal_value

In [5]:
df_cleaned['X'] = df_cleaned['X'].astype(str)
df_cleaned["X"] = df_cleaned["X"].apply(converter)
df_cleaned["X"].value_counts().sum()

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
2.14
3.15987
3.15987
3.15987
3.15987
3.15987
3.15987
3.15987
3.15987
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
06 06 22
6.106111111111111
06 06 15
6.104166666666666
06 06 35
6.109722222222222
06 06 55
6.115277777777777
06 06 25
6.106944444444444
06 06 35
6.109722222222222
06 06 05
6.101388888888889
06 06 25
6.106944444444444
05 57 14.21
5.953947222222222
05 57 19.15
5.955319444444445
05 56 44.55
5.945708333333333
05 57 29.05
5.958069444444445
05 56 59.38
5.949827777777778
05 57 14.21
5.953947222222222
05 56 34.65
5.942958333333333
05 57 43.88
5.962188888888889
05 58 28.37
5.974547222222222
06 06 22
6.106111111111111
06 06 15
6.104166666666666
06 06 35
6.109722222222222
06 06 55
6.115277777777777
06 06 25
6.106944444444444
06 06 35
6.109722222222222
06 06 05
6.101388888888889
06 06 25
6.106944444444444
05 57 14.21
5.953947222222222
05 57 19.15
5.955319444444445
05 56 44.55
5.945708333333333
05 57 29.05
5.958069444444445
05 56 59.38
5.949827777777778
05 57 14.21
5.953947222222222
05 56 34.65
5.942958333333333
05 57 43.88
5.962188888888889
05 58 28.37
5.974547222222222
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
982
982
982
982
982
986
986
986
986
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
1002
1002
1002
1003
1003
1003
1003
1003
1003
1003
982
982
982
982
982
982
982
982
982
982
1002
1002
1002
1002
1002
1002
1002
7.904167
7.904167
7.904167
7.904167
7.904167
7.904167
7.904167
7.904167
7.904167
7.904167
7.904167
7.904167
8.25
8.25
8.25
8.25
8.168056
8.168056
8.168056
8.168056
8.168056
8.2
8.2
8.2
8.316667
8.316667
8.316667
8.316667
8.316667
8.35
8.35
8.35
8.35
8.35
8.316667
8.316667
8.316667
8.316667
8.316667
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
673883
1
1
2
2
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
1
1
2
123
123
1
1
2
1
1
2
2
510.8
510.8
506.7
506.7
514.4
514.4
514.4
514.4
509.9
509.9
509.9
510.8
510.8
514.5
514.5
511.7
511.7
514.6
514.6
514.6
519.7
519.7
519.7
513.5
513.5
520.5
520.5
520.5
510.4
510.4
510.4
510.4
510.4
519.1
519.1
518.1
518.1
518.1
518.1
514.5
514.5
514.5
515.7
515.7
515.7
515.7
521.4
521.4
521.4
520.6
520.6
520.6
520.6
506.4
506.4
284.3
284.3
293.5
293.5
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
748589.34
749284.17
749331.1
749486.96
749587.89
749679.82
749778.72
749880.64
749978.56
750084.48
750163.43
750286.36
750378.32
750480.27
750696.19
750798.18
750904.18
751014.02
751123.84
750199.2
750316.24
750398.9
797826.4
747913.93
749133.79
749354.87
749613.85
750391.39
751843.9245
749632
749990
748640
720720
721941
722162
722421
723200
723783
723844
724130
724413
749114.75
749311.61
749499.97
749661.38
749830.41
749993.01
750168.14
750639.52
750522.35
750710.45
750892.07
751092.56
751314.02
751487.14
751678.74
751856.14
752041.8
752224.35
752417.42
752619.15
752982.02
753127.77
752964.13
753291.39
753435.64
753541.3
753675.68
751939.25
752107.34
752259.14
752808.81
753040.13
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
161.12
161.12
161.11
161.11
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
4° 10' 39.60
4.177666666666667
4° 10' 39.60
4.177666666666667
4° 10' 39.60
4.177666666666667
4° 10' 39.60
4.177666666666667
4° 10' 39.60
4.177666666666667
4° 14' 47.60
4.246555555555555
4° 14' 47.60
4.246555555555555
4° 14' 47.60
4.246555555555555
4° 14' 47.60
4.246555555555555
4° 14' 47.60
4.246555555555555
4° 14' 43.10
4.245305555555555
4° 14' 43.10
4.245305555555555
4° 14' 43.10
4.245305555555555
4° 14' 43.10
4.245305555555555
4° 14' 43.10
4.245305555555555
4° 14' 43.10
4.245305555555555
4° 14' 36.50
4.2434722222222225
4° 14' 36.50
4.2434722222222225
4° 14' 36.50
4.2434722222222225
4° 14' 36.50
4.2434722222222225
4° 14' 36.50
4.2434722222222225
4° 11' 9.20
4.185888888888889
4° 11' 9.20
4.185888888888889
4° 11' 9.20
4.185888888888889
4° 11' 9.20
4.185888888888889
4° 11' 9.20
4.185888888888889
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
1º 28' 20''E
1.4722222222222223
1º 28' 20''E
1.4722222222222223
1º 28' 20''E
1.4722222222222223
1º 28' 20''E
1.4722222222222223
1º 15' 30''E
1.2583333333333333
1º 15' 30''E
1.2583333333333333
1º 15' 30''E
1.2583333333333333
1º 15' 30''E
1.2583333333333333
1º 15' 20''E
1.2555555555555555
1º 15' 20''E
1.2555555555555555
1º 15' 20''E
1.2555555555555555
1º 38' 32''E
1.6422222222222222
1º 38' 32''E
1.6422222222222222
1º 38' 32''E
1.6422222222222222
1º 24' 49''E
1.413611111111111
1º 24' 49''E
1.413611111111111
1º 24' 49''E
1.413611111111111
1º 24' 49''E
1.413611111111111
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
283.5
322
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
N 06° 20’ 11\".E 34° 44’ 37\""
N 06° 20’ 11\".E 34° 44’ 37\""
N 06° 20’ 11\".E 34° 44’ 37\""
N 05° 19’ 05\".E 34° 35’ 40\""
N 05° 19’ 05\".E 34° 35’ 40\""
N 05° 19’ 05\".E 34° 35’ 40\""
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
5°34'24.8
5.573555555555555
5°34'24.8
5.573555555555555
5°34'24.8
5.573555555555555
5°33'42.03
5.561675
5°33'42.03
5.561675
5°33'42.03
5.561675
5°35'44
5.595555555555555
5°35'44
5.595555555555555
5°35'44
5.595555555555555
5°37'55
5.631944444444445
5°37'55
5.631944444444445
5°37'55
5.631944444444445
5°35'44
5.595555555555555
5°35'44
5.595555555555555
5°35'44
5.595555555555555
5°35'44
5.595555555555555
5°36'56
5.615555555555555
5°36'56
5.615555555555555
5°36'56
5.615555555555555
5°30'58
5.516111111111111
5°30'58
5.516111111111111
5°30'58
5.516111111111111
5°31'7
5.518611111111111
5°31'7
5.518611111111111
5°31'7
5.518611111111111
5°31'7
5.518611111111111
741915
741915
743595
743595
744705
744705
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
741915
741915
743595
744705
744705
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
716.740
716.740
716.740
716.740
716.690
716.690
716.690
716.690
716.908
716.908
716.908
716.908
716.828
716.828
716.828
716.863
716.863
716.863
716.863
716.758
716.758
716.758
716.695
716.695
716.695
716.695
716.790
716.790
716.790
716.790
716.685
716.685
716.685
716.685
1
1
2
2
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
790
790
795
795
800
800
805
805
805
790
790
790
790
790
790
790
790
790
785
785
785
780
780
775
775
770
770
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
02 58 05.0
2.968055555555556
02 58 05.0
2.968055555555556
02 58 10.0
2.9694444444444446
02 58 10.0
2.9694444444444446
02 58 30.2
2.9750555555555556
02 58 30.2
2.9750555555555556
02 58 49.4
2.980388888888889
02 58 49.4
2.980388888888889
02 58 30.3
2.9750833333333335
02 58 30.3
2.9750833333333335
02 58 44.8
2.979111111111111
02 58 38
2.977222222222222
02 58 31.3
2.9753611111111113
02 58 6.8
2.9685555555555556
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
02° 27 736
2.6544444444444446
02° 27 736
2.6544444444444446
02° 27 736
2.6544444444444446
02° 27 736
2.6544444444444446
02° 27 736
2.6544444444444446
02° 27 491
2.586388888888889
02° 27 491
2.586388888888889
02° 27 491
2.586388888888889
02° 24 232
2.464444444444444
02° 24 232
2.464444444444444
02° 24 232
2.464444444444444
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\2396268829.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['X'] = df_cleaned['X'].astype(str)
C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\2396268829.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["X"] = df_cleaned["X"].apply(converter)

129

In [6]:
df_cleaned['Y'] = df_cleaned['Y'].astype(str)
df_cleaned["X"] = df_cleaned["Y"].apply(converter)
df_cleaned["X"].value_counts().sum()

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
30.43
36.71253
36.71253
36.71253
36.71253
36.71253
36.71253
36.71253
36.71253
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
35 34 58
35.58277777777778
35 34 58
35.58277777777778
35 34 48
35.580000000000005
35 34 38
35.577222222222225
35 34 28
35.574444444444445
35 34 41
35.57805555555556
35 34 46
35.57944444444445
35 34 36
35.57666666666667
35 33 42.15
35.56170833333333
35 34 10.03
35.569452777777784
35 34 14.34
35.57065
35 34 14.34
35.57065
35 34 26.39
35.573997222222225
35 34 46.48
35.57957777777778
35 35 02.57
35.584047222222225
35 35 34.72
35.59297777777778
35 35 14.64
35.5874
35 34 58
35.58277777777778
35 34 58
35.58277777777778
35 34 48
35.580000000000005
35 34 38
35.577222222222225
35 34 28
35.574444444444445
35 34 41
35.57805555555556
35 34 46
35.57944444444445
35 34 36
35.57666666666667
35 33 42.15
35.56170833333333
35 34 10.03
35.569452777777784
35 34 14.34
35.57065
35 34 14.34
35.57065
35 34 26.39
35.573997222222225
35 34 46.48
35.57957777777778
35 35 02.57
35.584047222222225
35 35 34.72
35.59297777777778
35 35 14.64
35.5874
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
408
408
408
408
408
412
412
412
412
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
416
416
416
415
415
415
415
415
415
415
408
408
408
408
408
408
408
408
408
408
414
414
414
414
414
414
414
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.78333
36.85
36.85
36.85
36.85
36.85
36.83333
36.83333
36.83333
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
3917621
1
1
2
2
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
1
1
2
456
456
1
1
2
1
1
2
2
328.6
328.6
321.4
321.4
328.5
328.3
328.3
328.3
318.5
318.5
318.5
327.8
327.8
328.4
328.4
326.4
326.4
328.4
328.4
328.4
332.6
332.6
332.6
327.5
327.5
330.3
330.3
330.3
329.5
329.5
329.5
329.5
329.5
321.1
321.1
323.6
323.6
323.6
323.6
322.6
322.6
322.6
320.7
320.7
320.7
320.7
329.6
329.6
329.6
328.3
328.3
328.3
328.3
316
316
433.1
433.1
440.1
440.1
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
285027.67
284962.91
284977.05
284996.53
285000.85
285008.14
285020.45
285029.76
285038.07
285043.4
285046.65
285048.04
285045.33
285042.66
285032.35
285015.68
284998.03
285031.36
285068.68
285113.72
285080.11
285175.32
-3471389.75
284638.76
284792.54
284729.28
284692.12
285021.39
283524.7216
284964
284630
283950
3967766
3967916
3967852
3967814
3968141
3968136
3968136
3968209
3968419
285152.97
285155.02
285197.96
285276.48
285337.95
285383.75
285438.25
285494.88
285515.01
285568.24
285620.33
285665.88
285709.24
285761.12
285801.99
285829.66
285882.41
284936.48
285981.76
286031.36
286071.87
286125.63
286117.2
286124.58
286104.59
286056.38
285979.45
285455.24
285566.76
285707.57
285653.52
285602.31
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
199.12
199.12
199.12
199.12
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
35° 38' 57.92
35.64942222222222
35° 38' 57.92
35.64942222222222
35° 38' 57.92
35.64942222222222
35° 38' 57.92
35.64942222222222
35° 38' 57.92
35.64942222222222
35° 37' 3.10
35.61752777777778
35° 37' 3.10
35.61752777777778
35° 37' 3.10
35.61752777777778
35° 37' 3.10
35.61752777777778
35° 37' 3.10
35.61752777777778
35° 37' 8.90
35.61913888888889
35° 37' 8.90
35.61913888888889
35° 37' 8.90
35.61913888888889
35° 37' 8.90
35.61913888888889
35° 37' 8.90
35.61913888888889
35° 37' 8.90
35.61913888888889
35° 37' 19.60
35.62211111111111
35° 37' 19.60
35.62211111111111
35° 37' 19.60
35.62211111111111
35° 37' 19.60
35.62211111111111
35° 37' 19.60
35.62211111111111
35° 38' 0.90
35.633583333333334
35° 38' 0.90
35.633583333333334
35° 38' 0.90
35.633583333333334
35° 38' 0.90
35.633583333333334
35° 38' 0.90
35.633583333333334
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
35º 22' 08''N
35.36888888888889
35º 22' 08''N
35.36888888888889
35º 22' 08''N
35.36888888888889
35º 22' 08''N
35.36888888888889
35º 20' 57''N
35.34916666666667
35º 20' 57''N
35.34916666666667
35º 20' 57''N
35.34916666666667
35º 20' 57''N
35.34916666666667
35º 20'52''N
35.34777777777778
35º 20'52''N
35.34777777777778
35º 20'52''N
35.34777777777778
35º 30' 32''N
35.50888888888889
35º 30' 32''N
35.50888888888889
35º 30' 32''N
35.50888888888889
35º 24' 49''N
35.41361111111111
35º 24' 49''N
35.41361111111111
35º 24' 49''N
35.41361111111111
35º 24' 49''N
35.41361111111111
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
259
285
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
6.33638889
6.33638889
6.33638889
5.31805556
5.31805556
5.31805556
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
35°01'50.5
35.03069444444444
35°01'50.5
35.03069444444444
35°01'50.5
35.03069444444444
35°00'15.45
35.00429166666667
35°00'15.45
35.00429166666667
35°00'15.45
35.00429166666667
34°59'9.7
34.98602777777778
34°59'9.7
34.98602777777778
34°59'9.7
34.98602777777778
34°57'20
34.955555555555556
34°57'20
34.955555555555556
34°57'20
34.955555555555556
34°56'13
34.93694444444444
34°56'13
34.93694444444444
34°56'13
34.93694444444444
34°56'13
34.93694444444444
34°55'0
34.916666666666664
34°55'0
34.916666666666664
34°55'0
34.916666666666664
34°55'15
34.920833333333334
34°55'15
34.920833333333334
34°55'15
34.920833333333334
34°54'15
34.90416666666667
34°54'15
34.90416666666667
34°54'15
34.90416666666667
34°54'15
34.90416666666667
3853095
3853095
3848655
3848655
3845715
3845715
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
3853095
3853095
3848655
3845715
3845715
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
3536.291
3536.291
3536.291
3536.291
3536.216
3536.216
3536.216
3536.216
3536.166
3536.166
3536.166
3536.166
3536.225
3536.225
3536.225
3536.089
3536.089
3536.089
3536.089
3536.154
3536.154
3536.154
3536.105
3536.105
3536.105
3536.105
3536.029
3536.029
3536.029
3536.029
3535.860
3535.860
3535.860
3535.860
1
1
2
2
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
410
410
405
405
395
395
410
410
410
405
405
405
400
400
400
415
415
415
400
395
395
400
400
395
395
390
390
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
30 26 06.4
30.435111111111112
30 26 06.4
30.435111111111112
30 26 58.0
30.449444444444445
30 26 58.0
30.449444444444445
30 27 05.0
30.45138888888889
30 27 05.0
30.45138888888889
30 27 04.6
30.451277777777776
30 27 04.6
30.451277777777776
30 27 21.0
30.45583333333333
30 27 21.0
30.45583333333333
30 26 07.3
30.43536111111111
30 26 41
30.44472222222222
30 27 22.0
30.45611111111111
30 26 40.6
30.44461111111111
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
27° 11 43
27.19527777777778
27° 11 43
27.19527777777778
27° 11 43
27.19527777777778
27° 11 43
27.19527777777778
27° 11 43
27.19527777777778
27° 11 6
27.185
27° 11 6
27.185
27° 11 6
27.185
27° 11 036
27.193333333333335
27° 11 036
27.193333333333335
27° 11 036
27.193333333333335
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\1956847533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Y'] = df_cleaned['Y'].astype(str)
C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\1956847533.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["X"] = df_cleaned["Y"].apply(converter)

129

In [7]:
def dms_to_dd(degrees, minutes=0, seconds=0):
    return float(degrees) + float(minutes)/60 + float(seconds)/3600

def convert_line_to_decimal(line):
    line = line.strip().replace('˚', '°').replace("''", '"').replace("’", "'").replace("“", '"').replace("”", '"')
    dms_pattern = re.compile(r"(\d+)[°:\s]+(\d+)?[':\s]*(\d+(?:\.\d+)?)?[\"\s]*")
    
    matches = dms_pattern.findall(line)
    if matches:
        degrees, minutes, seconds = 0, 0, 0
        for match in matches:
            if match[0]: degrees = float(match[0])
            if match[1]: minutes = float(match[1])
            if match[2]: seconds = float(match[2])
        return round(dms_to_dd(degrees, minutes, seconds), 8)

    try:
        return round(float(line), 8)
    except:
        return line

In [8]:
df_cleaned['Latitude'] = df_cleaned['Latitude'].astype(str)
df_cleaned['Latitude'] = df_cleaned['Latitude'].apply(convert_line_to_decimal)
for i in df_cleaned["Latitude"]:
    print(i)

36.7232
36.7232
36.81484056
36.87836
35.56102417
32.49022472
32.49022472
36.74718694
36.70705806
52.39416667
36.15978667
30.43N
36.7
36.7
36.7
36.7
36.7
36.7
36.7
36.7
34.716667
34.716667
34.716667
34.716667
34.716667
34.716667
34.633333
34.633333
34.633333
34.633333
34.633333
34.633333
34.716667
34.716667
34.716667
34.716667
34.716667
34.716667
34.8
34.8
34.8
34.8
34.8
34.8
34.7
34.7
34.7
34.683333
34.683333
34.683333
34.9
34.9
34.9
34.916667
34.916667
34.916667
35.582778
35.582778
35.58
35.577222
35.574444
35.578056
35.579444
35.576667
35.561708
35.569453
35.57065
35.57065
35.573997
35.579578
35.584047
35.593
35.5874
35.582778
35.582778
35.58
35.577222
35.574444
35.578056
35.579444
35.576667
35.561708
35.569453
35.57065
35.57065
35.573997
35.579578
35.584047
35.593
35.5874
35.616667
35.6261111
35.6
35.6
35.59
35.59
35.601
35.601
35.603
35.603
35.606
35.606
35.608
35.608
35.61
35.61
35.613
35.613
35.61
35.61
35.576613
35.576613
35.59
35.59
35.59
35.63
35.63
35.63
35.63
35.63
35.6308
35.6308
35.6308
35.6308
35.6166
35.6166
35.6166
35.533
35.533
36.5
36.5
36.5
36.223333
36.223333
36.223333
36.223333
36.223333
35.20027778
35.20027778
35.20027778
35.20027778
35.20027778
35.20027778
35.20027778
35.25916667
35.25916667
35.25916667
35.25916667
35.25916667
35.25916667
35.25916667
12.0
12.0
12.0
12.0
12.0
12.0
12.0
12.0
12.0
12.0
12.0
12.0
12.0
12.0
32.86666667
36.84722
36.84722
36.84722
36.84722
36.84722
36.84722
36.84722
36.84722
36.84722
36.93333
36.93333
36.93333
36.93333
36.93333
36.95
36.95
36.95
36.95
36.9
36.9
36.9
36.9
36.9
36.9
36.9
36.9
36.9
36.9
36.91667
36.91667
36.91667
36.9
36.9
36.9
36.9
36.9
36.9
36.9
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.85
36.88333
36.88333
36.88333
36.88333
36.88333
36.88333
36.88333
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
0.0
15.0
40.0
60.0
0.0
50.0
110.0
320.0
400.0
0.0
40.0
80.0
0.0
30.0
90.0
110.0
170.0
0.0
30.0
60.0
70.0
130.0
0.0
20.0
120.0
180.0
0.0
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
35.35
nan
36.8
36.8
36.9
36.9
5.9
5.9
6.0
36.7833
36.7833
36.82
36.82
36.82
36.82
36.82
36.82
36.8
36.8
36.9
36.6667
36.6667
36.8
36.8
36.9
36.789
36.789
36.8
36.8
36.9
36.7
36.7
36.8
36.8
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
36.066667
36.066667
36.066667
36.133333
36.125
36.13333333
36.13333333
36.13333333
36.13333333
36.13333333
36.13333333
36.13333333
36.13333333
36.09
36.09
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
36.13333333
36.13333333
34.84833333
34.84833333
34.84833333
34.84833333
34.84944167
34.84944167
34.84944167
34.85109167
34.85109167
34.85109167
34.85109167
34.85264167
34.85264167
34.85264167
34.85264167
34.85429167
34.85429167
34.85429167
34.85530278
34.85530278
34.85530278
34.85530278
34.85782222
34.85782222
34.85782222
34.85782222
7.0
7.0
7.0
7.0
7.0
7.0
7.0
34.72694444
34.72694444
34.72694444
34.71833333
34.71833333
34.71833333
34.63777778
34.63777778
34.63777778
34.63777778
34.63777778
34.63777778
34.71666667
34.71666667
34.71666667
34.71666667
34.71666667
34.71666667
34.80944444
34.80944444
34.80944444
34.80611111
34.80611111
34.80611111
8.70138889
8.70138889
8.70138889
34.69527778
34.69527778
34.69527778
34.90694444
34.90694444
34.90694444
34.92083333
34.92083333
34.92083333
El Enasser
El Enasser
0.73805556
0.73805556
0.73805556
0.73805556
0.73805556
0.79564722
0.79564722
0.79564722
0.79564722
0.79564722
6" E
6" E
6" E
6" E
6" E
1.54694444
1.54694444
1.54694444
1.54694444
0.73805556
0.73805556
0.73805556
0.73805556
0.73805556
0.79564722
0.79564722
0.79564722
0.79564722
0.79564722
6" E
6" E
6" E
6" E
6" E
1.54694444
1.54694444
1.54694444
1.54694444
0.73805556
0.73805556
0.73805556
0.73805556
0.73805556
0.73805556
0.79564722
0.79564722
0.79564722
0.79564722
0.79564722
6" E
6" E
6" E
6" E
6" E
1.54694444
1.54694444
1.54694444
1.54694444
0.73805556
0.73805556
0.73805556
0.73805556
0.73805556
0.73805556
0.79564722
0.79564722
0.79564722
0.79564722
0.79564722
6" E
6" E
6" E
6" E
6" E
1.54694444
1.54694444
1.54694444
1.54694444
36.4912
36.4912
36.4912
36.4912
36.4903
36.4903
36.4903
36.4903
36.4886
36.4886
36.4886
36.4886
36.4869
36.4869
36.4869
36.4869
36.4858
36.4858
36.4858
36.4858
36.4847
36.4847
36.4847
36.4847
36.4836
36.4836
36.4836
36.4836
36.4912
36.4912
36.4912
36.4912
36.4903
36.4903
36.4903
36.4903
36.4886
36.4886
36.4886
36.4886
36.4869
36.4869
36.4869
36.4869
36.4858
36.4858
36.4858
36.4858
36.4847
36.4847
36.4847
36.4847
36.4836
36.4836
36.4836
36.4836
36.4903
36.4903
36.4903
36.4903
35.64942222
35.64942222
35.64942222
35.64942222
35.64942222
35.61752778
35.61752778
35.61752778
35.61752778
35.61752778
35.61913889
35.61913889
35.61913889
35.61913889
35.61913889
35.61913889
35.62211111
35.62211111
35.62211111
35.62211111
35.62211111
35.63358333
35.63358333
35.63358333
35.63358333
35.63358333
35.73805556
35.73805556
35.73805556
35.73805556
35.73805556
35.79564722
35.79564722
35.79564722
35.79564722
35.79564722
35.79564722
35.79564722
35.79564722
35.96319444
35.96319444
35.96319444
35.96319444
35.96319444
35.36888889
35.36888889
35.36888889
35.36888889
35.34916667
35.34916667
35.34916667
35.34916667
35.34777778
35.34777778
35.34777778
35.50888889
35.50888889
35.50888889
35.41361111
35.41361111
35.41361111
35.41361111
35.65
35.48
35.48
36.7
36.7
36.7
36.7
36.7
36.71
36.72
36.72
36.72
36.73
36.73
36.73
36.73
36.74
36.74
36.74
36.74
36.74
36.75
36.75
36.75
36.75
36.76
36.76
36.76
36.76
36.77
36.77
35.48
35.48
35.48
35.48
35.33
35.33
35.33
35.33
35.33
35.33
35.32
35.32
35.32
2"
6"
35.9
35.9
35.9
35.9
35.9
35.9
35.9
35.9
35.9
35.9
35.9
35.9
36.2
28.613056
28.613056
28.60725
28.60725
28.60725
28.60725
28.60725
28.60725
28.659472
28.659472
28.659472
28.659472
28.659472
28.659472
28.642361
28.642361
28.642361
28.642361
28.642361
28.642361
27.839722
27.839722
27.839722
27.839722
26.7166667
26.7166667
28.4230556
28.4230556
28.4230556
0.3183333
0.3183333
0.3183333
27.96361111
1.47472222
34.75
34.71
34.1
nan
nan
nan
nan
nan
nan
35.287222
35.287222
35.287222
35.289075
35.289075
35.289075
35.325833
35.325833
35.325833
35.325833
35.325833
35.325278
35.325278
35.325278
35.325278
35.325278
35.338611
35.338611
35.338611
35.337222
35.337222
35.337222
35.337222
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
34.72
34.72
34.72
34.72
34.72
34.72
34.63
34.63
34.63
34.63
34.63
34.63
34.72
34.72
34.72
34.72
34.72
34.72
34.81
34.81
34.81
34.81
34.81
34.81
34.7
34.7
34.7
34.69
34.69
34.69
34.91
34.91
34.91
34.91
34.91
34.91
nan
34.67712389
34.67712389
34.67712389
nan
nan
nan
nan
nan
35.73802
35.73802
35.73802
35.73802
35.73802
35.734
35.734
35.734
35.734
35.734
35.734
35.734
32.56666667
32.56666667
32.56666667
32.56666667
32.56666667
6.85
6.85
6.85
6.9
6.9
6.9
6.95
6.95
6.95
32.38333333
32.38333333
32.38333333
34.254
34.254
34.254
31.95
31.95
31.95
33.33333333
33.33333333
33.33333333
33.33333333
33.33333333
33.33333333
34.30841667
34.30841667
34.30841667
34.30761111
34.30761111
32.37527778
32.37527778
32.26444444
32.26444444
32.26444444
32.26444444
32.26444444
32.26583333
32.26583333
32.26583333
32.26583333
32.24222222
32.24222222
32.24222222
32.24222222
32.245
32.245
32.245
32.04444444
32.04444444
32.04444444
32.04444444
32.04444444
32.04444444
32.04611111
32.04611111
32.04611111
32.04611111
31.92916667
31.92916667
31.92916667
31.93388889
31.93388889
32.72305
32.72305
32.72305
32.725833
32.725833
32.725833
32.725833
32.725833
32.7122
32.7122
32.7122
32.7122
32.72055
32.72055
32.72055
32.72055
32.72
32.72
32.72
32.72
32.72
32.72
32.72
32.72
32.71
32.71
32.71
32.71
32.72
32.72
32.72
32.72
32.7836
32.7836
32.7908
32.7908
32.7897
32.7897
32.7826
32.7826
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.77
32.773
32.773
32.773
32.773
32.773
32.773
32.773
32.773
32.773
32.773
32.7738
32.7738
32.7738
32.7738
32.7738
32.7738
32.7738
32.7738
32.7738
32.7738
32.774378
32.774378
32.774378
32.774378
32.774378
32.774378
32.77919
32.77919
32.77919
32.77919
32.77919
32.77919
32.6717
32.6717
32.6717
32.6717
32.6717
32.6717
32.45992
32.45992
32.45992
32.45992
32.45992
32.45992
32.478
32.478
32.478
32.478
32.478
32.478
32.478
32.478
32.478
32.454
32.454
32.454
32.454
32.454
32.454
32.46986
32.46986
32.46986
32.46986
32.46986
32.46986
32.4993
32.4993
32.4993
32.4993
32.4993
32.4993
32.45364
32.45364
32.45364
32.45364
33.95
33.95
33.95
33.95
33.95
33.95
-33.72
-33.72
-33.72
-33.72
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
31.57
32.0
32.0
32.0
32.0
32.0
32.0
31.96
31.96
31.96
31.96
32.01
32.01
32.01
32.13
32.13
32.13
32.13
32.13
32.13
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
32.05
32.05
32.06
32.06
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.96666667
31.57
31.57
31.983333
31.983333
31.983333
31.983333
31.983333
31.983333
31.983333
31.983333
31.983333
31.983333
31.983333
31.983333
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.883333
31.883333
31.883333
31.883333
31.883333
31.883333
31.883333
31.883333
31.883333
31.883333
31.883333
31.883333
32.0
32.0
32.0
32.0
32.0
32.0
32.0
32.0
32.0
32.0
32.0
32.0
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.93
31.93
31.93
31.93
31.93
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
31.95
32.49421
32.49421
32.49421
32.49418
32.49418
32.49418
32.4936
32.4936
32.4936
32.4936
32.4936
32.49329
32.49329
32.49329
32.49329
32.49329
32.49314
32.49314
32.49314
32.49314
32.49314
32.49315
32.49315
32.49315
32.49315
32.49315
32.49315
32.49315
32.45241
32.45241
32.45241
32.45241
32.45241
32.45241
32.45241
32.45241
32.40139
32.40139
32.40127
32.40127
32.40127
32.40127
32.40127
32.39067
32.39067
32.39067
32.39067
32.39067
32.38601
32.38601
32.38601
32.38601
31.95
31.95
32.001944
32.001944
32.001944
32.000278
32.000278
32.000278
32.007778
32.007778
32.007778
32.1
32.1
32.1
31.57
31.57
31.57
31.57
38.0
38.0
37.8
37.8
37.6
37.6
38.0
38.0
38.0
37.8
37.8
37.8
37.7
37.7
37.7
38.1
38.1
38.1
37.7
37.6
37.6
37.7
37.7
37.6
37.6
37.5
37.5
0.0
0.0
0.0
0.0
0.0
0.0
0.28333333
0.28333333
0.28333333
0.28333333
0.28333333
33.62
33.62
33.62
33.62
33.62
33.62
33.62
33.62
33.62
33.62
33.62
33.1008
33.1008
33.0823
33.0823
33.0823
33.0823
32.9942
32.9942
32.9942
32.9942
33.1114
33.1114
33.1114
32.898
32.898
32.898
32.8963
32.8963
33.5
33.5
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33.0
33º 55'30,4'' N
33º 34'52,1'' N
33º 31'52,6'' N
33º41'68,6''N
33.41
33.41
33.41
33.42
33.42
33.42
33.45
33.45
33.45
33.27
33.27
33.27
33.13
33.13
33.13
33.19
33.19
33.19
33.1
33.1
33.1
33.0
33.0
33.0
32.93
32.93
32.93
33.18
33.18
33.18
34.7833
34.8
32.4
32.4
32.4
32.72361111
32.72361111
32.72361111
32.72583333
32.72583333
32.72583333
32.72583333
32.72583333
32.71222222
32.71222222
32.71222222
32.71222222
32.33888889
32.33888889
32.33888889
32.33888889
30.95
32.43793
32.43793
32.43793
32.43793
32.43806
32.43806
32.43806
32.43778
32.43778
32.43778
32.43778
32.4375
32.4375
32.43694
32.43694
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
32.45
32.45
32.45
32.51
32.51
32.51
32.48
32.48
32.48
32.5
32.5
32.5
32.3
32.3
32.3
32.19919
32.19919
32.19919
32.19849
32.19849
32.19849
32.13174
32.13174
32.13174
27.19
27.19
27.19
27.19
27.19
27.18
27.18
27.18
27.18
27.18
27.18
27.352776
27.352776
27.352776
27.352776
21.1321
21.1321
27.95762
27.95762
27.95762
27.95762
27.95762
27.1988
27.1988
27.1988
27.19314
27.19314
27.19314
27.19314
27.19314

C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\2585741323.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Latitude'] = df_cleaned['Latitude'].astype(str)
C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\2585741323.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Latitude'] = df_cleaned['Latitude'].apply(convert_line_to_decimal)

In [9]:
df_cleaned['Longitude'] = df_cleaned['Longitude'].astype(str)
df_cleaned['Longitude'] = df_cleaned['Longitude'].apply(convert_line_to_decimal)
for i in df_cleaned["Longitude"]:
    print(i)

3.0583
3.0583
3.0160075
3.93684389
6.17391139
3.67384111
3.67384111
3.19043194
3.18620333
2.92758333
5.41751889
2.14E
3.15
3.15
3.15
3.15
3.15
3.15
3.15
3.15
6.283333
6.283333
6.283333
6.3
6.3
6.3
5.133333
5.133333
5.133333
5.133333
5.133333
5.133333
5.366667
5.366667
5.366667
5.366667
5.366667
5.366667
5.683333
5.683333
5.683333
5.716667
5.716667
5.716667
6.433333
6.433333
6.433333
6.45
6.45
6.45
5.633333
5.633333
5.633333
5.633333
5.633333
5.633333
6.106111
6.104167
6.109722
6.115278
6.106944
6.109722
6.101389
6.106944
5.953947
5.955319
5.945708
5.958069
5.949828
5.953947
5.942958
5.962189
5.974547
6.106111
6.104167
6.109722
6.115278
6.106944
6.109722
6.101389
6.106944
5.953947
5.955319
5.945708
5.958069
5.949828
5.953947
5.942958
5.962189
5.974547
6.233333
6.2388889
6.25
6.25
6.212
6.212
6.223
6.223
6.229
6.229
6.235
6.235
6.24
6.24
6.247
6.247
6.27
6.27
6.267
6.267
6.188585
6.188585
6.11
6.11
6.11
6.04
6.04
6.04
6.04
6.04
6.1885
6.1885
6.1885
6.1885
6.1722
6.1722
6.1722
5.883
5.883
1.33333333
1.33333333
1.33333333
1.454444
1.454444
1.454444
1.454444
1.454444
3.0275
3.0275
3.0275
3.0275
3.0275
3.0275
3.0275
3.08166667
3.08166667
3.08166667
3.08166667
3.08166667
3.08166667
3.08166667
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.53333333
7.958333
7.958333
7.958333
7.958333
7.958333
7.958333
7.958333
7.958333
7.958333
8.116667
8.116667
8.116667
8.116667
8.116667
8.15
8.15
8.15
8.15
8.133333
8.133333
8.133333
8.133333
8.133333
8.133333
8.133333
8.133333
8.133333
8.133333
8.333333
8.333333
8.333333
8.35
8.35
8.35
8.35
8.35
8.35
8.35
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.316667
8.316667
8.316667
8.316667
8.316667
8.316667
8.316667
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
22.0
22.0
22.0
22.0
16.0
16.0
16.0
16.0
16.0
63.0
63.0
63.0
63.0
63.0
63.0
63.0
63.0
34.0
34.0
34.0
34.0
34.0
34.0
34.0
34.0
34.0
34.0
4.57
4.57
4.57
4.57
4.57
4.57
4.57
4.57
4.56
4.56
4.56
4.56
4.56
4.54
4.54
4.54
4.54
nan
4.5
4.5
4.6
4.6
nan
nan
nan
5.65
5.65
5.49
5.49
5.49
5.49
5.49
5.49
5.7
5.7
5.8
5.7833
5.7833
4.5
4.5
4.6
3.123
3.123
3.5
3.5
3.6
3.5
3.5
3.6
3.6
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
5.333333
5.316667
5.3
5.333333
5.333333
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.21
5.21
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
5.33333333
5.33333333
1.35081944
1.35081944
1.35081944
1.35081944
1.35029167
1.35029167
1.35029167
1.35023889
1.35023889
1.35023889
1.35023889
1.35164444
1.35164444
1.35164444
1.35164444
1.35086111
1.35086111
1.35086111
1.35065833
1.35065833
1.35065833
1.35065833
1.35226667
1.35226667
1.35226667
1.35226667
126.0
126.0
126.0
126.0
126.0
126.0
126.0
6.27388889
6.27388889
6.27388889
6.30611111
6.30611111
6.30611111
5.13777778
5.13777778
5.13777778
5.13777778
5.13777778
5.13777778
5.36972222
5.36972222
5.36972222
5.36972222
5.36972222
5.36972222
5.685
5.685
5.685
5.72111111
5.72111111
5.72111111
6.425
6.425
6.425
6.45388889
6.45388889
6.45388889
5.63277778
5.63277778
5.63277778
5.61666667
5.61666667
5.61666667
nan
nan
0.492
0.492
0.492
0.492
0.492
0.55611111
0.55611111
0.55611111
0.55611111
0.55611111
0.74972222
0.74972222
0.74972222
0.74972222
0.74972222
1.24722222
1.24722222
1.24722222
1.24722222
0.492
0.492
0.492
0.492
0.492
0.55611111
0.55611111
0.55611111
0.55611111
0.55611111
0.74972222
0.74972222
0.74972222
0.74972222
0.74972222
1.24722222
1.24722222
1.24722222
1.24722222
0.492
0.492
0.492
0.492
0.492
0.492
0.55611111
0.55611111
0.55611111
0.55611111
0.55611111
0.74972222
0.74972222
0.74972222
0.74972222
0.74972222
1.24722222
1.24722222
1.24722222
1.24722222
0.492
0.492
0.492
0.492
0.492
0.492
0.55611111
0.55611111
0.55611111
0.55611111
0.55611111
0.74972222
0.74972222
0.74972222
0.74972222
0.74972222
1.24722222
1.24722222
1.24722222
1.24722222
6.12279
6.12279
6.12279
6.12279
6.11694
6.11694
6.11694
6.11694
6.1075
6.1075
6.1075
6.1075
6.09778
6.09778
6.09778
6.09778
6.09361
6.09361
6.09361
6.09361
6.08722
6.08722
6.08722
6.08722
6.07917
6.07917
6.07917
6.07917
6.12279
6.12279
6.12279
6.12279
6.11694
6.11694
6.11694
6.11694
6.1075
6.1075
6.1075
6.1075
6.09778
6.09778
6.09778
6.09778
6.09361
6.09361
6.09361
6.09361
6.08722
6.08722
6.08722
6.08722
6.07917
6.07917
6.07917
6.07917
6.11694
6.11694
6.11694
6.11694
4.17766667
4.17766667
4.17766667
4.17766667
4.17766667
4.24655556
4.24655556
4.24655556
4.24655556
4.24655556
4.24530556
4.24530556
4.24530556
4.24530556
4.24530556
4.24530556
4.24347222
4.24347222
4.24347222
4.24347222
4.24347222
4.18588889
4.18588889
4.18588889
4.18588889
4.18588889
0.492
0.492
0.492
0.492
0.492
0.55611111
0.55611111
0.55611111
0.55611111
0.55611111
0.55611111
0.55611111
0.55611111
0.74988889
0.74988889
0.74988889
0.74988889
0.74988889
1.47222222
1.47222222
1.47222222
1.47222222
1.25833333
1.25833333
1.25833333
1.25833333
1.25555556
1.25555556
1.25555556
1.64222222
1.64222222
1.64222222
1.41361111
1.41361111
1.41361111
1.41361111
nan
36.72
36.33
3.03
2.78
2.6
2.52
2.43
2.36
1.87
1.78
1.65
1.57
1.5
1.43
1.35
1.27
1.18
1.1
1.02
0.94
0.85
0.77
0.68
0.6
0.52
0.43
0.35
0.27
0.18
0.1
3.52
5.18
5.1
5.02
3.45
3.37
3.28
3.2
3.11
3.03
2.94
2.86
2.78
0.48333333
0.49472222
0.75
0.75
0.75
0.75
0.75
0.75
0.75
0.75
0.75
0.75
0.75
0.75
5.5
0.278444
0.278444
0.1718
0.1718
0.1718
0.1718
0.1718
0.1718
0.293
0.293
0.293
0.293
0.293
0.293
0.325
0.325
0.325
0.325
0.325
0.325
0.1666667
0.1666667
0.1666667
0.1666667
0.1
0.1
0.2833333
0.2833333
0.2833333
0.3183333
0.3183333
0.3183333
0.31222222
7.10861111
5.9
16.93
5.01
34.7436111
34.7436111
34.7436111
34.5944444
34.5944444
34.5944444
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
6.18
6.18
6.18
6.3
6.3
6.3
5.08
5.08
5.08
5.13
5.13
5.13
5.37
5.37
5.37
5.37
5.37
5.37
5.68
5.68
5.68
5.72
5.72
5.72
6.43
6.43
6.43
6.45
6.45
6.45
5.63
5.63
5.63
5.62
5.62
5.62
34.67712389
5.88148889
5.88148889
5.88148889
nan
nan
nan
nan
nan
4.55835
4.55835
4.55835
4.55835
4.55835
4.55821
4.55821
4.55821
4.55821
4.55821
4.55821
4.55821
nan
nan
nan
nan
nan
33.5
33.5
33.5
33.65
33.65
33.65
33.8
33.8
33.8
3.81666667
3.81666667
3.81666667
1.03341667
1.03341667
1.03341667
5.33333333
5.33333333
5.33333333
6.08333333
6.08333333
6.08333333
6.08333333
6.08333333
6.08333333
1.030475
1.030475
1.030475
1.03033333
1.03033333
3.52027778
3.52027778
3.67722222
3.67722222
3.67722222
3.67722222
3.67722222
3.68583333
3.68583333
3.68583333
3.68583333
3.79638889
3.79638889
3.79638889
3.79638889
3.80138889
3.80138889
3.80138889
4.43611111
4.43611111
4.43611111
4.43611111
4.43611111
4.43611111
4.42
4.42
4.42
4.42
4.72027778
4.72027778
4.72027778
4.72444444
4.72444444
4.548633
4.548633
4.548633
4.556233
4.556233
4.556233
4.556233
4.556233
4.55135
4.55135
4.55135
4.55135
4.5483
4.5483
4.5483
4.5483
4.33
4.33
4.33
4.33
4.33
4.33
4.33
4.33
4.33
4.33
4.33
4.33
4.32
4.32
4.32
4.32
4.49363
4.49363
4.50555
4.50555
4.50528
4.50528
4.49047
4.49047
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.52
4.30767
4.30767
4.30767
4.30767
4.30767
4.30767
4.30767
4.30767
4.30767
4.30767
4.50817
4.50817
4.50817
4.50817
4.50817
4.50817
4.50817
4.50817
4.50817
4.50817
4.503767
4.503767
4.503767
4.503767
4.503767
4.503767
4.30687
4.30687
4.30687
4.30687
4.30687
4.30687
4.31687
4.31687
4.31687
4.31687
4.31687
4.31687
4.316687
4.316687
4.316687
4.316687
4.316687
4.316687
4.53108
4.53108
4.53108
4.53108
4.53108
4.53108
4.53108
4.53108
4.53108
4.29923
4.29923
4.29923
4.29923
4.29923
4.29923
4.30106
4.30106
4.30106
4.30106
4.30106
4.30106
4.29444
4.29444
4.29444
4.29444
4.29444
4.29444
4.2923
4.2923
4.2923
4.2923
5.916667
5.916667
5.916667
5.916667
5.916667
5.916667
0.72
0.72
0.72
0.72
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.2
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.22
5.22
5.22
5.22
5.44
5.44
5.44
31.95
31.95
31.95
31.95
31.95
31.95
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
31.95
31.95
31.96
31.96
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.33333333
5.35
5.35
5.35
5.33333333
5.33333333
5.2
5.2
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.316667
5.316667
5.316667
5.316667
5.316667
5.316667
5.316667
5.316667
5.316667
5.316667
5.316667
5.316667
5.35
5.35
5.35
5.35
5.35
5.35
5.35
5.35
5.35
5.35
5.35
5.35
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.333333
5.31666667
5.19
5.19
5.19
5.19
5.19
5.19
5.33
5.33
5.33
5.33
5.33
5.32
5.32
5.24
5.24
5.24
5.24
5.24
5.24
5.24
5.24
5.24
5.24
5.24
5.24
5.24
5.31931
5.31931
5.31931
5.31942
5.31942
5.31942
5.32039
5.32039
5.32039
5.32039
5.32039
5.32055
5.32055
5.32055
5.32055
5.32055
5.32094
5.32094
5.32094
5.32094
5.32094
5.32095
5.32095
5.32095
5.32095
5.32095
5.32095
5.32095
5.28119
5.28119
5.28119
5.28119
5.28119
5.28119
5.28119
5.28119
5.37225
5.37225
5.37201
5.37201
5.37201
5.37201
5.37201
5.37631
5.37631
5.37631
5.37631
5.37631
5.37644
5.37644
5.37644
5.37644
nan
nan
5.372833
5.372833
5.372833
5.375
5.375
5.375
5.371944
5.371944
5.371944
5.27
5.27
5.27
5.2
5.2
5.2
5.2
6.0
6.0
6.0
6.0
6.0
6.0
5.9
5.9
5.9
5.8
5.8
5.8
5.8
5.8
5.8
5.9
5.9
5.9
5.7
5.7
5.7
5.7
5.7
5.6
5.6
5.6
5.6
0.01666667
0.01666667
0.01666667
0.01666667
0.01666667
0.01666667
0.73333333
0.73333333
0.73333333
0.73333333
0.73333333
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.106
6.106
6.0903
6.0903
6.0903
6.0903
5.9617
5.9617
5.9617
5.9617
6.1497
6.1497
6.1497
5.9158
5.9158
5.9158
5.9163
5.9163
6.2
6.2
6.1
6.1
6.1
6.1
6.1
6.1
6.1
6.1
6.1
6.1
6.1
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
1º 09' 02,2‘' E
1º 12' 24,0‘' E
1º 09' 02,5‘' E
1º13'61,1'' E
0.09
0.09
0.09
0.09
0.09
0.09
0.07
0.07
0.07
0.03
0.03
0.03
0.2
0.2
0.2
0.18
0.18
0.18
0.22
0.22
0.22
0.29
0.29
0.29
0.27
0.27
0.27
0.11
0.11
0.11
nan
5.7
4.233
4.233
4.233
4.549
4.549
4.549
4.3314
4.3314
4.3314
4.3314
4.3314
4.334
4.334
4.334
4.334
4.548
4.548
4.548
4.548
2.87
3.79931
3.79931
3.79581
3.79581
3.79535
3.79535
3.79535
3.79833
3.79833
3.79833
3.79833
3.79861
3.79861
3.80194
3.80194
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
3.55
3.55
3.55
3.638
3.638
3.638
3.56
3.56
3.56
3.64
3.64
3.64
3.63
3.63
3.63
3.55338
3.55338
3.55338
3.55362
3.55362
3.55362
3.63889
3.63889
3.63889
2.45
2.45
2.45
2.45
2.45
2.45
2.45
2.45
2.41
2.41
2.41
2.246503
2.246503
2.246503
2.246503
44.7217
44.7217
2.4069
2.4069
2.4069
2.4069
2.4069
2.4464
2.4464
2.4464
2.4319
2.4319
2.4319
2.4319
2.4319

C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\2716947769.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Longitude'] = df_cleaned['Longitude'].astype(str)
C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\2716947769.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Longitude'] = df_cleaned['Longitude'].apply(convert_line_to_decimal)

In [10]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1636 entries, 3 to 2355
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   filename            1636 non-null   object
 1   X                   129 non-null    float64
 2   Y                   1636 non-null   object
 3   Longitude           1381 non-null   object
 4   Latitude            1399 non-null   object
 5   Altitude            989 non-null    object
 6   UD                  1519 non-null   object
 7   LD                  1437 non-null   object
 8   Average profondeur  1309 non-null   object
 9   USDA Soil Taxonomy  583 non-null    object
 10  pH                  1324 non-null   object
 11  CE                  1221 non-null   object
 12  CEC                 489 non-null    object
 13  A%                  1139 non-null   object
 14  L%                  1130 non-null   object
 15  S%                  1153 non-null   object
 16  ALR(L)              152 non-null    object
 17  ALR(S)              95 non-null     object
 18  OM                  892 non-null    object
dtypes: float64(1), object(18)
memory usage: 255.6+ KB

In [22]:
def type_converter(val):
    try : 
        return round(float(val), 2)
    except Exception:
        return None

In [12]:
df_cleaned["Y"] = df_cleaned["Y"].apply(type_converter)
df_cleaned["Latitude"] = df_cleaned["Latitude"].apply(type_converter)
df_cleaned["Longitude"] = df_cleaned["Longitude"].apply(type_converter)

C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\695684658.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Y"] = df_cleaned["Y"].apply(type_converter)
C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\695684658.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Latitude"] = df_cleaned["Latitude"].apply(type_converter)
C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\695684658.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["Longitude"] = df_cleaned["Longitude"].apply(type_converter)

In [13]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1636 entries, 3 to 2355
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   filename            1636 non-null   object
 1   X                   129 non-null    float64
 2   Y                   321 non-null    float64
 3   Longitude           1376 non-null   float64
 4   Latitude            1370 non-null   float64
 5   Altitude            989 non-null    object
 6   UD                  1519 non-null   object
 7   LD                  1437 non-null   object
 8   Average profondeur  1309 non-null   object
 9   USDA Soil Taxonomy  583 non-null    object
 10  pH                  1324 non-null   object
 11  CE                  1221 non-null   object
 12  CEC                 489 non-null    object
 13  A%                  1139 non-null   object
 14  L%                  1130 non-null   object
 15  S%                  1153 non-null   object
 16  ALR(L)              152 non-null    object
 17  ALR(S)              95 non-null     object
 18  OM                  892 non-null    object
dtypes: float64(4), object(15)
memory usage: 255.6+ KB

In [14]:
df_cleaned['Latitude'] = df_cleaned['Latitude'].fillna(df['X'])
df_cleaned['Longitude'] = df_cleaned['Longitude'].fillna(df['Y'])

C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\1819996865.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Latitude'] = df_cleaned['Latitude'].fillna(df['X'])
C:\Users\abdo7\AppData\Local\Temp\ipykernel_2776\1819996865.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Longitude'] = df_cleaned['Longitude'].fillna(df['Y'])

In [15]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1636 entries, 3 to 2355
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   filename            1636 non-null   object
 1   X                   129 non-null    float64
 2   Y                   321 non-null    float64
 3   Longitude           1595 non-null   object
 4   Latitude            1609 non-null   object
 5   Altitude            989 non-null    object
 6   UD                  1519 non-null   object
 7   LD                  1437 non-null   object
 8   Average profondeur  1309 non-null   object
 9   USDA Soil Taxonomy  583 non-null    object
 10  pH                  1324 non-null   object
 11  CE                  1221 non-null   object
 12  CEC                 489 non-null    object
 13  A%                  1139 non-null   object
 14  L%                  1130 non-null   object
 15  S%                  1153 non-null   object
 16  ALR(L)              152 non-null    object
 17  ALR(S)              95 non-null     object
 18  OM                  892 non-null    object
dtypes: float64(2), object(17)
memory usage: 255.6+ KB

In [16]:
df_unique = df_cleaned.drop_duplicates(subset=["Latitude" , "Longitude"])
df_unique

,filename,X,Y,Longitude,Latitude,Altitude,UD,LD,Average profondeur,USDA Soil Taxonomy,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
3,../theses/Nord\memoires traited\Caractérisatio...,NaN,NaN,3.0583,36.7232,1200,0,10,5,NaN,7.2,NaN,15,20,40,40,NaN,NaN,NaN
57,../theses/Nord\memoires traited\TH9217.pdf,NaN,NaN,3.016008,36.814841,NaN,NaN,NaN,NaN,NaN,NaN,8.04,0.575,NaN,NaN,NaN,NaN,NaN,NaN
58,../theses/Nord\memoires traited\TH9217.pdf,NaN,NaN,3.936844,36.87836,NaN,NaN,NaN,NaN,NaN,NaN,7.65,0.582,NaN,NaN,NaN,NaN,NaN,NaN
59,../theses/Nord\memoires traited\TH9217.pdf,NaN,NaN,6.173911,35.561024,NaN,NaN,NaN,NaN,NaN,NaN,7.74,0.210,NaN,NaN,NaN,NaN,NaN,NaN
60,../theses/Nord\memoires traited\TH9217.pdf,NaN,NaN,3.673841,32.490225,NaN,NaN,NaN,NaN,NaN,NaN,7.17,2.93,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2337,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.246503,27.352776,NaN,0,20,10,NaN,7.63,1.15,NaN,NaN,NaN,NaN,NaN,NaN,2.38
2341,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,44.7217,21.1321,NaN,0,75,37.5,NaN,7.65,8.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2343,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.4069,27.95762,NaN,0,10,5,NaN,6.72,3.71,NaN,NaN,NaN,NaN,NaN,NaN,1.06
2348,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.4464,27.1988,NaN,0,3,1.5,NaN,6.8,3.75,NaN,NaN,NaN,NaN,NaN,NaN,1.32
2351,../theses/Sud\new memoires\In salah\TIATAOUI_T...,NaN,NaN,2.4319,27.19314,NaN,0,8,4,NaN,7.39,2.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_cleaned.to_csv("mydata.csv")

In [18]:
df1 = pd.read_excel("../results/soil_dataset.xlsx",sheet_name="soil_data")
df1 = df1.drop(columns=["id" ,"id_memoire","id_ech","Wilaya","Region"])
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1256 entries, 0 to 1255
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   X                   1256 non-null   float64
 1   Y                   1256 non-null   float64
 2   altitude            759 non-null    object
 3   UD                  1256 non-null   int64
 4   LD                  1256 non-null   int64
 5   average profondeur  1256 non-null   float64
 6   USDA Soil Taxonomy  241 non-null    object
 7   pH                  1256 non-null   float64
 8   CE                  1256 non-null   float64
 9   CEC                 1256 non-null   float64
 10  A%                  1256 non-null   float64
 11  L%                  1256 non-null   float64
 12  S%                  1256 non-null   float64
 13  ALR(L)              1088 non-null   float64
 14  ALR(S)              1088 non-null   float64
 15  OM                  1256 non-null   float64
dtypes: float64(12), int64(2), object(2)
memory usage: 157.1+ KB

In [29]:
df2 = pd.read_csv("mydata.csv")
df2 = df2.drop(columns=["filename" , "Unnamed: 0" , "X" , "Y"])
df2["Latitude"] = df2["Latitude"].apply(type_converter)
df2["Longitude"] = df2["Longitude"].apply(type_converter)
df2

,Longitude,Latitude,Altitude,UD,LD,Average profondeur,USDA Soil Taxonomy,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.06,36.72,1200,0,10,5,NaN,7.2,NaN,15.000,20,40,40,NaN,NaN,NaN
1,3.06,36.72,1200,10,20,15,NaN,7.5,NaN,12.000,25,35,40,NaN,NaN,NaN
2,3.02,36.81,NaN,NaN,NaN,NaN,NaN,NaN,8.04,0.575,NaN,NaN,NaN,NaN,NaN,NaN
3,3.94,36.88,NaN,NaN,NaN,NaN,NaN,NaN,7.65,0.582,NaN,NaN,NaN,NaN,NaN,NaN
4,6.17,35.56,NaN,NaN,NaN,NaN,NaN,NaN,7.74,0.210,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,2.43,27.19,NaN,0,8,4,NaN,7.39,2.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1632,2.43,27.19,NaN,8,34,21,NaN,7.65,4.87,NaN,NaN,NaN,NaN,NaN,NaN,0.53
1633,2.43,27.19,NaN,34,43,38.5,NaN,7.99,5.48,NaN,NaN,NaN,NaN,NaN,NaN,1.06
1634,2.43,27.19,NaN,43,60,51.5,NaN,8.04,4.07,NaN,NaN,NaN,NaN,NaN,NaN,0
1635,2.43,27.19,NaN,60,80,70,NaN,7.9,3.13,NaN,NaN,NaN,NaN,NaN,NaN,0

In [30]:
for i in df2.columns:
    if i not in ["USDA Soil Taxonomy"]:
        df2[i] = df2[i].apply(type_converter)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1636 entries, 0 to 1635
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Longitude           1555 non-null   float64
 1   Latitude            1563 non-null   float64
 2   Altitude            951 non-null    float64
 3   UD                  1488 non-null   float64
 4   LD                  1433 non-null   float64
 5   Average profondeur  1302 non-null   float64
 6   USDA Soil Taxonomy  583 non-null    object
 7   pH                  1277 non-null   float64
 8   CE                  1184 non-null   float64
 9   CEC                 489 non-null    float64
 10  A%                  1101 non-null   float64
 11  L%                  1097 non-null   float64
 12  S%                  1114 non-null   float64
 13  ALR(L)              151 non-null    float64
 14  ALR(S)              95 non-null     float64
 15  OM                  852 non-null    float64
dtypes: float64(15), object(1)
memory usage: 204.6+ KB

In [31]:
df2.columns = df1.columns 
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1636 entries, 0 to 1635
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   X                   1555 non-null   float64
 1   Y                   1563 non-null   float64
 2   altitude            951 non-null    float64
 3   UD                  1488 non-null   float64
 4   LD                  1433 non-null   float64
 5   average profondeur  1302 non-null   float64
 6   USDA Soil Taxonomy  583 non-null    object
 7   pH                  1277 non-null   float64
 8   CE                  1184 non-null   float64
 9   CEC                 489 non-null    float64
 10  A%                  1101 non-null   float64
 11  L%                  1097 non-null   float64
 12  S%                  1114 non-null   float64
 13  ALR(L)              151 non-null    float64
 14  ALR(S)              95 non-null     float64
 15  OM                  852 non-null    float64
dtypes: float64(15), object(1)
memory usage: 204.6+ KB

In [32]:
df2

,X,Y,altitude,UD,LD,average profondeur,USDA Soil Taxonomy,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.06,36.72,1200.0,0.0,10.0,5.0,NaN,7.20,NaN,15.00,20.0,40.0,40.0,NaN,NaN,NaN
1,3.06,36.72,1200.0,10.0,20.0,15.0,NaN,7.50,NaN,12.00,25.0,35.0,40.0,NaN,NaN,NaN
2,3.02,36.81,NaN,NaN,NaN,NaN,NaN,NaN,8.04,0.57,NaN,NaN,NaN,NaN,NaN,NaN
3,3.94,36.88,NaN,NaN,NaN,NaN,NaN,NaN,7.65,0.58,NaN,NaN,NaN,NaN,NaN,NaN
4,6.17,35.56,NaN,NaN,NaN,NaN,NaN,NaN,7.74,0.21,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,2.43,27.19,NaN,0.0,8.0,4.0,NaN,7.39,2.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1632,2.43,27.19,NaN,8.0,34.0,21.0,NaN,7.65,4.87,NaN,NaN,NaN,NaN,NaN,NaN,0.53
1633,2.43,27.19,NaN,34.0,43.0,38.5,NaN,7.99,5.48,NaN,NaN,NaN,NaN,NaN,NaN,1.06
1634,2.43,27.19,NaN,43.0,60.0,51.5,NaN,8.04,4.07,NaN,NaN,NaN,NaN,NaN,NaN,0.00
1635,2.43,27.19,NaN,60.0,80.0,70.0,NaN,7.90,3.13,NaN,NaN,NaN,NaN,NaN,NaN,0.00

In [27]:
df_combined = pd.concat([df1, df2], ignore_index=True)
df_combined

,X,Y,altitude,UD,LD,average profondeur,USDA Soil Taxonomy,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.10700,36.684000,22,15.0,30.0,22.5,NaN,7.870,0.170,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019
1,3.10700,36.684000,22,30.0,60.0,45.0,NaN,7.774,0.170,17.207000,40.361496,37.281777,22.356727,-0.034471,-0.256559,1.503
2,3.10700,36.684000,22,60.0,100.0,80.0,NaN,7.799,0.170,15.049000,49.608530,42.317043,8.074427,-0.069041,-0.788445,0.706
3,3.13333,36.071667,24,15.0,30.0,22.5,CL,7.950,0.260,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645
4,3.13333,36.071667,24,30.0,60.0,45.0,CL,8.096,0.279,40.610953,33.898341,39.248386,26.853273,0.063643,-0.101181,1.097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2887,2.43000,27.190000,NaN,0.0,8.0,4.0,NaN,7.390,2.860,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2888,2.43000,27.190000,NaN,8.0,34.0,21.0,NaN,7.650,4.870,NaN,NaN,NaN,NaN,NaN,NaN,0.530
2889,2.43000,27.190000,NaN,34.0,43.0,38.5,NaN,7.990,5.480,NaN,NaN,NaN,NaN,NaN,NaN,1.060
2890,2.43000,27.190000,NaN,43.0,60.0,51.5,NaN,8.040,4.070,NaN,NaN,NaN,NaN,NaN,NaN,0.000
2891,2.43000,27.190000,NaN,60.0,80.0,70.0,NaN,7.900,3.130,NaN,NaN,NaN,NaN,NaN,NaN,0.000

In [28]:
df_unique = df_combined.drop_duplicates(subset=["X" , "Y"])
df_unique

,X,Y,altitude,UD,LD,average profondeur,USDA Soil Taxonomy,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.107000,36.684000,22,15.0,30.0,22.5,NaN,7.87,0.170000,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019
3,3.133330,36.071667,24,15.0,30.0,22.5,CL,7.95,0.260000,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645
5,3.150000,36.724167,42,15.0,30.0,22.5,NaN,8.50,2.632808,40.610953,13.000000,32.000000,55.000000,0.391206,0.626419,7.270
7,2.880278,36.757500,44,5.0,15.0,10.0,NaN,8.59,0.370000,40.610953,7.210000,11.570000,81.220000,0.205397,1.051727,4.100
9,3.178361,36.704083,12,15.0,30.0,22.5,NaN,7.83,2.632808,3.750000,27.239966,42.857252,29.902781,NaN,NaN,1.360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2873,2.250000,27.350000,NaN,0.0,20.0,10.0,NaN,7.63,1.150000,NaN,NaN,NaN,NaN,NaN,NaN,2.380
2877,44.720000,21.130000,NaN,0.0,75.0,37.5,NaN,7.65,8.650000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2879,2.410000,27.960000,NaN,0.0,10.0,5.0,NaN,6.72,3.710000,NaN,NaN,NaN,NaN,NaN,NaN,1.060
2884,2.450000,27.200000,NaN,0.0,3.0,1.5,NaN,6.80,3.750000,NaN,NaN,NaN,NaN,NaN,NaN,1.320
2887,2.430000,27.190000,NaN,0.0,8.0,4.0,NaN,7.39,2.860000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df_combined.to_csv("CombinedData.csv")

In [5]:
from pyproj import Transformer
import pandas as pd

In [11]:
df = pd.read_csv("../results/CombinedData.csv")
transformer = Transformer.from_crs("EPSG:30491", "EPSG:4326", always_xy=True)

for i in range(len(df)):
    if df.iloc[i]["X"] > 100 and df.iloc[i]["X"] < 1000 and df.iloc[i]["Y"] > 100 and df.iloc[i]["Y"]<1000:
        x = df.at[i, "X"] * 1000
        y = df.at[i, "Y"] * 1000
        lon, lat = transformer.transform(x, y)
        df.at[i, "X"] = round(lon, 2) 
        df.at[i, "Y"] = round(lat, 2) 
        print(df.at[i, "X"] , df.at[i, "Y"])
    elif df.iloc[i]["X"] > 1000 and df.iloc[i]["Y"] > 1000:
        lon, lat = transformer.transform(x, y)
        df.at[i, "X"] = round(lon, 2) 
        df.at[i, "Y"] = round(lat, 2) 
        print(df.at[i, "X"] , df.at[i, "Y"])

2.03 35.94
0.75 37.88
0.75 37.88
0.67 37.85
0.67 37.85
0.75 37.92
0.74 37.92
0.74 37.92
0.74 37.92
0.63 37.87
0.63 37.87
0.63 37.87
0.74 37.88
0.74 37.88
0.75 37.92
0.75 37.92
0.72 37.89
0.72 37.89
0.75 37.92
0.75 37.92
0.75 37.92
0.79 37.96
0.79 37.96
0.79 37.96
0.74 37.91
0.74 37.91
0.77 37.97
0.77 37.97
0.77 37.97
0.76 37.88
0.76 37.88
0.76 37.88
0.76 37.88
0.76 37.88
0.66 37.96
0.66 37.96
0.69 37.95
0.69 37.95
0.69 37.95
0.69 37.95
0.68 37.92
0.68 37.92
0.68 37.92
0.66 37.93
0.66 37.93
0.66 37.93
0.66 37.93
0.76 37.98
0.76 37.98
0.76 37.98
0.74 37.97
0.74 37.97
0.74 37.97
0.74 37.97
0.61 37.84
0.61 37.84
1.96 35.86
1.96 35.86
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94
2.03 35.94

In [12]:
df.to_csv("CombinedData.csv")