In [13]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import os 
import glob

In [14]:
base_url = "../../results/Splined/"
variables = ["A%","ALR(L)","ALR(S)","CE","CEC","L%","OC(%)","OM%","pH","S%"]
csv_files = sorted(glob.glob(os.path.join(base_url, "*.csv")))

merged_df = None
for file, var_name in zip(csv_files, variables):
    df = pd.read_csv(file)
    df = df[['SID', 'UD', 'LD', 'SPLINED_VALUE']].copy()
    df = df.rename(columns={'SPLINED_VALUE': var_name})
    if merged_df is None:
        merged_df = df
    else:
        merged_df = pd.merge(merged_df, df, on=['SID', 'UD', 'LD'], how='outer')

merged_df

,SID,UD,LD,A%,ALR(L),ALR(S),CE,CEC,L%,OC(%),OM%,pH,S%
0,-0.09455116238_35.78682408,0,5,12.333685,0.893930,2.306617,6.404642,7.311231,18.140976,NaN,NaN,74.547794,7.110377
1,-0.09455116238_35.78682408,5,15,11.847969,0.946038,2.353142,6.190028,7.048924,18.278750,NaN,NaN,74.672326,7.144755
2,-0.09455116238_35.78682408,15,30,9.743061,1.171362,2.554309,5.262191,5.915067,18.874708,NaN,NaN,75.210226,7.293732
3,-0.09455116238_35.78682408,30,60,5.525814,1.512805,2.855176,3.901625,4.290227,19.820767,NaN,NaN,75.889006,7.591430
4,-0.09455116238_35.78682408,60,100,4.621229,1.047307,2.419303,6.050623,7.109795,18.809306,NaN,NaN,74.080899,7.651464
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2736,8.414166667_37.09472222,5,15,0.100000,1.401231,2.420257,NaN,6.131968,24.892460,11.696769,NaN,68.975573,6.177699
2737,8.414166667_37.09472222,15,30,0.100000,1.423329,2.403869,NaN,6.165818,25.601487,14.661547,NaN,68.232695,6.271719
2738,8.414166667_37.09472222,30,60,0.100000,1.477367,2.372119,NaN,6.210706,27.210403,18.866199,NaN,66.578892,6.405402
2739,8.414166667_37.09472222,60,100,0.100000,1.535705,2.358143,NaN,6.166735,28.642714,15.976235,NaN,65.190550,6.314960
2740,8.414166667_37.09472222,100,200,0.100000,1.559496,2.354472,NaN,6.139571,29.196387,14.055585,NaN,64.664042,6.254627

In [15]:
merged_df[['X', 'Y']] = merged_df['SID'].str.split('_', expand=True)

merged_df['X'] = pd.to_numeric(merged_df['X'])
merged_df['Y'] = pd.to_numeric(merged_df['Y'])

merged_df

,SID,UD,LD,A%,ALR(L),ALR(S),CE,CEC,L%,OC(%),OM%,pH,S%,X,Y
0,-0.09455116238_35.78682408,0,5,12.333685,0.893930,2.306617,6.404642,7.311231,18.140976,NaN,NaN,74.547794,7.110377,-0.094551,35.786824
1,-0.09455116238_35.78682408,5,15,11.847969,0.946038,2.353142,6.190028,7.048924,18.278750,NaN,NaN,74.672326,7.144755,-0.094551,35.786824
2,-0.09455116238_35.78682408,15,30,9.743061,1.171362,2.554309,5.262191,5.915067,18.874708,NaN,NaN,75.210226,7.293732,-0.094551,35.786824
3,-0.09455116238_35.78682408,30,60,5.525814,1.512805,2.855176,3.901625,4.290227,19.820767,NaN,NaN,75.889006,7.591430,-0.094551,35.786824
4,-0.09455116238_35.78682408,60,100,4.621229,1.047307,2.419303,6.050623,7.109795,18.809306,NaN,NaN,74.080899,7.651464,-0.094551,35.786824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2736,8.414166667_37.09472222,5,15,0.100000,1.401231,2.420257,NaN,6.131968,24.892460,11.696769,NaN,68.975573,6.177699,8.414167,37.094722
2737,8.414166667_37.09472222,15,30,0.100000,1.423329,2.403869,NaN,6.165818,25.601487,14.661547,NaN,68.232695,6.271719,8.414167,37.094722
2738,8.414166667_37.09472222,30,60,0.100000,1.477367,2.372119,NaN,6.210706,27.210403,18.866199,NaN,66.578892,6.405402,8.414167,37.094722
2739,8.414166667_37.09472222,60,100,0.100000,1.535705,2.358143,NaN,6.166735,28.642714,15.976235,NaN,65.190550,6.314960,8.414167,37.094722
2740,8.414166667_37.09472222,100,200,0.100000,1.559496,2.354472,NaN,6.139571,29.196387,14.055585,NaN,64.664042,6.254627,8.414167,37.094722

In [16]:
merged_df = merged_df.drop(columns=["SID"])
merged_df

,UD,LD,A%,ALR(L),ALR(S),CE,CEC,L%,OC(%),OM%,pH,S%,X,Y
0,0,5,12.333685,0.893930,2.306617,6.404642,7.311231,18.140976,NaN,NaN,74.547794,7.110377,-0.094551,35.786824
1,5,15,11.847969,0.946038,2.353142,6.190028,7.048924,18.278750,NaN,NaN,74.672326,7.144755,-0.094551,35.786824
2,15,30,9.743061,1.171362,2.554309,5.262191,5.915067,18.874708,NaN,NaN,75.210226,7.293732,-0.094551,35.786824
3,30,60,5.525814,1.512805,2.855176,3.901625,4.290227,19.820767,NaN,NaN,75.889006,7.591430,-0.094551,35.786824
4,60,100,4.621229,1.047307,2.419303,6.050623,7.109795,18.809306,NaN,NaN,74.080899,7.651464,-0.094551,35.786824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2736,5,15,0.100000,1.401231,2.420257,NaN,6.131968,24.892460,11.696769,NaN,68.975573,6.177699,8.414167,37.094722
2737,15,30,0.100000,1.423329,2.403869,NaN,6.165818,25.601487,14.661547,NaN,68.232695,6.271719,8.414167,37.094722
2738,30,60,0.100000,1.477367,2.372119,NaN,6.210706,27.210403,18.866199,NaN,66.578892,6.405402,8.414167,37.094722
2739,60,100,0.100000,1.535705,2.358143,NaN,6.166735,28.642714,15.976235,NaN,65.190550,6.314960,8.414167,37.094722
2740,100,200,0.100000,1.559496,2.354472,NaN,6.139571,29.196387,14.055585,NaN,64.664042,6.254627,8.414167,37.094722

In [20]:
merged_df = merged_df[["X","Y","UD","LD","pH","CE","CEC","A%","L%","S%","ALR(L)","ALR(S)","OC(%)","OM%"]]
merged_df

,X,Y,UD,LD,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OC(%),OM%
0,-0.094551,35.786824,0,5,74.547794,6.404642,7.311231,12.333685,18.140976,7.110377,0.893930,2.306617,NaN,NaN
1,-0.094551,35.786824,5,15,74.672326,6.190028,7.048924,11.847969,18.278750,7.144755,0.946038,2.353142,NaN,NaN
2,-0.094551,35.786824,15,30,75.210226,5.262191,5.915067,9.743061,18.874708,7.293732,1.171362,2.554309,NaN,NaN
3,-0.094551,35.786824,30,60,75.889006,3.901625,4.290227,5.525814,19.820767,7.591430,1.512805,2.855176,NaN,NaN
4,-0.094551,35.786824,60,100,74.080899,6.050623,7.109795,4.621229,18.809306,7.651464,1.047307,2.419303,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2736,8.414167,37.094722,5,15,68.975573,NaN,6.131968,0.100000,24.892460,6.177699,1.401231,2.420257,11.696769,NaN
2737,8.414167,37.094722,15,30,68.232695,NaN,6.165818,0.100000,25.601487,6.271719,1.423329,2.403869,14.661547,NaN
2738,8.414167,37.094722,30,60,66.578892,NaN,6.210706,0.100000,27.210403,6.405402,1.477367,2.372119,18.866199,NaN
2739,8.414167,37.094722,60,100,65.190550,NaN,6.166735,0.100000,28.642714,6.314960,1.535705,2.358143,15.976235,NaN
2740,8.414167,37.094722,100,200,64.664042,NaN,6.139571,0.100000,29.196387,6.254627,1.559496,2.354472,14.055585,NaN

In [21]:
merged_df.to_csv("../../results/Soil/full_splined.csv")

In [25]:
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

numeric_df = merged_df.select_dtypes(include=['float64', 'int64'])
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

imputer = KNNImputer(n_neighbors=5)
imputed_array = imputer.fit_transform(scaled_data)
real_values = scaler.inverse_transform(imputed_array)
merged_df[numeric_df.columns] = real_values

merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2741 entries, 0 to 2740
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       2741 non-null   float64
 1   Y       2741 non-null   float64
 2   UD      2741 non-null   float64
 3   LD      2741 non-null   float64
 4   pH      2741 non-null   float64
 5   CE      2741 non-null   float64
 6   CEC     2741 non-null   float64
 7   A%      2741 non-null   float64
 8   L%      2741 non-null   float64
 9   S%      2741 non-null   float64
 10  ALR(L)  2741 non-null   float64
 11  ALR(S)  2741 non-null   float64
 12  OC(%)   2741 non-null   float64
 13  OM%     2741 non-null   float64
dtypes: float64(14)
memory usage: 299.9 KB

In [26]:
merged_df.to_csv("../../results/Soil/full_splined_NAN.csv")

In [24]:
uniques = merged_df.drop_duplicates(subset=["X","Y"])
uniques

,X,Y,UD,LD,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OC(%),OM%
0,-0.094551,35.786824,0,5,74.547794,6.404642,7.311231,12.333685,18.140976,7.110377,0.893930,2.306617,NaN,NaN
6,-0.094682,35.783222,0,5,83.291593,6.028645,8.795516,4.101079,7.912891,7.576187,0.000000,2.247701,NaN,NaN
12,-0.094814,35.779620,0,5,69.783936,5.292950,6.339849,4.232644,23.833469,7.557264,1.329243,2.392225,NaN,NaN
18,-0.094945,35.776018,0,5,46.695050,3.400624,3.270652,14.641522,50.034298,7.668368,2.763003,2.696493,NaN,NaN
24,-0.095076,35.772417,0,5,59.103610,2.440479,1.517456,9.439977,39.378934,7.051867,3.200028,3.605780,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2714,7.698333,36.781111,0,5,27.490613,383.853774,30.381132,0.099906,38.016981,8.299528,0.224196,0.000000,NaN,NaN
2717,7.992500,36.848611,0,5,68.516530,NaN,4.610997,0.121828,26.872473,5.687539,1.761085,2.698702,48.783917,NaN
2723,8.200000,36.900000,0,5,54.761945,NaN,3.171597,0.100015,42.066458,5.614928,2.579962,2.843597,34.722968,NaN
2729,8.386667,37.064444,0,5,62.874878,NaN,12.245741,0.100000,24.879419,5.094341,0.708640,1.635620,27.972723,NaN
2735,8.414167,37.094722,0,5,69.146825,NaN,6.124133,0.100000,24.729042,6.155947,1.396141,2.424040,11.010841,NaN