In [58]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import os 
import rasterio
from rasterio.transform import rowcol
from rasterio.transform import xy
from rasterio.windows import Window

# Data Explanation : 
1. Fauna : all animals distribution (amphibians , birds , mammals , reptiles) the data gives th nombre of birds , mammals ...etc in this area for example each pixel containe 1km²and the value is he number of animals in this area (form 0 --> 153  or 0 --> 178)

2. vegetation : the percentage of a specific land cover  (barren , evergreen, herbaceous) in speicific area (pixel)

3. human activities : gives the human modification in 1km² area between 0 and 1 

we can deduct somethings like : 
- High Species Richness + Low Human Modification → Biodiversity hotspots with low disturbance (ideal for conservation).
- High Species Richness + High Human Modification → Threatened ecosystems (urgent conservation priority).
- Low Species Richness + High Human Modification → Urban/agricultural areas with low ecological value.
- Low Species Richness + Low Human Modification → Natural areas with fewer species (e.g., deserts).

In [59]:
df = pd.read_csv("../results/Soil/full_splined_NAN.csv")
df

,Unnamed: 0,SID,X,Y,UD,LD,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM%,Ranges
0,0,-0.09455116238_35.78682408,-0.094551,35.786824,0.0,5.0,7.110377,6.404642,7.311231,12.333685,18.140976,74.547794,0.893930,2.306617,0.533126,0_5
1,1,-0.09455116238_35.78682408,-0.094551,35.786824,5.0,15.0,7.144755,6.190028,7.048924,11.847969,18.278750,74.672326,0.946038,2.353142,0.467774,5_15
2,2,-0.09455116238_35.78682408,-0.094551,35.786824,15.0,30.0,7.293732,5.262191,5.915067,9.743061,18.874708,75.210226,1.171362,2.554309,0.474109,15_30
3,3,-0.09455116238_35.78682408,-0.094551,35.786824,30.0,60.0,7.591430,3.901625,4.290227,5.525814,19.820767,75.889006,1.512805,2.855176,0.356968,30_60
4,4,-0.09455116238_35.78682408,-0.094551,35.786824,60.0,100.0,7.651464,6.050623,7.109795,4.621229,18.809306,74.080899,1.047307,2.419303,0.262489,60_100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3181,3181,8.414166667_37.09472222,8.414167,37.094722,5.0,15.0,6.177699,28.007083,6.131968,0.100000,24.892460,68.975573,1.401231,2.420257,11.696769,5_15
3182,3182,8.414166667_37.09472222,8.414167,37.094722,15.0,30.0,6.271719,26.751345,6.165818,0.100000,25.601487,68.232695,1.423329,2.403869,14.661547,15_30
3183,3183,8.414166667_37.09472222,8.414167,37.094722,30.0,60.0,6.405402,20.919296,6.210706,0.100000,27.210403,66.578892,1.477367,2.372119,18.866199,30_60
3184,3184,8.414166667_37.09472222,8.414167,37.094722,60.0,100.0,6.314960,19.177498,6.166735,0.100000,28.642714,65.190550,1.535705,2.358143,15.976235,60_100
3185,3185,8.414166667_37.09472222,8.414167,37.094722,100.0,200.0,6.254627,10.323197,6.139571,0.100000,29.196387,64.664042,1.559496,2.354472,14.055585,100_200

In [60]:
df = df.drop(columns=["Unnamed: 0" , "SID"])
df

,X,Y,UD,LD,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM%,Ranges
0,-0.094551,35.786824,0.0,5.0,7.110377,6.404642,7.311231,12.333685,18.140976,74.547794,0.893930,2.306617,0.533126,0_5
1,-0.094551,35.786824,5.0,15.0,7.144755,6.190028,7.048924,11.847969,18.278750,74.672326,0.946038,2.353142,0.467774,5_15
2,-0.094551,35.786824,15.0,30.0,7.293732,5.262191,5.915067,9.743061,18.874708,75.210226,1.171362,2.554309,0.474109,15_30
3,-0.094551,35.786824,30.0,60.0,7.591430,3.901625,4.290227,5.525814,19.820767,75.889006,1.512805,2.855176,0.356968,30_60
4,-0.094551,35.786824,60.0,100.0,7.651464,6.050623,7.109795,4.621229,18.809306,74.080899,1.047307,2.419303,0.262489,60_100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3181,8.414167,37.094722,5.0,15.0,6.177699,28.007083,6.131968,0.100000,24.892460,68.975573,1.401231,2.420257,11.696769,5_15
3182,8.414167,37.094722,15.0,30.0,6.271719,26.751345,6.165818,0.100000,25.601487,68.232695,1.423329,2.403869,14.661547,15_30
3183,8.414167,37.094722,30.0,60.0,6.405402,20.919296,6.210706,0.100000,27.210403,66.578892,1.477367,2.372119,18.866199,30_60
3184,8.414167,37.094722,60.0,100.0,6.314960,19.177498,6.166735,0.100000,28.642714,65.190550,1.535705,2.358143,15.976235,60_100
3185,8.414167,37.094722,100.0,200.0,6.254627,10.323197,6.139571,0.100000,29.196387,64.664042,1.559496,2.354472,14.055585,100_200

In [61]:
df_unique = df.copy()
df_unique = df_unique.drop_duplicates(subset=["X" ,"Y"])
df_unique

,X,Y,UD,LD,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM%,Ranges
0,-0.094551,35.786824,0.0,5.0,7.110377,6.404642,7.311231,12.333685,18.140976,74.547794,0.893930,2.306617,0.533126,0_5
6,-0.094682,35.783222,0.0,5.0,7.576187,6.028645,8.795516,4.101079,7.912891,83.291593,0.000000,2.247701,0.567299,0_5
12,-0.094814,35.779620,0.0,5.0,7.557264,5.292950,6.339849,4.232644,23.833469,69.783936,1.329243,2.392225,0.745866,0_5
18,-0.094945,35.776018,0.0,5.0,7.668368,3.400624,3.270652,14.641522,50.034298,46.695050,2.763003,2.696493,0.676091,0_5
24,-0.095076,35.772417,0.0,5.0,7.051867,2.440479,1.517456,9.439977,39.378934,59.103610,3.200028,3.605780,0.653315,0_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3156,7.698333,36.781111,0.0,5.0,8.299528,383.853774,30.381132,0.099906,38.016981,27.490613,0.224196,0.000000,1.004885,0_5
3162,7.992500,36.848611,0.0,5.0,5.687539,28.007083,4.610997,0.121828,26.872473,68.516530,1.761085,2.698702,48.783917,0_5
3168,8.200000,36.900000,0.0,5.0,5.614928,23.527257,3.171597,0.100015,42.066458,54.761945,2.579962,2.843597,34.722968,0_5
3174,8.386667,37.064444,0.0,5.0,5.094341,27.049788,12.245741,0.100000,24.879419,62.874878,0.708640,1.635620,27.972723,0_5
3180,8.414167,37.094722,0.0,5.0,6.155947,28.007083,6.124133,0.100000,24.729042,69.146825,1.396141,2.424040,11.010841,0_5

In [62]:
def latlon_to_pixel(lat, lon, dataset ,transform):
    # Validate if the coordinate is within the image bounds
    print(dataset.bounds.left , lat , dataset.bounds.right)
    print(dataset.bounds.bottom , lon , dataset.bounds.top)

    if not (dataset.bounds.left <= lat <= dataset.bounds.right and
            dataset.bounds.bottom <= lon <= dataset.bounds.top):
        lat -=0.1
        lon -=0.1
    # Convert to pixel row & column
    row, col = rowcol(dataset.transform, lon, lat)
    return row, col

In [63]:
# windows Forming  for full one file (nefthou el file mera brk)
def window_forming(raster_path, df, height=15, width=15 , var=None):
    covariable_files = os.listdir(raster_path)
    covariable_num = len(covariable_files)

    datasets = [rasterio.open(os.path.join(raster_path, fname)) for fname in covariable_files]
    transforms = [ds.transform for ds in datasets]
    print(len(datasets))
    windows = []
    mid = height // 2

    for i in range(len(df)):
        print(f"Processing point {i}")
        lat = df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]
        window = np.empty((height, width, covariable_num))

        for idx, src in enumerate(datasets):
            transform = transforms[idx] 
            pixel_y, pixel_x = latlon_to_pixel(lat, lon, src, transform)
            print(src.crs)
            print(src.res)
            try:
                win = Window(pixel_x - mid, pixel_y - mid, width, height)
                data = src.read(1, window=win)
                window[:, :, idx] = data

            except Exception as e:
                print(f"Error at point {i}, covariable {idx}")
                print(e)
                window[:, :, idx] = np.nan  # Fill with NaNs on failure

        windows.append(window)

    for ds in datasets:
        ds.close()

    return windows

In [64]:
# for devided tiff files 
def window_forming2(raster_path  , df ,height=15 , width=15 ):
    covariable_num = 1
    windows = []

    for i in range(len(df)) :
        print(f"the dataset is in : {i}") 
        lat =  df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]
        window = np.empty((height, width, covariable_num))
        for index , j in enumerate(os.listdir(raster_path)):
            with rasterio.open(f"{raster_path}/{j}") as src :
                raster_data = src.read()
                transform = src.transform 
            try : 
                pixel_x ,pixel_y = latlon_to_pixel(lat , lon , src , transform)
                mid = height//2
                window[:,:,index] = raster_data[ 0 , pixel_x - mid : pixel_x + mid +1 , pixel_y - mid : pixel_y + mid +1 ]
                break 
            except Exception as e:
                print("can'found in ")
                continue 
        windows.append(window)
    return windows

In [65]:
def window_forming3(all_files  , df ,height=15 , width=15 ):
    covariable_num = len(all_files)
    windows = []
    for i in range(len(df)) :
        print(f"the dataset is in : {i}") 
        lat =  df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]

        window = np.empty((height, width, covariable_num))

        for index , i in enumerate(all_files):
            raster_data = i.raster_data
            pixel_x ,pixel_y = latlon_to_pixel(lat , lon ,  i.src , i.transform)
            print(pixel_x , pixel_y)
            mid = height//2
            try : 
                window[:,:,index] = raster_data[ pixel_x - mid : pixel_x + mid +1 , pixel_y - mid : pixel_y + mid +1 ]
            except Exception as e:
                print("error is here ")
                print(e)
        windows.append(window)
    return windows

### 1.Climat

In [66]:
climat_window = window_forming("../Resampled/climat/" , df_unique)
climat_window = np.array(climat_window)
np.save("../Data_multi_CNN/climat.npy", climat_window)

6
Processing point 0
-180.0 -0.0945511623800001 180.0
-90.0 35.78682408 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-90.0 35.78682408 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-90.0 35.78682408 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-90.0 35.78682408 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-90.0 35.78682408 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-90.0 35.78682408 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 1
-180.0 -0.0946823495400002 180.0
-90.0 35.78322222 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-90.0 35.78322222 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-90.0 35.78322222 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-90.0 35.78322222 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-90.0 35.78322222 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-90.0 35.78322222 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 2
-180.0 -0.0948135134200001 180.0
-90.0 35.77962036 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-90.0 35.77962036 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-90.0 35.77962036 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-90.0 35.77962036 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-90.0 35.77962036 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-90.0 35.77962036 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 3
-180.0 -0.0949446540399998 180.0
-90.0 35.7760185 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-90.0 35.7760185 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-90.0 35.7760185 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-90.0 35.7760185 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-90.0 35.7760185 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-90.0 35.7760185 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 4
-180.0 -0.0950757713799999 180.0
-90.0 35.77241663 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-90.0 35.77241663 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-90.0 35.77241663 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-90.0 35.77241663 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-90.0 35.77241663 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-90.0 35.77241663 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 5
-180.0 -0.0952409953400001 180.0
-90.0 35.76878855 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-90.0 35.76878855 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-90.0 35.76878855 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-90.0 35.76878855 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-90.0 35.76878855 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-90.0 35.76878855 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 6
-180.0 -0.0989717369199998 180.0
-90.0 35.7869309 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-90.0 35.7869309 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-90.0 35.7869309 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-90.0 35.7869309 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-90.0 35.7869309 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-90.0 35.7869309 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 7
-180.0 -0.0991027251599998 180.0
-90.0 35.78332903 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-90.0 35.78332903 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-90.0 35.78332903 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-90.0 35.78332903 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-90.0 35.78332903 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-90.0 35.78332903 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 8
-180.0 -0.0992336901700001 180.0
-90.0 35.77972715 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-90.0 35.77972715 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-90.0 35.77972715 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-90.0 35.77972715 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-90.0 35.77972715 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-90.0 35.77972715 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 9
-180.0 -0.0993646319399998 180.0
-90.0 35.77612528 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-90.0 35.77612528 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-90.0 35.77612528 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-90.0 35.77612528 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-90.0 35.77612528 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-90.0 35.77612528 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 10
-180.0 -0.103523124 180.0
-90.0 35.78343567 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-90.0 35.78343567 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-90.0 35.78343567 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-90.0 35.78343567 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-90.0 35.78343567 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-90.0 35.78343567 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 11
-180.0 -0.1036538900999999 180.0
-90.0 35.77983378 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-90.0 35.77983378 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-90.0 35.77983378 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-90.0 35.77983378 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-90.0 35.77983378 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-90.0 35.77983378 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 12
-180.0 -0.1037846331 180.0
-90.0 35.77623189 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-90.0 35.77623189 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-90.0 35.77623189 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-90.0 35.77623189 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-90.0 35.77623189 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-90.0 35.77623189 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 13
-180.0 -0.1080741132999998 180.0
-90.0 35.77994025 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-90.0 35.77994025 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-90.0 35.77994025 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-90.0 35.77994025 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-90.0 35.77994025 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-90.0 35.77994025 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 14
-180.0 -0.1082046573999999 180.0
-90.0 35.77633834 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-90.0 35.77633834 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-90.0 35.77633834 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-90.0 35.77633834 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-90.0 35.77633834 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-90.0 35.77633834 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 15
-180.0 -0.421419637 180.0
-90.0 35.0443358 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-90.0 35.0443358 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-90.0 35.0443358 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-90.0 35.0443358 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-90.0 35.0443358 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-90.0 35.0443358 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 16
-180.0 -0.4215329289 180.0
-90.0 35.04073251 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-90.0 35.04073251 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-90.0 35.04073251 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-90.0 35.04073251 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-90.0 35.04073251 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-90.0 35.04073251 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 17
-180.0 -0.4346766278 180.0
-90.0 35.0410113 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-90.0 35.0410113 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-90.0 35.0410113 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-90.0 35.0410113 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-90.0 35.0410113 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-90.0 35.0410113 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 18
-180.0 -0.4347893238 180.0
-90.0 35.03740797 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-90.0 35.03740797 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-90.0 35.03740797 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-90.0 35.03740797 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-90.0 35.03740797 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-90.0 35.03740797 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 19
-180.0 -0.4390579008999999 180.0
-90.0 35.04110391 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-90.0 35.04110391 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-90.0 35.04110391 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-90.0 35.04110391 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-90.0 35.04110391 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-90.0 35.04110391 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 20
-180.0 -0.4434391939000002 180.0
-90.0 35.04119637 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-90.0 35.04119637 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-90.0 35.04119637 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-90.0 35.04119637 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-90.0 35.04119637 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-90.0 35.04119637 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 21
-180.0 -0.4435515058999999 180.0
-90.0 35.03759302 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-90.0 35.03759302 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-90.0 35.03759302 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-90.0 35.03759302 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-90.0 35.03759302 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-90.0 35.03759302 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 22
-180.0 -0.4479326269000001 180.0
-90.0 35.0376853 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-90.0 35.0376853 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-90.0 35.0376853 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-90.0 35.0376853 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-90.0 35.0376853 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-90.0 35.0376853 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 23
-180.0 -0.4523137677000002 180.0
-90.0 35.03777743 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-90.0 35.03777743 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-90.0 35.03777743 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-90.0 35.03777743 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-90.0 35.03777743 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-90.0 35.03777743 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 24
-180.0 -0.4565831924000001 180.0
-90.0 35.04147279 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-90.0 35.04147279 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-90.0 35.04147279 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-90.0 35.04147279 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-90.0 35.04147279 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-90.0 35.04147279 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 25
-180.0 -0.4569183412000002 180.0
-90.0 35.03066262 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-90.0 35.03066262 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-90.0 35.03066262 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-90.0 35.03066262 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-90.0 35.03066262 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-90.0 35.03066262 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 26
-180.0 -0.4573091225999999 180.0
-90.0 35.01805072 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-90.0 35.01805072 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-90.0 35.01805072 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-90.0 35.01805072 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-90.0 35.01805072 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-90.0 35.01805072 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 27
-180.0 -0.4609645649999998 180.0
-90.0 35.04156462 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-90.0 35.04156462 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-90.0 35.04156462 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-90.0 35.04156462 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-90.0 35.04156462 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-90.0 35.04156462 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 28
-180.0 -0.4612991378999997 180.0
-90.0 35.0307544 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-90.0 35.0307544 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-90.0 35.0307544 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-90.0 35.0307544 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-90.0 35.0307544 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-90.0 35.0307544 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 29
-180.0 -0.4616892478999999 180.0
-90.0 35.01814246 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4616892478999999 180.0
-90.0 35.01814246 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4616892478999999 180.0
-90.0 35.01814246 90.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)

In [67]:
climat_window.shape

(531, 15, 15, 6)

### 2. organisme

In [68]:
organisme = window_forming("../Resampled/organisme/" , df_unique)
organisme = np.array(organisme)
print(organisme.shape)
np.save("../Data_multi_CNN/organisme.npy", organisme)

20
Processing point 0
-179.999948976711 -0.0945511623800001 179.84350768202054
-89.04039831914453 35.78682408 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.999948976711 -0.0945511623800001 179.84350768202054
-89.04039831914453 35.78682408 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-180.0 -0.0945511623800001 179.9985600001673
-90.0 35.78682408 89.99928000008367
EPSG:4326
(0.008333492904932228, 0.008333685818791781)
-179.999948976711 -0.0945511623800001 179.84350768202054
-89.04039831914453 35.78682408 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.99999991978757 -0.0945511623800001 179.9971167959036
-60.000802620970376 35.78682408 83.64317286591495
EPSG:4326
(0.008333459494795971, 0.008333467278928197)
-180.0 -0.0945511623800001 179.9999985600001
-90.00000000000006 35.78682408 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0945511623800001 179.9999985600001
-90.00000000000006 35.78682408 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0945511623800001 179.9999985600001
-90.00000000000006 35.78682408 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0945511623800001 179.9999985600001
-90.00000000000006 35.78682408 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0945511623800001 180.00000000000003
-56.000000000000014 35.78682408 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
Processing point 1
-179.999948976711 -0.0946823495400002 179.84350768202054
-89.04039831914453 35.78322222 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.999948976711 -0.0946823495400002 179.84350768202054
-89.04039831914453 35.78322222 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-180.0 -0.0946823495400002 179.9985600001673
-90.0 35.78322222 89.99928000008367
EPSG:4326
(0.008333492904932228, 0.008333685818791781)
-179.999948976711 -0.0946823495400002 179.84350768202054
-89.04039831914453 35.78322222 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.99999991978757 -0.0946823495400002 179.9971167959036
-60.000802620970376 35.78322222 83.64317286591495
EPSG:4326
(0.008333459494795971, 0.008333467278928197)
-180.0 -0.0946823495400002 179.9999985600001
-90.00000000000006 35.78322222 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0946823495400002 179.9999985600001
-90.00000000000006 35.78322222 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0946823495400002 179.9999985600001
-90.00000000000006 35.78322222 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0946823495400002 179.9999985600001
-90.00000000000006 35.78322222 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0946823495400002 180.00000000000003
-56.000000000000014 35.78322222 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
Processing point 2
-179.999948976711 -0.0948135134200001 179.84350768202054
-89.04039831914453 35.77962036 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.999948976711 -0.0948135134200001 179.84350768202054
-89.04039831914453 35.77962036 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-180.0 -0.0948135134200001 179.9985600001673
-90.0 35.77962036 89.99928000008367
EPSG:4326
(0.008333492904932228, 0.008333685818791781)
-179.999948976711 -0.0948135134200001 179.84350768202054
-89.04039831914453 35.77962036 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.99999991978757 -0.0948135134200001 179.9971167959036
-60.000802620970376 35.77962036 83.64317286591495
EPSG:4326
(0.008333459494795971, 0.008333467278928197)
-180.0 -0.0948135134200001 179.9999985600001
-90.00000000000006 35.77962036 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0948135134200001 179.9999985600001
-90.00000000000006 35.77962036 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0948135134200001 179.9999985600001
-90.00000000000006 35.77962036 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0948135134200001 179.9999985600001
-90.00000000000006 35.77962036 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0948135134200001 180.00000000000003
-56.000000000000014 35.77962036 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
Processing point 3
-179.999948976711 -0.0949446540399998 179.84350768202054
-89.04039831914453 35.7760185 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.999948976711 -0.0949446540399998 179.84350768202054
-89.04039831914453 35.7760185 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-180.0 -0.0949446540399998 179.9985600001673
-90.0 35.7760185 89.99928000008367
EPSG:4326
(0.008333492904932228, 0.008333685818791781)
-179.999948976711 -0.0949446540399998 179.84350768202054
-89.04039831914453 35.7760185 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.99999991978757 -0.0949446540399998 179.9971167959036
-60.000802620970376 35.7760185 83.64317286591495
EPSG:4326
(0.008333459494795971, 0.008333467278928197)
-180.0 -0.0949446540399998 179.9999985600001
-90.00000000000006 35.7760185 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0949446540399998 179.9999985600001
-90.00000000000006 35.7760185 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0949446540399998 179.9999985600001
-90.00000000000006 35.7760185 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0949446540399998 179.9999985600001
-90.00000000000006 35.7760185 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0949446540399998 180.00000000000003
-56.000000000000014 35.7760185 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
Processing point 4
-179.999948976711 -0.0950757713799999 179.84350768202054
-89.04039831914453 35.77241663 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.999948976711 -0.0950757713799999 179.84350768202054
-89.04039831914453 35.77241663 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-180.0 -0.0950757713799999 179.9985600001673
-90.0 35.77241663 89.99928000008367
EPSG:4326
(0.008333492904932228, 0.008333685818791781)
-179.999948976711 -0.0950757713799999 179.84350768202054
-89.04039831914453 35.77241663 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.99999991978757 -0.0950757713799999 179.9971167959036
-60.000802620970376 35.77241663 83.64317286591495
EPSG:4326
(0.008333459494795971, 0.008333467278928197)
-180.0 -0.0950757713799999 179.9999985600001
-90.00000000000006 35.77241663 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0950757713799999 179.9999985600001
-90.00000000000006 35.77241663 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0950757713799999 179.9999985600001
-90.00000000000006 35.77241663 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0950757713799999 179.9999985600001
-90.00000000000006 35.77241663 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0950757713799999 180.00000000000003
-56.000000000000014 35.77241663 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
Processing point 5
-179.999948976711 -0.0952409953400001 179.84350768202054
-89.04039831914453 35.76878855 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.999948976711 -0.0952409953400001 179.84350768202054
-89.04039831914453 35.76878855 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-180.0 -0.0952409953400001 179.9985600001673
-90.0 35.76878855 89.99928000008367
EPSG:4326
(0.008333492904932228, 0.008333685818791781)
-179.999948976711 -0.0952409953400001 179.84350768202054
-89.04039831914453 35.76878855 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.99999991978757 -0.0952409953400001 179.9971167959036
-60.000802620970376 35.76878855 83.64317286591495
EPSG:4326
(0.008333459494795971, 0.008333467278928197)
-180.0 -0.0952409953400001 179.9999985600001
-90.00000000000006 35.76878855 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0952409953400001 179.9999985600001
-90.00000000000006 35.76878855 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0952409953400001 179.9999985600001
-90.00000000000006 35.76878855 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.0 -0.0952409953400001 179.9999985600001
-90.00000000000006 35.76878855 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
-180.00000000000003 -0.0952409953400001 180.00000000000003
-56.000000000000014 35.76878855 90.00000000000001
EPSG:4326
(0.008333333333333335, 0.008333333333333335)
Processing point 6
-179.999948976711 -0.0989717369199998 179.84350768202054
-89.04039831914453 35.7869309 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.999948976711 -0.0989717369199998 179.84350768202054
-89.04039831914453 35.7869309 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-180.0 -0.0989717369199998 179.9985600001673
-90.0 35.7869309 89.99928000008367
EPSG:4326
(0.008333492904932228, 0.008333685818791781)
-179.999948976711 -0.0989717369199998 179.84350768202054
-89.04039831914453 35.7869309 83.88685421908791
EPSG:4326
(0.008333374786566582, 0.008333441884161363)
-179.99999991978757 -0.0989717369199998 179.9971167959036
-60.000802620970376 35.7869309 83.64317286591495
EPSG:4326
(0.008333459494795971, 0.008333467278928197)
-180.0 -0.0989717369199998 179.9999985600001
-90.00000000000006 35.7869309 89.99999928
EPSG:4326
(0.008333333300000002, 0.008333333300000002)

### 3. relief

In [69]:
relief = window_forming("../Resampled/relief/" , df_unique)
relief = np.array(relief)
print(relief.shape)
np.save("../Data_multi_CNN/relief.npy", relief)

6
Processing point 0
-180.0 -0.0945511623800001 180.0
-56.0 35.78682408 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-56.0 35.78682408 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-56.0 35.78682408 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-56.0 35.78682408 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-56.0 35.78682408 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0945511623800001 180.0
-56.0 35.78682408 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 1
-180.0 -0.0946823495400002 180.0
-56.0 35.78322222 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-56.0 35.78322222 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-56.0 35.78322222 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-56.0 35.78322222 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-56.0 35.78322222 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0946823495400002 180.0
-56.0 35.78322222 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 2
-180.0 -0.0948135134200001 180.0
-56.0 35.77962036 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-56.0 35.77962036 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-56.0 35.77962036 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-56.0 35.77962036 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-56.0 35.77962036 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0948135134200001 180.0
-56.0 35.77962036 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 3
-180.0 -0.0949446540399998 180.0
-56.0 35.7760185 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-56.0 35.7760185 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-56.0 35.7760185 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-56.0 35.7760185 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-56.0 35.7760185 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0949446540399998 180.0
-56.0 35.7760185 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 4
-180.0 -0.0950757713799999 180.0
-56.0 35.77241663 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-56.0 35.77241663 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-56.0 35.77241663 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-56.0 35.77241663 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-56.0 35.77241663 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0950757713799999 180.0
-56.0 35.77241663 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 5
-180.0 -0.0952409953400001 180.0
-56.0 35.76878855 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-56.0 35.76878855 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-56.0 35.76878855 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-56.0 35.76878855 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-56.0 35.76878855 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0952409953400001 180.0
-56.0 35.76878855 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 6
-180.0 -0.0989717369199998 180.0
-56.0 35.7869309 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-56.0 35.7869309 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-56.0 35.7869309 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-56.0 35.7869309 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-56.0 35.7869309 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0989717369199998 180.0
-56.0 35.7869309 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 7
-180.0 -0.0991027251599998 180.0
-56.0 35.78332903 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-56.0 35.78332903 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-56.0 35.78332903 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-56.0 35.78332903 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-56.0 35.78332903 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0991027251599998 180.0
-56.0 35.78332903 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 8
-180.0 -0.0992336901700001 180.0
-56.0 35.77972715 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-56.0 35.77972715 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-56.0 35.77972715 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-56.0 35.77972715 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-56.0 35.77972715 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0992336901700001 180.0
-56.0 35.77972715 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 9
-180.0 -0.0993646319399998 180.0
-56.0 35.77612528 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-56.0 35.77612528 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-56.0 35.77612528 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-56.0 35.77612528 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-56.0 35.77612528 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.0993646319399998 180.0
-56.0 35.77612528 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 10
-180.0 -0.103523124 180.0
-56.0 35.78343567 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-56.0 35.78343567 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-56.0 35.78343567 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-56.0 35.78343567 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-56.0 35.78343567 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.103523124 180.0
-56.0 35.78343567 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 11
-180.0 -0.1036538900999999 180.0
-56.0 35.77983378 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-56.0 35.77983378 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-56.0 35.77983378 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-56.0 35.77983378 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-56.0 35.77983378 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1036538900999999 180.0
-56.0 35.77983378 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 12
-180.0 -0.1037846331 180.0
-56.0 35.77623189 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-56.0 35.77623189 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-56.0 35.77623189 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-56.0 35.77623189 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-56.0 35.77623189 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1037846331 180.0
-56.0 35.77623189 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 13
-180.0 -0.1080741132999998 180.0
-56.0 35.77994025 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-56.0 35.77994025 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-56.0 35.77994025 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-56.0 35.77994025 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-56.0 35.77994025 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1080741132999998 180.0
-56.0 35.77994025 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 14
-180.0 -0.1082046573999999 180.0
-56.0 35.77633834 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-56.0 35.77633834 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-56.0 35.77633834 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-56.0 35.77633834 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-56.0 35.77633834 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.1082046573999999 180.0
-56.0 35.77633834 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 15
-180.0 -0.421419637 180.0
-56.0 35.0443358 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-56.0 35.0443358 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-56.0 35.0443358 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-56.0 35.0443358 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-56.0 35.0443358 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.421419637 180.0
-56.0 35.0443358 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 16
-180.0 -0.4215329289 180.0
-56.0 35.04073251 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-56.0 35.04073251 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-56.0 35.04073251 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-56.0 35.04073251 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-56.0 35.04073251 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4215329289 180.0
-56.0 35.04073251 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 17
-180.0 -0.4346766278 180.0
-56.0 35.0410113 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-56.0 35.0410113 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-56.0 35.0410113 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-56.0 35.0410113 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-56.0 35.0410113 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4346766278 180.0
-56.0 35.0410113 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 18
-180.0 -0.4347893238 180.0
-56.0 35.03740797 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-56.0 35.03740797 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-56.0 35.03740797 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-56.0 35.03740797 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-56.0 35.03740797 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4347893238 180.0
-56.0 35.03740797 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 19
-180.0 -0.4390579008999999 180.0
-56.0 35.04110391 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-56.0 35.04110391 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-56.0 35.04110391 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-56.0 35.04110391 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-56.0 35.04110391 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4390579008999999 180.0
-56.0 35.04110391 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 20
-180.0 -0.4434391939000002 180.0
-56.0 35.04119637 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-56.0 35.04119637 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-56.0 35.04119637 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-56.0 35.04119637 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-56.0 35.04119637 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4434391939000002 180.0
-56.0 35.04119637 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 21
-180.0 -0.4435515058999999 180.0
-56.0 35.03759302 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-56.0 35.03759302 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-56.0 35.03759302 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-56.0 35.03759302 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-56.0 35.03759302 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4435515058999999 180.0
-56.0 35.03759302 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 22
-180.0 -0.4479326269000001 180.0
-56.0 35.0376853 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-56.0 35.0376853 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-56.0 35.0376853 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-56.0 35.0376853 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-56.0 35.0376853 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4479326269000001 180.0
-56.0 35.0376853 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 23
-180.0 -0.4523137677000002 180.0
-56.0 35.03777743 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-56.0 35.03777743 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-56.0 35.03777743 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-56.0 35.03777743 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-56.0 35.03777743 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4523137677000002 180.0
-56.0 35.03777743 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 24
-180.0 -0.4565831924000001 180.0
-56.0 35.04147279 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-56.0 35.04147279 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-56.0 35.04147279 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-56.0 35.04147279 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-56.0 35.04147279 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4565831924000001 180.0
-56.0 35.04147279 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 25
-180.0 -0.4569183412000002 180.0
-56.0 35.03066262 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-56.0 35.03066262 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-56.0 35.03066262 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-56.0 35.03066262 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-56.0 35.03066262 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4569183412000002 180.0
-56.0 35.03066262 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 26
-180.0 -0.4573091225999999 180.0
-56.0 35.01805072 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-56.0 35.01805072 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-56.0 35.01805072 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-56.0 35.01805072 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-56.0 35.01805072 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4573091225999999 180.0
-56.0 35.01805072 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 27
-180.0 -0.4609645649999998 180.0
-56.0 35.04156462 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-56.0 35.04156462 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-56.0 35.04156462 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-56.0 35.04156462 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-56.0 35.04156462 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4609645649999998 180.0
-56.0 35.04156462 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 28
-180.0 -0.4612991378999997 180.0
-56.0 35.0307544 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-56.0 35.0307544 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-56.0 35.0307544 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-56.0 35.0307544 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-56.0 35.0307544 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4612991378999997 180.0
-56.0 35.0307544 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
Processing point 29
-180.0 -0.4616892478999999 180.0
-56.0 35.01814246 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4616892478999999 180.0
-56.0 35.01814246 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)
-180.0 -0.4616892478999999 180.0
-56.0 35.01814246 84.0
EPSG:4326
(0.008333333333333333, 0.008333333333333333)

### 4. Spatial Position

In [70]:
landuse_windo = window_forming2("../Resampled/Spatial_position/" , df_unique)
np.array(landuse_windo).shape

the dataset is in : 0
0.0 -0.0945511623800001 10.000000000000002
9.999999999999998 35.78682408 20.0
can'found in
10.0 -0.0945511623800001 20.0
9.999999999999998 35.78682408 20.0
can'found in
-10.0 -0.0945511623800001 1.7763568394002505e-15
9.999999999999998 35.78682408 20.0
can'found in
0.0 -0.0945511623800001 10.000000000000002
20.0 35.78682408 30.0
can'found in
10.0 -0.0945511623800001 20.0
20.0 35.78682408 30.0
can'found in
-10.0 -0.0945511623800001 1.7763568394002505e-15
20.0 35.78682408 30.0
can'found in
-20.0 -0.0945511623800001 -9.999999999999998
20.0 35.78682408 30.0
can'found in
0.0 -0.0945511623800001 10.000000000000002
30.0 35.78682408 40.0
can'found in
-10.0 -0.0945511623800001 1.7763568394002505e-15
30.0 35.78682408 40.0
can'found in
the dataset is in : 1
0.0 -0.0946823495400002 10.000000000000002
9.999999999999998 35.78322222 20.0
can'found in
10.0 -0.0946823495400002 20.0
9.999999999999998 35.78322222 20.0
can'found in
-10.0 -0.0946823495400002 1.7763568394002505e-15
9.999999999999998 35.78322222 20.0
can'found in
0.0 -0.0946823495400002 10.000000000000002
20.0 35.78322222 30.0
can'found in
10.0 -0.0946823495400002 20.0
20.0 35.78322222 30.0
can'found in
-10.0 -0.0946823495400002 1.7763568394002505e-15
20.0 35.78322222 30.0
can'found in
-20.0 -0.0946823495400002 -9.999999999999998
20.0 35.78322222 30.0
can'found in
0.0 -0.0946823495400002 10.000000000000002
30.0 35.78322222 40.0
can'found in
-10.0 -0.0946823495400002 1.7763568394002505e-15
30.0 35.78322222 40.0
can'found in
the dataset is in : 2
0.0 -0.0948135134200001 10.000000000000002
9.999999999999998 35.77962036 20.0
can'found in
10.0 -0.0948135134200001 20.0
9.999999999999998 35.77962036 20.0
can'found in
-10.0 -0.0948135134200001 1.7763568394002505e-15
9.999999999999998 35.77962036 20.0
can'found in
0.0 -0.0948135134200001 10.000000000000002
20.0 35.77962036 30.0
can'found in
10.0 -0.0948135134200001 20.0
20.0 35.77962036 30.0
can'found in
-10.0 -0.0948135134200001 1.7763568394002505e-15
20.0 35.77962036 30.0
can'found in
-20.0 -0.0948135134200001 -9.999999999999998
20.0 35.77962036 30.0
can'found in
0.0 -0.0948135134200001 10.000000000000002
30.0 35.77962036 40.0
can'found in
-10.0 -0.0948135134200001 1.7763568394002505e-15
30.0 35.77962036 40.0
can'found in
the dataset is in : 3
0.0 -0.0949446540399998 10.000000000000002
9.999999999999998 35.7760185 20.0
can'found in
10.0 -0.0949446540399998 20.0
9.999999999999998 35.7760185 20.0
can'found in
-10.0 -0.0949446540399998 1.7763568394002505e-15
9.999999999999998 35.7760185 20.0
can'found in
0.0 -0.0949446540399998 10.000000000000002
20.0 35.7760185 30.0
can'found in
10.0 -0.0949446540399998 20.0
20.0 35.7760185 30.0
can'found in
-10.0 -0.0949446540399998 1.7763568394002505e-15
20.0 35.7760185 30.0
can'found in
-20.0 -0.0949446540399998 -9.999999999999998
20.0 35.7760185 30.0
can'found in
0.0 -0.0949446540399998 10.000000000000002
30.0 35.7760185 40.0
can'found in
-10.0 -0.0949446540399998 1.7763568394002505e-15
30.0 35.7760185 40.0
can'found in
the dataset is in : 4
0.0 -0.0950757713799999 10.000000000000002
9.999999999999998 35.77241663 20.0
can'found in
10.0 -0.0950757713799999 20.0
9.999999999999998 35.77241663 20.0
can'found in
-10.0 -0.0950757713799999 1.7763568394002505e-15
9.999999999999998 35.77241663 20.0
can'found in
0.0 -0.0950757713799999 10.000000000000002
20.0 35.77241663 30.0
can'found in
10.0 -0.0950757713799999 20.0
20.0 35.77241663 30.0
can'found in
-10.0 -0.0950757713799999 1.7763568394002505e-15
20.0 35.77241663 30.0
can'found in
-20.0 -0.0950757713799999 -9.999999999999998
20.0 35.77241663 30.0
can'found in
0.0 -0.0950757713799999 10.000000000000002
30.0 35.77241663 40.0
can'found in
-10.0 -0.0950757713799999 1.7763568394002505e-15
30.0 35.77241663 40.0
can'found in
the dataset is in : 5
0.0 -0.0952409953400001 10.000000000000002
9.999999999999998 35.76878855 20.0
can'found in
10.0 -0.0952409953400001 20.0
9.999999999999998 35.76878855 20.0
can'found in
-10.0 -0.0952409953400001 1.7763568394002505e-15
9.999999999999998 35.76878855 20.0
can'found in
0.0 -0.0952409953400001 10.000000000000002
20.0 35.76878855 30.0
can'found in
10.0 -0.0952409953400001 20.0
20.0 35.76878855 30.0
can'found in
-10.0 -0.0952409953400001 1.7763568394002505e-15
20.0 35.76878855 30.0
can'found in
-20.0 -0.0952409953400001 -9.999999999999998
20.0 35.76878855 30.0
can'found in
0.0 -0.0952409953400001 10.000000000000002
30.0 35.76878855 40.0
can'found in
-10.0 -0.0952409953400001 1.7763568394002505e-15
30.0 35.76878855 40.0
can'found in
the dataset is in : 6
0.0 -0.0989717369199998 10.000000000000002
9.999999999999998 35.7869309 20.0
can'found in
10.0 -0.0989717369199998 20.0
9.999999999999998 35.7869309 20.0
can'found in
-10.0 -0.0989717369199998 1.7763568394002505e-15
9.999999999999998 35.7869309 20.0
can'found in
0.0 -0.0989717369199998 10.000000000000002
20.0 35.7869309 30.0
can'found in
10.0 -0.0989717369199998 20.0
20.0 35.7869309 30.0
can'found in
-10.0 -0.0989717369199998 1.7763568394002505e-15
20.0 35.7869309 30.0
can'found in
-20.0 -0.0989717369199998 -9.999999999999998
20.0 35.7869309 30.0
can'found in
0.0 -0.0989717369199998 10.000000000000002
30.0 35.7869309 40.0
can'found in
-10.0 -0.0989717369199998 1.7763568394002505e-15
30.0 35.7869309 40.0
can'found in
the dataset is in : 7
0.0 -0.0991027251599998 10.000000000000002
9.999999999999998 35.78332903 20.0
can'found in
10.0 -0.0991027251599998 20.0
9.999999999999998 35.78332903 20.0
can'found in
-10.0 -0.0991027251599998 1.7763568394002505e-15
9.999999999999998 35.78332903 20.0
can'found in
0.0 -0.0991027251599998 10.000000000000002
20.0 35.78332903 30.0
can'found in
10.0 -0.0991027251599998 20.0
20.0 35.78332903 30.0
can'found in
-10.0 -0.0991027251599998 1.7763568394002505e-15
20.0 35.78332903 30.0
can'found in
-20.0 -0.0991027251599998 -9.999999999999998
20.0 35.78332903 30.0
can'found in
0.0 -0.0991027251599998 10.000000000000002
30.0 35.78332903 40.0
can'found in
-10.0 -0.0991027251599998 1.7763568394002505e-15
30.0 35.78332903 40.0
can'found in
the dataset is in : 8
0.0 -0.0992336901700001 10.000000000000002
9.999999999999998 35.77972715 20.0
can'found in
10.0 -0.0992336901700001 20.0
9.999999999999998 35.77972715 20.0
can'found in
-10.0 -0.0992336901700001 1.7763568394002505e-15
9.999999999999998 35.77972715 20.0
can'found in
0.0 -0.0992336901700001 10.000000000000002
20.0 35.77972715 30.0
can'found in
10.0 -0.0992336901700001 20.0
20.0 35.77972715 30.0
can'found in
-10.0 -0.0992336901700001 1.7763568394002505e-15
20.0 35.77972715 30.0
can'found in
-20.0 -0.0992336901700001 -9.999999999999998
20.0 35.77972715 30.0
can'found in
0.0 -0.0992336901700001 10.000000000000002
30.0 35.77972715 40.0
can'found in
-10.0 -0.0992336901700001 1.7763568394002505e-15
30.0 35.77972715 40.0
can'found in
the dataset is in : 9
0.0 -0.0993646319399998 10.000000000000002
9.999999999999998 35.77612528 20.0
can'found in
10.0 -0.0993646319399998 20.0
9.999999999999998 35.77612528 20.0
can'found in
-10.0 -0.0993646319399998 1.7763568394002505e-15
9.999999999999998 35.77612528 20.0
can'found in
0.0 -0.0993646319399998 10.000000000000002
20.0 35.77612528 30.0
can'found in
10.0 -0.0993646319399998 20.0
20.0 35.77612528 30.0
can'found in
-10.0 -0.0993646319399998 1.7763568394002505e-15
20.0 35.77612528 30.0
can'found in
-20.0 -0.0993646319399998 -9.999999999999998
20.0 35.77612528 30.0
can'found in
0.0 -0.0993646319399998 10.000000000000002
30.0 35.77612528 40.0
can'found in
-10.0 -0.0993646319399998 1.7763568394002505e-15
30.0 35.77612528 40.0
can'found in
the dataset is in : 10
0.0 -0.103523124 10.000000000000002
9.999999999999998 35.78343567 20.0
can'found in
10.0 -0.103523124 20.0
9.999999999999998 35.78343567 20.0
can'found in
-10.0 -0.103523124 1.7763568394002505e-15
9.999999999999998 35.78343567 20.0
can'found in
0.0 -0.103523124 10.000000000000002
20.0 35.78343567 30.0
can'found in
10.0 -0.103523124 20.0
20.0 35.78343567 30.0
can'found in
-10.0 -0.103523124 1.7763568394002505e-15
20.0 35.78343567 30.0
can'found in
-20.0 -0.103523124 -9.999999999999998
20.0 35.78343567 30.0
can'found in
0.0 -0.103523124 10.000000000000002
30.0 35.78343567 40.0
can'found in
-10.0 -0.103523124 1.7763568394002505e-15
30.0 35.78343567 40.0
can'found in
the dataset is in : 11
0.0 -0.1036538900999999 10.000000000000002
9.999999999999998 35.77983378 20.0
can'found in
10.0 -0.1036538900999999 20.0
9.999999999999998 35.77983378 20.0
can'found in
-10.0 -0.1036538900999999 1.7763568394002505e-15
9.999999999999998 35.77983378 20.0
can'found in
0.0 -0.1036538900999999 10.000000000000002
20.0 35.77983378 30.0
can'found in
10.0 -0.1036538900999999 20.0
20.0 35.77983378 30.0
can'found in
-10.0 -0.1036538900999999 1.7763568394002505e-15
20.0 35.77983378 30.0
can'found in
-20.0 -0.1036538900999999 -9.999999999999998
20.0 35.77983378 30.0
can'found in
0.0 -0.1036538900999999 10.000000000000002
30.0 35.77983378 40.0
can'found in
-10.0 -0.1036538900999999 1.7763568394002505e-15
30.0 35.77983378 40.0
can'found in
the dataset is in : 12
0.0 -0.1037846331 10.000000000000002
9.999999999999998 35.77623189 20.0
can'found in
10.0 -0.1037846331 20.0
9.999999999999998 35.77623189 20.0
can'found in
-10.0 -0.1037846331 1.7763568394002505e-15
9.999999999999998 35.77623189 20.0
can'found in
0.0 -0.1037846331 10.000000000000002
20.0 35.77623189 30.0
can'found in
10.0 -0.1037846331 20.0
20.0 35.77623189 30.0
can'found in
-10.0 -0.1037846331 1.7763568394002505e-15
20.0 35.77623189 30.0
can'found in
-20.0 -0.1037846331 -9.999999999999998
20.0 35.77623189 30.0
can'found in
0.0 -0.1037846331 10.000000000000002
30.0 35.77623189 40.0
can'found in
-10.0 -0.1037846331 1.7763568394002505e-15
30.0 35.77623189 40.0
can'found in
the dataset is in : 13
0.0 -0.1080741132999998 10.000000000000002
9.999999999999998 35.77994025 20.0
can'found in
10.0 -0.1080741132999998 20.0
9.999999999999998 35.77994025 20.0
can'found in
-10.0 -0.1080741132999998 1.7763568394002505e-15
9.999999999999998 35.77994025 20.0
can'found in
0.0 -0.1080741132999998 10.000000000000002
20.0 35.77994025 30.0
can'found in
10.0 -0.1080741132999998 20.0
20.0 35.77994025 30.0
can'found in
-10.0 -0.1080741132999998 1.7763568394002505e-15
20.0 35.77994025 30.0
can'found in
-20.0 -0.1080741132999998 -9.999999999999998
20.0 35.77994025 30.0
can'found in
0.0 -0.1080741132999998 10.000000000000002
30.0 35.77994025 40.0
can'found in
-10.0 -0.1080741132999998 1.7763568394002505e-15
30.0 35.77994025 40.0
can'found in
the dataset is in : 14
0.0 -0.1082046573999999 10.000000000000002
9.999999999999998 35.77633834 20.0
can'found in
10.0 -0.1082046573999999 20.0
9.999999999999998 35.77633834 20.0
can'found in
-10.0 -0.1082046573999999 1.7763568394002505e-15
9.999999999999998 35.77633834 20.0
can'found in
0.0 -0.1082046573999999 10.000000000000002
20.0 35.77633834 30.0
can'found in
10.0 -0.1082046573999999 20.0
20.0 35.77633834 30.0
can'found in
-10.0 -0.1082046573999999 1.7763568394002505e-15
20.0 35.77633834 30.0
can'found in
-20.0 -0.1082046573999999 -9.999999999999998
20.0 35.77633834 30.0
can'found in
0.0 -0.1082046573999999 10.000000000000002
30.0 35.77633834 40.0
can'found in
-10.0 -0.1082046573999999 1.7763568394002505e-15
30.0 35.77633834 40.0
can'found in
the dataset is in : 15
0.0 -0.421419637 10.000000000000002
9.999999999999998 35.0443358 20.0
can'found in
10.0 -0.421419637 20.0
9.999999999999998 35.0443358 20.0
can'found in
-10.0 -0.421419637 1.7763568394002505e-15
9.999999999999998 35.0443358 20.0
can'found in
0.0 -0.421419637 10.000000000000002
20.0 35.0443358 30.0
can'found in
10.0 -0.421419637 20.0
20.0 35.0443358 30.0
can'found in
-10.0 -0.421419637 1.7763568394002505e-15
20.0 35.0443358 30.0
can'found in
-20.0 -0.421419637 -9.999999999999998
20.0 35.0443358 30.0
can'found in
0.0 -0.421419637 10.000000000000002
30.0 35.0443358 40.0
can'found in
-10.0 -0.421419637 1.7763568394002505e-15
30.0 35.0443358 40.0
can'found in
the dataset is in : 16
0.0 -0.4215329289 10.000000000000002
9.999999999999998 35.04073251 20.0
can'found in
10.0 -0.4215329289 20.0
9.999999999999998 35.04073251 20.0
can'found in
-10.0 -0.4215329289 1.7763568394002505e-15
9.999999999999998 35.04073251 20.0
can'found in
0.0 -0.4215329289 10.000000000000002
20.0 35.04073251 30.0
can'found in
10.0 -0.4215329289 20.0
20.0 35.04073251 30.0
can'found in
-10.0 -0.4215329289 1.7763568394002505e-15
20.0 35.04073251 30.0
can'found in
-20.0 -0.4215329289 -9.999999999999998
20.0 35.04073251 30.0
can'found in
0.0 -0.4215329289 10.000000000000002
30.0 35.04073251 40.0
can'found in
-10.0 -0.4215329289 1.7763568394002505e-15
30.0 35.04073251 40.0
can'found in
the dataset is in : 17
0.0 -0.4346766278 10.000000000000002
9.999999999999998 35.0410113 20.0
can'found in
10.0 -0.4346766278 20.0
9.999999999999998 35.0410113 20.0
can'found in
-10.0 -0.4346766278 1.7763568394002505e-15
9.999999999999998 35.0410113 20.0
can'found in
0.0 -0.4346766278 10.000000000000002
20.0 35.0410113 30.0
can'found in
10.0 -0.4346766278 20.0
20.0 35.0410113 30.0
can'found in
-10.0 -0.4346766278 1.7763568394002505e-15
20.0 35.0410113 30.0
can'found in
-20.0 -0.4346766278 -9.999999999999998
20.0 35.0410113 30.0
can'found in
0.0 -0.4346766278 10.000000000000002
30.0 35.0410113 40.0
can'found in
-10.0 -0.4346766278 1.7763568394002505e-15
30.0 35.0410113 40.0
can'found in
the dataset is in : 18
0.0 -0.4347893238 10.000000000000002
9.999999999999998 35.03740797 20.0
can'found in
10.0 -0.4347893238 20.0
9.999999999999998 35.03740797 20.0
can'found in
-10.0 -0.4347893238 1.7763568394002505e-15
9.999999999999998 35.03740797 20.0
can'found in
0.0 -0.4347893238 10.000000000000002
20.0 35.03740797 30.0
can'found in
10.0 -0.4347893238 20.0
20.0 35.03740797 30.0
can'found in
-10.0 -0.4347893238 1.7763568394002505e-15
20.0 35.03740797 30.0
can'found in
-20.0 -0.4347893238 -9.999999999999998
20.0 35.03740797 30.0
can'found in
0.0 -0.4347893238 10.000000000000002
30.0 35.03740797 40.0
can'found in
-10.0 -0.4347893238 1.7763568394002505e-15
30.0 35.03740797 40.0
can'found in
the dataset is in : 19
0.0 -0.4390579008999999 10.000000000000002
9.999999999999998 35.04110391 20.0
can'found in
10.0 -0.4390579008999999 20.0
9.999999999999998 35.04110391 20.0
can'found in
-10.0 -0.4390579008999999 1.7763568394002505e-15
9.999999999999998 35.04110391 20.0
can'found in
0.0 -0.4390579008999999 10.000000000000002
20.0 35.04110391 30.0
can'found in
10.0 -0.4390579008999999 20.0
20.0 35.04110391 30.0
can'found in
-10.0 -0.4390579008999999 1.7763568394002505e-15
20.0 35.04110391 30.0
can'found in
-20.0 -0.4390579008999999 -9.999999999999998
20.0 35.04110391 30.0
can'found in
0.0 -0.4390579008999999 10.000000000000002
30.0 35.04110391 40.0
can'found in
-10.0 -0.4390579008999999 1.7763568394002505e-15
30.0 35.04110391 40.0
can'found in
the dataset is in : 20
0.0 -0.4434391939000002 10.000000000000002
9.999999999999998 35.04119637 20.0
can'found in
10.0 -0.4434391939000002 20.0
9.999999999999998 35.04119637 20.0
can'found in
-10.0 -0.4434391939000002 1.7763568394002505e-15
9.999999999999998 35.04119637 20.0
can'found in
0.0 -0.4434391939000002 10.000000000000002
20.0 35.04119637 30.0
can'found in
10.0 -0.4434391939000002 20.0
20.0 35.04119637 30.0
can'found in
-10.0 -0.4434391939000002 1.7763568394002505e-15
20.0 35.04119637 30.0
can'found in
-20.0 -0.4434391939000002 -9.999999999999998
20.0 35.04119637 30.0
can'found in
0.0 -0.4434391939000002 10.000000000000002
30.0 35.04119637 40.0
can'found in
-10.0 -0.4434391939000002 1.7763568394002505e-15
30.0 35.04119637 40.0
can'found in
the dataset is in : 21
0.0 -0.4435515058999999 10.000000000000002
9.999999999999998 35.03759302 20.0
can'found in
10.0 -0.4435515058999999 20.0
9.999999999999998 35.03759302 20.0
can'found in
-10.0 -0.4435515058999999 1.7763568394002505e-15
9.999999999999998 35.03759302 20.0
can'found in
0.0 -0.4435515058999999 10.000000000000002
20.0 35.03759302 30.0
can'found in
10.0 -0.4435515058999999 20.0
20.0 35.03759302 30.0
can'found in
-10.0 -0.4435515058999999 1.7763568394002505e-15
20.0 35.03759302 30.0
can'found in
-20.0 -0.4435515058999999 -9.999999999999998
20.0 35.03759302 30.0
can'found in
0.0 -0.4435515058999999 10.000000000000002
30.0 35.03759302 40.0
can'found in
-10.0 -0.4435515058999999 1.7763568394002505e-15
30.0 35.03759302 40.0
can'found in
the dataset is in : 22
0.0 -0.4479326269000001 10.000000000000002
9.999999999999998 35.0376853 20.0
can'found in
10.0 -0.4479326269000001 20.0
9.999999999999998 35.0376853 20.0
can'found in
-10.0 -0.4479326269000001 1.7763568394002505e-15
9.999999999999998 35.0376853 20.0
can'found in
0.0 -0.4479326269000001 10.000000000000002
20.0 35.0376853 30.0
can'found in
10.0 -0.4479326269000001 20.0
20.0 35.0376853 30.0
can'found in
-10.0 -0.4479326269000001 1.7763568394002505e-15
20.0 35.0376853 30.0
can'found in
-20.0 -0.4479326269000001 -9.999999999999998
20.0 35.0376853 30.0
can'found in
0.0 -0.4479326269000001 10.000000000000002
30.0 35.0376853 40.0
can'found in
-10.0 -0.4479326269000001 1.7763568394002505e-15
30.0 35.0376853 40.0
can'found in
the dataset is in : 23
0.0 -0.4523137677000002 10.000000000000002
9.999999999999998 35.03777743 20.0
can'found in
10.0 -0.4523137677000002 20.0
9.999999999999998 35.03777743 20.0
can'found in
-10.0 -0.4523137677000002 1.7763568394002505e-15
9.999999999999998 35.03777743 20.0
can'found in
0.0 -0.4523137677000002 10.000000000000002
20.0 35.03777743 30.0
can'found in
10.0 -0.4523137677000002 20.0
20.0 35.03777743 30.0
can'found in
-10.0 -0.4523137677000002 1.7763568394002505e-15
20.0 35.03777743 30.0
can'found in
-20.0 -0.4523137677000002 -9.999999999999998
20.0 35.03777743 30.0
can'found in
0.0 -0.4523137677000002 10.000000000000002
30.0 35.03777743 40.0
can'found in
-10.0 -0.4523137677000002 1.7763568394002505e-15
30.0 35.03777743 40.0
can'found in
the dataset is in : 24
0.0 -0.4565831924000001 10.000000000000002
9.999999999999998 35.04147279 20.0
can'found in
10.0 -0.4565831924000001 20.0
9.999999999999998 35.04147279 20.0
can'found in
-10.0 -0.4565831924000001 1.7763568394002505e-15
9.999999999999998 35.04147279 20.0
can'found in
0.0 -0.4565831924000001 10.000000000000002
20.0 35.04147279 30.0
can'found in
10.0 -0.4565831924000001 20.0
20.0 35.04147279 30.0
can'found in
-10.0 -0.4565831924000001 1.7763568394002505e-15
20.0 35.04147279 30.0
can'found in
-20.0 -0.4565831924000001 -9.999999999999998
20.0 35.04147279 30.0
can'found in
0.0 -0.4565831924000001 10.000000000000002
30.0 35.04147279 40.0
can'found in
-10.0 -0.4565831924000001 1.7763568394002505e-15
30.0 35.04147279 40.0
can'found in
the dataset is in : 25
0.0 -0.4569183412000002 10.000000000000002
9.999999999999998 35.03066262 20.0
can'found in
10.0 -0.4569183412000002 20.0
9.999999999999998 35.03066262 20.0
can'found in
-10.0 -0.4569183412000002 1.7763568394002505e-15
9.999999999999998 35.03066262 20.0
can'found in
0.0 -0.4569183412000002 10.000000000000002
20.0 35.03066262 30.0
can'found in
10.0 -0.4569183412000002 20.0
20.0 35.03066262 30.0
can'found in
-10.0 -0.4569183412000002 1.7763568394002505e-15
20.0 35.03066262 30.0
can'found in
-20.0 -0.4569183412000002 -9.999999999999998
20.0 35.03066262 30.0
can'found in
0.0 -0.4569183412000002 10.000000000000002
30.0 35.03066262 40.0
can'found in
-10.0 -0.4569183412000002 1.7763568394002505e-15
30.0 35.03066262 40.0
can'found in
the dataset is in : 26
0.0 -0.4573091225999999 10.000000000000002
9.999999999999998 35.01805072 20.0
can'found in
10.0 -0.4573091225999999 20.0
9.999999999999998 35.01805072 20.0
can'found in
-10.0 -0.4573091225999999 1.7763568394002505e-15
9.999999999999998 35.01805072 20.0
can'found in
0.0 -0.4573091225999999 10.000000000000002
20.0 35.01805072 30.0
can'found in
10.0 -0.4573091225999999 20.0
20.0 35.01805072 30.0
can'found in
-10.0 -0.4573091225999999 1.7763568394002505e-15
20.0 35.01805072 30.0
can'found in
-20.0 -0.4573091225999999 -9.999999999999998
20.0 35.01805072 30.0
can'found in
0.0 -0.4573091225999999 10.000000000000002
30.0 35.01805072 40.0
can'found in

(531, 15, 15, 1)

In [71]:
def replace_nan_with_column_mean(data):
    data_filled = data.copy()
    for idx in range(data.shape[0]):  # for each matrix
        matrix = data_filled[idx, :, :, 0]  # shape (9, 9)
        nan_indices = np.argwhere(np.isnan(matrix))
        for i, j in nan_indices:
            # Get surrounding row indices (up and down)
            rows_to_consider = []
            if i > 0:
                rows_to_consider.append(matrix[i-1, j])
            if i < 8:
                rows_to_consider.append(matrix[i+1, j])
            # Remove NaNs from consideration
            rows_to_consider = [val for val in rows_to_consider if not np.isnan(val)]
            if rows_to_consider:
                matrix[i, j] = np.mean(rows_to_consider)
            else:
                matrix[i, j] = 0  # or some default if all neighbors are NaN
        data_filled[idx, :, :, 0] = matrix
    return data_filled

landuse_windo = replace_nan_with_column_mean(np.array(landuse_windo))

In [72]:
np.isnan(landuse_windo).sum()

0

In [73]:
np.save("../Data_multi_CNN/landuse.npy" , landuse_windo)

### 4. Parent Material

In [74]:
parent_window = window_forming("../Resampled/Parent_Material/", df_unique)
np.save("../Data_multi_CNN/Parent_Material.npy", parent_window)
np.array(parent_window).shape

1
Processing point 0
-22.4133525492225 -0.0945511623800001 64.54036521609329
-38.574875710885514 35.78682408 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 1
-22.4133525492225 -0.0946823495400002 64.54036521609329
-38.574875710885514 35.78322222 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 2
-22.4133525492225 -0.0948135134200001 64.54036521609329
-38.574875710885514 35.77962036 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 3
-22.4133525492225 -0.0949446540399998 64.54036521609329
-38.574875710885514 35.7760185 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 4
-22.4133525492225 -0.0950757713799999 64.54036521609329
-38.574875710885514 35.77241663 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 5
-22.4133525492225 -0.0952409953400001 64.54036521609329
-38.574875710885514 35.76878855 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 6
-22.4133525492225 -0.0989717369199998 64.54036521609329
-38.574875710885514 35.7869309 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 7
-22.4133525492225 -0.0991027251599998 64.54036521609329
-38.574875710885514 35.78332903 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 8
-22.4133525492225 -0.0992336901700001 64.54036521609329
-38.574875710885514 35.77972715 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 9
-22.4133525492225 -0.0993646319399998 64.54036521609329
-38.574875710885514 35.77612528 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 10
-22.4133525492225 -0.103523124 64.54036521609329
-38.574875710885514 35.78343567 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 11
-22.4133525492225 -0.1036538900999999 64.54036521609329
-38.574875710885514 35.77983378 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 12
-22.4133525492225 -0.1037846331 64.54036521609329
-38.574875710885514 35.77623189 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 13
-22.4133525492225 -0.1080741132999998 64.54036521609329
-38.574875710885514 35.77994025 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 14
-22.4133525492225 -0.1082046573999999 64.54036521609329
-38.574875710885514 35.77633834 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 15
-22.4133525492225 -0.421419637 64.54036521609329
-38.574875710885514 35.0443358 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 16
-22.4133525492225 -0.4215329289 64.54036521609329
-38.574875710885514 35.04073251 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 17
-22.4133525492225 -0.4346766278 64.54036521609329
-38.574875710885514 35.0410113 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 18
-22.4133525492225 -0.4347893238 64.54036521609329
-38.574875710885514 35.03740797 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 19
-22.4133525492225 -0.4390579008999999 64.54036521609329
-38.574875710885514 35.04110391 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 20
-22.4133525492225 -0.4434391939000002 64.54036521609329
-38.574875710885514 35.04119637 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 21
-22.4133525492225 -0.4435515058999999 64.54036521609329
-38.574875710885514 35.03759302 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 22
-22.4133525492225 -0.4479326269000001 64.54036521609329
-38.574875710885514 35.0376853 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 23
-22.4133525492225 -0.4523137677000002 64.54036521609329
-38.574875710885514 35.03777743 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 24
-22.4133525492225 -0.4565831924000001 64.54036521609329
-38.574875710885514 35.04147279 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 25
-22.4133525492225 -0.4569183412000002 64.54036521609329
-38.574875710885514 35.03066262 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 26
-22.4133525492225 -0.4573091225999999 64.54036521609329
-38.574875710885514 35.01805072 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 27
-22.4133525492225 -0.4609645649999998 64.54036521609329
-38.574875710885514 35.04156462 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 28
-22.4133525492225 -0.4612991378999997 64.54036521609329
-38.574875710885514 35.0307544 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 29
-22.4133525492225 -0.4616892478999999 64.54036521609329
-38.574875710885514 35.01814246 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 30
-22.4133525492225 -0.4653459572999998 64.54036521609329
-38.574875710885514 35.04165628 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 31
-22.4133525492225 -0.4654573094000001 64.54036521609329
-38.574875710885514 35.03805287 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 32
-22.4133525492225 -0.4656799544000001 64.54036521609329
-38.574875710885514 35.03084603 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 33
-22.4133525492225 -0.4698385296 64.54036521609329
-38.574875710885514 35.03814437 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 34
-22.4133525492225 -0.4742197693999999 64.54036521609329
-38.574875710885514 35.0382357 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 35
-22.4133525492225 -0.4744416466999999 64.54036521609329
-38.574875710885514 35.03102882 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 36
-22.4133525492225 -0.478601029 64.54036521609329
-38.574875710885514 35.03832688 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 37
-22.4133525492225 -0.4787117854999998 64.54036521609329
-38.574875710885514 35.03472343 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 38
-22.4133525492225 -0.4830928727999999 64.54036521609329
-38.574875710885514 35.03481444 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 39
-22.4133525492225 -0.4873636070999998 64.54036521609329
-38.574875710885514 35.03850877 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 40
-22.4133525492225 -0.4874739796999998 64.54036521609329
-38.574875710885514 35.03490529 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 41
-22.4133525492225 -0.4875843327 64.54036521609329
-38.574875710885514 35.03130181 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 42
-22.4133525492225 -0.4919652671999999 64.54036521609329
-38.574875710885514 35.0313925 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 43
-22.4133525492225 -0.4963462213 64.54036521609329
-38.574875710885514 35.03148302 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 44
-22.4133525492225 -0.4964561709000001 64.54036521609329
-38.574875710885514 35.02787952 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 45
-22.4133525492225 -0.5008369525999998 64.54036521609329
-38.574875710885514 35.02796987 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 46
-22.4133525492225 -1.0507943170000005 64.54036521609329
-38.574875710885514 29.21530985 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 47
-22.4133525492225 -1.05223529 64.54036521609329
-38.574875710885514 29.21851594 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 48
-22.4133525492225 -1.0536503229999998 64.54036521609329
-38.574875710885514 29.22201037 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 49
-22.4133525492225 -1.3627170249999998 64.54036521609329
-38.574875710885514 34.99381825 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 50
-22.4133525492225 -1.3671381510000002 64.54036521609329
-38.574875710885514 35.00113442 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 51
-22.4133525492225 -1.3709324379999996 64.54036521609329
-38.574875710885514 34.98638606 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 52
-22.4133525492225 -1.374775628 64.54036521609329
-38.574875710885514 34.97719384 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 53
-22.4133525492225 -1.3869694440000004 64.54036521609329
-38.574875710885514 35.12853333 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 54
-22.4133525492225 -1.3869000000000002 64.54036521609329
-38.574875710885514 35.13213889 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 55
-22.4133525492225 -1.3916388889999998 64.54036521609329
-38.574875710885514 35.12913889 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 56
-22.4133525492225 -1.398722222 64.54036521609329
-38.574875710885514 35.20081944 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 57
-22.4133525492225 -1.3988638890000002 64.54036521609329
-38.574875710885514 35.19360833 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 58
-22.4133525492225 -1.400277778 64.54036521609329
-38.574875710885514 35.12149722 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 59
-22.4133525492225 -1.401111111 64.54036521609329
-38.574875710885514 35.12558333 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 60
-22.4133525492225 -1.4030444440000005 64.54036521609329
-38.574875710885514 35.20448056 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 61
-22.4133525492225 -1.4031833329999994 64.54036521609329
-38.574875710885514 35.19726944 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 62
-22.4133525492225 -1.403255556 64.54036521609329
-38.574875710885514 35.19366667 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 63
-22.4133525492225 -1.4033055559999998 64.54036521609329
-38.574875710885514 35.20086111 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 64
-22.4133525492225 -1.4033972220000002 64.54036521609329
-38.574875710885514 35.18645556 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 65
-22.4133525492225 -1.4043833329999995 64.54036521609329
-38.574875710885514 35.13597778 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 66
-22.4133525492225 -1.4045 64.54036521609329
-38.574875710885514 35.13930556 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 67
-22.4133525492225 -1.4047861109999995 64.54036521609329
-38.574875710885514 35.16144722 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 68
-22.4133525492225 -1.407436111 64.54036521609329
-38.574875710885514 35.20453889 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 69
-22.4133525492225 -1.4075777779999998 64.54036521609329
-38.574875710885514 35.19732778 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 70
-22.4133525492225 -1.4076472219999996 64.54036521609329
-38.574875710885514 35.193725 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 71
-22.4133525492225 -1.4079305559999995 64.54036521609329
-38.574875710885514 35.17930278 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 72
-22.4133525492225 -1.4082805560000002 64.54036521609329
-38.574875710885514 35.161275 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 73
-22.4133525492225 -1.408422222 64.54036521609329
-38.574875710885514 35.15406389 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 74
-22.4133525492225 -1.4084444440000006 64.54036521609329
-38.574875710885514 35.13936111 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 75
-22.4133525492225 -1.4084916670000005 64.54036521609329
-38.574875710885514 35.15045833 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 76
-22.4133525492225 -1.4087722220000003 64.54036521609329
-38.574875710885514 35.13603611 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 77
-22.4133525492225 -1.4116888890000006 64.54036521609329
-38.574875710885514 35.21180833 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 78
-22.4133525492225 -1.4119694439999997 64.54036521609329
-38.574875710885514 35.19738611 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 79
-22.4133525492225 -1.4121805559999996 64.54036521609329
-38.574875710885514 35.18656944 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 80
-22.4133525492225 -1.412319444 64.54036521609329
-38.574875710885514 35.17935833 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 81
-22.4133525492225 -1.4130416669999994 64.54036521609329
-38.574875710885514 35.13606944 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 82
-22.4133525492225 -1.4131666669999996 64.54036521609329
-38.574875710885514 35.14691667 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 83
-22.4133525492225 -1.413372222 64.54036521609329
-38.574875710885514 35.12527778 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 84
-22.4133525492225 -1.416222222 64.54036521609329
-38.574875710885514 35.20465556 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 85
-22.4133525492225 -1.416363889 64.54036521609329
-38.574875710885514 35.19744444 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 86
-22.4133525492225 -1.4164333329999996 64.54036521609329
-38.574875710885514 35.19383889 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 87
-22.4133525492225 -1.4167111110000006 64.54036521609329
-38.574875710885514 35.17941667 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 88
-22.4133525492225 -1.417130556 64.54036521609329
-38.574875710885514 35.15778333 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 89
-22.4133525492225 -1.4172694440000004 64.54036521609329
-38.574875710885514 35.15057222 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 90
-22.4133525492225 -1.420416667 64.54036521609329
-38.574875710885514 35.20461111 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 91
-22.4133525492225 -1.4204750000000006 64.54036521609329
-38.574875710885514 35.21192222 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 92
-22.4133525492225 -1.420683333 64.54036521609329
-38.574875710885514 35.20110556 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 93
-22.4133525492225 -1.420811111 64.54036521609329
-38.574875710885514 35.19379444 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 94
-22.4133525492225 -1.4211750000000007 64.54036521609329
-38.574875710885514 35.17586944 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 95
-22.4133525492225 -1.4215222219999992 64.54036521609329
-38.574875710885514 35.15784167 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 96
-22.4133525492225 -1.421661111 64.54036521609329
-38.574875710885514 35.15063056 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 97
-22.4133525492225 -1.425077778 64.54036521609329
-38.574875710885514 35.20116389 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 98
-22.4133525492225 -1.425355556 64.54036521609329
-38.574875710885514 35.18674167 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 99
-22.4133525492225 -1.425361111 64.54036521609329
-38.574875710885514 35.17938889 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 100
-22.4133525492225 -1.4254250000000002 64.54036521609329
-38.574875710885514 35.18313611 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 101
-22.4133525492225 -1.4257500000000003 64.54036521609329
-38.574875710885514 35.176 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 102
-22.4133525492225 -1.4265361110000003 64.54036521609329
-38.574875710885514 35.12544722 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 103
-22.4133525492225 -1.4294722219999998 64.54036521609329
-38.574875710885514 35.18708333 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 104
-22.4133525492225 -1.4298166670000003 64.54036521609329
-38.574875710885514 35.18319444 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 105
-22.4133525492225 -1.4309249999999991 64.54036521609329
-38.574875710885514 35.12550556 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 106
-22.4133525492225 -1.4344166670000005 64.54036521609329
-38.574875710885514 35.17243333 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 107
-22.4133525492225 -1.4344861109999996 64.54036521609329
-38.574875710885514 35.16882778 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 108
-22.4133525492225 -1.435313889 64.54036521609329
-38.574875710885514 35.12556111 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 109
-22.4133525492225 -1.4353833330000003 64.54036521609329
-38.574875710885514 35.12195556 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 110
-22.4133525492225 -1.4386694439999994 64.54036521609329
-38.574875710885514 35.17970278 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 111
-22.4133525492225 -1.4386 64.54036521609329
-38.574875710885514 35.18330556 40.0038669850103
EPSG:4326
(0.008333689645899539, 0.008333730267885864)
Processing point 112
-22.4133525492225 -1.438722222 64.54036521609329

(531, 15, 15, 1)

In [ ]:
parent_window

In [ ]:
# shape file transformation
import geopandas as gpd
from rasterio.transform import from_bounds
from rasterio.features import rasterize

def transform_shape(shapefile_path , attribute , output_path):
    gdf = gpd.read_file(shapefile_path)
    gdf["category_numeric"], category_mapping = gdf[attribute].factorize()
    bounds = gdf.total_bounds  
    print("Bounds:", bounds)
    resolution = 0.008983  # -- 1KM
    width = int((bounds[2] - bounds[0]) / resolution)
    height = int((bounds[3] - bounds[1]) / resolution)

    print(f"Raster size: Width={width}, Height={height}")

    transform = from_bounds(*bounds, width, height)
    raster = rasterize(
        [(geom, value) for geom, value in zip(gdf.geometry, gdf["category_numeric"])],
        out_shape=(height, width),
        transform=transform,
        fill=-1, 
        dtype=rasterio.int32
    )

    tiff_path = output_path
    with rasterio.open(
        tiff_path, "w", 
        driver="GTiff",
        height=height, 
        width=width, 
        count=1,
        dtype=rasterio.uint8,
        crs=gdf.crs,  # Use same CRS as shapefile
        transform=transform
    ) as dst:
        dst.write(raster, 1)
    print(f"Saved 1 km raster to {tiff_path}")

In [1]:
transform_shape("../Maps/ParentMaterial/Geomorphology/Algeria/Algeria_HG.shp" , "AlgGLG"  , "output_1km.tif")
geoMorpho_window = window_forming2("../Maps/ParentMaterial/Geomorphology/tiff" , df_unique)
np.save("../Data_multi_CNN/geoMorpho.npy", geoMorpho_window)
geoMorpho_window

NameError: name 'transform_shape' is not defined

In [ ]:
class optimizerKhefoufi:
    def __init__(self , raster_data , transforme , src ):
        self.raster_data = raster_data
        self.transform = transforme
        self.src = src

def data_saver(path):
    files = []
    lat_min = 0 
    lat_max = 10

    lon_min = 30
    lon_max = 40


    for i in os.listdir(path):
        print(i)
        with rasterio.open(f"{path}/{i}") as src :
            raster_data = src.read()
            transform = src.transform 

            pixel_minx , pixel_miny = latlon_to_pixel(lat_min , lon_min ,src, transform)
            pixel_maxx , pixel_maxy = latlon_to_pixel(lat_max , lon_max , src , transform)
            print(pixel_minx , pixel_maxx , pixel_miny , pixel_maxy)
            
            raster_data = raster_data[0 , pixel_minx : pixel_maxx , pixel_miny : pixel_maxy]

            tiff_val = optimizerKhefoufi(raster_data , transform , src)
        files.append(tiff_val)
    return files

all_files = data_saver("../Maps/organisme/Microbial/SoilResp_HeterotrophicResp_1928/data")

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../Maps/organisme/Microbial/SoilResp_HeterotrophicResp_1928/data'

In [ ]:
Microbial_window = window_forming3(all_files , df_unique)
np.save("../Data_multi_CNN/microbial.npy", Microbial_window)
Microbial_window

In [ ]:
def pixel_to_latlon(row, col, dataset):
    lon, lat = xy(dataset.transform, row, col)
    return lat, lon

In [ ]:
windows = []
raster_data_used = "../Resampled/climat/wc2.1_30s_prec_01.tif"
with rasterio.open(raster_data_used) as src: 
    raster = src.read()
    transform = src.transform
    for index in range(len(df_unique)):
        lat = df_unique.iloc[index]["X"]
        lon = df_unique.iloc[index]["Y"]

        pixel_row, pixel_col = latlon_to_pixel(lat, lon, src, transform)
        window = np.zeros((9, 9, 2))  # Only initialize once

        for i in range(pixel_row - 4, pixel_row + 5):
            for j in range(pixel_col - 4, pixel_col + 5):
                lat_val, lon_val = pixel_to_latlon(i, j, src)

                row_idx = i - (pixel_row - 4)
                col_idx = j - (pixel_col - 4)

                window[row_idx, col_idx, 0] = lat_val
                window[row_idx, col_idx, 1] = lon_val

        windows.append(window)

# Check result
print(windows[0].shape)
np.save("../Data_multi_CNN/latlon.npy", windows)

-180.0 -0.0945511623800001 180.0
-90.0 35.78682408 90.0
-180.0 -0.0946823495400002 180.0
-90.0 35.78322222 90.0
-180.0 -0.0948135134200001 180.0
-90.0 35.77962036 90.0
-180.0 -0.0949446540399998 180.0
-90.0 35.7760185 90.0
-180.0 -0.0950757713799999 180.0
-90.0 35.77241663 90.0
-180.0 -0.0952409953400001 180.0
-90.0 35.76878855 90.0
-180.0 -0.0989717369199998 180.0
-90.0 35.7869309 90.0
-180.0 -0.0991027251599998 180.0
-90.0 35.78332903 90.0
-180.0 -0.0992336901700001 180.0
-90.0 35.77972715 90.0
-180.0 -0.0993646319399998 180.0
-90.0 35.77612528 90.0
-180.0 -0.103523124 180.0
-90.0 35.78343567 90.0
-180.0 -0.1036538900999999 180.0
-90.0 35.77983378 90.0
-180.0 -0.1037846331 180.0
-90.0 35.77623189 90.0
-180.0 -0.1080741132999998 180.0
-90.0 35.77994025 90.0
-180.0 -0.1082046573999999 180.0
-90.0 35.77633834 90.0
-180.0 -0.421419637 180.0
-90.0 35.0443358 90.0
-180.0 -0.4215329289 180.0
-90.0 35.04073251 90.0
-180.0 -0.4346766278 180.0
-90.0 35.0410113 90.0
-180.0 -0.4347893238 180.0
-90.0 35.03740797 90.0
-180.0 -0.4390579008999999 180.0
-90.0 35.04110391 90.0
-180.0 -0.4434391939000002 180.0
-90.0 35.04119637 90.0
-180.0 -0.4435515058999999 180.0
-90.0 35.03759302 90.0
-180.0 -0.4479326269000001 180.0
-90.0 35.0376853 90.0
-180.0 -0.4523137677000002 180.0
-90.0 35.03777743 90.0
-180.0 -0.4565831924000001 180.0
-90.0 35.04147279 90.0
-180.0 -0.4569183412000002 180.0
-90.0 35.03066262 90.0
-180.0 -0.4573091225999999 180.0
-90.0 35.01805072 90.0
-180.0 -0.4609645649999998 180.0
-90.0 35.04156462 90.0
-180.0 -0.4612991378999997 180.0
-90.0 35.0307544 90.0
-180.0 -0.4616892478999999 180.0
-90.0 35.01814246 90.0
-180.0 -0.4653459572999998 180.0
-90.0 35.04165628 90.0
-180.0 -0.4654573094000001 180.0
-90.0 35.03805287 90.0
-180.0 -0.4656799544000001 180.0
-90.0 35.03084603 90.0
-180.0 -0.4698385296 180.0
-90.0 35.03814437 90.0
-180.0 -0.4742197693999999 180.0
-90.0 35.0382357 90.0
-180.0 -0.4744416466999999 180.0
-90.0 35.03102882 90.0
-180.0 -0.478601029 180.0
-90.0 35.03832688 90.0
-180.0 -0.4787117854999998 180.0
-90.0 35.03472343 90.0
-180.0 -0.4830928727999999 180.0
-90.0 35.03481444 90.0
-180.0 -0.4873636070999998 180.0
-90.0 35.03850877 90.0
-180.0 -0.4874739796999998 180.0
-90.0 35.03490529 90.0
-180.0 -0.4875843327 180.0
-90.0 35.03130181 90.0
-180.0 -0.4919652671999999 180.0
-90.0 35.0313925 90.0
-180.0 -0.4963462213 180.0
-90.0 35.03148302 90.0
-180.0 -0.4964561709000001 180.0
-90.0 35.02787952 90.0
-180.0 -0.5008369525999998 180.0
-90.0 35.02796987 90.0
-180.0 -1.0507943170000005 180.0
-90.0 29.21530985 90.0
-180.0 -1.05223529 180.0
-90.0 29.21851594 90.0
-180.0 -1.0536503229999998 180.0
-90.0 29.22201037 90.0
-180.0 -1.3627170249999998 180.0
-90.0 34.99381825 90.0
-180.0 -1.3671381510000002 180.0
-90.0 35.00113442 90.0
-180.0 -1.3709324379999996 180.0
-90.0 34.98638606 90.0
-180.0 -1.374775628 180.0
-90.0 34.97719384 90.0
-180.0 -1.3869694440000004 180.0
-90.0 35.12853333 90.0
-180.0 -1.3869000000000002 180.0
-90.0 35.13213889 90.0
-180.0 -1.3916388889999998 180.0
-90.0 35.12913889 90.0
-180.0 -1.398722222 180.0
-90.0 35.20081944 90.0
-180.0 -1.3988638890000002 180.0
-90.0 35.19360833 90.0
-180.0 -1.400277778 180.0
-90.0 35.12149722 90.0
-180.0 -1.401111111 180.0
-90.0 35.12558333 90.0
-180.0 -1.4030444440000005 180.0
-90.0 35.20448056 90.0
-180.0 -1.4031833329999994 180.0
-90.0 35.19726944 90.0
-180.0 -1.403255556 180.0
-90.0 35.19366667 90.0
-180.0 -1.4033055559999998 180.0
-90.0 35.20086111 90.0
-180.0 -1.4033972220000002 180.0
-90.0 35.18645556 90.0
-180.0 -1.4043833329999995 180.0
-90.0 35.13597778 90.0
-180.0 -1.4045 180.0
-90.0 35.13930556 90.0
-180.0 -1.4047861109999995 180.0
-90.0 35.16144722 90.0
-180.0 -1.407436111 180.0
-90.0 35.20453889 90.0
-180.0 -1.4075777779999998 180.0
-90.0 35.19732778 90.0
-180.0 -1.4076472219999996 180.0
-90.0 35.193725 90.0
-180.0 -1.4079305559999995 180.0
-90.0 35.17930278 90.0
-180.0 -1.4082805560000002 180.0
-90.0 35.161275 90.0
-180.0 -1.408422222 180.0
-90.0 35.15406389 90.0
-180.0 -1.4084444440000006 180.0
-90.0 35.13936111 90.0
-180.0 -1.4084916670000005 180.0
-90.0 35.15045833 90.0
-180.0 -1.4087722220000003 180.0
-90.0 35.13603611 90.0
-180.0 -1.4116888890000006 180.0
-90.0 35.21180833 90.0
-180.0 -1.4119694439999997 180.0
-90.0 35.19738611 90.0
-180.0 -1.4121805559999996 180.0
-90.0 35.18656944 90.0
-180.0 -1.412319444 180.0
-90.0 35.17935833 90.0
-180.0 -1.4130416669999994 180.0
-90.0 35.13606944 90.0
-180.0 -1.4131666669999996 180.0
-90.0 35.14691667 90.0
-180.0 -1.413372222 180.0
-90.0 35.12527778 90.0
-180.0 -1.416222222 180.0
-90.0 35.20465556 90.0
-180.0 -1.416363889 180.0
-90.0 35.19744444 90.0
-180.0 -1.4164333329999996 180.0
-90.0 35.19383889 90.0
-180.0 -1.4167111110000006 180.0
-90.0 35.17941667 90.0
-180.0 -1.417130556 180.0
-90.0 35.15778333 90.0
-180.0 -1.4172694440000004 180.0
-90.0 35.15057222 90.0
-180.0 -1.420416667 180.0
-90.0 35.20461111 90.0
-180.0 -1.4204750000000006 180.0
-90.0 35.21192222 90.0
-180.0 -1.420683333 180.0
-90.0 35.20110556 90.0
-180.0 -1.420811111 180.0
-90.0 35.19379444 90.0
-180.0 -1.4211750000000007 180.0
-90.0 35.17586944 90.0
-180.0 -1.4215222219999992 180.0
-90.0 35.15784167 90.0
-180.0 -1.421661111 180.0
-90.0 35.15063056 90.0
-180.0 -1.425077778 180.0
-90.0 35.20116389 90.0
-180.0 -1.425355556 180.0
-90.0 35.18674167 90.0
-180.0 -1.425361111 180.0
-90.0 35.17938889 90.0
-180.0 -1.4254250000000002 180.0
-90.0 35.18313611 90.0
-180.0 -1.4257500000000003 180.0
-90.0 35.176 90.0
-180.0 -1.4265361110000003 180.0
-90.0 35.12544722 90.0
-180.0 -1.4294722219999998 180.0
-90.0 35.18708333 90.0
-180.0 -1.4298166670000003 180.0
-90.0 35.18319444 90.0
-180.0 -1.4309249999999991 180.0
-90.0 35.12550556 90.0
-180.0 -1.4344166670000005 180.0
-90.0 35.17243333 90.0
-180.0 -1.4344861109999996 180.0
-90.0 35.16882778 90.0
-180.0 -1.435313889 180.0
-90.0 35.12556111 90.0
-180.0 -1.4353833330000003 180.0
-90.0 35.12195556 90.0
-180.0 -1.4386694439999994 180.0
-90.0 35.17970278 90.0
-180.0 -1.4386 180.0
-90.0 35.18330556 90.0
-180.0 -1.438722222 180.0
-90.0 35.16908333 90.0
-180.0 -1.4388083330000003 180.0
-90.0 35.17249167 90.0
-180.0 -1.4390833329999997 180.0
-90.0 35.15806944 90.0
-180.0 -1.4394527780000002 180.0
-90.0 35.13639444 90.0
-180.0 -1.4395555559999995 180.0
-90.0 35.16558333 90.0
-180.0 -1.4395638889999995 180.0
-90.0 35.13283056 90.0
-180.0 -1.4397027779999996 180.0
-90.0 35.12561944 90.0
-180.0 -1.4397722219999998 180.0
-90.0 35.12201389 90.0
-180.0 -1.4398388890000002 180.0
-90.0 35.11840833 90.0
-180.0 -1.443305556 180.0
-90.0 35.16919444 90.0
-180.0 -1.4433361110000005 180.0
-90.0 35.16533611 90.0
-180.0 -1.4437472220000005 180.0
-90.0 35.14370278 90.0
-180.0 -1.443816667 180.0
-90.0 35.14009722 90.0
-180.0 -1.444091667 180.0
-90.0 35.125675 90.0
-180.0 -1.4441583330000003 180.0
-90.0 35.12206944 90.0
-180.0 -1.444222222 180.0
-90.0 35.11825 90.0
-180.0 -1.444472222 180.0
-90.0 35.13288889 90.0
-180.0 -1.447519444 180.0
-90.0 35.17620833 90.0
-180.0 -1.447658333 180.0
-90.0 35.16899722 90.0
-180.0 -1.447666667 180.0
-90.0 35.16197222 90.0
-180.0 -1.447727778 180.0
-90.0 35.16539167 90.0
-180.0 -1.4478638890000002 180.0
-90.0 35.15818056 90.0
-180.0 -1.4479722220000002 180.0
-90.0 35.17227778 90.0
-180.0 -1.448138889 180.0
-90.0 35.14370278 90.0
-180.0 -1.4481666670000002 180.0
-90.0 35.12930556 90.0
-180.0 -1.448205556 180.0
-90.0 35.14015278 90.0
-180.0 -1.448416667 180.0
-90.0 35.12586111 90.0
-180.0 -1.4485277780000003 180.0
-90.0 35.12244444 90.0
-180.0 -1.448555556 180.0
-90.0 35.11841667 90.0
-180.0 -1.448 180.0
-90.0 35.15096944 90.0
-180.0 -1.451913889 180.0
-90.0 35.17626389 90.0
-180.0 -1.4521166670000003 180.0
-90.0 35.16545 90.0
-180.0 -1.452186111 180.0
-90.0 35.16184167 90.0
-180.0 -1.4522527779999996 180.0
-90.0 35.15823889 90.0
-180.0 -1.4523222219999998 180.0
-90.0 35.15463056 90.0
-180.0 -1.4528611110000005 180.0
-90.0 35.14402778 90.0
-180.0 -1.452869444 180.0
-90.0 35.12578889 90.0
-180.0 -1.4528000000000003 180.0
-90.0 35.12939167 90.0
-180.0 -1.4531944439999998 180.0
-90.0 35.12166667 90.0
-180.0 -1.4565749999999995 180.0
-90.0 35.1619 90.0
-180.0 -1.4566444439999997 180.0
-90.0 35.15829444 90.0
-180.0 -1.4567138890000004 180.0
-90.0 35.15468889 90.0
-180.0 -1.456780556 180.0
-90.0 35.15108333 90.0
-180.0 -1.4568499999999998 180.0
-90.0 35.14747778 90.0
-180.0 -1.457188888999999 180.0
-90.0 35.12945 90.0
-180.0 -1.4573222219999995 180.0
-90.0 35.12223889 90.0
-180.0 -1.458111111 180.0
-90.0 35.12622222 90.0
-180.0 -1.460966667 180.0
-90.0 35.16195556 90.0
-180.0 -1.4611027780000003 180.0
-90.0 35.15474444 90.0
-180.0 -1.4611111109999997 180.0
-90.0 35.15827778 90.0
-180.0 -1.461238889 180.0
-90.0 35.14753333 90.0
-180.0 -1.4613055559999997 180.0
-90.0 35.14392778 90.0
-180.0 -1.4654250000000002 180.0
-90.0 35.15840556 90.0
-180.0 -1.4654444440000003 180.0
-90.0 35.15472222 90.0
-180.0 -1.465561111 180.0
-90.0 35.15119444 90.0
-180.0 -1.465627778 180.0
-90.0 35.14758889 90.0
-180.0 -1.465694444 180.0
-90.0 35.14398333 90.0
-180.0 -1.4698833329999998 180.0
-90.0 35.15485556 90.0
-180.0 -1.469916667 180.0
-90.0 35.15138889 90.0
-180.0 -1.4700166670000003 180.0
-90.0 35.14764444 90.0
-180.0 -1.4704222220000005 180.0
-90.0 35.126025 90.0
-180.0 -1.4748111109999995 180.0
-90.0 35.12606667 90.0
-180.0 -1.479266667 180.0
-90.0 35.12251389 90.0
-180.0 -1.4792000000000003 180.0
-90.0 35.12611944 90.0
-180.0 -1.483655556 180.0
-90.0 35.12256944 90.0
-180.0 -1.6286593340000004 180.0
-90.0 29.60028403 90.0
-180.0 -1.638375698 180.0
-90.0 29.61181728 90.0
-180.0 -2.507935127 180.0
-90.0 29.9785827 90.0
-180.0 -3.589166667 180.0
-90.0 29.24777778 90.0
-180.0 0.1102777777999999 180.0
-90.0 28.77222222 90.0
-180.0 0.1130555555999999 180.0
-90.0 28.77972222 90.0
-180.0 0.1155555555999998 180.0
-90.0 28.77222222 90.0
-180.0 0.1208333332999997 180.0
-90.0 28.77166667 90.0
-180.0 0.2213888888999999 180.0
-90.0 29.07111111 90.0
-180.0 0.2313888889000002 180.0
-90.0 29.065 90.0
-180.0 0.2341666667000002 180.0
-90.0 29.06583333 90.0
-180.0 0.3047222222000001 180.0
-90.0 28.81055556 90.0
-180.0 0.3052777777999997 180.0
-90.0 28.81527778 90.0
-180.0 0.3152777778 180.0
-90.0 28.81138889 90.0
-180.0 0.3155555556000002 180.0
-90.0 28.81916667 90.0
-180.0 0.3158333333000001 180.0
-90.0 28.70916667 90.0
-180.0 0.4011331629999999 180.0
-90.0 34.09960773 90.0
-180.0 0.4027845414000002 180.0
-90.0 34.04555064 90.0
-180.0 0.4069606315 180.0
-90.0 34.08620796 90.0
-180.0 0.4173784366999997 180.0
-90.0 34.09995145 90.0
-180.0 0.4190195478999998 180.0
-90.0 34.04589277 90.0
-180.0 0.4352548274000001 180.0
-90.0 34.04623277 90.0
-180.0 0.4356618457999999 180.0
-90.0 34.03271806 90.0
-180.0 0.4843615958 180.0
-90.0 34.03372469 90.0
-180.0 0.492 180.0
-90.0 35.73805556 90.0
-180.0 0.5240116973 180.0
-90.0 35.91181411 90.0
-180.0 0.5354921482999997 180.0
-90.0 35.74683197 90.0
-180.0 0.5464499167999999 180.0
-90.0 35.76805792 90.0
-180.0 0.5561111110999999 180.0
-90.0 35.79564722 90.0
-180.0 0.5671666666999999 180.0
-90.0 35.73155556 90.0
-180.0 0.5802222222 180.0
-90.0 35.72227778 90.0
-180.0 0.5950833332999999 180.0
-90.0 35.77075 90.0
-180.0 0.6027777778000001 180.0
-90.0 29.24583333 90.0
-180.0 0.6108333333 180.0
-90.0 29.23361111 90.0
-180.0 0.6142833332999997 180.0
-90.0 35.75227222 90.0
-180.0 0.738145 180.0
-90.0 35.975601 90.0
-180.0 0.7386019999999998 180.0
-90.0 35.929667 90.0
-180.0 0.7391619999999999 180.0
-90.0 35.934705 90.0
-180.0 0.739722 180.0
-90.0 35.93912 90.0
-180.0 0.743765 180.0
-90.0 35.933361 90.0
-180.0 0.7442009999999999 180.0
-90.0 35.936577 90.0
-180.0 0.7470620000000001 180.0
-90.0 35.925252 90.0
-180.0 0.7481199999999999 180.0
-90.0 35.930818 90.0
-180.0 0.748804 180.0
-90.0 35.936912 90.0
-180.0 0.752909 180.0
-90.0 35.931154 90.0
-180.0 0.7529720000000002 180.0
-90.0 35.926068 90.0
-180.0 0.753034 180.0
-90.0 35.932018 90.0
-180.0 0.817261 180.0
-90.0 35.972541 90.0
-180.0 0.870336 180.0
-90.0 35.989594 90.0
-180.0 1.247222222 180.0
-90.0 36.54694444 90.0
-180.0 1.255555556 180.0
-90.0 35.34777778 90.0
-180.0 1.258333333 180.0
-90.0 35.34916667 90.0
-180.0 1.392093 180.0
-90.0 36.200368 90.0
-180.0 1.413611111 180.0
-90.0 35.41361111 90.0
-180.0 1.472222222 180.0
-90.0 35.36888889 90.0
-180.0 1.537723 180.0
-90.0 36.176619 90.0
-180.0 1.580147 180.0
-90.0 36.227691 90.0
-180.0 1.642222222 180.0
-90.0 35.50888889 90.0
-180.0 1.68818 180.0
-90.0 36.237664 90.0
-180.0 1.85645 180.0
-90.0 36.268803 90.0
-180.0 1.893333333 180.0
-90.0 35.78826667 90.0
-180.0 2.164473 180.0
-90.0 36.20746 90.0
-180.0 2.40175 180.0
-90.0 27.35277778 90.0
-180.0 2.427777778 180.0
-90.0 36.51553889 90.0
-180.0 2.429580556 180.0
-90.0 36.51418111 90.0
-180.0 2.431238889 180.0
-90.0 36.51254167 90.0
-180.0 2.432102778 180.0
-90.0 36.50821111 90.0
-180.0 2.442308333 180.0
-90.0 36.53488889 90.0
-180.0 2.4434 180.0
-90.0 36.50640556 90.0
-180.0 2.443569444 180.0
-90.0 36.52870278 90.0
-180.0 2.452580556 180.0
-90.0 36.50893611 90.0
-180.0 2.464444444 180.0
-90.0 27.19333333 90.0
-180.0 2.479397222 180.0
-90.0 36.54522778 90.0
-180.0 2.483888889 180.0
-90.0 36.49722222 90.0
-180.0 2.489444444 180.0
-90.0 36.49277778 90.0
-180.0 2.489444444 180.0
-90.0 36.51083333 90.0
-180.0 2.492941667 180.0
-90.0 36.54385278 90.0
-180.0 2.495 180.0
-90.0 36.51527778 90.0
-180.0 2.495 180.0
-90.0 36.51972222 90.0
-180.0 2.495 180.0
-90.0 36.52444444 90.0
-180.0 2.500555556 180.0
-90.0 36.51083333 90.0
-180.0 2.500555556 180.0
-90.0 36.52 90.0
-180.0 2.500555556 180.0
-90.0 36.54694444 90.0
-180.0 2.506111111 180.0
-90.0 36.52444444 90.0
-180.0 2.506388889 180.0
-90.0 36.47944444 90.0
-180.0 2.506388889 180.0
-90.0 36.48388889 90.0
-180.0 2.511666667 180.0
-90.0 36.52444444 90.0
-180.0 2.511666667 180.0
-90.0 36.55138889 90.0
-180.0 2.5175 180.0
-90.0 36.47944444 90.0
-180.0 2.523055556 180.0
-90.0 36.50194444 90.0
-180.0 2.523408333 180.0
-90.0 36.55511667 90.0
-180.0 2.527688889 180.0
-90.0 36.55059722 90.0
-180.0 2.528611111 180.0
-90.0 36.47472222 90.0
-180.0 2.528611111 180.0
-90.0 36.48388889 90.0
-180.0 2.539722222 180.0
-90.0 36.47944444 90.0
-180.0 2.542866667 180.0
-90.0 36.53226944 90.0
-180.0 2.542997222 180.0
-90.0 36.52935833 90.0
-180.0 2.543297222 180.0
-90.0 36.52684444 90.0
-180.0 2.543425 180.0
-90.0 36.52400278 90.0
-180.0 2.548080556 180.0
-90.0 36.52132778 90.0
-180.0 2.550833333 180.0
-90.0 36.50194444 90.0
-180.0 2.550833333 180.0
-90.0 36.52 90.0
-180.0 2.556388889 180.0
-90.0 36.52 90.0
-180.0 2.561944444 180.0
-90.0 36.48388889 90.0
-180.0 2.561944444 180.0
-90.0 36.50194444 90.0
-180.0 2.564863889 180.0
-90.0 36.50845556 90.0
-180.0 2.567263889 180.0
-90.0 36.50956389 90.0
-180.0 2.568588889 180.0
-90.0 36.49045 90.0
-180.0 2.568805556 180.0
-90.0 36.49461389 90.0
-180.0 2.573055556 180.0
-90.0 36.52 90.0
-180.0 2.573055556 180.0
-90.0 36.53361111 90.0
-180.0 2.573333333 180.0
-90.0 36.4975 90.0
-180.0 2.5735 180.0
-90.0 36.50859444 90.0
-180.0 2.574069444 180.0
-90.0 36.47494167 90.0
-180.0 2.575869444 180.0
-90.0 36.50725556 90.0
-180.0 2.578888889 180.0
-90.0 36.47027778 90.0
-180.0 2.584444444 180.0
-90.0 36.47027778 90.0
-180.0 2.584444444 180.0
-90.0 36.47944444 90.0
-180.0 2.584444444 180.0
-90.0 36.48833333 90.0
-180.0 2.584444444 180.0
-90.0 36.51083333 90.0
-180.0 2.584444444 180.0
-90.0 36.51555556 90.0
-180.0 2.586388889 180.0
-90.0 27.185 90.0
-180.0 2.589305556 180.0
-90.0 36.56950278 90.0
-180.0 2.595569444 180.0
-90.0 36.56732222 90.0
-180.0 2.595941667 180.0
-90.0 36.5635 90.0
-180.0 2.597683333 180.0
-90.0 36.47054722 90.0
-180.0 2.59 180.0
-90.0 36.48833333 90.0
-180.0 2.59 180.0
-90.0 36.52444444 90.0
-180.0 2.59 180.0
-90.0 36.53805556 90.0
-180.0 2.611669444 180.0
-90.0 36.47150556 90.0
-180.0 2.628802778 180.0
-90.0 36.51838056 90.0
-180.0 2.654444444 180.0
-90.0 27.19527778 90.0
-180.0 2.685833333 180.0
-90.0 27.96722222 90.0
-180.0 2.721944444 180.0
-90.0 27.32055556 90.0
-180.0 2.751111111 180.0
-90.0 27.34111111 90.0
-180.0 2.968055556 180.0
-90.0 30.43511111 90.0
-180.0 2.969444444 180.0
-90.0 30.44944444 90.0
-180.0 2.975055556 180.0
-90.0 30.45138889 90.0
-180.0 2.975083333 180.0
-90.0 30.45583333 90.0
-180.0 2.980388889 180.0
-90.0 30.45127778 90.0
-180.0 3.107 180.0
-90.0 36.684 90.0
-180.0 3.133333333 180.0
-90.0 36.71666667 90.0
-180.0 3.15955 180.0
-90.0 36.70531667 90.0
-180.0 3.51419 180.0
-90.0 32.26112 90.0
-180.0 3.520330556 180.0
-90.0 32.37543333 90.0
-180.0 3.677452778 180.0
-90.0 32.26458611 90.0
-180.0 3.686038889 180.0
-90.0 32.26595278 90.0
-180.0 3.79581 180.0
-90.0 32.43793 90.0
-180.0 3.796580556 180.0
-90.0 32.24238611 90.0
-180.0 3.799263889 180.0
-90.0 32.43658333 90.0
-180.0 3.801527778 180.0
-90.0 32.24511944 90.0
-180.0 3.88016 180.0
-90.0 32.42822 90.0
-180.0 3.8893 180.0
-90.0 32.4084 90.0
-180.0 3.913805556 180.0
-90.0 35.02913889 90.0
-180.0 3.914944444 180.0
-90.0 35.02977778 90.0
-180.0 4.016666667 180.0
-90.0 34.77672222 90.0
-180.0 4.031611111 180.0
-90.0 34.773 90.0
-180.0 4.031611111 180.0
-90.0 34.775 90.0
-180.0 4.129111111 180.0
-90.0 34.68988889 90.0
-180.0 4.144987 180.0
-90.0 35.527771 90.0
-180.0 4.232111111 180.0
-90.0 34.67205556 90.0
-180.0 4.237277778 180.0
-90.0 34.68802778 90.0
-180.0 4.244638889 180.0
-90.0 34.68119444 90.0
-180.0 4.247333333 180.0
-90.0 34.68872222 90.0
-180.0 4.25125 180.0
-90.0 34.88441667 90.0
-180.0 4.269333333 180.0
-90.0 34.86619444 90.0
-180.0 4.276364 180.0
-90.0 35.589227 90.0
-180.0 4.301573 180.0
-90.0 35.360755 90.0
-180.0 4.303891 180.0
-90.0 35.476145 90.0
-180.0 4.337823 180.0
-90.0 35.410759 90.0
-180.0 4.353149 180.0
-90.0 35.565645 90.0
-180.0 4.376902 180.0
-90.0 35.697868 90.0
-180.0 4.380583333 180.0
-90.0 34.74919444 90.0
-180.0 4.381583333 180.0
-90.0 34.74111111 90.0
-180.0 4.397444444 180.0
-90.0 34.73666667 90.0
-180.0 4.399283333 180.0
-90.0 35.29036667 90.0
-180.0 4.420208333 180.0
-90.0 32.04634722 90.0
-180.0 4.4363 180.0
-90.0 32.04470556 90.0
-180.0 4.445195 180.0
-90.0 35.585975 90.0
-180.0 4.490472222 180.0
-90.0 32.78259444 90.0
-180.0 4.493133333 180.0
-90.0 32.78359722 90.0
-180.0 4.505105556 180.0
-90.0 32.78979167 90.0
-180.0 4.50555 180.0
-90.0 32.79069167 90.0
-180.0 4.529444444 180.0
-90.0 33.04055556 90.0
-180.0 4.537326 180.0
-90.0 35.751417 90.0
-180.0 4.53925 180.0
-90.0 35.34972222 90.0
-180.0 4.548333333 180.0
-90.0 32.72222222 90.0
-180.0 4.549722222 180.0
-90.0 32.72444444 90.0
-180.0 4.551138889 180.0
-90.0 35.34902778 90.0
-180.0 4.551666667 180.0
-90.0 32.72833333 90.0
-180.0 4.553888889 180.0
-90.0 32.72583333 90.0
-180.0 4.556388889 180.0
-90.0 35.74 90.0
-180.0 4.566805556 180.0
-90.0 35.34922222 90.0
-180.0 4.568416667 180.0
-90.0 35.34861111 90.0
-180.0 4.599079 180.0
-90.0 35.743238 90.0
-180.0 4.628049 180.0
-90.0 35.660713 90.0
-180.0 4.632527778 180.0
-90.0 35.33311111 90.0
-180.0 4.65943 180.0
-90.0 35.588962 90.0
-180.0 4.691529 180.0
-90.0 35.768787 90.0
-180.0 4.7075 180.0
-90.0 33.02555556 90.0
-180.0 4.713055556 180.0
-90.0 32.87166667 90.0
-180.0 4.720330556 180.0
-90.0 31.92933611 90.0
-180.0 4.724658333 180.0
-90.0 31.93413889 90.0
-180.0 4.739722222 180.0
-90.0 32.85111111 90.0
-180.0 4.785722222 180.0
-90.0 35.26425 90.0
-180.0 4.788111111 180.0
-90.0 35.299 90.0
-180.0 4.797596 180.0
-90.0 35.637114 90.0
-180.0 4.839611111 180.0
-90.0 36.07402778 90.0
-180.0 4.901707 180.0
-90.0 35.527019 90.0
-180.0 4.952107 180.0
-90.0 35.592814 90.0
-180.0 5.017376 180.0
-90.0 35.483341 90.0
-180.0 5.065277778 180.0
-90.0 35.0375 90.0
-180.0 5.0 180.0
-90.0 34.0 90.0
-180.0 5.137791667 180.0
-90.0 34.63802222 90.0
-180.0 5.191799 180.0
-90.0 35.772034 90.0
-180.0 5.19 180.0
-90.0 36.2 90.0
-180.0 5.19 180.0
-90.0 36.3 90.0
-180.0 5.21 180.0
-90.0 36.2 90.0
-180.0 5.234025 180.0
-90.0 35.77746 90.0
-180.0 5.23 180.0
-90.0 36.3 90.0
-180.0 5.292234989 180.0
-90.0 31.9380254 90.0
-180.0 5.292367544999999 180.0
-90.0 31.94123366 90.0
-180.0 5.292395552 180.0
-90.0 31.94023208 90.0
-180.0 5.29291293 180.0
-90.0 31.94190021 90.0
-180.0 5.293072540000001 180.0

In [ ]:
windows

[array([[[ 1.33324104, 36.18646279],
         [ 1.33324104, 36.19115959],
         [ 1.33324104, 36.19585638],
         [ 1.33324104, 36.20055318],
         [ 1.33324104, 36.20524997],
         [ 1.33324104, 36.20994677],
         [ 1.33324104, 36.21464357]],

        [[ 1.32874942, 36.18646279],
         [ 1.32874942, 36.19115959],
         [ 1.32874942, 36.19585638],
         [ 1.32874942, 36.20055318],
         [ 1.32874942, 36.20524997],
         [ 1.32874942, 36.20994677],
         [ 1.32874942, 36.21464357]],

        [[ 1.32425781, 36.18646279],
         [ 1.32425781, 36.19115959],
         [ 1.32425781, 36.19585638],
         [ 1.32425781, 36.20055318],
         [ 1.32425781, 36.20524997],
         [ 1.32425781, 36.20994677],
         [ 1.32425781, 36.21464357]],

        [[ 1.31976619, 36.18646279],
         [ 1.31976619, 36.19115959],
         [ 1.31976619, 36.19585638],
         [ 1.31976619, 36.20055318],
         [ 1.31976619, 36.20524997],
         [ 1.31976619, 36.20994677],
         [ 1.31976619, 36.21464357]],

        [[ 1.31527457, 36.18646279],
         [ 1.31527457, 36.19115959],
         [ 1.31527457, 36.19585638],
         [ 1.31527457, 36.20055318],
         [ 1.31527457, 36.20524997],
         [ 1.31527457, 36.20994677],
         [ 1.31527457, 36.21464357]],

        [[ 1.31078296, 36.18646279],
         [ 1.31078296, 36.19115959],
         [ 1.31078296, 36.19585638],
         [ 1.31078296, 36.20055318],
         [ 1.31078296, 36.20524997],
         [ 1.31078296, 36.20994677],
         [ 1.31078296, 36.21464357]],

        [[ 1.30629134, 36.18646279],
         [ 1.30629134, 36.19115959],
         [ 1.30629134, 36.19585638],
         [ 1.30629134, 36.20055318],
         [ 1.30629134, 36.20524997],
         [ 1.30629134, 36.20994677],
         [ 1.30629134, 36.21464357]]]),
 array([[[ 1.29281649, 37.98533556],
         [ 1.29281649, 37.99003236],
         [ 1.29281649, 37.99472915],
         [ 1.29281649, 37.99942595],
         [ 1.29281649, 38.00412274],
         [ 1.29281649, 38.00881954],
         [ 1.29281649, 38.01351633]],

        [[ 1.28832487, 37.98533556],
         [ 1.28832487, 37.99003236],
         [ 1.28832487, 37.99472915],
         [ 1.28832487, 37.99942595],
         [ 1.28832487, 38.00412274],
         [ 1.28832487, 38.00881954],
         [ 1.28832487, 38.01351633]],

        [[ 1.28383326, 37.98533556],
         [ 1.28383326, 37.99003236],
         [ 1.28383326, 37.99472915],
         [ 1.28383326, 37.99942595],
         [ 1.28383326, 38.00412274],
         [ 1.28383326, 38.00881954],
         [ 1.28383326, 38.01351633]],

        [[ 1.27934164, 37.98533556],
         [ 1.27934164, 37.99003236],
         [ 1.27934164, 37.99472915],
         [ 1.27934164, 37.99942595],
         [ 1.27934164, 38.00412274],
         [ 1.27934164, 38.00881954],
         [ 1.27934164, 38.01351633]],

        [[ 1.27485002, 37.98533556],
         [ 1.27485002, 37.99003236],
         [ 1.27485002, 37.99472915],
         [ 1.27485002, 37.99942595],
         [ 1.27485002, 38.00412274],
         [ 1.27485002, 38.00881954],
         [ 1.27485002, 38.01351633]],

        [[ 1.27035841, 37.98533556],
         [ 1.27035841, 37.99003236],
         [ 1.27035841, 37.99472915],
         [ 1.27035841, 37.99942595],
         [ 1.27035841, 38.00412274],
         [ 1.27035841, 38.00881954],
         [ 1.27035841, 38.01351633]],

        [[ 1.26586679, 37.98533556],
         [ 1.26586679, 37.99003236],
         [ 1.26586679, 37.99472915],
         [ 1.26586679, 37.99942595],
         [ 1.26586679, 38.00412274],
         [ 1.26586679, 38.00881954],
         [ 1.26586679, 38.01351633]]]),
 array([[[ 1.32425781, 36.18646279],
         [ 1.32425781, 36.19115959],
         [ 1.32425781, 36.19585638],
         [ 1.32425781, 36.20055318],
         [ 1.32425781, 36.20524997],
         [ 1.32425781, 36.20994677],
         [ 1.32425781, 36.21464357]],

        [[ 1.31976619, 36.18646279],
         [ 1.31976619, 36.19115959],
         [ 1.31976619, 36.19585638],
         [ 1.31976619, 36.20055318],
         [ 1.31976619, 36.20524997],
         [ 1.31976619, 36.20994677],
         [ 1.31976619, 36.21464357]],

        [[ 1.31527457, 36.18646279],
         [ 1.31527457, 36.19115959],
         [ 1.31527457, 36.19585638],
         [ 1.31527457, 36.20055318],
         [ 1.31527457, 36.20524997],
         [ 1.31527457, 36.20994677],
         [ 1.31527457, 36.21464357]],

        [[ 1.31078296, 36.18646279],
         [ 1.31078296, 36.19115959],
         [ 1.31078296, 36.19585638],
         [ 1.31078296, 36.20055318],
         [ 1.31078296, 36.20524997],
         [ 1.31078296, 36.20994677],
         [ 1.31078296, 36.21464357]],

        [[ 1.30629134, 36.18646279],
         [ 1.30629134, 36.19115959],
         [ 1.30629134, 36.19585638],
         [ 1.30629134, 36.20055318],
         [ 1.30629134, 36.20524997],
         [ 1.30629134, 36.20994677],
         [ 1.30629134, 36.21464357]],

        [[ 1.30179972, 36.18646279],
         [ 1.30179972, 36.19115959],
         [ 1.30179972, 36.19585638],
         [ 1.30179972, 36.20055318],
         [ 1.30179972, 36.20524997],
         [ 1.30179972, 36.20994677],
         [ 1.30179972, 36.21464357]],

        [[ 1.29730811, 36.18646279],
         [ 1.29730811, 36.19115959],
         [ 1.29730811, 36.19585638],
         [ 1.29730811, 36.20055318],
         [ 1.29730811, 36.20524997],
         [ 1.29730811, 36.20994677],
         [ 1.29730811, 36.21464357]]]),
 array([[[ 1.31527457, 36.1770692 ],
         [ 1.31527457, 36.181766  ],
         [ 1.31527457, 36.18646279],
         [ 1.31527457, 36.19115959],
         [ 1.31527457, 36.19585638],
         [ 1.31527457, 36.20055318],
         [ 1.31527457, 36.20524997]],

        [[ 1.31078296, 36.1770692 ],
         [ 1.31078296, 36.181766  ],
         [ 1.31078296, 36.18646279],
         [ 1.31078296, 36.19115959],
         [ 1.31078296, 36.19585638],
         [ 1.31078296, 36.20055318],
         [ 1.31078296, 36.20524997]],

        [[ 1.30629134, 36.1770692 ],
         [ 1.30629134, 36.181766  ],
         [ 1.30629134, 36.18646279],
         [ 1.30629134, 36.19115959],
         [ 1.30629134, 36.19585638],
         [ 1.30629134, 36.20055318],
         [ 1.30629134, 36.20524997]],

        [[ 1.30179972, 36.1770692 ],
         [ 1.30179972, 36.181766  ],
         [ 1.30179972, 36.18646279],
         [ 1.30179972, 36.19115959],
         [ 1.30179972, 36.19585638],
         [ 1.30179972, 36.20055318],
         [ 1.30179972, 36.20524997]],

        [[ 1.29730811, 36.1770692 ],
         [ 1.29730811, 36.181766  ],
         [ 1.29730811, 36.18646279],
         [ 1.29730811, 36.19115959],
         [ 1.29730811, 36.19585638],
         [ 1.29730811, 36.20055318],
         [ 1.29730811, 36.20524997]],

        [[ 1.29281649, 36.1770692 ],
         [ 1.29281649, 36.181766  ],
         [ 1.29281649, 36.18646279],
         [ 1.29281649, 36.19115959],
         [ 1.29281649, 36.19585638],
         [ 1.29281649, 36.20055318],
         [ 1.29281649, 36.20524997]],

        [[ 1.28832487, 36.1770692 ],
         [ 1.28832487, 36.181766  ],
         [ 1.28832487, 36.18646279],
         [ 1.28832487, 36.19115959],
         [ 1.28832487, 36.19585638],
         [ 1.28832487, 36.20055318],
         [ 1.28832487, 36.20524997]]]),
 array([[[ 1.33324104, 36.20524997],
         [ 1.33324104, 36.20994677],
         [ 1.33324104, 36.21464357],
         [ 1.33324104, 36.21934036],
         [ 1.33324104, 36.22403716],
         [ 1.33324104, 36.22873395],
         [ 1.33324104, 36.23343075]],

        [[ 1.32874942, 36.20524997],
         [ 1.32874942, 36.20994677],
         [ 1.32874942, 36.21464357],
         [ 1.32874942, 36.21934036],
         [ 1.32874942, 36.22403716],
         [ 1.32874942, 36.22873395],
         [ 1.32874942, 36.23343075]],

        [[ 1.32425781, 36.20524997],
         [ 1.32425781, 36.20994677],
         [ 1.32425781, 36.21464357],
         [ 1.32425781, 36.21934036],
         [ 1.32425781, 36.22403716],
         [ 1.32425781, 36.22873395],
         [ 1.32425781, 36.23343075]],

        [[ 1.31976619, 36.20524997],
         [ 1.31976619, 36.20994677],
         [ 1.31976619, 36.21464357],
         [ 1.31976619, 36.21934036],
         [ 1.31976619, 36.22403716],
         [ 1.31976619, 36.22873395],
         [ 1.31976619, 36.23343075]],

        [[ 1.31527457, 36.20524997],
         [ 1.31527457, 36.20994677],
         [ 1.31527457, 36.21464357],
         [ 1.31527457, 36.21934036],
         [ 1.31527457, 36.22403716],
         [ 1.31527457, 36.22873395],
         [ 1.31527457, 36.23343075]],

        [[ 1.31078296, 36.20524997],
         [ 1.31078296, 36.20994677],
         [ 1.31078296, 36.21464357],
         [ 1.31078296, 36.21934036],
         [ 1.31078296, 36.22403716],
         [ 1.31078296, 36.22873395],
         [ 1.31078296, 36.23343075]],

        [[ 1.30629134, 36.20524997],
         [ 1.30629134, 36.20994677],
         [ 1.30629134, 36.21464357],
         [ 1.30629134, 36.21934036],
         [ 1.30629134, 36.22403716],
         [ 1.30629134, 36.22873395],
         [ 1.30629134, 36.23343075]]]),
 array([[[ 1.29281649, 36.18646279],
         [ 1.29281649, 36.19115959],
         [ 1.29281649, 36.19585638],
         [ 1.29281649, 36.20055318],
         [ 1.29281649, 36.20524997],
         [ 1.29281649, 36.20994677],
         [ 1.29281649, 36.21464357]],

        [[ 1.28832487, 36.18646279],
         [ 1.28832487, 36.19115959],
         [ 1.28832487, 36.19585638],
         [ 1.28832487, 36.20055318],
         [ 1.28832487, 36.20524997],
         [ 1.28832487, 36.20994677],
         [ 1.28832487, 36.21464357]],

        [[ 1.28383326, 36.18646279],
         [ 1.28383326, 36.19115959],
         [ 1.28383326, 36.19585638],
         [ 1.28383326, 36.20055318],
         [ 1.28383326, 36.20524997],
         [ 1.28383326, 36.20994677],
         [ 1.28383326, 36.21464357]],

        [[ 1.27934164, 36.18646279],
         [ 1.27934164, 36.19115959],
         [ 1.27934164, 36.19585638],
         [ 1.27934164, 36.20055318],
         [ 1.27934164, 36.20524997],
         [ 1.27934164, 36.20994677],
         [ 1.27934164, 36.21464357]],

        [[ 1.27485002, 36.18646279],
         [ 1.27485002, 36.19115959],
         [ 1.27485002, 36.19585638],
         [ 1.27485002, 36.20055318],
         [ 1.27485002, 36.20524997],
         [ 1.27485002, 36.20994677],
         [ 1.27485002, 36.21464357]],

        [[ 1.27035841, 36.18646279],
         [ 1.27035841, 36.19115959],
         [ 1.27035841, 36.19585638],
         [ 1.27035841, 36.20055318],
         [ 1.27035841, 36.20524997],
         [ 1.27035841, 36.20994677],
         [ 1.27035841, 36.21464357]],

        [[ 1.26586679, 36.18646279],
         [ 1.26586679, 36.19115959],
         [ 1.26586679, 36.19585638],
         [ 1.26586679, 36.20055318],
         [ 1.26586679, 36.20524997],
         [ 1.26586679, 36.20994677],
         [ 1.26586679, 36.21464357]]]),
 array([[[ 1.29281649, 36.1770692 ],
         [ 1.29281649, 36.181766  ],
         [ 1.29281649, 36.18646279],
         [ 1.29281649, 36.19115959],
         [ 1.29281649, 36.19585638],
         [ 1.29281649, 36.20055318],
         [ 1.29281649, 36.20524997]],

        [[ 1.28832487, 36.1770692 ],
         [ 1.28832487, 36.181766  ],
         [ 1.28832487, 36.18646279],
         [ 1.28832487, 36.19115959],
         [ 1.28832487, 36.19585638],
         [ 1.28832487, 36.20055318],
         [ 1.28832487, 36.20524997]],

        [[ 1.28383326, 36.1770692 ],
         [ 1.28383326, 36.181766  ],
         [ 1.28383326, 36.18646279],
         [ 1.28383326, 36.19115959],
         [ 1.28383326, 36.19585638],
         [ 1.28383326, 36.20055318],
         [ 1.28383326, 36.20524997]],

        [[ 1.27934164, 36.1770692 ],
         [ 1.27934164, 36.181766  ],
         [ 1.27934164, 36.18646279],
         [ 1.27934164, 36.19115959],
         [ 1.27934164, 36.19585638],
         [ 1.27934164, 36.20055318],
         [ 1.27934164, 36.20524997]],

        [[ 1.27485002, 36.1770692 ],
         [ 1.27485002, 36.181766  ],
         [ 1.27485002, 36.18646279],
         [ 1.27485002, 36.19115959],
         [ 1.27485002, 36.19585638],
         [ 1.27485002, 36.20055318],
         [ 1.27485002, 36.20524997]],

        [[ 1.27035841, 36.1770692 ],
         [ 1.27035841, 36.181766  ],
         [ 1.27035841, 36.18646279],
         [ 1.27035841, 36.19115959],
         [ 1.27035841, 36.19585638],
         [ 1.27035841, 36.20055318],
         [ 1.27035841, 36.20524997]],

        [[ 1.26586679, 36.1770692 ],
         [ 1.26586679, 36.181766  ],
         [ 1.26586679, 36.18646279],
         [ 1.26586679, 36.19115959],
         [ 1.26586679, 36.19585638],
         [ 1.26586679, 36.20055318],
         [ 1.26586679, 36.20524997]]]),
 array([[[ 1.30179972, 36.22403716],
         [ 1.30179972, 36.22873395],
         [ 1.30179972, 36.23343075],
         [ 1.30179972, 36.23812754],
         [ 1.30179972, 36.24282434],
         [ 1.30179972, 36.24752114],
         [ 1.30179972, 36.25221793]],

        [[ 1.29730811, 36.22403716],
         [ 1.29730811, 36.22873395],
         [ 1.29730811, 36.23343075],
         [ 1.29730811, 36.23812754],
         [ 1.29730811, 36.24282434],
         [ 1.29730811, 36.24752114],
         [ 1.29730811, 36.25221793]],

        [[ 1.29281649, 36.22403716],
         [ 1.29281649, 36.22873395],
         [ 1.29281649, 36.23343075],
         [ 1.29281649, 36.23812754],
         [ 1.29281649, 36.24282434],
         [ 1.29281649, 36.24752114],
         [ 1.29281649, 36.25221793]],

        [[ 1.28832487, 36.22403716],
         [ 1.28832487, 36.22873395],
         [ 1.28832487, 36.23343075],
         [ 1.28832487, 36.23812754],
         [ 1.28832487, 36.24282434],
         [ 1.28832487, 36.24752114],
         [ 1.28832487, 36.25221793]],

        [[ 1.28383326, 36.22403716],
         [ 1.28383326, 36.22873395],
         [ 1.28383326, 36.23343075],
         [ 1.28383326, 36.23812754],
         [ 1.28383326, 36.24282434],
         [ 1.28383326, 36.24752114],
         [ 1.28383326, 36.25221793]],

        [[ 1.27934164, 36.22403716],
         [ 1.27934164, 36.22873395],
         [ 1.27934164, 36.23343075],
         [ 1.27934164, 36.23812754],
         [ 1.27934164, 36.24282434],
         [ 1.27934164, 36.24752114],
         [ 1.27934164, 36.25221793]],

        [[ 1.27485002, 36.22403716],
         [ 1.27485002, 36.22873395],
         [ 1.27485002, 36.23343075],
         [ 1.27485002, 36.23812754],
         [ 1.27485002, 36.24282434],
         [ 1.27485002, 36.24752114],
         [ 1.27485002, 36.25221793]]]),
 array([[[ 1.28383326, 36.16767561],
         [ 1.28383326, 36.1723724 ],
         [ 1.28383326, 36.1770692 ],
         [ 1.28383326, 36.181766  ],
         [ 1.28383326, 36.18646279],
         [ 1.28383326, 36.19115959],
         [ 1.28383326, 36.19585638]],

        [[ 1.27934164, 36.16767561],
         [ 1.27934164, 36.1723724 ],
         [ 1.27934164, 36.1770692 ],
         [ 1.27934164, 36.181766  ],
         [ 1.27934164, 36.18646279],
         [ 1.27934164, 36.19115959],
         [ 1.27934164, 36.19585638]],

        [[ 1.27485002, 36.16767561],
         [ 1.27485002, 36.1723724 ],
         [ 1.27485002, 36.1770692 ],
         [ 1.27485002, 36.181766  ],
         [ 1.27485002, 36.18646279],
         [ 1.27485002, 36.19115959],
         [ 1.27485002, 36.19585638]],

        [[ 1.27035841, 36.16767561],
         [ 1.27035841, 36.1723724 ],
         [ 1.27035841, 36.1770692 ],
         [ 1.27035841, 36.181766  ],
         [ 1.27035841, 36.18646279],
         [ 1.27035841, 36.19115959],
         [ 1.27035841, 36.19585638]],

        [[ 1.26586679, 36.16767561],
         [ 1.26586679, 36.1723724 ],
         [ 1.26586679, 36.1770692 ],
         [ 1.26586679, 36.181766  ],
         [ 1.26586679, 36.18646279],
         [ 1.26586679, 36.19115959],
         [ 1.26586679, 36.19585638]],

        [[ 1.26137517, 36.16767561],
         [ 1.26137517, 36.1723724 ],
         [ 1.26137517, 36.1770692 ],
         [ 1.26137517, 36.181766  ],
         [ 1.26137517, 36.18646279],
         [ 1.26137517, 36.19115959],
         [ 1.26137517, 36.19585638]],

        [[ 1.25688356, 36.16767561],
         [ 1.25688356, 36.1723724 ],
         [ 1.25688356, 36.1770692 ],
         [ 1.25688356, 36.181766  ],
         [ 1.25688356, 36.18646279],
         [ 1.25688356, 36.19115959],
         [ 1.25688356, 36.19585638]]]),
 array([[[ 1.27485002, 36.1770692 ],
         [ 1.27485002, 36.181766  ],
         [ 1.27485002, 36.18646279],
         [ 1.27485002, 36.19115959],
         [ 1.27485002, 36.19585638],
         [ 1.27485002, 36.20055318],
         [ 1.27485002, 36.20524997]],

        [[ 1.27035841, 36.1770692 ],
         [ 1.27035841, 36.181766  ],
         [ 1.27035841, 36.18646279],
         [ 1.27035841, 36.19115959],
         [ 1.27035841, 36.19585638],
         [ 1.27035841, 36.20055318],
         [ 1.27035841, 36.20524997]],

        [[ 1.26586679, 36.1770692 ],
         [ 1.26586679, 36.181766  ],
         [ 1.26586679, 36.18646279],
         [ 1.26586679, 36.19115959],
         [ 1.26586679, 36.19585638],
         [ 1.26586679, 36.20055318],
         [ 1.26586679, 36.20524997]],

        [[ 1.26137517, 36.1770692 ],
         [ 1.26137517, 36.181766  ],
         [ 1.26137517, 36.18646279],
         [ 1.26137517, 36.19115959],
         [ 1.26137517, 36.19585638],
         [ 1.26137517, 36.20055318],
         [ 1.26137517, 36.20524997]],

        [[ 1.25688356, 36.1770692 ],
         [ 1.25688356, 36.181766  ],
         [ 1.25688356, 36.18646279],
         [ 1.25688356, 36.19115959],
         [ 1.25688356, 36.19585638],
         [ 1.25688356, 36.20055318],
         [ 1.25688356, 36.20524997]],

        [[ 1.25239194, 36.1770692 ],
         [ 1.25239194, 36.181766  ],
         [ 1.25239194, 36.18646279],
         [ 1.25239194, 36.19115959],
         [ 1.25239194, 36.19585638],
         [ 1.25239194, 36.20055318],
         [ 1.25239194, 36.20524997]],

        [[ 1.24790032, 36.1770692 ],
         [ 1.24790032, 36.181766  ],
         [ 1.24790032, 36.18646279],
         [ 1.24790032, 36.19115959],
         [ 1.24790032, 36.19585638],
         [ 1.24790032, 36.20055318],
         [ 1.24790032, 36.20524997]]]),
 array([[[ 1.33324104, 36.1770692 ],
         [ 1.33324104, 36.181766  ],
         [ 1.33324104, 36.18646279],
         [ 1.33324104, 36.19115959],
         [ 1.33324104, 36.19585638],
         [ 1.33324104, 36.20055318],
         [ 1.33324104, 36.20524997]],

        [[ 1.32874942, 36.1770692 ],
         [ 1.32874942, 36.181766  ],
         [ 1.32874942, 36.18646279],
         [ 1.32874942, 36.19115959],
         [ 1.32874942, 36.19585638],
         [ 1.32874942, 36.20055318],
         [ 1.32874942, 36.20524997]],

        [[ 1.32425781, 36.1770692 ],
         [ 1.32425781, 36.181766  ],
         [ 1.32425781, 36.18646279],
         [ 1.32425781, 36.19115959],
         [ 1.32425781, 36.19585638],
         [ 1.32425781, 36.20055318],
         [ 1.32425781, 36.20524997]],

        [[ 1.31976619, 36.1770692 ],
         [ 1.31976619, 36.181766  ],
         [ 1.31976619, 36.18646279],
         [ 1.31976619, 36.19115959],
         [ 1.31976619, 36.19585638],
         [ 1.31976619, 36.20055318],
         [ 1.31976619, 36.20524997]],

        [[ 1.31527457, 36.1770692 ],
         [ 1.31527457, 36.181766  ],
         [ 1.31527457, 36.18646279],
         [ 1.31527457, 36.19115959],
         [ 1.31527457, 36.19585638],
         [ 1.31527457, 36.20055318],
         [ 1.31527457, 36.20524997]],

        [[ 1.31078296, 36.1770692 ],
         [ 1.31078296, 36.181766  ],
         [ 1.31078296, 36.18646279],
         [ 1.31078296, 36.19115959],
         [ 1.31078296, 36.19585638],
         [ 1.31078296, 36.20055318],
         [ 1.31078296, 36.20524997]],

        [[ 1.30629134, 36.1770692 ],
         [ 1.30629134, 36.181766  ],
         [ 1.30629134, 36.18646279],
         [ 1.30629134, 36.19115959],

In [ ]:
transform_shape("../Maps/ParentMaterial/Rock_type/geo7_2ag.shp" , "GLG"  , "../Maps/ParentMaterial/Rock_type/tiff/rocksType_1km.tif")
rocks_window = window_forming("../Maps/ParentMaterial/Rock_type/tiff", df_unique)
np.save("../Data_multi_CNN/rocks.npy", rocks_window)
rocks_window

,AREA,PERIMETER,GEO2_7G_,GEO2_7G_ID,GLG,geometry,category_numeric
0,2250.44404,966.65344,2,11939,SEA,"POLYGON ((5.40701 5.57146, 5.4109 5.4694, 5.42...",0
1,1.60529,7.58497,3,6,oth,"POLYGON ((15.64759 40.00266, 15.66 40, 15.676 ...",1
2,7.02790,33.05255,4,3,oth,"POLYGON ((19.89965 39.96591, 22.81549 39.8342,...",1
3,0.06592,1.66218,5,7,oth,"POLYGON ((19.67681 39.78778, 19.7106 39.7867, ...",1
4,0.90818,4.50544,6,4,oth,"POLYGON ((8.40944 39.76892, 9.63446 39.84441, ...",1
...,...,...,...,...,...,...,...
11972,0.01677,0.69987,11974,11935,SO,"POLYGON ((19.69988 -34.58595, 19.70456 -34.581...",31
11973,0.00456,0.35706,11975,11936,D,"POLYGON ((19.69988 -34.58595, 19.70059 -34.602...",27
11974,0.00239,0.20456,11976,11934,pCm,"POLYGON ((19.43258 -34.60229, 19.40437 -34.627...",11
11975,0.00641,0.35766,11977,11938,SO,"POLYGON ((19.84761 -34.67162, 19.85932 -34.661...",31
11976,0.00790,0.45490,11978,11937,pCm,"POLYGON ((19.84761 -34.67162, 19.85032 -34.677...",11

In [ ]:
def outputs_building(df ,df_unique, atr):
    depth_ranges = [
        (0, 15),
        (5, 15),
        (15, 30),
        (30, 60),
        (60, 100),
        (100, 200)
    ]
    result_array = np.zeros((531, 6))
    depth_indices = {i: [] for i in range(len(depth_ranges))}

    for i, (lb, ub) in enumerate(depth_ranges):
        for j in range(lb, ub + 1):
            depth_indices[i].append(j)
    
    for _, row in df.iterrows():
        x, y, ud, ld, val = row['X'], row['Y'], row['UD'], row['LD'] , row[atr]
        for index, depth_range in depth_indices.items():
            if any(d in range(int(ud), int(ld) + 1) for d in depth_range):
                result_array[df_unique[(df_unique['X'] == x) & (df_unique['Y'] == y)].index[0], index] = val

    mean = df[atr].mean()
    result_array = np.nan_to_num(result_array, nan=mean)
    finals = np.array(result_array).reshape(531,6,1)
    for i in finals:
        print(i)
    
    print(finals.shape)
    return finals

In [ ]:
df_unique = df_unique.reset_index()
df_unique

,index,X,Y,UD,LD,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM%,Ranges
0,0,-0.094551,35.786824,0.0,5.0,7.110377,6.404642,7.311231,12.333685,18.140976,74.547794,0.893930,2.306617,0.533126,0_5
1,1,-0.094682,35.783222,0.0,5.0,7.576187,6.028645,8.795516,4.101079,7.912891,83.291593,0.000000,2.247701,0.567299,0_5
2,2,-0.094814,35.779620,0.0,5.0,7.557264,5.292950,6.339849,4.232644,23.833469,69.783936,1.329243,2.392225,0.745866,0_5
3,3,-0.094945,35.776018,0.0,5.0,7.668368,3.400624,3.270652,14.641522,50.034298,46.695050,2.763003,2.696493,0.676091,0_5
4,4,-0.095076,35.772417,0.0,5.0,7.051867,2.440479,1.517456,9.439977,39.378934,59.103610,3.200028,3.605780,0.653315,0_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,526,7.698333,36.781111,0.0,5.0,8.299528,383.853774,30.381132,0.099906,38.016981,27.490613,0.224196,0.000000,1.004885,0_5
527,527,7.992500,36.848611,0.0,5.0,5.687539,28.007083,4.610997,0.121828,26.872473,68.516530,1.761085,2.698702,48.783917,0_5
528,528,8.200000,36.900000,0.0,5.0,5.614928,23.527257,3.171597,0.100015,42.066458,54.761945,2.579962,2.843597,34.722968,0_5
529,529,8.386667,37.064444,0.0,5.0,5.094341,27.049788,12.245741,0.100000,24.879419,62.874878,0.708640,1.635620,27.972723,0_5
530,530,8.414167,37.094722,0.0,5.0,6.155947,28.007083,6.124133,0.100000,24.729042,69.146825,1.396141,2.424040,11.010841,0_5

In [ ]:
df_unique = df_unique.drop(columns=["index"])
df_unique

,X,Y,UD,LD,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM%,Ranges
0,-0.094551,35.786824,0.0,5.0,7.110377,6.404642,7.311231,12.333685,18.140976,74.547794,0.893930,2.306617,0.533126,0_5
1,-0.094682,35.783222,0.0,5.0,7.576187,6.028645,8.795516,4.101079,7.912891,83.291593,0.000000,2.247701,0.567299,0_5
2,-0.094814,35.779620,0.0,5.0,7.557264,5.292950,6.339849,4.232644,23.833469,69.783936,1.329243,2.392225,0.745866,0_5
3,-0.094945,35.776018,0.0,5.0,7.668368,3.400624,3.270652,14.641522,50.034298,46.695050,2.763003,2.696493,0.676091,0_5
4,-0.095076,35.772417,0.0,5.0,7.051867,2.440479,1.517456,9.439977,39.378934,59.103610,3.200028,3.605780,0.653315,0_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526,7.698333,36.781111,0.0,5.0,8.299528,383.853774,30.381132,0.099906,38.016981,27.490613,0.224196,0.000000,1.004885,0_5
527,7.992500,36.848611,0.0,5.0,5.687539,28.007083,4.610997,0.121828,26.872473,68.516530,1.761085,2.698702,48.783917,0_5
528,8.200000,36.900000,0.0,5.0,5.614928,23.527257,3.171597,0.100015,42.066458,54.761945,2.579962,2.843597,34.722968,0_5
529,8.386667,37.064444,0.0,5.0,5.094341,27.049788,12.245741,0.100000,24.879419,62.874878,0.708640,1.635620,27.972723,0_5
530,8.414167,37.094722,0.0,5.0,6.155947,28.007083,6.124133,0.100000,24.729042,69.146825,1.396141,2.424040,11.010841,0_5

In [ ]:
df

,X,Y,UD,LD,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM%,Ranges
0,-0.094551,35.786824,0.0,5.0,7.110377,6.404642,7.311231,12.333685,18.140976,74.547794,0.893930,2.306617,0.533126,0_5
1,-0.094551,35.786824,5.0,15.0,7.144755,6.190028,7.048924,11.847969,18.278750,74.672326,0.946038,2.353142,0.467774,5_15
2,-0.094551,35.786824,15.0,30.0,7.293732,5.262191,5.915067,9.743061,18.874708,75.210226,1.171362,2.554309,0.474109,15_30
3,-0.094551,35.786824,30.0,60.0,7.591430,3.901625,4.290227,5.525814,19.820767,75.889006,1.512805,2.855176,0.356968,30_60
4,-0.094551,35.786824,60.0,100.0,7.651464,6.050623,7.109795,4.621229,18.809306,74.080899,1.047307,2.419303,0.262489,60_100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3181,8.414167,37.094722,5.0,15.0,6.177699,28.007083,6.131968,0.100000,24.892460,68.975573,1.401231,2.420257,11.696769,5_15
3182,8.414167,37.094722,15.0,30.0,6.271719,26.751345,6.165818,0.100000,25.601487,68.232695,1.423329,2.403869,14.661547,15_30
3183,8.414167,37.094722,30.0,60.0,6.405402,20.919296,6.210706,0.100000,27.210403,66.578892,1.477367,2.372119,18.866199,30_60
3184,8.414167,37.094722,60.0,100.0,6.314960,19.177498,6.166735,0.100000,28.642714,65.190550,1.535705,2.358143,15.976235,60_100
3185,8.414167,37.094722,100.0,200.0,6.254627,10.323197,6.139571,0.100000,29.196387,64.664042,1.559496,2.354472,14.055585,100_200

In [ ]:
for i in df.columns[4:-1]:
    print(i)
    finals = outputs_building(df ,df_unique, i)
    np.save(f'../Data_multi_CNN/output{i}.npy', np.array(finals))

pH
[[7.29373154]
 [7.29373154]
 [7.59143019]
 [7.65146429]
 [7.57452488]
 [7.57452488]]
[[7.58622173]
 [7.58622173]
 [7.60088013]
 [7.60088648]
 [7.59851575]
 [7.59851575]]
[[7.66997854]
 [7.66997854]
 [7.89051155]
 [8.11582066]
 [8.21838373]
 [8.21838373]]
[[7.67130487]
 [7.67130487]
 [7.67487779]
 [7.6563084 ]
 [7.62556016]
 [7.62556016]]
[[7.01251675]
 [7.01251675]
 [6.97049256]
 [7.26538293]
 [7.73813716]
 [7.73813716]]
[[7.25033398]
 [7.25033398]
 [7.61246254]
 [7.6451182 ]
 [7.60468725]
 [7.60468725]]
[[7.68976514]
 [7.68976514]
 [7.78616511]
 [8.1666771 ]
 [8.36276623]
 [8.36276623]]
[[7.79399611]
 [7.79399611]
 [8.09441163]
 [8.23945213]
 [8.18851021]
 [8.18851021]]
[[7.60929194]
 [7.60929194]
 [7.69755855]
 [7.98712567]
 [8.03154272]
 [8.03154272]]
[[7.72736942]
 [7.72736942]
 [7.72165181]
 [7.77229999]
 [7.89785135]
 [7.89785135]]
[[7.68617442]
 [7.68617442]
 [7.68698331]
 [7.83417455]
 [8.1644042 ]
 [8.1644042 ]]
[[7.74655942]
 [7.74655942]
 [8.09349752]
 [8.11900094]
 [8.15563015]
 [8.15563015]]
[[7.71279681]
 [7.71279681]
 [7.96674721]
 [8.20716909]
 [8.25445257]
 [8.25445257]]
[[8.07271094]
 [8.07271094]
 [8.11402217]
 [8.13283286]
 [8.15563015]
 [8.15563015]]
[[7.91849526]
 [7.91849526]
 [8.0233868 ]
 [8.18137605]
 [8.27293243]
 [8.27293243]]
[[8.19066343]
 [8.19066343]
 [8.18697209]
 [8.07361183]
 [8.1410918 ]
 [8.1410918 ]]
[[7.93863731]
 [7.93863731]
 [8.14034284]
 [8.07361183]
 [8.1410918 ]
 [8.1410918 ]]
[[7.9432595 ]
 [7.9432595 ]
 [7.74418924]
 [7.88061976]
 [8.20789254]
 [8.20789254]]
[[7.88302704]
 [7.88302704]
 [7.88848293]
 [7.96405104]
 [8.02734961]
 [8.02734961]]
[[8.13595909]
 [8.13595909]
 [8.05990967]
 [8.08538223]
 [8.11675817]
 [8.11675817]]
[[8.19635109]
 [8.19635109]
 [8.19781504]
 [8.21890678]
 [8.23526762]
 [8.23526762]]
[[8.11116139]
 [8.11116139]
 [8.20090498]
 [8.12933959]
 [8.14256876]
 [8.14256876]]
[[7.87643955]
 [7.87643955]
 [8.24830136]
 [8.21909935]
 [8.11819109]
 [8.11819109]]
[[8.07095231]
 [8.07095231]
 [8.0866223 ]
 [8.15925855]
 [8.21527733]
 [8.21527733]]
[[8.04486335]
 [8.04486335]
 [8.11011511]
 [8.17809139]
 [8.20578019]
 [8.20578019]]
[[7.64406   ]
 [7.64406   ]
 [7.84080223]
 [7.97187632]
 [7.96748187]
 [7.96748187]]
[[7.83572122]
 [7.83572122]
 [7.68543083]
 [8.13971819]
 [8.14747874]
 [8.14747874]]
[[8.24010833]
 [8.24010833]
 [8.28004453]
 [8.31250176]
 [8.32557885]
 [8.32557885]]
[[8.16113977]
 [8.16113977]
 [8.17279211]
 [8.13924753]
 [8.16042851]
 [8.16042851]]
[[8.12091541]
 [8.12091541]
 [8.15050227]
 [8.16147281]
 [8.16272658]
 [8.16272658]]
[[8.13385176]
 [8.13385176]
 [8.20120436]
 [8.18395964]
 [8.13645075]
 [8.13645075]]
[[7.98750688]
 [7.98750688]
 [8.08595727]
 [8.2195319 ]
 [8.27406287]
 [8.27406287]]
[[8.1880492 ]
 [8.1880492 ]
 [8.24703998]
 [8.18688393]
 [8.16238054]
 [8.16238054]]
[[8.07480662]
 [8.07480662]
 [8.09946933]
 [8.15868693]
 [8.18293991]
 [8.18293991]]
[[8.1667394 ]
 [8.1667394 ]
 [8.23519774]
 [8.04759439]
 [7.83815784]
 [7.83815784]]
[[8.20506348]
 [8.20506348]
 [8.21141113]
 [8.15091422]
 [8.11750758]
 [8.11750758]]
[[8.1968618 ]
 [8.1968618 ]
 [8.18954678]
 [8.19390684]
 [8.20206237]
 [8.20206237]]
[[8.06989308]
 [8.06989308]
 [8.17504588]
 [8.20991031]
 [8.19443027]
 [8.19443027]]
[[8.05804824]
 [8.05804824]
 [8.08548115]
 [8.15149553]
 [8.20962935]
 [8.20962935]]
[[8.1649965 ]
 [8.1649965 ]
 [8.11788842]
 [8.09195087]
 [8.10121698]
 [8.10121698]]
[[7.97008716]
 [7.97008716]
 [8.05036853]
 [8.09799124]
 [7.85625287]
 [7.85625287]]
[[7.46528418]
 [7.46528418]
 [7.11028929]
 [7.09553794]
 [7.11845514]
 [7.11845514]]
[[7.6366419 ]
 [7.6366419 ]
 [7.4765357 ]
 [7.59276123]
 [7.65753262]
 [7.65753262]]
[[8.11059823]
 [8.11059823]
 [8.11476198]
 [8.12878216]
 [8.14962277]
 [8.14962277]]
[[7.91356689]
 [7.91356689]
 [7.97488489]
 [8.00166643]
 [7.98691313]
 [7.98691313]]
[[8.21507711]
 [8.21507711]
 [8.23155139]
 [8.2403625 ]
 [8.23969557]
 [8.23969557]]
[[8.38346014]
 [8.38346014]
 [8.13851789]
 [8.34526134]
 [7.60525838]
 [7.60525838]]
[[8.19636672]
 [8.19636672]
 [7.97098119]
 [8.311754  ]
 [7.60525838]
 [7.60525838]]
[[8.32413729]
 [8.32413729]
 [8.22061224]
 [8.36168021]
 [7.60525838]
 [7.60525838]]
[[7.95197123]
 [7.95197123]
 [8.12105628]
 [8.07257024]
 [7.95126765]
 [7.95126765]]
[[8.02025974]
 [8.02025974]
 [7.9326461 ]
 [6.34304887]
 [5.16667698]
 [5.16667698]]
[[8.2997114 ]
 [8.2997114 ]
 [8.39705988]
 [6.49203137]
 [5.47189519]
 [5.47189519]]
[[7.81144036]
 [7.81144036]
 [7.91275   ]
 [7.78533625]
 [7.78918483]
 [7.78918483]]
[[7.32751253]
 [7.32751253]
 [4.99742076]
 [4.91529821]
 [2.5361572 ]
 [2.5361572 ]]
[[7.82307293]
 [7.82307293]
 [7.59453371]
 [7.27218052]
 [6.78151502]
 [6.78151502]]
[[7.86358344]
 [7.86358344]
 [7.04203363]
 [5.63544714]
 [3.48496478]
 [3.48496478]]
[[7.12153439]
 [7.12153439]
 [3.08125392]
 [0.90165326]
 [4.65943871]
 [4.65943871]]
[[8.30286094]
 [8.30286094]
 [7.81705591]
 [6.7038837 ]
 [4.88839157]
 [4.88839157]]
[[7.36279124]
 [7.36279124]
 [5.7093136 ]
 [3.39493283]
 [0.46757109]
 [0.46757109]]
[[8.24003438]
 [8.24003438]
 [6.55030118]
 [3.9962577 ]
 [0.6331339 ]
 [0.6331339 ]]
[[6.07882236]
 [6.07882236]
 [4.63489805]
 [4.77743367]
 [4.65943871]
 [4.65943871]]
[[5.70033351]
 [5.70033351]
 [1.48992716]
 [4.51648459]
 [4.65943871]
 [4.65943871]]
[[7.67680702]
 [7.67680702]
 [5.13562618]
 [4.04930514]
 [5.17563354]
 [5.17563354]]
[[5.94263682]
 [5.94263682]
 [4.27433389]
 [4.51648459]
 [4.65943871]
 [4.65943871]]
[[8.11495665]
 [8.11495665]
 [3.5429193 ]
 [4.58272159]
 [5.14744316]
 [5.14744316]]
[[7.53072431]
 [7.53072431]
 [6.23546553]
 [4.27767287]
 [1.3136012 ]
 [1.3136012 ]]
[[7.81483691]
 [7.81483691]
 [7.28593163]
 [6.34806868]
 [4.90982167]
 [4.90982167]]
[[7.75950617]
 [7.75950617]
 [7.70110308]
 [7.66539411]
 [3.67810457]
 [3.67810457]]
[[6.71214736]
 [6.71214736]
 [5.44342214]
 [4.25809748]
 [4.65943871]
 [4.65943871]]
[[8.15713964]
 [8.15713964]
 [8.36403173]
 [4.51648459]
 [4.65943871]
 [4.65943871]]
[[7.95075333]
 [7.95075333]
 [6.82352071]
 [6.06939711]
 [5.17563354]
 [5.17563354]]
[[6.2025955 ]
 [6.2025955 ]
 [2.3348404 ]
 [0.71851387]
 [5.14744316]
 [5.14744316]]
[[8.51814815]
 [8.51814815]
 [7.11647381]
 [6.25945869]
 [3.15359339]
 [3.15359339]]
[[7.43802474]
 [7.43802474]
 [3.2132563 ]
 [0.14870676]
 [2.37758047]
 [2.37758047]]
[[7.75764105]
 [7.75764105]
 [5.91648657]
 [4.51692374]
 [2.37758047]
 [2.37758047]]
[[8.54206665]
 [8.54206665]
 [7.15745333]
 [4.97863341]
 [2.37758047]
 [2.37758047]]
[[6.84386454]
 [6.84386454]
 [4.4224502 ]
 [4.1703646 ]
 [1.698508  ]
 [1.698508  ]]
[[7.20592316]
 [7.20592316]
 [6.5244227 ]
 [3.79824375]
 [4.65943871]
 [4.65943871]]
[[7.81294372]
 [7.81294372]
 [5.03111061]
 [4.88762786]
 [4.65943871]
 [4.65943871]]
[[7.85511248]
 [7.85511248]
 [6.95990455]
 [5.37250813]
 [2.93817789]
 [2.93817789]]
[[5.63337177]
 [5.63337177]
 [4.36972413]
 [4.97542496]
 [5.14744316]
 [5.14744316]]
[[6.88296481]
 [6.88296481]
 [4.66378371]
 [4.1703646 ]
 [1.698508  ]
 [1.698508  ]]
[[8.38558629]
 [8.38558629]
 [5.77292825]
 [1.74062349]
 [0.78249229]
 [0.78249229]]
[[8.50127822]
 [8.50127822]
 [7.08735851]
 [4.48920024]
 [0.85349092]
 [0.85349092]]
[[7.71170359]
 [7.71170359]
 [6.51753815]
 [4.85818376]
 [2.33242014]
 [2.33242014]]
[[5.73404185]
 [5.73404185]
 [2.17571926]
 [4.57971597]
 [4.65943871]
 [4.65943871]]
[[5.11646993]
 [5.11646993]
 [1.60458015]
 [3.89071606]
 [4.65943871]
 [4.65943871]]
[[7.90254177]
 [7.90254177]
 [7.88348761]
 [7.85681741]
 [7.81622173]
 [7.81622173]]
[[7.85089306]
 [7.85089306]
 [8.33149466]
 [8.49842444]
 [2.08284709]
 [2.08284709]]
[[7.87241811]
 [7.87241811]
 [6.90166306]
 [5.23962027]
 [2.69857946]
 [2.69857946]]
[[8.11894667]
 [8.11894667]
 [8.07782855]
 [8.00862908]
 [7.90295636]
 [7.90295636]]
[[7.88975861]
 [7.88975861]
 [4.25269226]
 [2.16203601]
 [4.65943871]
 [4.65943871]]
[[8.25242794]
 [8.25242794]
 [5.42809383]
 [1.4526242 ]
 [4.65943871]
 [4.65943871]]
[[7.8351171 ]
 [7.8351171 ]
 [7.09766204]
 [4.40944282]
 [4.65943871]
 [4.65943871]]
[[7.696121  ]
 [7.696121  ]
 [6.2883055 ]
 [4.97542496]
 [4.627218  ]
 [4.627218  ]]
[[8.03080247]
 [8.03080247]
 [6.94304478]
 [6.27796534]
 [2.08284709]
 [2.08284709]]
[[7.77368248]
 [7.77368248]
 [6.78722687]
 [4.9745583 ]
 [2.18340773]
 [2.18340773]]
[[9.04013411]
 [9.04013411]
 [6.7749691 ]
 [2.5097457 ]
 [4.65943871]
 [4.65943871]]
[[7.12821033]
 [7.12821033]
 [4.94827491]
 [6.16030998]
 [4.64616789]
 [4.64616789]]
[[8.05642191]
 [8.05642191]
 [7.49223852]
 [6.45551931]
 [4.85917705]
 [4.85917705]]
[[8.19463715]
 [8.19463715]
 [8.64224346]
 [6.16030998]
 [4.64616789]
 [4.64616789]]
[[8.36034233]
 [8.36034233]
 [5.75521644]
 [4.47376608]
 [4.98087964]
 [4.98087964]]
[[7.72724743]
 [7.72724743]
 [7.32978216]
 [6.1239071 ]
 [4.55498833]
 [4.55498833]]
[[8.00443086]
 [8.00443086]
 [7.54659545]
 [6.64293895]
 [5.23524758]
 [5.23524758]]
[[7.30276753]
 [7.30276753]
 [5.20756458]
 [6.16030998]
 [4.64616789]
 [4.64616789]]
[[7.96666224]
 [7.96666224]
 [7.53930897]
 [6.8076317 ]
 [5.68899513]
 [5.68899513]]
[[6.70239143]
 [6.70239143]
 [3.42286853]
 [5.47289218]
 [3.88199726]
 [3.88199726]]
[[6.73286232]
 [6.73286232]
 [2.00867754]
 [5.42392035]
 [3.3025024 ]
 [3.3025024 ]]
[[7.68000161]
 [7.68000161]
 [4.90754472]
 [5.58461105]
 [6.04425019]
 [6.04425019]]
[[7.6934086 ]
 [7.6934086 ]
 [7.10936392]
 [6.28557244]
 [5.0316495 ]
 [5.0316495 ]]
[[7.60415103]
 [7.60415103]
 [6.73800129]
 [4.85097555]
 [3.92393608]
 [3.92393608]]
[[7.65920434]
 [7.65920434]
 [7.25384676]
 [4.85097555]
 [3.92393608]
 [3.92393608]]
[[4.75931443]
 [4.75931443]
 [1.31661088]
 [5.55531379]
 [3.3025024 ]
 [3.3025024 ]]
[[7.46913753]
 [7.46913753]
 [7.06608392]
 [5.74474166]
 [3.38656489]
 [3.38656489]]
[[8.01386313]
 [8.01386313]
 [4.77631871]
 [1.36393562]
 [2.65388876]
 [2.65388876]]
[[8.49422945]
 [8.49422945]
 [7.96749247]
 [6.77859084]
 [4.85236716]
 [4.85236716]]
[[7.83181939]
 [7.83181939]
 [6.65781063]
 [4.92493647]
 [2.28726575]
 [2.28726575]]
[[7.82076715]
 [7.82076715]
 [6.78578015]
 [5.2213901 ]
 [2.8401289 ]
 [2.8401289 ]]
[[7.72527992]
 [7.72527992]
 [7.32719551]
 [6.76808065]
 [5.91703161]
 [5.91703161]]
[[7.38094972]
 [7.38094972]
 [6.91634858]
 [6.26905046]
 [5.28377449]
 [5.28377449]]
[[8.00280734]
 [8.00280734]
 [8.14358039]
 [8.46614734]
 [8.99222744]
 [8.99222744]]
[[8.02790062]
 [8.02790062]
 [7.46038848]
 [6.3795058 ]
 [4.70648611]
 [4.70648611]]
[[7.93751414]
 [7.93751414]
 [3.18903412]
 [5.3781674 ]
 [3.1635516 ]
 [3.1635516 ]]
[[5.58146977]
 [5.58146977]
 [3.0226613 ]
 [3.56675645]
 [4.74636031]
 [4.74636031]]
[[7.03137496]
 [7.03137496]
 [4.04067035]
 [4.13600037]
 [5.05429111]
 [5.05429111]]
[[6.87181638]
 [6.87181638]
 [3.65804106]
 [1.79271999]
 [5.34557251]
 [5.34557251]]
[[8.21373234]
 [8.21373234]
 [8.2242754 ]
 [8.25141749]
 [8.29980022]
 [8.29980022]]
[[7.58664011]
 [7.58664011]
 [6.43743435]
 [4.7411702 ]
 [2.15922492]
 [2.15922492]]
[[7.57506652]
 [7.57506652]
 [4.51618574]
 [1.51527162]
 [5.10362722]
 [5.10362722]]
[[8.76997923]
 [8.76997923]
 [7.78224269]
 [5.69243818]
 [2.38201521]
 [2.38201521]]
[[7.96806708]
 [7.96806708]
 [7.52773262]
 [6.59609458]
 [5.12030296]
 [5.12030296]]
[[7.00346946]
 [7.00346946]
 [5.88940128]
 [4.24500133]
 [1.74200042]
 [1.74200042]]
[[7.78386336]
 [7.78386336]
 [6.57400626]
 [4.74529884]
 [1.96170274]
 [1.96170274]]
[[7.69467463]
 [7.69467463]
 [6.58680721]
 [4.95155976]
 [2.46249021]
 [2.46249021]]
[[7.9636744 ]
 [7.9636744 ]
 [6.89656645]
 [5.13073327]
 [2.43675443]
 [2.43675443]]
[[7.42915099]
 [7.42915099]
 [3.66231271]
 [1.10323159]
 [3.78289844]
 [3.78289844]]
[[7.82771279]
 [7.82771279]
 [7.28976117]
 [6.45390897]
 [5.18130277]
 [5.18130277]]
[[8.7984604 ]
 [8.7984604 ]
 [7.93742102]
 [5.99396316]
 [2.84522952]
 [2.84522952]]
[[7.64865317]
 [7.64865317]
 [7.15896032]
 [6.17519976]
 [4.63707448]
 [4.63707448]]
[[7.91507636]
 [7.91507636]
 [6.80927585]
 [5.17707924]
 [2.69265348]
 [2.69265348]]
[[5.43233795]
 [5.43233795]
 [4.38066376]
 [4.92612199]
 [5.76395542]
 [5.76395542]]
[[7.94936587]
 [7.94936587]
 [6.71128269]
 [4.88383265]
 [2.10220455]
 [2.10220455]]
[[8.07170404]
 [8.07170404]
 [4.41720717]
 [0.99021525]
 [3.40920323]
 [3.40920323]]
[[7.64739669]
 [7.64739669]
 [6.59357612]
 [4.93158291]
 [2.40045741]
 [2.40045741]]
[[8.28393821]
 [8.28393821]
 [7.48059844]
 [5.7237047 ]
 [2.91126216]
 [2.91126216]]
[[7.81603991]
 [7.81603991]
 [7.24425041]
 [6.23034452]
 [4.67548288]
 [4.67548288]]
[[7.27538899]
 [7.27538899]
 [5.28969137]
 [4.06598966]
 [3.41142156]
 [3.41142156]]
[[7.50094235]
 [7.50094235]
 [3.95834463]
 [0.81733617]
 [4.0312529 ]
 [4.0312529 ]]
[[7.16913858]
 [7.16913858]
 [6.91894631]
 [6.50493213]
 [5.87330655]
 [5.87330655]]
[[8.11964378]
 [8.11964378]
 [8.01327684]
 [7.84552426]
 [7.59004617]
 [7.59004617]]
[[8.30006972]
 [8.30006972]
 [7.88289404]
 [6.94128395]
 [5.41571479]
 [5.41571479]]
[[8.22904708]
 [8.22904708]
 [7.20059468]
 [5.02464555]
 [1.58862494]
 [1.58862494]]
[[8.28718043]
 [8.28718043]
 [7.73874861]
 [6.65627669]
 [4.97003155]
 [4.97003155]]
[[7.75178485]
 [7.75178485]
 [6.25475499]
 [5.13339125]
 [4.64877494]
 [4.64877494]]
[[7.92256197]
 [7.92256197]
 [6.97022733]
 [5.33972236]
 [2.84689863]
 [2.84689863]]
[[7.84560425]
 [7.84560425]
 [7.23731409]
 [6.03669627]
 [4.16640668]
 [4.16640668]]
[[7.56932764]
 [7.56932764]
 [7.04532292]
 [6.23114096]
 [4.99152825]
 [4.99152825]]
[[8.14864639]
 [8.14864639]
 [7.4839411 ]
 [6.3052755 ]
 [4.49774885]
 [4.49774885]]
[[7.66931007]
 [7.66931007]
 [7.27483565]
 [6.67858483]
 [5.77099215]
 [5.77099215]]
[[8.94906679]
 [8.94906679]
 [7.90389956]
 [5.7671707 ]
 [2.41293227]
 [2.41293227]]
[[7.5494245 ]
 [7.5494245 ]
 [5.69702192]
 [4.47005639]
 [4.64877494]
 [4.64877494]]
[[8.09620095]
 [8.09620095]
 [7.65936042]
 [6.67336467]
 [5.07588317]
 [5.07588317]]
[[8.12277164]
 [8.12277164]
 [7.8572962 ]
 [7.25808978]
 [6.28727305]
 [6.28727305]]
[[7.8938909 ]
 [7.8938909 ]
 [6.718367  ]
 [4.89187516]
 [2.11099493]
 [2.11099493]]
[[8.06118739]
 [8.06118739]
 [6.4256128 ]
 [5.31207011]
 [3.94461009]
 [3.94461009]]
[[7.4514905 ]
 [7.4514905 ]
 [4.93772509]
 [3.84926339]
 [4.81002623]
 [4.81002623]]
[[8.13805501]
 [8.13805501]
 [7.76985762]
 [6.96461465]
 [5.67557849]
 [5.67557849]]
[[7.99263104]
 [7.99263104]
 [7.59112434]
 [6.7702883 ]
 [5.4817393 ]
 [5.4817393 ]]
[[7.83265272]
 [7.83265272]
 [7.17744009]
 [6.21032546]
 [4.73824514]
 [4.73824514]]
[[8.22032822]
 [8.22032822]
 [5.84810493]
 [4.04286209]
 [4.72323296]
 [4.72323296]]
[[7.90398551]
 [7.90398551]
 [5.97279528]
 [4.50317506]
 [5.00594692]
 [5.00594692]]
[[8.39801445]
 [8.39801445]
 [6.59105384]
 [4.53740041]
 [4.85876618]
 [4.85876618]]
[[6.90567073]
 [6.90567073]
 [5.40429878]
 [6.22023573]
 [5.2489041 ]
 [5.2489041 ]]
[[6.78763514]
 [6.78763514]
 [4.9239527 ]
 [6.22023573]
 [5.2489041 ]
 [5.2489041 ]]
[[8.10057631]
 [8.10057631]
 [7.72355261]
 [7.05500842]
 [6.02977153]
 [6.02977153]]
[[7.61390919]
 [7.61390919]
 [5.40695315]
 [4.59207051]
 [5.2489041 ]
 [5.2489041 ]]
[[8.20415216]
 [8.20415216]
 [7.58551134]
 [6.54437395]
 [4.95447971]
 [4.95447971]]
[[8.61010633]
 [8.61010633]
 [8.09353985]
 [8.33626573]
 [7.60525838]
 [7.60525838]]
[[8.51698621]
 [8.51698621]
 [8.80688835]
 [8.47893543]
 [7.60525838]
 [7.60525838]]
[[8.09740741]
 [8.09740741]
 [8.13078884]
 [8.4194711 ]
 [7.97282889]
 [7.97282889]]
[[9.1892842 ]
 [9.1892842 ]
 [8.95357978]
 [8.77613864]
 [7.95952532]
 [7.95952532]]
[[8.11787995]
 [8.11787995]
 [8.66668212]
 [8.16788384]
 [7.60525838]
 [7.60525838]]
[[8.39929924]
 [8.39929924]
 [8.39378906]
 [8.11330523]
 [7.60525838]
 [7.60525838]]
[[8.28773504]
 [8.28773504]
 [8.509671  ]
 [8.16788384]
 [7.60525838]
 [7.60525838]]
[[8.30819883]
 [8.30819883]
 [8.2746989 ]
 [8.28999982]
 [7.60525838]
 [7.60525838]]
[[8.37403296]
 [8.37403296]
 [8.04569112]
 [7.97848376]
 [7.60525838]
 [7.60525838]]
[[7.70090987]
 [7.70090987]
 [7.71968173]
 [7.97848376]
 [7.60525838]
 [7.60525838]]
[[7.70050043]
 [7.70050043]
 [6.78135424]
 [7.79081826]
 [7.60525838]
 [7.60525838]]
[[8.90444984]
 [8.90444984]
 [8.65712985]
 [7.89999256]
 [7.60525838]
 [7.60525838]]
[[8.91804554]
 [8.91804554]
 [8.55605506]
 [7.89999256]
 [7.60525838]
 [7.60525838]]
[[8.22628122]
 [8.22628122]
 [8.29729648]
 [7.89999256]
 [7.60525838]
 [7.60525838]]
[[8.64625913]
 [8.64625913]
 [8.51423473]
 [7.89999256]
 [7.60525838]
 [7.60525838]]
[[9.56446823]
 [9.56446823]
 [9.72185773]
 [7.89999256]
 [7.60525838]
 [7.60525838]]
[[8.12218841]
 [8.12218841]
 [7.97530021]
 [8.22072954]
 [8.09665913]
 [8.09665913]]
[[8.54893728]
 [8.54893728]
 [8.57913667]
 [8.22072954]
 [8.09665913]
 [8.09665913]]
[[8.51529372]
 [8.51529372]
 [8.54321965]
 [8.22072954]
 [8.09665913]
 [8.09665913]]
[[8.60470534]
 [8.60470534]
 [8.57219915]
 [8.53661346]
 [8.09665913]
 [8.09665913]]
[[8.33076389]
 [8.33076389]
 [8.30711628]
 [8.22072954]
 [8.09665913]
 [8.09665913]]
[[8.69148782]
 [8.69148782]
 [8.74755791]
 [8.22072954]
 [8.09665913]
 [8.09665913]]
[[8.73625296]
 [8.73625296]
 [8.8067249 ]
 [8.22072954]
 [8.09665913]
 [8.09665913]]
[[8.57274584]
 [8.57274584]
 [8.49106458]
 [8.46963408]
 [8.08753466]
 [8.08753466]]
[[7.75350821]
 [7.75350821]
 [7.22137449]
 [7.31025158]
 [7.56958644]
 [7.56958644]]
[[7.99212227]
 [7.99212227]
 [8.00948372]
 [8.05751895]
 [8.14020253]
 [8.14020253]]
[[8.01934642]
 [8.01934642]
 [8.06853721]
 [8.20463702]
 [8.43890718]
 [8.43890718]]
[[7.9765917 ]
 [7.9765917 ]
 [7.98961279]
 [8.02563921]
 [8.0876519 ]
 [8.0876519 ]]
[[7.21544274]
 [7.21544274]
 [7.22168928]
 [8.28554268]
 [8.68432989]
 [8.68432989]]
[[8.80500602]
 [8.80500602]
 [8.29588182]
 [8.01221208]
 [8.18413559]
 [8.18413559]]
[[7.91260433]
 [7.91260433]
 [8.28153491]
 [8.4870927 ]
 [8.18413559]
 [8.18413559]]
[[8.14195626]
 [8.14195626]
 [8.16409209]
 [8.17642556]
 [8.18413559]
 [8.18413559]]
[[8.77722323]
 [8.77722323]
 [8.35168377]
 [8.14740449]
 [7.60525838]
 [7.60525838]]
[[8.45734682]
 [8.45734682]
 [8.09210026]
 [8.37424586]
 [7.60525838]
 [7.60525838]]
[[8.02673957]
 [8.02673957]
 [7.98984651]
 [7.96929073]
 [8.18413559]
 [8.18413559]]
[[7.58726391]
 [7.58726391]
 [7.5822924 ]
 [7.60641903]
 [7.65484316]
 [7.65484316]]
[[7.7684283 ]
 [7.7684283 ]
 [7.88347262]
 [7.71278785]
 [7.61790851]
 [7.61790851]]
[[7.87679793]
 [7.87679793]
 [7.94388493]
 [7.71888473]
 [7.80472877]
 [7.80472877]]
[[7.68235196]
 [7.68235196]
 [7.74849211]
 [7.49802479]
 [7.22099068]
 [7.22099068]]
[[7.76133791]
 [7.76133791]
 [7.79885017]
 [7.72507308]
 [7.51075213]
 [7.51075213]]
[[7.80141235]
 [7.80141235]
 [7.54921717]
 [7.59698751]
 [7.52083841]
 [7.52083841]]
[[8.19239674]
 [8.19239674]
 [8.08139052]
 [7.99641792]
 [8.07841403]
 [8.07841403]]
[[7.83518538]
 [7.83518538]
 [7.80295014]
 [7.53607272]
 [7.67236183]
 [7.67236183]]
[[7.70843748]
 [7.70843748]
 [7.70583601]
 [7.50988453]
 [7.51625051]
 [7.51625051]]
[[8.17734344]
 [8.17734344]
 [8.18941508]
 [7.62108243]
 [7.48077363]
 [7.48077363]]
[[7.93313656]
 [7.93313656]
 [8.0117489 ]
 [7.89051882]
 [7.75262531]
 [7.75262531]]
[[8.30301665]
 [8.30301665]
 [8.09603864]
 [7.96631574]
 [7.76922807]
 [7.76922807]]
[[8.2338216 ]
 [8.2338216 ]
 [8.30026224]
 [8.50810184]
 [8.44754121]
 [8.44754121]]
[[8.09169638]
 [8.09169638]
 [8.03486834]
 [8.09062588]
 [8.19698875]
 [8.19698875]]
[[7.54155079]
 [7.54155079]
 [7.43005689]
 [7.24355746]
 [8.13439479]
 [8.13439479]]
[[8.2737957 ]
 [8.2737957 ]
 [8.21952507]
 [8.17132226]
 [8.04996431]
 [8.04996431]]
[[7.96768369]
 [7.96768369]
 [7.57235369]
 [7.57993849]
 [7.61068134]
 [7.61068134]]
[[8.210036  ]
 [8.210036  ]
 [8.20287953]
 [8.34055768]
 [8.34736055]
 [8.34736055]]
[[8.07645631]
 [8.07645631]
 [7.96838592]
 [8.14495019]
 [8.08657209]
 [8.08657209]]
[[8.04274918]
 [8.04274918]
 [8.11238766]
 [8.14495019]
 [8.08657209]
 [8.08657209]]
[[7.43003825]
 [7.43003825]
 [7.52457881]
 [7.79898802]
 [7.60684344]
 [7.60684344]]
[[8.02389708]
 [8.02389708]
 [8.15185534]
 [7.99322275]
 [8.04170729]
 [8.04170729]]
[[8.        ]
 [8.        ]
 [8.        ]
 [8.03159629]
 [8.08100989]
 [8.08100989]]
[[8.03936302]