In [23]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import os 
import rasterio
from rasterio.transform import rowcol
from rasterio.transform import xy
from rasterio.windows import Window

# Data Explanation : 
1. Fauna : all animals distribution (amphibians , birds , mammals , reptiles) the data gives th nombre of birds , mammals ...etc in this area for example each pixel containe 1km²and the value is he number of animals in this area (form 0 --> 153  or 0 --> 178)

2. vegetation : the percentage of a specific land cover  (barren , evergreen, herbaceous) in speicific area (pixel)

3. human activities : gives the human modification in 1km² area between 0 and 1 

we can deduct somethings like : 
- High Species Richness + Low Human Modification → Biodiversity hotspots with low disturbance (ideal for conservation).
- High Species Richness + High Human Modification → Threatened ecosystems (urgent conservation priority).
- Low Species Richness + High Human Modification → Urban/agricultural areas with low ecological value.
- Low Species Richness + Low Human Modification → Natural areas with fewer species (e.g., deserts).

In [54]:
df = pd.read_csv("CombinedData.csv")
df = df.drop(columns=["USDA Soil Taxonomy" , "altitude"])
df = df.dropna(subset=["X" , "Y"])
df = df[(df['X'] >= 0) & (df['X'] <= 20) & ((df['Y'] >= 20) & (df['Y'] <= 50))]
df.fillna(df.mean(), inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2440 entries, 0 to 2891
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          2440 non-null   int64
 1   X                   2440 non-null   float64
 2   Y                   2440 non-null   float64
 3   UD                  2440 non-null   float64
 4   LD                  2440 non-null   float64
 5   average profondeur  2440 non-null   float64
 6   pH                  2440 non-null   float64
 7   CE                  2440 non-null   float64
 8   CEC                 2440 non-null   float64
 9   A%                  2440 non-null   float64
 10  L%                  2440 non-null   float64
 11  S%                  2440 non-null   float64
 12  ALR(L)              2440 non-null   float64
 13  ALR(S)              2440 non-null   float64
 14  OM                  2440 non-null   float64
dtypes: float64(14), int64(1)
memory usage: 305.0 KB

In [55]:
df = df.drop(columns=["Unnamed: 0"])
df

,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.10700,36.684000,15.0,30.0,22.5,7.870,0.170,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019000
1,3.10700,36.684000,30.0,60.0,45.0,7.774,0.170,17.207000,40.361496,37.281777,22.356727,-0.034471,-0.256559,1.503000
2,3.10700,36.684000,60.0,100.0,80.0,7.799,0.170,15.049000,49.608530,42.317043,8.074427,-0.069041,-0.788445,0.706000
3,3.13333,36.071667,15.0,30.0,22.5,7.950,0.260,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645000
4,3.13333,36.071667,30.0,60.0,45.0,8.096,0.279,40.610953,33.898341,39.248386,26.853273,0.063643,-0.101181,1.097000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2887,2.43000,27.190000,0.0,8.0,4.0,7.390,2.860,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,2.975432
2888,2.43000,27.190000,8.0,34.0,21.0,7.650,4.870,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,0.530000
2889,2.43000,27.190000,34.0,43.0,38.5,7.990,5.480,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,1.060000
2890,2.43000,27.190000,43.0,60.0,51.5,8.040,4.070,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,0.000000
2891,2.43000,27.190000,60.0,80.0,70.0,7.900,3.130,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,0.000000

In [63]:
df_unique = df.copy()
df_unique = df_unique.drop_duplicates(subset=["X" ,"Y"])
df_unique

,X,Y,UD,LD,average profondeur,pH,CE,CEC,A%,L%,S%,ALR(L),ALR(S),OM
0,3.107000,36.684000,15.0,30.0,22.5,7.87,0.170000,17.929000,46.172091,45.613249,8.214660,-0.005289,-0.749790,2.019000
3,3.133330,36.071667,15.0,30.0,22.5,7.95,0.260000,40.610953,32.330400,40.460456,27.209144,0.097420,-0.074896,2.645000
5,3.150000,36.724167,15.0,30.0,22.5,8.50,2.632808,40.610953,13.000000,32.000000,55.000000,0.391206,0.626419,7.270000
7,2.880278,36.757500,5.0,15.0,10.0,8.59,0.370000,40.610953,7.210000,11.570000,81.220000,0.205397,1.051727,4.100000
9,3.178361,36.704083,15.0,30.0,22.5,7.83,2.632808,3.750000,27.239966,42.857252,29.902781,4.599834,0.139389,1.360000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,2.410000,27.180000,0.0,23.0,11.5,8.43,20.000000,6.720000,0.460000,35.531762,39.888796,4.599834,0.139389,0.800000
2873,2.250000,27.350000,0.0,20.0,10.0,7.63,1.150000,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,2.380000
2879,2.410000,27.960000,0.0,10.0,5.0,6.72,3.710000,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,1.060000
2884,2.450000,27.200000,0.0,3.0,1.5,6.80,3.750000,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,1.320000
2887,2.430000,27.190000,0.0,8.0,4.0,7.39,2.860000,27.887979,24.101929,35.531762,39.888796,4.599834,0.139389,2.975432

In [76]:
def latlon_to_pixel(lat, lon, dataset ,transform):
    # Validate if the coordinate is within the image bounds
    if not (dataset.bounds.left <= lon <= dataset.bounds.right and
            dataset.bounds.bottom <= lat <= dataset.bounds.top):
        print("error here ")

    # Convert to pixel row & column
    row, col = rowcol(dataset.transform, lon, lat)
    return row, col

In [65]:
# windows Forming  for full one file (nefthou el file mera brk)
def window_forming(raster_path, df, height=7, width=7 , var=None):
    covariable_files = os.listdir(raster_path)
    covariable_num = len(covariable_files)

    datasets = [rasterio.open(os.path.join(raster_path, fname)) for fname in covariable_files]
    transforms = [ds.transform for ds in datasets]

    windows = []
    mid = height // 2

    for i in range(len(df)):
        print(f"Processing point {i}")
        lat = df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]
        window = np.empty((height, width, covariable_num))

        for idx, src in enumerate(datasets):
            transform = transforms[idx]
            if var :
                pixel_y, pixel_x = latlon_to_pixel(lon, lat, src, transform)
            else : 
                pixel_y, pixel_x = latlon_to_pixel(lat, lon, src, transform)

            try:
                win = Window(pixel_x - mid, pixel_y - mid, width, height)
                data = src.read(1, window=win)
                window[:, :, idx] = data

            except Exception as e:
                print(f"Error at point {i}, covariable {idx}")
                print(e)
                window[:, :, idx] = np.nan  # Fill with NaNs on failure

        windows.append(window)

    for ds in datasets:
        ds.close()

    return windows

In [66]:
# for devided tiff files 
def window_forming2(raster_path  , df ,height=7 , width=7 ):
    covariable_num = len(os.listdir(raster_path))
    windows = []

    for i in range(len(df)) :

        print(f"the dataset is in : {i}") 
        lat =  df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]

        window = np.empty((height, width, covariable_num))
        for index , j in enumerate(os.listdir(raster_path)):
            with rasterio.open(f"{raster_path}/{j}") as src :
                raster_data = src.read()
                transform = src.transform 
                
            try : 
                pixel_x ,pixel_y = latlon_to_pixel(lat , lon , src , transform)
                mid = height//2
                window[:,:,index] = raster_data[ 0 , pixel_x - mid : pixel_x + mid +1 , pixel_y - mid : pixel_y + mid +1 ]
                break 
            except Exception as e :
                continue 
        
        windows.append(window)
    return windows

In [67]:
def window_forming3(all_files  , df ,height=7 , width=7 ):
    covariable_num = len(all_files)
    windows = []
    for i in range(len(df)) :
        print(f"the dataset is in : {i}") 
        lat =  df.iloc[i]["X"]
        lon = df.iloc[i]["Y"]

        window = np.empty((height, width, covariable_num))

        for index , i in enumerate(all_files):
            raster_data = i.raster_data
            pixel_x ,pixel_y = latlon_to_pixel(lat , lon ,  i.src , i.transform)
            print(pixel_x , pixel_y)
            mid = height//2
            try : 
                window[:,:,index] = raster_data[ pixel_x - mid : pixel_x + mid +1 , pixel_y - mid : pixel_y + mid +1 ]
            except Exception as e:
                print("error is here ")
                print(e)
        windows.append(window)
    return windows

### 1.Climat

In [68]:
climat_window = window_forming("../Resmapled/climat/" , df_unique)
climat_window = np.array(climat_window)
np.save("../Data_multi_CNN/climat.npy", climat_window)

Processing point 0
Processing point 1
Processing point 2
Processing point 3
Processing point 4
Processing point 5
Processing point 6
Processing point 7
Processing point 8
Processing point 9
Processing point 10
Processing point 11
Processing point 12
Processing point 13
Processing point 14
Processing point 15
Processing point 16
Processing point 17
Processing point 18
Processing point 19
Processing point 20
Processing point 21
Processing point 22
Processing point 23
Processing point 24
Processing point 25
Processing point 26
Processing point 27
Processing point 28
Processing point 29
Processing point 30
Processing point 31
Processing point 32
Processing point 33
Processing point 34
Processing point 35
Processing point 36
Processing point 37
Processing point 38
Processing point 39
Processing point 40
Processing point 41
Processing point 42
Processing point 43
Processing point 44
Processing point 45
Processing point 46
Processing point 47
Processing point 48
Processing point 49
Processing point 50
Processing point 51
Processing point 52
Processing point 53
Processing point 54
Processing point 55
Processing point 56
Processing point 57
Processing point 58
Processing point 59
Processing point 60
Processing point 61
Processing point 62
Processing point 63
Processing point 64
Processing point 65
Processing point 66
Processing point 67
Processing point 68
Processing point 69
Processing point 70
Processing point 71
Processing point 72
Processing point 73
Processing point 74
Processing point 75
Processing point 76
Processing point 77
Processing point 78
Processing point 79
Processing point 80
Processing point 81
Processing point 82
Processing point 83
Processing point 84
Processing point 85
Processing point 86
Processing point 87
Processing point 88
Processing point 89
Processing point 90
Processing point 91
Processing point 92
Processing point 93
Processing point 94
Processing point 95
Processing point 96
Processing point 97
Processing point 98
Processing point 99
Processing point 100
Processing point 101
Processing point 102
Processing point 103
Processing point 104
Processing point 105
Processing point 106
Processing point 107
Processing point 108
Processing point 109
Processing point 110
Processing point 111
Processing point 112
Processing point 113
Processing point 114
Processing point 115
Processing point 116
Processing point 117
Processing point 118
Processing point 119
Processing point 120
Processing point 121
Processing point 122
Processing point 123
Processing point 124
Processing point 125
Processing point 126
Processing point 127
Processing point 128
Processing point 129
Processing point 130
Processing point 131
Processing point 132
Processing point 133
Processing point 134
Processing point 135
Processing point 136
Processing point 137
Processing point 138
Processing point 139
Processing point 140
Processing point 141
Processing point 142
Processing point 143
Processing point 144
Processing point 145
Processing point 146
Processing point 147
Processing point 148
Processing point 149
Processing point 150
Processing point 151
Processing point 152
Processing point 153
Processing point 154
Processing point 155
Processing point 156
Processing point 157
Processing point 158
Processing point 159
Processing point 160
Processing point 161
Processing point 162
Processing point 163
Processing point 164
Processing point 165
Processing point 166
Processing point 167
Processing point 168
Processing point 169
Processing point 170
Processing point 171
Processing point 172
Processing point 173
Processing point 174
Processing point 175
Processing point 176
Processing point 177
Processing point 178
Processing point 179
Processing point 180
Processing point 181
Processing point 182
Processing point 183
Processing point 184
Processing point 185
Processing point 186
Processing point 187
Processing point 188
Processing point 189
Processing point 190
Processing point 191
Processing point 192
Processing point 193
Processing point 194
Processing point 195
Processing point 196
Processing point 197
Processing point 198
Processing point 199
Processing point 200
Processing point 201
Processing point 202
Processing point 203
Processing point 204
Processing point 205
Processing point 206
Processing point 207
Processing point 208
Processing point 209
Processing point 210
Processing point 211
Processing point 212
Processing point 213
Processing point 214
Processing point 215
Processing point 216
Processing point 217
Processing point 218
Processing point 219
Processing point 220
Processing point 221
Processing point 222
Processing point 223
Processing point 224
Processing point 225
Processing point 226
Processing point 227
Processing point 228
Processing point 229
Processing point 230
Processing point 231
Processing point 232
Processing point 233
Processing point 234
Processing point 235
Processing point 236
Processing point 237
Processing point 238
Processing point 239
Processing point 240
Processing point 241
Processing point 242
Processing point 243
Processing point 244
Processing point 245
Processing point 246
Processing point 247
Processing point 248
Processing point 249
Processing point 250
Processing point 251
Processing point 252
Processing point 253
Processing point 254
Processing point 255
Processing point 256
Processing point 257
Processing point 258
Processing point 259
Processing point 260
Processing point 261
Processing point 262
Processing point 263
Processing point 264
Processing point 265
Processing point 266
Processing point 267
Processing point 268
Processing point 269
Processing point 270
Processing point 271
Processing point 272
Processing point 273
Processing point 274
Processing point 275
Processing point 276
Processing point 277
Processing point 278
Processing point 279
Processing point 280
Processing point 281
Processing point 282
Processing point 283
Processing point 284
Processing point 285
Processing point 286
Processing point 287
Processing point 288
Processing point 289
Processing point 290
Processing point 291
Processing point 292
Processing point 293
Processing point 294
Processing point 295
Processing point 296
Processing point 297
Processing point 298
Processing point 299
Processing point 300
Processing point 301
Processing point 302
Processing point 303
Processing point 304
Processing point 305
Processing point 306
Processing point 307
Processing point 308
Processing point 309
Processing point 310
Processing point 311
Processing point 312
Processing point 313
Processing point 314
Processing point 315
Processing point 316
Processing point 317
Processing point 318
Processing point 319
Processing point 320
Processing point 321
Processing point 322
Processing point 323
Processing point 324
Processing point 325
Processing point 326
Processing point 327
Processing point 328
Processing point 329
Processing point 330
Processing point 331
Processing point 332
Processing point 333
Processing point 334
Processing point 335
Processing point 336
Processing point 337
Processing point 338
Processing point 339
Processing point 340
Processing point 341
Processing point 342
Processing point 343
Processing point 344
Processing point 345
Processing point 346
Processing point 347
Processing point 348
Processing point 349
Processing point 350
Processing point 351
Processing point 352
Processing point 353
Processing point 354
Processing point 355
Processing point 356
Processing point 357
Processing point 358
Processing point 359
Processing point 360
Processing point 361
Processing point 362
Processing point 363
Processing point 364
Processing point 365
Processing point 366
Processing point 367
Processing point 368
Processing point 369
Processing point 370
Processing point 371
Processing point 372
Processing point 373
Processing point 374
Processing point 375
Processing point 376
Processing point 377
Processing point 378
Processing point 379
Processing point 380
Processing point 381
Processing point 382
Processing point 383
Processing point 384
Processing point 385
Processing point 386
Processing point 387
Processing point 388
Processing point 389
Processing point 390
Processing point 391
Processing point 392
Processing point 393
Processing point 394
Processing point 395
Processing point 396
Processing point 397
Processing point 398
Processing point 399
Processing point 400
Processing point 401
Processing point 402
Processing point 403
Processing point 404
Processing point 405
Processing point 406
Processing point 407
Processing point 408
Processing point 409
Processing point 410
Processing point 411
Processing point 412
Processing point 413
Processing point 414
Processing point 415
Processing point 416
Processing point 417
Processing point 418
Processing point 419
Processing point 420
Processing point 421
Processing point 422
Processing point 423
Processing point 424
Processing point 425
Processing point 426
Processing point 427
Processing point 428
Processing point 429
Processing point 430
Processing point 431
Processing point 432
Processing point 433
Processing point 434
Processing point 435
Processing point 436
Processing point 437
Processing point 438
Processing point 439
Processing point 440
Processing point 441
Processing point 442
Processing point 443
Processing point 444
Processing point 445
Processing point 446
Processing point 447

In [69]:
climat_window.shape

(448, 7, 7, 6)

### 2. organisme

In [81]:
organisme = window_forming("../Resmapled/organisme/" , df_unique)
organisme = np.array(organisme)
print(organisme.shape)
np.save("../Data_multi_CNN/organisme.npy", organisme)

Processing point 0
Processing point 1
Processing point 2
Processing point 3
Processing point 4
Processing point 5
Processing point 6
Processing point 7
Processing point 8
Processing point 9
Processing point 10
Processing point 11
Processing point 12
Processing point 13
Processing point 14
Processing point 15
Processing point 16
Processing point 17
Processing point 18
Processing point 19
Processing point 20
Processing point 21
Processing point 22
Processing point 23
Processing point 24
Processing point 25
Processing point 26
Processing point 27
Processing point 28
Processing point 29
Processing point 30
Processing point 31
Processing point 32
Processing point 33
Processing point 34
Processing point 35
Processing point 36
Processing point 37
Processing point 38
Processing point 39
Processing point 40
Processing point 41
Processing point 42
Processing point 43
Processing point 44
Processing point 45
Processing point 46
Processing point 47
Processing point 48
Processing point 49
Processing point 50
Processing point 51
Processing point 52
Processing point 53
Processing point 54
Processing point 55
Processing point 56
Processing point 57
Processing point 58
Processing point 59
Processing point 60
Processing point 61
Processing point 62
Processing point 63
Processing point 64
Processing point 65
Processing point 66
Processing point 67
Processing point 68
Processing point 69
Processing point 70
Processing point 71
Processing point 72
Processing point 73
Processing point 74
Processing point 75
Processing point 76
Processing point 77
Processing point 78
Processing point 79
Processing point 80
Processing point 81
Processing point 82
Processing point 83
Processing point 84
Processing point 85
Processing point 86
Processing point 87
Processing point 88
Processing point 89
Processing point 90
Processing point 91
Processing point 92
Processing point 93
Processing point 94
Processing point 95
Processing point 96
Processing point 97
Processing point 98
Processing point 99
Processing point 100
Processing point 101
Processing point 102
Processing point 103
Processing point 104
Processing point 105
Processing point 106
Processing point 107
Processing point 108
Processing point 109
Processing point 110
Processing point 111
Processing point 112
Processing point 113
Processing point 114
Processing point 115
Processing point 116
Processing point 117
Processing point 118
Processing point 119
Processing point 120
Processing point 121
Processing point 122
Processing point 123
Processing point 124
Processing point 125
Processing point 126
Processing point 127
Processing point 128
Processing point 129
Processing point 130
Processing point 131
Processing point 132
Processing point 133
Processing point 134
Processing point 135
Processing point 136
Processing point 137
Processing point 138
Processing point 139
Processing point 140
Processing point 141
Processing point 142
Processing point 143
Processing point 144
Processing point 145
Processing point 146
Processing point 147
Processing point 148
Processing point 149
Processing point 150
Processing point 151
Processing point 152
Processing point 153
Processing point 154
Processing point 155
Processing point 156
Processing point 157
Processing point 158
Processing point 159
Processing point 160
Processing point 161
Processing point 162
Processing point 163
Processing point 164
Processing point 165
Processing point 166
Processing point 167
Processing point 168
Processing point 169
Processing point 170
Processing point 171
Processing point 172
Processing point 173
Processing point 174
Processing point 175
Processing point 176
Processing point 177
Processing point 178
Processing point 179
Processing point 180
Processing point 181
Processing point 182
Processing point 183
Processing point 184
Processing point 185
Processing point 186
Processing point 187
Processing point 188
Processing point 189
Processing point 190
Processing point 191
Processing point 192
Processing point 193
Processing point 194
Processing point 195
Processing point 196
Processing point 197
Processing point 198
Processing point 199
Processing point 200
Processing point 201
Processing point 202
Processing point 203
Processing point 204
Processing point 205
Processing point 206
Processing point 207
Processing point 208
Processing point 209
Processing point 210
Processing point 211
Processing point 212
Processing point 213
Processing point 214
Processing point 215
Processing point 216
Processing point 217
Processing point 218
Processing point 219
Processing point 220
Processing point 221
Processing point 222
Processing point 223
Processing point 224
Processing point 225
Processing point 226
Processing point 227
Processing point 228
Processing point 229
Processing point 230
Processing point 231
Processing point 232
Processing point 233
Processing point 234
Processing point 235
Processing point 236
Processing point 237
Processing point 238
Processing point 239
Processing point 240
Processing point 241
Processing point 242
Processing point 243
Processing point 244
Processing point 245
Processing point 246
Processing point 247
Processing point 248
Processing point 249
Processing point 250
Processing point 251
Processing point 252
Processing point 253
Processing point 254
Processing point 255
Processing point 256
Processing point 257
Processing point 258
Processing point 259
Processing point 260
Processing point 261
Processing point 262
Processing point 263
Processing point 264
Processing point 265
Processing point 266
Processing point 267
Processing point 268
Processing point 269
Processing point 270
Processing point 271
Processing point 272
Processing point 273
Processing point 274
Processing point 275
Processing point 276
Processing point 277
Processing point 278
Processing point 279
Processing point 280
Processing point 281
Processing point 282
Processing point 283
Processing point 284
Processing point 285
Processing point 286
Processing point 287
Processing point 288
Processing point 289
Processing point 290
Processing point 291
Processing point 292
Processing point 293
Processing point 294
Processing point 295
Processing point 296
Processing point 297
Processing point 298
Processing point 299
Processing point 300
Processing point 301
Processing point 302
Processing point 303
Processing point 304
Processing point 305
Processing point 306
Processing point 307
Processing point 308
Processing point 309
Processing point 310
Processing point 311
Processing point 312
Processing point 313
Processing point 314
Processing point 315
Processing point 316
Processing point 317
Processing point 318
Processing point 319
Processing point 320
Processing point 321
Processing point 322
Processing point 323
Processing point 324
Processing point 325
Processing point 326
Processing point 327
Processing point 328
Processing point 329
Processing point 330
Processing point 331
Processing point 332
Processing point 333
Processing point 334
Processing point 335
Processing point 336
Processing point 337
Processing point 338
Processing point 339
Processing point 340
Processing point 341
Processing point 342
Processing point 343
Processing point 344
Processing point 345
Processing point 346
Processing point 347
Processing point 348
Processing point 349
Processing point 350
Processing point 351
Processing point 352
Processing point 353
Processing point 354
Processing point 355
Processing point 356
Processing point 357
Processing point 358
Processing point 359
Processing point 360
Processing point 361
Processing point 362
Processing point 363
Processing point 364
Processing point 365
Processing point 366
Processing point 367
Processing point 368
Processing point 369
Processing point 370
Processing point 371
Processing point 372
Processing point 373
Processing point 374
Processing point 375
Processing point 376
Processing point 377
Processing point 378
Processing point 379
Processing point 380
Processing point 381
Processing point 382
Processing point 383
Processing point 384
Processing point 385
Processing point 386
Processing point 387
Processing point 388
Processing point 389
Processing point 390
Processing point 391
Processing point 392
Processing point 393
Processing point 394
Processing point 395
Processing point 396
Processing point 397
Processing point 398
Processing point 399
Processing point 400
Processing point 401
Processing point 402
Processing point 403
Processing point 404
Processing point 405
Processing point 406
Processing point 407
Processing point 408
Processing point 409
Processing point 410
Processing point 411
Processing point 412
Processing point 413
Processing point 414
Processing point 415
Processing point 416
Processing point 417
Processing point 418
Processing point 419
Processing point 420
Processing point 421
Processing point 422
Processing point 423
Processing point 424
Processing point 425
Processing point 426
Processing point 427
Processing point 428
Processing point 429
Processing point 430
Processing point 431
Processing point 432
Processing point 433
Processing point 434
Processing point 435
Processing point 436
Processing point 437
Processing point 438
Processing point 439
Processing point 440
Processing point 441
Processing point 442
Processing point 443
Processing point 444
Processing point 445
Processing point 446
Processing point 447
(448, 7, 7, 18)

### 3. relief

In [71]:
relief = window_forming("../Resmapled/relief/" , df_unique)
relief = np.array(relief)
print(relief.shape)
np.save("../Data_multi_CNN/relief.npy", relief)

Processing point 0
Processing point 1
Processing point 2
Processing point 3
Processing point 4
Processing point 5
Processing point 6
Processing point 7
Processing point 8
Processing point 9
Processing point 10
Processing point 11
Processing point 12
Processing point 13
Processing point 14
Processing point 15
Processing point 16
Processing point 17
Processing point 18
Processing point 19
Processing point 20
Processing point 21
Processing point 22
Processing point 23
Processing point 24
Processing point 25
Processing point 26
Processing point 27
Processing point 28
Processing point 29
Processing point 30
Processing point 31
Processing point 32
Processing point 33
Processing point 34
Processing point 35
Processing point 36
Processing point 37
Processing point 38
Processing point 39
Processing point 40
Processing point 41
Processing point 42
Processing point 43
Processing point 44
Processing point 45
Processing point 46
Processing point 47
Processing point 48
Processing point 49
Processing point 50
Processing point 51
Processing point 52
Processing point 53
Processing point 54
Processing point 55
Processing point 56
Processing point 57
Processing point 58
Processing point 59
Processing point 60
Processing point 61
Processing point 62
Processing point 63
Processing point 64
Processing point 65
Processing point 66
Processing point 67
Processing point 68
Processing point 69
Processing point 70
Processing point 71
Processing point 72
Processing point 73
Processing point 74
Processing point 75
Processing point 76
Processing point 77
Processing point 78
Processing point 79
Processing point 80
Processing point 81
Processing point 82
Processing point 83
Processing point 84
Processing point 85
Processing point 86
Processing point 87
Processing point 88
Processing point 89
Processing point 90
Processing point 91
Processing point 92
Processing point 93
Processing point 94
Processing point 95
Processing point 96
Processing point 97
Processing point 98
Processing point 99
Processing point 100
Processing point 101
Processing point 102
Processing point 103
Processing point 104
Processing point 105
Processing point 106
Processing point 107
Processing point 108
Processing point 109
Processing point 110
Processing point 111
Processing point 112
Processing point 113
Processing point 114
Processing point 115
Processing point 116
Processing point 117
Processing point 118
Processing point 119
Processing point 120
Processing point 121
Processing point 122
Processing point 123
Processing point 124
Processing point 125
Processing point 126
Processing point 127
Processing point 128
Processing point 129
Processing point 130
Processing point 131
Processing point 132
Processing point 133
Processing point 134
Processing point 135
Processing point 136
Processing point 137
Processing point 138
Processing point 139
Processing point 140
Processing point 141
Processing point 142
Processing point 143
Processing point 144
Processing point 145
Processing point 146
Processing point 147
Processing point 148
Processing point 149
Processing point 150
Processing point 151
Processing point 152
Processing point 153
Processing point 154
Processing point 155
Processing point 156
Processing point 157
Processing point 158
Processing point 159
Processing point 160
Processing point 161
Processing point 162
Processing point 163
Processing point 164
Processing point 165
Processing point 166
Processing point 167
Processing point 168
Processing point 169
Processing point 170
Processing point 171
Processing point 172
Processing point 173
Processing point 174
Processing point 175
Processing point 176
Processing point 177
Processing point 178
Processing point 179
Processing point 180
Processing point 181
Processing point 182
Processing point 183
Processing point 184
Processing point 185
Processing point 186
Processing point 187
Processing point 188
Processing point 189
Processing point 190
Processing point 191
Processing point 192
Processing point 193
Processing point 194
Processing point 195
Processing point 196
Processing point 197
Processing point 198
Processing point 199
Processing point 200
Processing point 201
Processing point 202
Processing point 203
Processing point 204
Processing point 205
Processing point 206
Processing point 207
Processing point 208
Processing point 209
Processing point 210
Processing point 211
Processing point 212
Processing point 213
Processing point 214
Processing point 215
Processing point 216
Processing point 217
Processing point 218
Processing point 219
Processing point 220
Processing point 221
Processing point 222
Processing point 223
Processing point 224
Processing point 225
Processing point 226
Processing point 227
Processing point 228
Processing point 229
Processing point 230
Processing point 231
Processing point 232
Processing point 233
Processing point 234
Processing point 235
Processing point 236
Processing point 237
Processing point 238
Processing point 239
Processing point 240
Processing point 241
Processing point 242
Processing point 243
Processing point 244
Processing point 245
Processing point 246
Processing point 247
Processing point 248
Processing point 249
Processing point 250
Processing point 251
Processing point 252
Processing point 253
Processing point 254
Processing point 255
Processing point 256
Processing point 257
Processing point 258
Processing point 259
Processing point 260
Processing point 261
Processing point 262
Processing point 263
Processing point 264
Processing point 265
Processing point 266
Processing point 267
Processing point 268
Processing point 269
Processing point 270
Processing point 271
Processing point 272
Processing point 273
Processing point 274
Processing point 275
Processing point 276
Processing point 277
Processing point 278
Processing point 279
Processing point 280
Processing point 281
Processing point 282
Processing point 283
Processing point 284
Processing point 285
Processing point 286
Processing point 287
Processing point 288
Processing point 289
Processing point 290
Processing point 291
Processing point 292
Processing point 293
Processing point 294
Processing point 295
Processing point 296
Processing point 297
Processing point 298
Processing point 299
Processing point 300
Processing point 301
Processing point 302
Processing point 303
Processing point 304
Processing point 305
Processing point 306
Processing point 307
Processing point 308
Processing point 309
Processing point 310
Processing point 311
Processing point 312
Processing point 313
Processing point 314
Processing point 315
Processing point 316
Processing point 317
Processing point 318
Processing point 319
Processing point 320
Processing point 321
Processing point 322
Processing point 323
Processing point 324
Processing point 325
Processing point 326
Processing point 327
Processing point 328
Processing point 329
Processing point 330
Processing point 331
Processing point 332
Processing point 333
Processing point 334
Processing point 335
Processing point 336
Processing point 337
Processing point 338
Processing point 339
Processing point 340
Processing point 341
Processing point 342
Processing point 343
Processing point 344
Processing point 345
Processing point 346
Processing point 347
Processing point 348
Processing point 349
Processing point 350
Processing point 351
Processing point 352
Processing point 353
Processing point 354
Processing point 355
Processing point 356
Processing point 357
Processing point 358
Processing point 359
Processing point 360
Processing point 361
Processing point 362
Processing point 363
Processing point 364
Processing point 365
Processing point 366
Processing point 367
Processing point 368
Processing point 369
Processing point 370
Processing point 371
Processing point 372
Processing point 373
Processing point 374
Processing point 375
Processing point 376
Processing point 377
Processing point 378
Processing point 379
Processing point 380
Processing point 381
Processing point 382
Processing point 383
Processing point 384
Processing point 385
Processing point 386
Processing point 387
Processing point 388
Processing point 389
Processing point 390
Processing point 391
Processing point 392
Processing point 393
Processing point 394
Processing point 395
Processing point 396
Processing point 397
Processing point 398
Processing point 399
Processing point 400
Processing point 401
Processing point 402
Processing point 403
Processing point 404
Processing point 405
Processing point 406
Processing point 407
Processing point 408
Processing point 409
Processing point 410
Processing point 411
Processing point 412
Processing point 413
Processing point 414
Processing point 415
Processing point 416
Processing point 417
Processing point 418
Processing point 419
Processing point 420
Processing point 421
Processing point 422
Processing point 423
Processing point 424
Processing point 425
Processing point 426
Processing point 427
Processing point 428
Processing point 429
Processing point 430
Processing point 431
Processing point 432
Processing point 433
Processing point 434
Processing point 435
Processing point 436
Processing point 437
Processing point 438
Processing point 439
Processing point 440
Processing point 441
Processing point 442
Processing point 443
Processing point 444
Processing point 445
Processing point 446
Processing point 447
(448, 7, 7, 7)

### 4. Spatial Position

In [72]:
landuse_window = window_forming2("../Resmapled/saptialPosition/landuse/" , df_unique)
water_window = window_forming2("../Resmapled/saptialPosition/water/" , df_unique)
np.save("../Data_multi_CNN/landuse.npy", landuse_window)
np.save("../Data_multi_CNN/water.npy", water_window)

the dataset is in : 0
the dataset is in : 1
the dataset is in : 2
the dataset is in : 3
the dataset is in : 4
the dataset is in : 5
the dataset is in : 6
the dataset is in : 7
the dataset is in : 8
the dataset is in : 9
the dataset is in : 10
the dataset is in : 11
the dataset is in : 12
the dataset is in : 13
the dataset is in : 14
the dataset is in : 15
the dataset is in : 16
the dataset is in : 17
the dataset is in : 18
the dataset is in : 19
the dataset is in : 20
the dataset is in : 21
the dataset is in : 22
the dataset is in : 23
the dataset is in : 24
the dataset is in : 25
the dataset is in : 26
the dataset is in : 27
the dataset is in : 28
the dataset is in : 29
the dataset is in : 30
the dataset is in : 31
the dataset is in : 32
the dataset is in : 33
the dataset is in : 34
the dataset is in : 35
the dataset is in : 36
the dataset is in : 37
the dataset is in : 38
the dataset is in : 39
the dataset is in : 40
the dataset is in : 41
the dataset is in : 42
the dataset is in : 43
the dataset is in : 44
the dataset is in : 45
the dataset is in : 46
the dataset is in : 47
the dataset is in : 48
the dataset is in : 49
the dataset is in : 50
the dataset is in : 51
the dataset is in : 52
the dataset is in : 53
the dataset is in : 54
the dataset is in : 55
the dataset is in : 56
the dataset is in : 57
the dataset is in : 58
the dataset is in : 59
the dataset is in : 60
the dataset is in : 61
the dataset is in : 62
the dataset is in : 63
the dataset is in : 64
the dataset is in : 65
the dataset is in : 66
the dataset is in : 67
the dataset is in : 68
the dataset is in : 69
the dataset is in : 70
the dataset is in : 71
the dataset is in : 72
the dataset is in : 73
the dataset is in : 74
the dataset is in : 75
the dataset is in : 76
the dataset is in : 77
the dataset is in : 78
the dataset is in : 79
the dataset is in : 80
the dataset is in : 81
the dataset is in : 82
the dataset is in : 83
the dataset is in : 84
the dataset is in : 85
the dataset is in : 86
the dataset is in : 87
the dataset is in : 88
the dataset is in : 89
the dataset is in : 90
the dataset is in : 91
the dataset is in : 92
the dataset is in : 93
the dataset is in : 94
the dataset is in : 95
the dataset is in : 96
the dataset is in : 97
the dataset is in : 98
the dataset is in : 99
the dataset is in : 100
the dataset is in : 101
the dataset is in : 102
the dataset is in : 103
the dataset is in : 104
the dataset is in : 105
the dataset is in : 106
the dataset is in : 107
the dataset is in : 108
the dataset is in : 109
the dataset is in : 110
the dataset is in : 111
the dataset is in : 112
the dataset is in : 113
the dataset is in : 114
the dataset is in : 115
the dataset is in : 116
the dataset is in : 117
the dataset is in : 118
the dataset is in : 119
the dataset is in : 120
the dataset is in : 121
the dataset is in : 122
the dataset is in : 123
the dataset is in : 124
the dataset is in : 125
the dataset is in : 126
the dataset is in : 127
the dataset is in : 128
the dataset is in : 129
the dataset is in : 130
the dataset is in : 131
the dataset is in : 132
the dataset is in : 133
the dataset is in : 134
the dataset is in : 135
the dataset is in : 136
the dataset is in : 137
the dataset is in : 138
the dataset is in : 139
the dataset is in : 140
the dataset is in : 141
the dataset is in : 142
the dataset is in : 143
the dataset is in : 144
the dataset is in : 145
the dataset is in : 146
the dataset is in : 147
the dataset is in : 148
the dataset is in : 149
the dataset is in : 150
the dataset is in : 151
the dataset is in : 152
the dataset is in : 153
the dataset is in : 154
the dataset is in : 155
the dataset is in : 156
the dataset is in : 157
the dataset is in : 158
the dataset is in : 159
the dataset is in : 160
the dataset is in : 161
the dataset is in : 162
the dataset is in : 163
the dataset is in : 164
the dataset is in : 165
the dataset is in : 166
the dataset is in : 167
the dataset is in : 168
the dataset is in : 169
the dataset is in : 170
the dataset is in : 171
the dataset is in : 172
the dataset is in : 173
the dataset is in : 174
the dataset is in : 175
the dataset is in : 176
the dataset is in : 177
the dataset is in : 178
the dataset is in : 179
the dataset is in : 180
the dataset is in : 181
the dataset is in : 182
the dataset is in : 183
the dataset is in : 184
the dataset is in : 185
the dataset is in : 186
the dataset is in : 187
the dataset is in : 188
the dataset is in : 189
the dataset is in : 190
the dataset is in : 191
the dataset is in : 192
the dataset is in : 193
the dataset is in : 194
the dataset is in : 195
the dataset is in : 196
the dataset is in : 197
the dataset is in : 198
the dataset is in : 199
the dataset is in : 200
the dataset is in : 201
the dataset is in : 202
the dataset is in : 203
the dataset is in : 204
the dataset is in : 205
the dataset is in : 206
the dataset is in : 207
the dataset is in : 208
the dataset is in : 209
the dataset is in : 210
the dataset is in : 211
the dataset is in : 212
the dataset is in : 213
the dataset is in : 214
the dataset is in : 215
the dataset is in : 216
the dataset is in : 217
the dataset is in : 218
the dataset is in : 219
the dataset is in : 220
the dataset is in : 221
the dataset is in : 222
the dataset is in : 223
the dataset is in : 224
the dataset is in : 225
the dataset is in : 226
the dataset is in : 227
the dataset is in : 228
the dataset is in : 229
the dataset is in : 230
the dataset is in : 231
the dataset is in : 232
the dataset is in : 233
the dataset is in : 234
the dataset is in : 235
the dataset is in : 236
the dataset is in : 237
the dataset is in : 238
the dataset is in : 239
the dataset is in : 240
the dataset is in : 241
the dataset is in : 242
the dataset is in : 243
the dataset is in : 244
the dataset is in : 245
the dataset is in : 246
the dataset is in : 247
the dataset is in : 248
the dataset is in : 249
the dataset is in : 250
the dataset is in : 251
the dataset is in : 252
the dataset is in : 253
the dataset is in : 254
the dataset is in : 255
the dataset is in : 256
the dataset is in : 257
the dataset is in : 258
the dataset is in : 259
the dataset is in : 260
the dataset is in : 261
the dataset is in : 262
the dataset is in : 263
the dataset is in : 264
the dataset is in : 265
the dataset is in : 266
the dataset is in : 267
the dataset is in : 268
the dataset is in : 269
the dataset is in : 270
the dataset is in : 271
the dataset is in : 272
the dataset is in : 273
the dataset is in : 274
the dataset is in : 275
the dataset is in : 276
the dataset is in : 277
the dataset is in : 278
the dataset is in : 279
the dataset is in : 280
the dataset is in : 281
the dataset is in : 282
the dataset is in : 283
the dataset is in : 284
the dataset is in : 285
the dataset is in : 286
the dataset is in : 287
the dataset is in : 288
the dataset is in : 289
the dataset is in : 290
the dataset is in : 291
the dataset is in : 292
the dataset is in : 293
the dataset is in : 294
the dataset is in : 295
the dataset is in : 296
the dataset is in : 297
the dataset is in : 298
the dataset is in : 299
the dataset is in : 300
the dataset is in : 301
the dataset is in : 302
the dataset is in : 303
the dataset is in : 304
the dataset is in : 305
the dataset is in : 306
the dataset is in : 307
the dataset is in : 308
the dataset is in : 309
the dataset is in : 310
the dataset is in : 311
the dataset is in : 312
the dataset is in : 313
the dataset is in : 314
the dataset is in : 315
the dataset is in : 316
the dataset is in : 317
the dataset is in : 318
the dataset is in : 319
the dataset is in : 320
the dataset is in : 321
the dataset is in : 322
the dataset is in : 323
the dataset is in : 324
the dataset is in : 325
the dataset is in : 326
the dataset is in : 327
the dataset is in : 328
the dataset is in : 329
the dataset is in : 330
the dataset is in : 331
the dataset is in : 332
the dataset is in : 333
the dataset is in : 334
the dataset is in : 335
the dataset is in : 336
the dataset is in : 337
the dataset is in : 338
the dataset is in : 339
the dataset is in : 340
the dataset is in : 341
the dataset is in : 342
the dataset is in : 343
the dataset is in : 344
the dataset is in : 345
the dataset is in : 346
the dataset is in : 347
the dataset is in : 348
the dataset is in : 349
the dataset is in : 350
the dataset is in : 351
the dataset is in : 352
the dataset is in : 353
the dataset is in : 354
the dataset is in : 355
the dataset is in : 356
the dataset is in : 357
the dataset is in : 358
the dataset is in : 359
the dataset is in : 360
the dataset is in : 361
the dataset is in : 362
the dataset is in : 363
the dataset is in : 364
the dataset is in : 365
the dataset is in : 366
the dataset is in : 367
the dataset is in : 368
the dataset is in : 369
the dataset is in : 370
the dataset is in : 371
the dataset is in : 372
the dataset is in : 373
the dataset is in : 374
the dataset is in : 375
the dataset is in : 376
the dataset is in : 377
the dataset is in : 378
the dataset is in : 379
the dataset is in : 380
the dataset is in : 381
the dataset is in : 382
the dataset is in : 383
the dataset is in : 384
the dataset is in : 385
the dataset is in : 386
the dataset is in : 387
the dataset is in : 388
the dataset is in : 389
the dataset is in : 390
the dataset is in : 391
the dataset is in : 392
the dataset is in : 393
the dataset is in : 394
the dataset is in : 395
the dataset is in : 396
the dataset is in : 397
the dataset is in : 398
the dataset is in : 399
the dataset is in : 400
the dataset is in : 401
the dataset is in : 402
the dataset is in : 403
the dataset is in : 404
the dataset is in : 405
the dataset is in : 406
the dataset is in : 407
the dataset is in : 408
the dataset is in : 409
the dataset is in : 410
the dataset is in : 411
the dataset is in : 412
the dataset is in : 413
the dataset is in : 414
the dataset is in : 415
the dataset is in : 416
the dataset is in : 417
the dataset is in : 418
the dataset is in : 419
the dataset is in : 420
the dataset is in : 421
the dataset is in : 422
the dataset is in : 423
the dataset is in : 424
the dataset is in : 425
the dataset is in : 426
the dataset is in : 427
the dataset is in : 428
the dataset is in : 429
the dataset is in : 430
the dataset is in : 431
the dataset is in : 432
the dataset is in : 433
the dataset is in : 434
the dataset is in : 435
the dataset is in : 436
the dataset is in : 437
the dataset is in : 438
the dataset is in : 439
the dataset is in : 440
the dataset is in : 441
the dataset is in : 442
the dataset is in : 443
the dataset is in : 444
the dataset is in : 445
the dataset is in : 446
the dataset is in : 447
the dataset is in : 0
the dataset is in : 1
the dataset is in : 2
the dataset is in : 3
the dataset is in : 4
the dataset is in : 5
the dataset is in : 6
the dataset is in : 7
the dataset is in : 8
the dataset is in : 9
the dataset is in : 10
the dataset is in : 11
the dataset is in : 12
the dataset is in : 13
the dataset is in : 14
the dataset is in : 15
the dataset is in : 16
the dataset is in : 17
the dataset is in : 18
the dataset is in : 19
the dataset is in : 20
the dataset is in : 21
the dataset is in : 22
the dataset is in : 23
the dataset is in : 24
the dataset is in : 25
the dataset is in : 26
the dataset is in : 27
the dataset is in : 28
the dataset is in : 29
the dataset is in : 30
the dataset is in : 31
the dataset is in : 32
the dataset is in : 33
the dataset is in : 34
the dataset is in : 35
the dataset is in : 36
the dataset is in : 37
the dataset is in : 38
the dataset is in : 39
the dataset is in : 40
the dataset is in : 41
the dataset is in : 42
the dataset is in : 43
the dataset is in : 44
the dataset is in : 45
the dataset is in : 46
the dataset is in : 47
the dataset is in : 48
the dataset is in : 49
the dataset is in : 50
the dataset is in : 51
the dataset is in : 52
the dataset is in : 53
the dataset is in : 54
the dataset is in : 55
the dataset is in : 56
the dataset is in : 57
the dataset is in : 58
the dataset is in : 59
the dataset is in : 60
the dataset is in : 61
the dataset is in : 62
the dataset is in : 63
the dataset is in : 64
the dataset is in : 65
the dataset is in : 66
the dataset is in : 67
the dataset is in : 68
the dataset is in : 69
the dataset is in : 70
the dataset is in : 71
the dataset is in : 72
the dataset is in : 73
the dataset is in : 74
the dataset is in : 75
the dataset is in : 76
the dataset is in : 77
the dataset is in : 78
the dataset is in : 79
the dataset is in : 80
the dataset is in : 81
the dataset is in : 82
the dataset is in : 83
the dataset is in : 84
the dataset is in : 85
the dataset is in : 86
the dataset is in : 87
the dataset is in : 88
the dataset is in : 89
the dataset is in : 90
the dataset is in : 91
the dataset is in : 92
the dataset is in : 93
the dataset is in : 94
the dataset is in : 95
the dataset is in : 96
the dataset is in : 97
the dataset is in : 98
the dataset is in : 99
the dataset is in : 100
the dataset is in : 101
the dataset is in : 102
the dataset is in : 103
the dataset is in : 104
the dataset is in : 105
the dataset is in : 106
the dataset is in : 107
the dataset is in : 108
the dataset is in : 109
the dataset is in : 110
the dataset is in : 111
the dataset is in : 112
the dataset is in : 113
the dataset is in : 114
the dataset is in : 115
the dataset is in : 116
the dataset is in : 117
the dataset is in : 118
the dataset is in : 119
the dataset is in : 120
the dataset is in : 121
the dataset is in : 122
the dataset is in : 123
the dataset is in : 124
the dataset is in : 125
the dataset is in : 126
the dataset is in : 127
the dataset is in : 128
the dataset is in : 129
the dataset is in : 130
the dataset is in : 131
the dataset is in : 132
the dataset is in : 133
the dataset is in : 134
the dataset is in : 135
the dataset is in : 136
the dataset is in : 137
the dataset is in : 138
the dataset is in : 139
the dataset is in : 140
the dataset is in : 141
the dataset is in : 142
the dataset is in : 143
the dataset is in : 144
the dataset is in : 145
the dataset is in : 146
the dataset is in : 147
the dataset is in : 148
the dataset is in : 149
the dataset is in : 150
the dataset is in : 151
the dataset is in : 152
the dataset is in : 153
the dataset is in : 154
the dataset is in : 155
the dataset is in : 156
the dataset is in : 157
the dataset is in : 158
the dataset is in : 159
the dataset is in : 160
the dataset is in : 161
the dataset is in : 162
the dataset is in : 163
the dataset is in : 164
the dataset is in : 165
the dataset is in : 166
the dataset is in : 167
the dataset is in : 168
the dataset is in : 169
the dataset is in : 170
the dataset is in : 171
the dataset is in : 172
the dataset is in : 173
the dataset is in : 174
the dataset is in : 175
the dataset is in : 176
the dataset is in : 177
the dataset is in : 178
the dataset is in : 179
the dataset is in : 180
the dataset is in : 181
the dataset is in : 182
the dataset is in : 183
the dataset is in : 184
the dataset is in : 185
the dataset is in : 186
the dataset is in : 187
the dataset is in : 188
the dataset is in : 189
the dataset is in : 190
the dataset is in : 191
the dataset is in : 192
the dataset is in : 193
the dataset is in : 194
the dataset is in : 195
the dataset is in : 196
the dataset is in : 197
the dataset is in : 198
the dataset is in : 199
the dataset is in : 200
the dataset is in : 201
the dataset is in : 202
the dataset is in : 203
the dataset is in : 204
the dataset is in : 205
the dataset is in : 206
the dataset is in : 207
the dataset is in : 208
the dataset is in : 209
the dataset is in : 210
the dataset is in : 211
the dataset is in : 212
the dataset is in : 213
the dataset is in : 214
the dataset is in : 215
the dataset is in : 216
the dataset is in : 217
the dataset is in : 218
the dataset is in : 219
the dataset is in : 220
the dataset is in : 221
the dataset is in : 222
the dataset is in : 223
the dataset is in : 224
the dataset is in : 225
the dataset is in : 226
the dataset is in : 227
the dataset is in : 228
the dataset is in : 229
the dataset is in : 230
the dataset is in : 231
the dataset is in : 232
the dataset is in : 233
the dataset is in : 234
the dataset is in : 235
the dataset is in : 236
the dataset is in : 237
the dataset is in : 238
the dataset is in : 239
the dataset is in : 240
the dataset is in : 241
the dataset is in : 242
the dataset is in : 243
the dataset is in : 244
the dataset is in : 245
the dataset is in : 246
the dataset is in : 247
the dataset is in : 248
the dataset is in : 249
the dataset is in : 250
the dataset is in : 251
the dataset is in : 252
the dataset is in : 253
the dataset is in : 254
the dataset is in : 255
the dataset is in : 256
the dataset is in : 257
the dataset is in : 258
the dataset is in : 259
the dataset is in : 260
the dataset is in : 261
the dataset is in : 262
the dataset is in : 263
the dataset is in : 264
the dataset is in : 265
the dataset is in : 266
the dataset is in : 267
the dataset is in : 268
the dataset is in : 269
the dataset is in : 270
the dataset is in : 271
the dataset is in : 272
the dataset is in : 273
the dataset is in : 274
the dataset is in : 275
the dataset is in : 276
the dataset is in : 277
the dataset is in : 278
the dataset is in : 279
the dataset is in : 280
the dataset is in : 281
the dataset is in : 282
the dataset is in : 283
the dataset is in : 284
the dataset is in : 285
the dataset is in : 286
the dataset is in : 287
the dataset is in : 288
the dataset is in : 289
the dataset is in : 290
the dataset is in : 291
the dataset is in : 292
the dataset is in : 293
the dataset is in : 294
the dataset is in : 295
the dataset is in : 296
the dataset is in : 297
the dataset is in : 298
the dataset is in : 299
the dataset is in : 300
the dataset is in : 301
the dataset is in : 302
the dataset is in : 303
the dataset is in : 304
the dataset is in : 305
the dataset is in : 306
the dataset is in : 307
the dataset is in : 308
the dataset is in : 309
the dataset is in : 310
the dataset is in : 311
the dataset is in : 312
the dataset is in : 313
the dataset is in : 314
the dataset is in : 315
the dataset is in : 316
the dataset is in : 317
the dataset is in : 318
the dataset is in : 319
the dataset is in : 320
the dataset is in : 321
the dataset is in : 322
the dataset is in : 323
the dataset is in : 324
the dataset is in : 325
the dataset is in : 326
the dataset is in : 327
the dataset is in : 328
the dataset is in : 329
the dataset is in : 330
the dataset is in : 331
the dataset is in : 332
the dataset is in : 333
the dataset is in : 334
the dataset is in : 335
the dataset is in : 336
the dataset is in : 337
the dataset is in : 338
the dataset is in : 339
the dataset is in : 340
the dataset is in : 341
the dataset is in : 342
the dataset is in : 343
the dataset is in : 344
the dataset is in : 345
the dataset is in : 346
the dataset is in : 347
the dataset is in : 348
the dataset is in : 349
the dataset is in : 350
the dataset is in : 351
the dataset is in : 352
the dataset is in : 353
the dataset is in : 354
the dataset is in : 355
the dataset is in : 356
the dataset is in : 357
the dataset is in : 358
the dataset is in : 359
the dataset is in : 360
the dataset is in : 361
the dataset is in : 362
the dataset is in : 363
the dataset is in : 364
the dataset is in : 365
the dataset is in : 366
the dataset is in : 367
the dataset is in : 368
the dataset is in : 369
the dataset is in : 370
the dataset is in : 371
the dataset is in : 372
the dataset is in : 373
the dataset is in : 374
the dataset is in : 375
the dataset is in : 376
the dataset is in : 377
the dataset is in : 378
the dataset is in : 379
the dataset is in : 380
the dataset is in : 381
the dataset is in : 382
the dataset is in : 383
the dataset is in : 384
the dataset is in : 385
the dataset is in : 386
the dataset is in : 387
the dataset is in : 388
the dataset is in : 389
the dataset is in : 390
the dataset is in : 391
the dataset is in : 392
the dataset is in : 393

### 4. Parent Material

In [77]:
parent_window = window_forming("../Resmapled/ParentMaterial/", df_unique , var=True)
np.save("../Data_multi_CNN/Parent_Material.npy", parent_window)
np.array(parent_window).shape

Processing point 0
Processing point 1
Processing point 2
Processing point 3
Processing point 4
Processing point 5
Processing point 6
Processing point 7
Processing point 8
Processing point 9
Processing point 10
Processing point 11
Processing point 12
Processing point 13
Processing point 14
Processing point 15
Processing point 16
Processing point 17
Processing point 18
Processing point 19
Processing point 20
Processing point 21
Processing point 22
Processing point 23
Processing point 24
Processing point 25
Processing point 26
Processing point 27
Processing point 28
Processing point 29
Processing point 30
Processing point 31
Processing point 32
Processing point 33
Processing point 34
Processing point 35
Processing point 36
Processing point 37
Processing point 38
Processing point 39
Processing point 40
Processing point 41
Processing point 42
Processing point 43
Processing point 44
Processing point 45
Processing point 46
Processing point 47
Processing point 48
Processing point 49
Processing point 50
Processing point 51
Processing point 52
Processing point 53
Processing point 54
Processing point 55
Processing point 56
Processing point 57
Processing point 58
Processing point 59
Processing point 60
Processing point 61
Processing point 62
Processing point 63
Processing point 64
Processing point 65
Processing point 66
Processing point 67
Processing point 68
Processing point 69
Processing point 70
Processing point 71
Processing point 72
Processing point 73
Processing point 74
Processing point 75
Processing point 76
Processing point 77
Processing point 78
Processing point 79
Processing point 80
Processing point 81
Processing point 82
Processing point 83
Processing point 84
Processing point 85
Processing point 86
Processing point 87
Processing point 88
Processing point 89
Processing point 90
Processing point 91
Processing point 92
Processing point 93
Processing point 94
Processing point 95
Processing point 96
Processing point 97
Processing point 98
Processing point 99
Processing point 100
Processing point 101
Processing point 102
Processing point 103
Processing point 104
Processing point 105
Processing point 106
Processing point 107
Processing point 108
Processing point 109
Processing point 110
Processing point 111
Processing point 112
Processing point 113
Processing point 114
Processing point 115
Processing point 116
Processing point 117
Processing point 118
Processing point 119
Processing point 120
Processing point 121
Processing point 122
Processing point 123
Processing point 124
Processing point 125
Processing point 126
Processing point 127
Processing point 128
Processing point 129
Processing point 130
Processing point 131
Processing point 132
Processing point 133
Processing point 134
Processing point 135
Processing point 136
Processing point 137
Processing point 138
Processing point 139
Processing point 140
Processing point 141
Processing point 142
Processing point 143
Processing point 144
Processing point 145
Processing point 146
Processing point 147
Processing point 148
Processing point 149
Processing point 150
Processing point 151
Processing point 152
Processing point 153
Processing point 154
Processing point 155
Processing point 156
Processing point 157
Processing point 158
Processing point 159
Processing point 160
Processing point 161
Processing point 162
Processing point 163
Processing point 164
Processing point 165
Processing point 166
Processing point 167
Processing point 168
Processing point 169
Processing point 170
Processing point 171
Processing point 172
Processing point 173
Processing point 174
Processing point 175
Processing point 176
Processing point 177
Processing point 178
Processing point 179
Processing point 180
Processing point 181
Processing point 182
Processing point 183
Processing point 184
Processing point 185
Processing point 186
Processing point 187
Processing point 188
Processing point 189
Processing point 190
Processing point 191
Processing point 192
Processing point 193
Processing point 194
Processing point 195
Processing point 196
Processing point 197
Processing point 198
Processing point 199
Processing point 200
Processing point 201
Processing point 202
Processing point 203
Processing point 204
Processing point 205
Processing point 206
Processing point 207
Processing point 208
Processing point 209
Processing point 210
Processing point 211
Processing point 212
Processing point 213
Processing point 214
Processing point 215
Processing point 216
Processing point 217
Processing point 218
Processing point 219
Processing point 220
Processing point 221
Processing point 222
Processing point 223
Processing point 224
Processing point 225
Processing point 226
Processing point 227
Processing point 228
Processing point 229
Processing point 230
Processing point 231
Processing point 232
Processing point 233
Processing point 234
Processing point 235
error here
Error at point 235, covariable 0
could not broadcast input array from shape (0,0) into shape (7,7)
error here
Error at point 235, covariable 1
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 236
Processing point 237
Processing point 238
Processing point 239
Processing point 240
Processing point 241
Processing point 242
Processing point 243
Processing point 244
Processing point 245
Processing point 246
Processing point 247
Processing point 248
Processing point 249
Processing point 250
Processing point 251
Processing point 252
Processing point 253
Processing point 254
Processing point 255
Processing point 256
Processing point 257
Processing point 258
Processing point 259
Processing point 260
Processing point 261
Processing point 262
Processing point 263
Processing point 264
Processing point 265
Processing point 266
Processing point 267
Processing point 268
Processing point 269
Processing point 270
Processing point 271
Processing point 272
Processing point 273
Processing point 274
Processing point 275
Processing point 276
Processing point 277
Processing point 278
Processing point 279
Processing point 280
Processing point 281
Processing point 282
Processing point 283
Processing point 284
Processing point 285
Processing point 286
Processing point 287
Processing point 288
Processing point 289
Processing point 290
Processing point 291
Processing point 292
Processing point 293
Processing point 294
Processing point 295
Processing point 296
Processing point 297
Processing point 298
Processing point 299
Processing point 300
Processing point 301
Processing point 302
Processing point 303
Processing point 304
Processing point 305
Processing point 306
Processing point 307
Processing point 308
Processing point 309
Processing point 310
Processing point 311
Processing point 312
Processing point 313
Processing point 314
Processing point 315
Processing point 316
Processing point 317
Processing point 318
Processing point 319
Processing point 320
Processing point 321
Processing point 322
Processing point 323
Processing point 324
Processing point 325
Processing point 326
Processing point 327
Processing point 328
Processing point 329
Processing point 330
Processing point 331
Processing point 332
Processing point 333
Processing point 334
Processing point 335
Processing point 336
error here
Error at point 336, covariable 0
could not broadcast input array from shape (7,0) into shape (7,7)
Processing point 337
Processing point 338
Processing point 339
Processing point 340
Processing point 341
Processing point 342
Processing point 343
Processing point 344
Processing point 345
Processing point 346
Processing point 347
Processing point 348
Processing point 349
Processing point 350
Processing point 351
Processing point 352
Processing point 353
Processing point 354
Processing point 355
Processing point 356
Processing point 357
Processing point 358
Processing point 359
Processing point 360
Processing point 361
Processing point 362
Processing point 363
Processing point 364
Processing point 365
Processing point 366
Processing point 367
Processing point 368
Processing point 369
Processing point 370
Processing point 371
Processing point 372
Processing point 373
Processing point 374
Processing point 375
Processing point 376
Processing point 377
Processing point 378
Processing point 379
Processing point 380
Processing point 381
Processing point 382
Processing point 383
Processing point 384
Processing point 385
Processing point 386
Processing point 387
Processing point 388
Processing point 389
Processing point 390
Processing point 391
Processing point 392
Processing point 393
Processing point 394
Processing point 395
Processing point 396
Processing point 397
Processing point 398
error here
Error at point 398, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 399
error here
Error at point 399, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 400
error here
Error at point 400, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 401
error here
Error at point 401, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 402
error here
Error at point 402, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 403
error here
Error at point 403, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 404
error here
Error at point 404, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 405
error here
Error at point 405, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 406
error here
Error at point 406, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 407
error here
Error at point 407, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 408
error here
Error at point 408, covariable 0
could not broadcast input array from shape (0,7) into shape (7,7)
Processing point 409
Processing point 410
Processing point 411
Processing point 412
Processing point 413
Processing point 414
Processing point 415
Processing point 416
Processing point 417
Processing point 418
Processing point 419
Processing point 420
Processing point 421
Processing point 422
Processing point 423
Processing point 424
Processing point 425
Processing point 426
Processing point 427
Processing point 428
Processing point 429
Processing point 430
Processing point 431
Processing point 432
Processing point 433
Processing point 434
Processing point 435
Processing point 436
Processing point 437
Processing point 438
Processing point 439
Processing point 440
Processing point 441
Processing point 442
Processing point 443
Processing point 444
Processing point 445
Processing point 446
Processing point 447

(448, 7, 7, 2)

In [ ]:
# shape file transformation
import geopandas as gpd
from rasterio.transform import from_bounds
from rasterio.features import rasterize

def transform_shape(shapefile_path , attribute , output_path):
    gdf = gpd.read_file(shapefile_path)
    gdf["category_numeric"], category_mapping = gdf[attribute].factorize()
    bounds = gdf.total_bounds  
    print("Bounds:", bounds)
    resolution = 0.008983  # -- 1KM
    width = int((bounds[2] - bounds[0]) / resolution)
    height = int((bounds[3] - bounds[1]) / resolution)

    print(f"Raster size: Width={width}, Height={height}")

    transform = from_bounds(*bounds, width, height)
    raster = rasterize(
        [(geom, value) for geom, value in zip(gdf.geometry, gdf["category_numeric"])],
        out_shape=(height, width),
        transform=transform,
        fill=-1, 
        dtype=rasterio.int32
    )

    tiff_path = output_path
    with rasterio.open(
        tiff_path, "w", 
        driver="GTiff",
        height=height, 
        width=width, 
        count=1,
        dtype=rasterio.uint8,
        crs=gdf.crs,  # Use same CRS as shapefile
        transform=transform
    ) as dst:
        dst.write(raster, 1)
    print(f"Saved 1 km raster to {tiff_path}")

In [ ]:
transform_shape("../Maps/ParentMaterial/Geomorphology/Algeria/Algeria_HG.shp" , "AlgGLG"  , "output_1km.tif")
geoMorpho_window = window_forming2("../Maps/ParentMaterial/Geomorphology/tiff" , df_unique)
np.save("../Data_multi_CNN/geoMorpho.npy", geoMorpho_window)
geoMorpho_window

In [78]:
class optimizerKhefoufi:
    def __init__(self , raster_data , transforme , src ):
        self.raster_data = raster_data
        self.transform = transforme
        self.src = src

def data_saver(path):
    files = []
    lat_min = 0 
    lat_max = 10

    lon_min = 30
    lon_max = 40


    for i in os.listdir(path):
        print(i)
        with rasterio.open(f"{path}/{i}") as src :
            raster_data = src.read()
            transform = src.transform 

            pixel_minx , pixel_miny = latlon_to_pixel(lat_min , lon_min ,src, transform)
            pixel_maxx , pixel_maxy = latlon_to_pixel(lat_max , lon_max , src , transform)
            print(pixel_minx , pixel_maxx , pixel_miny , pixel_maxy)
            
            raster_data = raster_data[0 , pixel_minx : pixel_maxx , pixel_miny : pixel_maxy]

            tiff_val = optimizerKhefoufi(raster_data , transform , src)
        files.append(tiff_val)
    return files
all_files = data_saver("../Maps/organisme/Microbial/SoilResp_HeterotrophicResp_1928/data")

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../Maps/organisme/Microbial/SoilResp_HeterotrophicResp_1928/data'

In [ ]:
Microbial_window = window_forming3(all_files , df_unique)
np.save("../Data_multi_CNN/microbial.npy", Microbial_window)
Microbial_window

In [79]:
def pixel_to_latlon(row, col, dataset):
    lon, lat = xy(dataset.transform, row, col)
    return lat, lon

In [80]:
windows = []
raster_data_used = "../Resmapled/organisme/evergreen.tif"
with rasterio.open(raster_data_used) as src: 
    raster = src.read()
    transform = src.transform

    for index in range(len(df_unique)):
        lat = df_unique.iloc[index]["X"]
        lon = df_unique.iloc[index]["Y"]

        pixel_row, pixel_col = latlon_to_pixel(lat, lon, src, transform)
        window = np.zeros((7, 7, 2))  # Only initialize once

        for i in range(pixel_row - 3, pixel_row + 4):  # rows (Y)
            for j in range(pixel_col - 3, pixel_col + 4):  # cols (X)
                lat_val, lon_val = pixel_to_latlon(i, j, src)

                row_idx = i - (pixel_row - 3)
                col_idx = j - (pixel_col - 3)

                window[row_idx, col_idx, 0] = lat_val
                window[row_idx, col_idx, 1] = lon_val

        windows.append(window)

# Check result
print(windows[0].shape)
np.save("../Data_multi_CNN/latlon.npy", windows)

(7, 7, 2)

In [ ]:
transform_shape("../Maps/ParentMaterial/Rock_type/geo7_2ag.shp" , "GLG"  , "../Maps/ParentMaterial/Rock_type/tiff/rocksType_1km.tif")
rocks_window = window_forming("../Maps/ParentMaterial/Rock_type/tiff", df_unique)
np.save("../Data_multi_CNN/rocks.npy", rocks_window)
rocks_window

,AREA,PERIMETER,GEO2_7G_,GEO2_7G_ID,GLG,geometry,category_numeric
0,2250.44404,966.65344,2,11939,SEA,"POLYGON ((5.40701 5.57146, 5.4109 5.4694, 5.42...",0
1,1.60529,7.58497,3,6,oth,"POLYGON ((15.64759 40.00266, 15.66 40, 15.676 ...",1
2,7.02790,33.05255,4,3,oth,"POLYGON ((19.89965 39.96591, 22.81549 39.8342,...",1
3,0.06592,1.66218,5,7,oth,"POLYGON ((19.67681 39.78778, 19.7106 39.7867, ...",1
4,0.90818,4.50544,6,4,oth,"POLYGON ((8.40944 39.76892, 9.63446 39.84441, ...",1
...,...,...,...,...,...,...,...
11972,0.01677,0.69987,11974,11935,SO,"POLYGON ((19.69988 -34.58595, 19.70456 -34.581...",31
11973,0.00456,0.35706,11975,11936,D,"POLYGON ((19.69988 -34.58595, 19.70059 -34.602...",27
11974,0.00239,0.20456,11976,11934,pCm,"POLYGON ((19.43258 -34.60229, 19.40437 -34.627...",11
11975,0.00641,0.35766,11977,11938,SO,"POLYGON ((19.84761 -34.67162, 19.85932 -34.661...",31
11976,0.00790,0.45490,11978,11937,pCm,"POLYGON ((19.84761 -34.67162, 19.85032 -34.677...",11