In [38]:
import pandas as pd 
import numpy as np

In [39]:
df = pd.read_csv("../results/ministere.csv")
df

,page,profile_id,X,Y,Z,Depth,Argile (%),Azote (%),C/N,Ca,...,Refus ≥ 2 mm (%),S,S/T,S/T = V %,Sable fin (%),Sable grossier (%),pH,pf 2.5,pf 3,pf 4.2
0,profile_1.csv,1,376.30,323.70,130.0,0-30,44.0,0.7,10.7,NaN,...,0.0,24.5,NaN,NaN,15.0,17.0,7.9,NaN,23.4,19.1
1,profile_1.csv,1,376.30,323.70,130.0,30-75,46.0,0.2,10.7,NaN,...,1.0,28.0,NaN,NaN,15.0,15.0,8.0,NaN,25.6,21.2
2,profile_1.csv,1,376.30,323.70,130.0,75-120,46.0,0.7,9.7,NaN,...,0.0,23.2,NaN,NaN,13.0,15.0,8.0,NaN,24.5,19.7
3,profile_1.csv,1,376.30,323.70,130.0,120-165,46.0,NaN,NaN,NaN,...,0.3,24.5,NaN,NaN,10.0,25.0,8.0,NaN,26.3,21.8
4,profile_2.csv,2,375.90,522.60,111.0,0-30,44.0,0.7,10.7,NaN,...,0.0,24.5,NaN,NaN,15.0,17.0,7.9,NaN,23.4,19.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,last_push\page_26.csv,36,377.10,323.65,126.0,70-115,45.0,NaN,NaN,NaN,...,0.5,25.7,NaN,NaN,20.0,21.0,NaN,NaN,NaN,NaN
80,last_push\page_26.csv,36,377.10,323.65,126.0,115-140,NaN,NaN,NaN,NaN,...,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,last_push\page_27.csv,37,377.28,325.10,154.0,0-33,31.0,0.6,11.9,NaN,...,NaN,17.5,NaN,NaN,26.0,25.0,NaN,13.1,NaN,15.4
82,last_push\page_27.csv,37,377.28,325.10,154.0,33-70,32.0,NaN,NaN,NaN,...,NaN,13.2,NaN,NaN,21.0,27.0,NaN,19.0,NaN,15.4
83,last_push\page_27.csv,37,377.28,325.10,154.0,70-115,45.0,NaN,NaN,NaN,...,NaN,25.7,NaN,NaN,20.0,21.0,NaN,NaN,NaN,NaN

In [40]:
rename_map = {
    "X": "X",
    "Y": "Y",
    "Z": "altitude",
    "Depth": "Depth",
    "pH": "pH",
    "Conductivité (mmhos/cm)": "CE",
    "Cation Exchange Capacity" if "CEC" not in df.columns else "CEC": "CEC",  # Safeguard
    "Argile (%)": "A%",
    "Limon fin (%)": "L%",
    "Sable fin (%)": "S%",
    "Fe2O3 libre %": "ALR(L)",
    "Fe2O3 total %": "ALR(S)",
    "Matière organique (%)": "OM"
}

df = df.rename(columns=rename_map)

In [41]:
df

,page,profile_id,X,Y,altitude,Depth,A%,Azote (%),C/N,Ca,...,Refus ≥ 2 mm (%),S,S/T,S/T = V %,S%,Sable grossier (%),pH,pf 2.5,pf 3,pf 4.2
0,profile_1.csv,1,376.30,323.70,130.0,0-30,44.0,0.7,10.7,NaN,...,0.0,24.5,NaN,NaN,15.0,17.0,7.9,NaN,23.4,19.1
1,profile_1.csv,1,376.30,323.70,130.0,30-75,46.0,0.2,10.7,NaN,...,1.0,28.0,NaN,NaN,15.0,15.0,8.0,NaN,25.6,21.2
2,profile_1.csv,1,376.30,323.70,130.0,75-120,46.0,0.7,9.7,NaN,...,0.0,23.2,NaN,NaN,13.0,15.0,8.0,NaN,24.5,19.7
3,profile_1.csv,1,376.30,323.70,130.0,120-165,46.0,NaN,NaN,NaN,...,0.3,24.5,NaN,NaN,10.0,25.0,8.0,NaN,26.3,21.8
4,profile_2.csv,2,375.90,522.60,111.0,0-30,44.0,0.7,10.7,NaN,...,0.0,24.5,NaN,NaN,15.0,17.0,7.9,NaN,23.4,19.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,last_push\page_26.csv,36,377.10,323.65,126.0,70-115,45.0,NaN,NaN,NaN,...,0.5,25.7,NaN,NaN,20.0,21.0,NaN,NaN,NaN,NaN
80,last_push\page_26.csv,36,377.10,323.65,126.0,115-140,NaN,NaN,NaN,NaN,...,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,last_push\page_27.csv,37,377.28,325.10,154.0,0-33,31.0,0.6,11.9,NaN,...,NaN,17.5,NaN,NaN,26.0,25.0,NaN,13.1,NaN,15.4
82,last_push\page_27.csv,37,377.28,325.10,154.0,33-70,32.0,NaN,NaN,NaN,...,NaN,13.2,NaN,NaN,21.0,27.0,NaN,19.0,NaN,15.4
83,last_push\page_27.csv,37,377.28,325.10,154.0,70-115,45.0,NaN,NaN,NaN,...,NaN,25.7,NaN,NaN,20.0,21.0,NaN,NaN,NaN,NaN

In [42]:
df.columns

Index(['page', 'profile_id', 'X', 'Y', 'altitude', 'Depth', 'A%', 'Azote (%)',
       'C/N', 'Ca', 'Ca++', 'CaCO₃ (%)', 'Calcaire actif (%)', 'Carbone (%)',
       'CE', 'Couleur', 'ALR(L)', 'ALR(S)', 'Humidité %',
       'Indice K Henin (cm/h)', 'Instabilité structurale', 'K',
       'K₂O assimilable (%)', 'L%', 'Limon grossier (%)', 'OM', 'Mg²⁺', 'Na⁺',
       'P2O5 total %', 'Perméabilité terrain (cm/h)',
       'Poids spécifique apparent', 'Poids spécifique réel',
       'P₂O₅ assimilable (%)', 'Refus ≥ 2 mm (%)', 'S', 'S/T', 'S/T = V %',
       'S%', 'Sable grossier (%)', 'pH', 'pf 2.5', 'pf 3', 'pf 4.2'],
      dtype='object')

In [43]:
df[["UD", "LD"]] = df["Depth"].str.extract(r'(\d+)[^\d]+(\d+)').astype(float)
df["average profondeur"] = (df["UD"] + df["LD"]) / 2
df["USDA Soil Taxonomy"] = "To classify"
keep_cols = [
    "X", "Y", "altitude", "UD", "LD", "average profondeur",
    "USDA Soil Taxonomy", "pH", "CE", 
    "A%", "L%", "S%", "ALR(L)", "ALR(S)", "OM"
]
df_final = df[keep_cols]
df_final

,X,Y,altitude,UD,LD,average profondeur,USDA Soil Taxonomy,pH,CE,A%,L%,S%,ALR(L),ALR(S),OM
0,376.30,323.70,130.0,0.0,30.0,15.0,To classify,7.9,1.4,44.0,13.0,15.0,NaN,NaN,1.3
1,376.30,323.70,130.0,30.0,75.0,52.5,To classify,8.0,0.5,46.0,16.0,15.0,NaN,NaN,1.2
2,376.30,323.70,130.0,75.0,120.0,97.5,To classify,8.0,0.4,46.0,29.0,13.0,NaN,NaN,1.1
3,376.30,323.70,130.0,120.0,165.0,142.5,To classify,8.0,NaN,46.0,27.0,10.0,NaN,NaN,NaN
4,375.90,522.60,111.0,0.0,30.0,15.0,To classify,7.9,1.4,44.0,13.0,15.0,NaN,NaN,1.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,377.10,323.65,126.0,70.0,115.0,92.5,To classify,NaN,NaN,45.0,9.0,20.0,NaN,NaN,NaN
80,377.10,323.65,126.0,115.0,140.0,127.5,To classify,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,377.28,325.10,154.0,0.0,33.0,16.5,To classify,NaN,NaN,31.0,12.0,26.0,NaN,NaN,1.2
82,377.28,325.10,154.0,33.0,70.0,51.5,To classify,NaN,NaN,32.0,10.0,21.0,NaN,NaN,NaN
83,377.28,325.10,154.0,70.0,115.0,92.5,To classify,NaN,NaN,45.0,9.0,20.0,NaN,NaN,NaN

In [44]:
df_final["CEC"]=np.nan
df_final

C:\Users\abdo7\AppData\Local\Temp\ipykernel_13608\2178286170.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["CEC"]=np.nan

,X,Y,altitude,UD,LD,average profondeur,USDA Soil Taxonomy,pH,CE,A%,L%,S%,ALR(L),ALR(S),OM,CEC
0,376.30,323.70,130.0,0.0,30.0,15.0,To classify,7.9,1.4,44.0,13.0,15.0,NaN,NaN,1.3,NaN
1,376.30,323.70,130.0,30.0,75.0,52.5,To classify,8.0,0.5,46.0,16.0,15.0,NaN,NaN,1.2,NaN
2,376.30,323.70,130.0,75.0,120.0,97.5,To classify,8.0,0.4,46.0,29.0,13.0,NaN,NaN,1.1,NaN
3,376.30,323.70,130.0,120.0,165.0,142.5,To classify,8.0,NaN,46.0,27.0,10.0,NaN,NaN,NaN,NaN
4,375.90,522.60,111.0,0.0,30.0,15.0,To classify,7.9,1.4,44.0,13.0,15.0,NaN,NaN,1.3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,377.10,323.65,126.0,70.0,115.0,92.5,To classify,NaN,NaN,45.0,9.0,20.0,NaN,NaN,NaN,NaN
80,377.10,323.65,126.0,115.0,140.0,127.5,To classify,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,377.28,325.10,154.0,0.0,33.0,16.5,To classify,NaN,NaN,31.0,12.0,26.0,NaN,NaN,1.2,NaN
82,377.28,325.10,154.0,33.0,70.0,51.5,To classify,NaN,NaN,32.0,10.0,21.0,NaN,NaN,NaN,NaN
83,377.28,325.10,154.0,70.0,115.0,92.5,To classify,NaN,NaN,45.0,9.0,20.0,NaN,NaN,NaN,NaN

In [45]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   X                   84 non-null     float64
 1   Y                   84 non-null     float64
 2   altitude            84 non-null     float64
 3   UD                  84 non-null     float64
 4   LD                  84 non-null     float64
 5   average profondeur  84 non-null     float64
 6   USDA Soil Taxonomy  84 non-null     object
 7   pH                  66 non-null     float64
 8   CE                  61 non-null     float64
 9   A%                  83 non-null     float64
 10  L%                  82 non-null     float64
 11  S%                  83 non-null     float64
 12  ALR(L)              0 non-null      float64
 13  ALR(S)              0 non-null      float64
 14  OM                  58 non-null     float64
 15  CEC                 0 non-null      float64
dtypes: float64(15), object(1)
memory usage: 10.6+ KB

In [46]:
from pyproj import Transformer

# Lambert Nord Sahara (EPSG:30491) -> WGS84 (EPSG:4326)
transformer = Transformer.from_crs("EPSG:30491", "EPSG:4326", always_xy=True)

for i in range(len(df)):
    x = df_final.at[i, "X"] * 1000
    y = df_final.at[i, "Y"] * 1000
    lon, lat = transformer.transform(x, y)
    df_final.at[i, "X"] = round(lon, 2) 
    df_final.at[i, "Y"] = round(lat, 2)

In [47]:
df_final

,X,Y,altitude,UD,LD,average profondeur,USDA Soil Taxonomy,pH,CE,A%,L%,S%,ALR(L),ALR(S),OM,CEC
0,1.32,36.20,130.0,0.0,30.0,15.0,To classify,7.9,1.4,44.0,13.0,15.0,NaN,NaN,1.3,NaN
1,1.32,36.20,130.0,30.0,75.0,52.5,To classify,8.0,0.5,46.0,16.0,15.0,NaN,NaN,1.2,NaN
2,1.32,36.20,130.0,75.0,120.0,97.5,To classify,8.0,0.4,46.0,29.0,13.0,NaN,NaN,1.1,NaN
3,1.32,36.20,130.0,120.0,165.0,142.5,To classify,8.0,NaN,46.0,27.0,10.0,NaN,NaN,NaN,NaN
4,1.28,38.00,111.0,0.0,30.0,15.0,To classify,7.9,1.4,44.0,13.0,15.0,NaN,NaN,1.3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,1.33,36.20,126.0,70.0,115.0,92.5,To classify,NaN,NaN,45.0,9.0,20.0,NaN,NaN,NaN,NaN
80,1.33,36.20,126.0,115.0,140.0,127.5,To classify,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,1.33,36.22,154.0,0.0,33.0,16.5,To classify,NaN,NaN,31.0,12.0,26.0,NaN,NaN,1.2,NaN
82,1.33,36.22,154.0,33.0,70.0,51.5,To classify,NaN,NaN,32.0,10.0,21.0,NaN,NaN,NaN,NaN
83,1.33,36.22,154.0,70.0,115.0,92.5,To classify,NaN,NaN,45.0,9.0,20.0,NaN,NaN,NaN,NaN

In [48]:
df_final.to_csv("../results/myministereData.csv")